### ISSUE TITLE
Cannot scroll after opening embedded page

### ISSUE THREAD

**Issue by Thing1Thing2** [nus-cs2103-AY2223S1/forum#1]
At [this page](https://nus-cs2103-ay2223s1.github.io/website/schedule/week2/topics.html) after opening and closing the embedded link " a Git repo can work with remote repos other than the one it was cloned from.", I am unable to scroll the page. It only works after refreshing the page. Here is a screenshot of the page concerned before and after the issue:
## before

![image](https://user-images.githubusercontent.com/93027319/184385600-cf62e450-af86-4020-a9c2-abee824f5b6a.png)

## after

![image](https://user-images.githubusercontent.com/93027319/184386470-4d5732c9-1ad8-46d4-a00a-33a9410bf1b4.png)

**Comment by damithc** [comment]
Thanks for the bug report @Thing1Thing2 Yes, it seems to be a bug in [MarkBind](https://markbind.org/) (the tool used to generate the module website) I'll ask the MarkBind team to look into it.

**Comment by damithc** [comment]
An update: The MarkBind team found that this happens only when the same pop-up modal link is present multiple times in the page, which is rare. Still, it needs to be fixed (and they will work on a fix in due course) but less urgent. In the meantime, you can use the workaround of refreshing the page if this happens.

**Comment by domlimm** [comment]
Hello @Thing1Thing2! I'm a senior from a previous batch, dropping by to look at the issues posted by you guys. Just a gentle reminder to close the issue once it has been resolved. Have a great day! 😄
