### ISSUE TITLE
Question on Level-2 of the project

### ISSUE THREAD

**Issue by SpecOps2016** [nus-cs2103-AY2223S1/forum#10]
We are told to use Arrays to store the items. Are we permitted to use ArrayList instead for Level-2? Thank you!

**Comment by RussellDash332** [comment]
While it is not stated whether the use of `ArrayList` is permitted for `Level-2`, it should be allowed as there is no restriction. The use of `Arrays` is just a suggestion. You will actually use `ArrayList` on `Level-6` anyways.

**Comment by damithc** [comment]
> While it is not stated whether the use of `ArrayList` is permitted for `Level-2`, it should be allowed as there is no restriction. The use of `Arrays` is just a suggestion. You will actually use `ArrayList` on `Level-6` anyways.

Yes, you may use any data structure to store the tasks.

**Comment by SpecOps2016** [comment]
Thank you!
