### ISSUE TITLE
Gradle Test Cases

### ISSUE THREAD

**Issue by SpecOps2016** [nus-cs2103-AY2223S1/forum#100]
![image](https://user-images.githubusercontent.com/76586680/187235859-78a0f00d-7336-408a-a46b-cc8cf091f354.png)
Hi I am unable to run test cases with Gradle. Can anyone help me with this?

**Comment by seelengxd** [comment]
try renaming `tests` folder to `test`

**Comment by linuschancs** [comment]
Perhaps you could check if you have `useJUnitPlatform()` in your build.gradle file under tests. Or try changing your Gradle settings to run tests using intellij instead!

**Comment by SpecOps2016** [comment]
> try renaming `tests` folder to `test`

Thanks this helped!
