### ISSUE TITLE
Commit and pushed Level-10 into master without making branch first

### ISSUE THREAD

**Issue by HoJunHao2000** [nus-cs2103-AY2223S1/forum#103]
I am in a bit of a dilemma, so i did my Level-10 on the master branch, instead of creating another branch, and pushed it to the remote repository already.

What should I do? Should I revert my repository back to before (the previous commits will still be there) and start again or just leave it as it is.

![image](https://user-images.githubusercontent.com/84698566/187333415-718428b3-1c80-42c5-8889-746fc8304b9b.png)

**Comment by damithc** [comment]
@HoJunHao2000 It's OK to miss a few iP requirements, provided you know the mistake and how to do it correctly. It would not affect final marks.
If you want it to be green in the dashboard, you can create a branch now, add some commits to it (e.g., some minor changes), and merge it.

**Comment by leonidas1712** [comment]
Not sure about SourceTree, but you could follow [this page](https://www.techiedelight.com/create-branch-from-previous-commit-git/) to make a branch from a previous commit and push it to the repo in the Git CLI if you want.

**Comment by damithc** [comment]
> Not sure about SourceTree, but you could follow [this page](https://www.techiedelight.com/create-branch-from-previous-commit-git/) to make a branch from a previous commit and push it to the repo in the Git CLI if you want.

Yes, it is also fine if you move the commit to a new branch too. While not required by the module, doing so will help you to learn more Git.
