### ISSUE TITLE
Encounter Bugs When Running JAR

### ISSUE THREAD

**Issue by myangat0343** [nus-cs2103-AY2223S1/forum#105]
When I run the JAR in the terminal, it encounters a bug. But there is no bug when running in Intellij. Can anyone figure out the reason?
I think it may the path of JAR file ?

<img width="233" alt="path" src="https://user-images.githubusercontent.com/70734965/187335824-158732c5-f6e9-4d97-b724-42c93354fe57.png">

<img width="384" alt="Correct result by IJ" src="https://user-images.githubusercontent.com/70734965/187335441-1528bd43-e4c6-4b3d-9201-8290a72882dd.png">
<img width="393" alt="Exception by JAR" src="https://user-images.githubusercontent.com/70734965/187335446-25029b68-6e49-4f88-837e-fa5e23a809ae.png">

**Comment by leonidas1712** [comment]
Hi, I tried cloning your ip repo from your profile and running Duke.main() and the ip.jar from src/test/artifacts inside IntelliJ. I do encounter the error you have shown in your last screenshot. 

<img width="1391" alt="Screenshot 2022-08-30 at 10 45 30 AM" src="https://user-images.githubusercontent.com/20151382/187337389-cb906a3d-ba3a-4d77-a4e7-1b2007ac7041.png">


Perhaps you could elaborate on the behaviour you are expecting and steps you would take to reproduce it?

**Comment by kxrt** [comment]
I took a quick peek at your code for `Storage.java`. Looks like you're not creating a directory if the filepath for your storage file doesn't exist, and the "IOException e" print comes from there. The Level-7 task description specifies this needs to be handled. 

A possible reason for this could be the hardcoded path in `Duke.java` - it might be worth reconsidering the implementation here!

**Comment by myangat0343** [comment]
> I took a quick peek at your code for `Storage.java`. Looks like you're not creating a directory if the filepath for your storage file doesn't exist, and the "IOException e" print comes from there. The Level-7 task description specifies this needs to be handled.
> 
> A possible reason for this could be the hardcoded path in `Duke.java` - it might be worth reconsidering the implementation here!

Thank you so much!

**Comment by myangat0343** [comment]
I rewrite the path of data and solve the problem. Thank you : )
