### ISSUE TITLE
JavaFX tutorial part 1 - Launcher error

### ISSUE THREAD

**Issue by bryanngzh** [nus-cs2103-AY2223S1/forum#107]
I was following the JavaFX tutorial but I got stuck at part 1.
When I try running the launcher, i get this error code.
![image](https://user-images.githubusercontent.com/50972999/187345469-ebd15535-9314-4eca-80f4-e5f1cae43f04.png)
How do I go about fixing this?

Thanks!

**Comment by leongdl135** [comment]
Hi, I managed to resolve this issue by creating a default constructor in my Duke class! 
``` java
public Duke() {}
```

**Comment by bryanngzh** [comment]
Thanks!
