### ISSUE TITLE
duke package error in intellij

### ISSUE THREAD

**Issue by guokweijie** [nus-cs2103-AY2223S1/forum#108]
![photo_2022-08-30_01-42-03](https://user-images.githubusercontent.com/66172460/187345754-3900035c-2d8b-444e-b476-09f9aa4dd3b9.jpg)

hi, does anyone know why intellij has this red underline under the package duke when I try to put my test classes in the same package as my main classes?  it tells me to move the test classes into the same package.

does this matter as long as i can access the classes in the duke package?

**Comment by RussellDash332** [comment]
This is because it's not under the `duke` directory. You can simply nest everything in `java` directory into `java/duke` directory.

Note: imo this is better than renaming `java` to `duke` as it might mess up your Gradle/JUnit build

**Comment by guokweijie** [comment]
> 

![image](https://user-images.githubusercontent.com/66172460/187347335-9966cbd6-39a9-4efb-b00c-ed85b7eb0131.png)

but if I create a duke package again under test directory, when i run the test, it says test no-source?

**Comment by RussellDash332** [comment]
You might need to modify `build.gradle` as well as the Gradle setup in the project accordingly

**Comment by guokweijie** [comment]
> You might need to modify `build.gradle` as well as the Gradle setup in the project accordingly

oh i rebuilded the different components of the gradle project manually and now it works! thank you!

**Comment by RussellDash332** [comment]
Nice, glad to see it finally worked! 😌
