### ISSUE TITLE
Cannot scroll after opening embedded page

### ISSUE THREAD

**Issue by RussellDash332** [nus-cs2103-AY2223S1/forum#109]
Similar to #1, but [this link](https://nus-cs2103-ay2223s1.github.io/website/se-book-adapted/chapters/codeQuality.html) instead.

(Issue was found when clicking `SLAP Hard -> "abstraction"` but I think other embedded pages within the same page have similar issues)

**Comment by damithc** [comment]
@RussellDash332 Thanks for the bug report. Yes, a few more such cases seem to remain. I've notified the MarkBind team.

**Comment by yixiann** [comment]
I am facing the same issue at:

https://nus-cs2103-ay2223s1.github.io/website/schedule/week5/topics.html#supplementary-requirements

In the sentence:
A supplementary requirements section can be used to capture requirements that do not fit elsewhere. Typically, this is where most Non-Functional Requirements will be listed.

After clicking 
"Non-Functional Requirements"

**Comment by damithc** [comment]
Both fixed. Thanks @yixiann and @RussellDash332
