### ISSUE TITLE
Unable to Push

### ISSUE THREAD

**Issue by lizekai-richard** [nus-cs2103-AY2223S1/forum#11]
I'm trying to push my commits of ip to the remote repo. However, the error below keeps prompting. It seems that there is an authentication problem. What should I do to fix this? I'm using Mac as my development environment.

<img width="642" alt="Screenshot 2022-08-17 at 10 17 46 AM" src="https://user-images.githubusercontent.com/88566387/185020433-b1abf191-b663-4447-a7bc-60796b47db54.png">

**Comment by carriezhengjr** [comment]
You could try the methods here first to see if the issue persists: https://github.com/nus-cs2103-AY2223S1/forum/issues/9 
(I am also using Mac and received similar error message as you when I tried to push to remote repo too.)

Hope it helps!

**Comment by lizekai-richard** [comment]
It works! Thanks a lot for your help.
