### ISSUE TITLE
Need help for Java Regex

### ISSUE THREAD

**Issue by ThomasHoooo** [nus-cs2103-AY2223S1/forum#110]
I have a Event string `String task = "[E][ ] dancing (at: 14 Aug 2022 1200)";` and I'm trying to extract out the task `dancing` and the time `14 Aug 2022 1200`.

I have tried the following but still couldn't work.
```
Pattern timePattern = Pattern.compile("at: (.*?)\\)"); // Pattern to match time 14 Aug 2022 1200
Matcher timeMatcher = timePattern.matcher(task);
```

Can someone enlighten me?

**Comment by RussellDash332** [comment]
Looking at [Parser.java here](https://github.com/se-edu/addressbook-level2/blob/master/src/seedu/addressbook/parser/Parser.java), you can see that giving names to the capturing group helps you to capture the respective keywords. I guess you can make use of that and hopefully will make it easier to extract.

**Comment by ThomasHoooo** [comment]
> Looking at [Parser.java here](https://github.com/se-edu/addressbook-level2/blob/master/src/seedu/addressbook/parser/Parser.java), you can see that giving names to the capturing group helps you to capture the respective keywords. I guess you can make use of that and hopefully will make it easier to extract.

Thanks for replying even though it's not really applicable in my context.

**Comment by RussellDash332** [comment]
An example of this would be something like this.
```java
String task = "[E][ ] dancing (at: 14 Aug 2022 1200)";
Pattern pattern = Pattern.compile("\\] (?<description>[^\\(]*)\\(at: (?<time>.*)\\)"); // might not work
Matcher matcher = pattern.matcher(task);
String description = matcher.group("description");
String time = matcher.group("time");
```

**Comment by ThomasHoooo** [comment]
> ```java
> String task = "[E][ ] dancing (at: 14 Aug 2022 1200)";
> Pattern pattern = Pattern.compile("\\] (?<description>[^\\(]*)\\(at: (?<time>.*)\\)"); // might not work
> Matcher matcher = pattern.matcher(task);
> String description = matcher.group("description");
> String time = matcher.group("time");
> ```

Thanks for replying and I just tried your code via an online compiler and it shows error.
```
/MyClass.java:4: error: cannot find symbol
        Pattern pattern = Pattern.compile("\\] (?<description>[^\\(]*)\\(at: (?<time>.*)\\)"); // might not work
        ^
  symbol:   class Pattern
  location: class MyClass
/MyClass.java:4: error: cannot find symbol
        Pattern pattern = Pattern.compile("\\] (?<description>[^\\(]*)\\(at: (?<time>.*)\\)"); // might not work
                          ^
  symbol:   variable Pattern
  location: class MyClass
/MyClass.java:5: error: cannot find symbol
        Matcher matcher = pattern.matcher(task);
        ^
  symbol:   class Matcher
  location: class MyClass
3 errors
```

I believe I have found the solution already. 
the trick is to add `timeMatcher.find();`.

**Comment by ThomasHoooo** [comment]
> An example of this would be something like this.
> 
> ```java
> String task = "[E][ ] dancing (at: 14 Aug 2022 1200)";
> Pattern pattern = Pattern.compile("\\] (?<description>[^\\(]*)\\(at: (?<time>.*)\\)"); // might not work
> Matcher matcher = pattern.matcher(task);
> String description = matcher.group("description");
> String time = matcher.group("time");
> ```

Hey my bad I just realised there were some mistakes in my previous comment. I tested out and everything seems to be working fine. Thank you very much.

**Comment by RussellDash332** [comment]
> > ```java
> > String task = "[E][ ] dancing (at: 14 Aug 2022 1200)";
> > Pattern pattern = Pattern.compile("\\] (?<description>[^\\(]*)\\(at: (?<time>.*)\\)"); // might not work
> > Matcher matcher = pattern.matcher(task);
> > String description = matcher.group("description");
> > String time = matcher.group("time");
> > ```
> 
> Thanks for replying and I just tried your code via an online compiler and it shows error.
> ```
> /MyClass.java:4: error: cannot find symbol
>         Pattern pattern = Pattern.compile("\\] (?<description>[^\\(]*)\\(at: (?<time>.*)\\)"); // might not work
>         ^
>   symbol:   class Pattern
>   location: class MyClass
> /MyClass.java:4: error: cannot find symbol
>         Pattern pattern = Pattern.compile("\\] (?<description>[^\\(]*)\\(at: (?<time>.*)\\)"); // might not work
>                           ^
>   symbol:   variable Pattern
>   location: class MyClass
> /MyClass.java:5: error: cannot find symbol
>         Matcher matcher = pattern.matcher(task);
>         ^
>   symbol:   class Matcher
>   location: class MyClass
> 3 errors
> ```
> 
> I believe I have found the solution already. 
> the trick is to add `timeMatcher.find();`.

Glad you managed to solve it. Seems like you didn't import `java.util.regex` on the online compiler yet?

Update: you commented faster haha

**Comment by ThomasHoooo** [comment]
Yup I realised my mistake. Nonetheless u will still need `matcher.find()` in order for it to work.
