### ISSUE TITLE
Getting Warning of Unsupported JavaFX configuration

### ISSUE THREAD

**Issue by janelleljt** [nus-cs2103-AY2223S1/forum#111]
Hi all, I'm having this issue where I cannot run `./gradlew run` via CLI due to a warning: 
> `WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @7d59e741'`

When running the ip using the gradle toolbar, a `Hello World` window does pop up in spite of the same warning received. 

Any help appreciated thanks!

![image](https://user-images.githubusercontent.com/75255420/187578878-490fa1d9-e3f7-4e5d-82b1-c47276d54f06.png)

**Comment by damithc** [comment]
@janelleljt While waiting for inputs from others, here are some things you can try:
* Push the code to a branch and share here so that other can try to replicate the problem.
* If using Intellij, try these common remedies one-at-a-time in this order:
  * File -> Invalidate caches
  * Delete the .idea folder -> Close and re import the project
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by deepimpactmir** [comment]
Can we see your build.gradle? Seems like `javafx` is not loaded.

**Comment by janelleljt** [comment]
@deepimpactmir Hi, here's my build.gradle

```
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '5.1.0'
    // id 'checkstyle'
}


repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'
    String javaFxVersion = '17.0.1'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'

}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClassName = "bobthebot.utils.Launcher";
}

shadowJar {
    archiveBaseName = "bob"
    archiveClassifier = null
}

run{
    standardInput = System.in
}

//checkstyle {
//    toolVersion = '10.2'
//}
```

I followed the tutorial [here](https://se-education.org/guides/tutorials/javaFxPart1.html) but changed 
> `String javaFxVersion = '11'`
to 
> `String javaFxVersion = '17.0.1'`
because version 11 was not working initially for me as well.

**Comment by deepimpactmir** [comment]
Can you try following [this](https://openjfx.io/openjfx-docs/#gradle) instead? This seems to work fine for me.

**Comment by Hikoya** [comment]
Side note here: the tutorial mentioned to use JavaFX version 11 instead

```
repositories {
    mavenCentral()
}

dependencies {
    String javaFxVersion = '11'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}
```

https://se-education.org/guides/tutorials/javaFxPart1.html

You are currently using 17.0.1

EDIT: My bad for not noticing your next comment, do try the link sent by deepimpactmir!

**Comment by janelleljt** [comment]
@Hikoya when I used 11 I got this haha :"
![image](https://user-images.githubusercontent.com/75255420/187600825-fad7d092-e56f-4e86-86a1-ba7d8428f86d.png)

**Comment by kxrt** [comment]
@janelleljt Hi! I think the "runtime components are missing" error occurs when you try running from `Main.java`, because I faced that error too. Could you try running from `Launcher.java` instead?

**Comment by janelleljt** [comment]
@kxrt I am running from `Launcher.java` hahaha :" It's ok I tried using @deepimpactmir 's reccomendation and it doesn't give me a warning when I use the Gradle toolbar, but I still cannot use CLI :". I'll just use the toolbar for now, thanks everyone!

**Comment by damithc** [comment]
@janelleljt you can also compare your build.gradle with those of who posted GUIs in https://github.com/nus-cs2103-AY2223S1/forum/issues/106
