### ISSUE TITLE
Taking input by input in JavaFX

### ISSUE THREAD

**Issue by rylzxc** [nus-cs2103-AY2223S1/forum#112]
Has anyone tried implementing the chatbot to take in one input at a time? 

Something like: first input: event, second input: work, third input: 2022-10-10

In code, it'll be the scanner reading the next line on pressing enter, but I'm not sure how to make it work in JavaFX.

**Comment by teekaytai** [comment]
Normally when you input your whole command in one shot the flow goes like this

1. JavaFX receives input from user and passes it over to Duke
2. Duke comes up with a response and passes it back to JavaFX
3. JavaFX shows the response to the user

If instead you would like to break the command into multiple steps, the flow might look something like this

1. JavaFX receives input from user and passes it over to Duke
2. Duke informs JavaFX that this particular command needs more inputs, maybe also informing JavaFX of what piece(s) of info it needs next. In the meantime this partial command has to be stored away somewhere
3. JavaFX relays Duke's 'response' to the user, asking the user for the next part of the command
4. Repeat as necessary
5. Once the full command is completed Duke can process it and return the response as before

Note that for the tP it is not recommended to do this one-input-at-a-time idea. To quote from the [website](https://nus-cs2103-ay2223s1.github.io/website/admin/tp-constraints.html#recommendation-cli-first):

> One-shot commands are faster over multi-step commands.

**Comment by rylzxc** [comment]
@teekaytai Thanks, I have implemented it. :)

**Comment by rylzxc** [comment]
@damithc Hi Prof, I was wondering how the iP is graded, like is it okay (won't penalize score) to do it this way or must I stick to the format that was proposed?

**Comment by damithc** [comment]
> @damithc Hi Prof, I was wondering how the iP is graded, like is it okay (won't penalize score) to do it this way or must I stick to the format that was proposed?

@rylzxc either approach is fine for the iP, but as @teekaytai mentioned, the multi-step approach is not recommended for the tP.

**Comment by rylzxc** [comment]
> @rylzxc either approach is fine for the iP, but as @teekaytai mentioned, the multi-step approach is not recommended for the tP.

Mine is implemented in a way such that a DialogBox pops up to request for further information after a command, this would be okay right just for the iP.

**Comment by damithc** [comment]
> Mine is implemented in a way such that a DialogBox pops up to request for further information after a command, this would be okay right just for the iP.

Yes, it's fine @rylzxc
