### ISSUE TITLE
Localization of IP and TP

### ISSUE THREAD

**Issue by Hikoya** [nus-cs2103-AY2223S1/forum#113]
Hi Prof

For the iP as well as the tP, do we assume that the input by the user will be in English eg. task name is written in English, addresses for tP written in English

or do we have to handle international languages eg. Mandarin separately.

Asking on behalf of tP members, tutor suggested to post on forum for everyone.

**Comment by damithc** [comment]
@Hikoya Good question.
Handling English only is enough. You are free to add support for other languages.
