### ISSUE TITLE
run .\gradlew checkstyleMain fails with could not initialize class error

### ISSUE THREAD

**Issue by quannam0124** [nus-cs2103-AY2223S1/forum#115]
#My Checkstyle with Gradle build is failing 
I have reused the checkstyle.xml and supressions.xml files. However, when i run gradlew checkstyleMain, the build fails with the following error:
> Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

If anyone encountered a similar problem and have solved it, I would greatly appreciate the assistance. Thank you! 👍

**Comment by leonidas1712** [comment]
Hi, I looked at your ip repo but I don't see the config/checkstyle folder in your root directory. Have you tried following all the steps in the [checkstyle guide](https://se-education.org/guides/tutorials/checkstyle.html)? Perhaps you can push what you have to your repo.

**Comment by malwaregarry** [comment]
Hi, try building your app to ensure all dependencies are installed?

either `./gradlew build` or `gradlew build`

**Comment by quannam0124** [comment]
> Hi, I looked at your ip repo but I don't see the config/checkstyle folder in your root directory. Have you tried following all the steps in the [checkstyle guide](https://se-education.org/guides/tutorials/checkstyle.html)? Perhaps you can push what you have to your repo.

Hello! I just pushed the checkstyle folder to the repo

**Comment by quannam0124** [comment]
> Hi, try building your app to ensure all dependencies are installed?
> 
> either `./gradlew build` or `gradlew build`

I tried doing that and the build failed with this error 😢 I ran it using the terminal on Intellij

> Could not initialize class org.codehaus.groovy.reflection.ReflectionCache


![image](https://user-images.githubusercontent.com/77949597/187690516-39c97218-f918-482f-809f-48f29e9cb2cb.png)

**Comment by leonidas1712** [comment]
I was going to say you should add the lines specified in the guide to your build.gradle file but I think you just added it to your master branch!
 
Do rename the file in /config/checkstyle to `suppressions.xml` (letter p twice) so checkstyle will run properly.

**Comment by quannam0124** [comment]
Oh thank you! I have added to build.gradle file and renamed suppressions.xml. So far Im still running into this error when i run ```./gradlew build``` and ```./gradlew checkstyleMain```

> Could not initialize class org.codehaus.groovy.reflection.ReflectionCache

When I run main method in Duke it builds and runs normally, so I'm not sure why this error is popping up

**Comment by malwaregarry** [comment]
hmm, maybe try `./gradlew clean build`? Also what JDK version are you? You can check in `File > Project Structure > Project` under SDK

Update: also check the JDK you are using for gradle JVM:
![image](https://user-images.githubusercontent.com/43949290/187698168-67ffd0fb-b849-424a-aeb2-86f6f7b5218a.png)

**Comment by leonidas1712** [comment]
Odd...when I run ./gradlew build using your repo it only fails at checkstyle (as expected) without the error you mentioned.
As malwaregarry mentioned, perhaps there is an issue with the JDK settings on your system or IDE.

You might also want to check out [this SO](https://stackoverflow.com/questions/61289461/java-lang-noclassdeffounderror-could-not-initialize-class-org-codehaus-groovy-v) thread if you haven't already.

**Comment by quannam0124** [comment]
My JDK Settings is JDK 11 for my project settings and GRADLE JVM. I deleted my .idea folder, .gradle folder, and build folder. Then I ran ./gradlew build again and the error doesn't show up anymore! Thank you everyone for your help!!
