### ISSUE TITLE
macOS JavaFX garbled text on JavaFx version 11.

### ISSUE THREAD

**Issue by yuehernkang** [nus-cs2103-AY2223S1/forum#117]
I am currently getting this garbled text if `javaFxVersion = '11'`.
![Image](https://i.imgur.com/IDNhBRa.png)

However, if i change the version to 14, it displays as normal english characters. Is it ok to use JavaFxVersion 14? Or has anyone fixed the issue for JavaFxVersion 11

**Comment by damithc** [comment]
@yuehernkang Have you followed this advisory given [here](https://nus-cs2103-ay2223s1.github.io/website/admin/programmingLanguages.html#programming-language)?

**Comment by yuehernkang** [comment]
> @yuehernkang Have you followed this advisory given [here](https://nus-cs2103-ay2223s1.github.io/website/admin/programmingLanguages.html#programming-language)?

Thank you Prof. I realised apart from checking the version in the command line, we have to change the version in the project settings in intellij too!
