### ISSUE TITLE
JavaFX UnsupportedOperationException: Unable to open DISPLAY

### ISSUE THREAD

**Issue by RussellDash332** [nus-cs2103-AY2223S1/forum#118]
Currently unable to launch the `Launcher` class due to this exception. One can take a look at the current status [here](https://github.com/RussellDash332/ip/tree/branch-Level-10).

* IntelliJ version: 2022.0
* Java JDK version: 11.0.8
* JavaFX version: 11
* Gradle version: 6.2
* OS: Linux Ubuntu 20.04.2 LTS focal (inside Windows 10 but not dual booting)

Approaches done so far:
* `export DISPLAY=:0`, but no effect
* Closing the project after deleting `.idea`
* Changing to other versions of JavaFX, such as version 18.0.2, on both local and Gradle, to no avail
* Actually using the Windows Command Prompt to no avail

The exact same issue seems to be discovered in other repos but they are pretty much repository-dependent. I was wondering if anyone can help me on this. Thanks!

```
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:173)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at javafx.graphics/com.sun.glass.ui.Application.run(Application.java:144)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kxrt** [comment]
Hi! I cloned your branch and executed the following steps:

- Switch to zulu-11's jdk 11.0.16 from [here](https://www.azul.com/downloads/).
- Update `fx:controller="MainWindow">` to `fx:controller="stashy.launcher.MainWindow">` in line 9 of MainWindow.xml.
- Add an images folder to the `resources` directory.

After this your application launches, but I seem to get garbled text. Running this on an Intel MacBook Pro 2020.
<img width="512" alt="Garbled text" src="https://user-images.githubusercontent.com/73589885/187824860-866a879c-fd2f-4b73-ba4a-dc1809e1b799.png">
Changing `javaFxVersion` to 14 in `build.gradle` seems to fix the garbled text, but I'm not sure if that's a hack or a proper solution to this issue.
<img width="512" alt="No garbled text" src="https://user-images.githubusercontent.com/73589885/187825389-b414d876-843c-4178-a0b0-9a3f8e538541.png">

**Comment by damithc** [comment]
While waiting for inputs from others:
* A common cause of  `Unable to open DISPLAY` is using an environment that doesn't support GUI applications. At least some versions of WSL don't support GUI applications.
* A common cause of garbled text is not installing the exact JDK version as specified in our advisory [here](https://nus-cs2103-ay2223s1.github.io/website/admin/programmingLanguages.html#programming-language).

**Comment by malwaregarry** [comment]
> * A common cause of  `Unable to open DISPLAY` is using an environment that doesn't support GUI applications. At least some versions of WSL don't support GUI applications.

I agree that it could be a WSL error. WSLg is currently only for Windows 11 so you might need to run the application on your Windows system.

**Comment by RussellDash332** [comment]
> - Switch to zulu-11's jdk 11.0.16 from [here](https://www.azul.com/downloads/).
> - Update fx:controller="MainWindow"> to fx:controller="stashy.launcher.MainWindow"> in line 9 of MainWindow.xml.
> - Add an images folder to the resources directory.

Thanks for this @kxrt! Switching to zulu is one possible solution for me to run the GUI outside WSL, which definitely does not support GUI when it comes to mine. I purposely haven't added an image the moment you cloned it because I wasn't ready with a good one 😆

> Changing javaFxVersion to 14 in build.gradle seems to fix the garbled text, but I'm not sure if that's a hack or a proper solution to this issue.

Interesting, mine works with JavaFX 11 but I'll try it with a Mac laptop sometime later. Thanks for letting me know about this.

> A common cause of Unable to open DISPLAY is using an environment that doesn't support GUI applications. At least some versions of WSL don't support GUI applications.

You are right Prof @damithc, I do suspect both my Ubuntu CLI and Windows Command Prompt don't support GUI. This happened to another GUI application I had with Python back then. Based on what is said above, opening directly with the JDK (not even Gradle since it makes use of the command line) is the solution

> I agree that it could be a WSL error. WSLg is currently only for Windows 11 so you might need to run the application on your Windows system.

Right, new knowledge indeed, thanks @malwaregarry!

Closing the issue now, thanks for the help!
