### ISSUE TITLE
Launcher : Cannot lock Java compile cache error 

### ISSUE THREAD

**Issue by xhphoong** [nus-cs2103-AY2223S1/forum#119]
When trying to run the launcher,  this error has popped up : 
**Cannot lock Java compile cache (C:  ... \iP\.gradle\6.2\javaCompile) as it has already been locked by this process** 
and I not sure how to resolve it.  Do anyone know how to resolve it? 
Thank you!

**Comment by kxrt** [comment]
Sounds like a Gradle lock error, going off of [here](https://stackoverflow.com/questions/68759744/cannot-lock-java-compile-cache-as-it-has-already-been-locked-by-this-process) and [here](https://stackoverflow.com/questions/62038122/cannot-lock-file-hash-cache-when-gradle-was-aborted). 

Could you try killing Gradle processes and restarting the IDE? If that doesn't work, perhaps try deleting the `.gradle` directory and rebuilding the project.

**Comment by xhphoong** [comment]
Thank you, it works now!
