### ISSUE TITLE
making edits to older commits and marking criteria

### ISSUE THREAD

**Issue by seanflyyy** [nus-cs2103-AY2223S1/forum#12]
Hello! I was working on the IP and I realised that I could have written some code better in level 2. However, I have already made commits until level 5, so may I know how I can go about making the improvements to level 2? 

Additionally, in this case, if I had fixed the bad coding decisions in level 5 which I noted in level 2, would I be penalised? Just wondering what the marking criteria would be? Would it be based on the individual commits or the final output?

Thank you!!

**Comment by deeyonn** [comment]
![image](https://user-images.githubusercontent.com/41563700/185060967-174c643b-0f06-4715-af47-650098843c8c.jpeg)

According to the FAQ in Week 2, this is what you should do.

**Comment by peppapighs** [comment]
If you really need to edit the previous commits, you may follow this [guide](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase), though I do not recommend doing so since it might cause merge conflicts to the subsequent commits.

**Comment by seanflyyy** [comment]
@deeyonn Ahh, I must have missed that. Thank you for pointing it out!
@peppapighs Understood, thanks for the help!
