### ISSUE TITLE
Unable to configure javafxm

### ISSUE THREAD

**Issue by linuschui** [nus-cs2103-AY2223S1/forum#121]
## Hi I am using i5 mac and but am unable to configure javafxm (not using Gradle) 

Taken from this [website](https://se-education.org/guides/tutorials/javaFxPart1.html) :

2. Import the libs folder from the SDK into your project (note: `JAVAFX_HOME` is the directory in which you have unzipped the JavaFX SDK). `File` > `Project Structure` > `Libraries` > `+` > `Java` > `{JAVAFX_HOME}/lib`

3. From `Run` > `Edit Configurations`, add the following line into your VM options for each of the main classes.
`--module-path {JAVAFX_HOME}/lib --add-modules javafx.controls,javafx.fxml`
e.g., `--module-path C:/javafx-sdk-11.0.2/lib --add-modules javafx.controls,javafx.fxml`

Here's what I have done :

2. `File` > `Project Structure` > `Libraries` > `+` > `Java` > `{JAVAFX_HOME}/lib`

<img width="1016" alt="Screenshot 2022-09-01 at 11 09 10 PM" src="https://user-images.githubusercontent.com/97402389/187948777-04491853-5132-4197-942c-7455972e162d.png">

3. `Run` > `Edit Configurations`
<img width="1033" alt="Screenshot 2022-09-01 at 11 09 49 PM" src="https://user-images.githubusercontent.com/97402389/187948988-d4e9c7b3-6f96-42f2-9017-d026d03a949c.png">

Could I get some help with fixing this issue, thank you!

**Comment by damithc** [comment]
@linuschui The Gradle method is recommended.

**Comment by linuschui** [comment]
Thank you for the suggestion prof, I have copied the code into `build.gradle` but it is unable to fix this issue 😢 
<img width="359" alt="Screenshot 2022-09-02 at 12 30 55 AM" src="https://user-images.githubusercontent.com/97402389/187965887-f15a0423-202e-4707-a9dc-fd56483e9205.png">

**Comment by ThomasHoooo** [comment]
You have to first close your project in Intellij, then reopen your project again so that it will download all the necessary packages.

**Comment by linuschui** [comment]
thanks @ThomasHoooo I've got it to work using your advice but I'm facing a different error now, will open up another issue for it. 👍
