### ISSUE TITLE
Java Code-Style XML

### ISSUE THREAD

**Issue by ShenyiCui** [nus-cs2103-AY2223S1/forum#122]
Hi! Does anyone have a Java Styling XML they can share that abides by the CS2103T coding standards? Thanks!

**Comment by damithc** [comment]
> Hi! Does anyone have a Java Styling XML they can share that abides by the CS2103T coding standards? Thanks!

@ShenyiCui Can you elaborate a bit more?

**Comment by teekaytai** [comment]
Do you mean the ones for CheckStyle? If so we can use the ones from [addressbook-level3](https://github.com/se-edu/addressbook-level3/tree/master/config/checkstyle)

**Comment by ShenyiCui** [comment]
thanks for your response @teekaytai! I was thinking something more like this
<img width="912" alt="Screenshot 2022-09-02 at 12 17 23 AM" src="https://user-images.githubusercontent.com/29945147/187963364-99a9b2fd-0824-4369-8166-55464565911d.png">
so that I can just save and have my code formatted properly like "Prettier" with JavaScript on VSCode

Thanks in advance!

**Comment by damithc** [comment]
@ShenyiCui our coding style is very similar to the default style used by Intellij, except for a few deviations. Thise may be useful to configure Intellij for those deviations: https://se-education.org/guides/tutorials/intellijCodeStyle.html
