### ISSUE TITLE
iP Progress not reflected in iP Progress Dashboard

### ISSUE THREAD

**Issue by RichDom2185** [nus-cs2103-AY2223S1/forum#123]
Checked and not a duplicate of #95.

For some reason, despite having merged my [`branch-Level-7`](/RichDom2185/iP/tree/branch-Level-7), [`branch-Level-8`](/RichDom2185/iP/tree/branch-Level-8), [`branch-Level-9`](/RichDom2185/iP/tree/branch-Level-9), [`branch-A-JavaDoc`](/RichDom2185/iP/tree/branch-A-JavaDoc) and [`branch-A-CodingStandard`](/RichDom2185/iP/tree/branch-A-CodingStandard) branches, for some reason, they are still not reflected on the iP progress dashboard.

I merged using one of the following commands (varies on branch):
```bash
git pull --no-ff origin/<branch_name>
git merge --no-ff origin/<branch_name>
```

Other possibly relevant info:
```bash
$ git branch --merged master
  branch-A-CodingStandard
  branch-A-JavaDoc
  branch-Level-7
  branch-Level-8
  branch-Level-9
* master
 // ... other branches I created that are not relevant to this discussion
```

**Comment by ShenyiCui** [comment]
hi! Did you tag your merge commits in master?
<img width="846" alt="Screenshot 2022-09-02 at 2 23 56 AM" src="https://user-images.githubusercontent.com/29945147/187985942-b3b34b11-7b04-4325-98bc-1dd3c80c1b1a.png">

**Comment by damithc** [comment]
@RichDom2185 looks like you set the default branch of your fork to `week4`. 
![image](https://user-images.githubusercontent.com/1673303/187987361-643ef215-f11e-4752-b5fa-6260a5754670.png)

If you change it back to `master`, the dashboard should be able to detect those missing branches.

**Comment by RichDom2185** [comment]
Even if `week4` contains the same merge commits as `master`? I will try to switch to `master` for now and will update here again if it works.

**Comment by deeyonn** [comment]
Yes, I am experiencing the same issue as well. I will try to add the tag to the master branch after merging to see if the issue is resolved. Thanks for the suggestions!

**Comment by damithc** [comment]
@RichDom2185 @deeyonn is it resolved now?

**Comment by deeyonn** [comment]
> @RichDom2185 @deeyonn is it resolved now?

Yes professor, I do see the missing tags on the dash. thank you!

**Comment by RichDom2185** [comment]
> hi! Did you tag your merge commits in master? <img alt="Screenshot 2022-09-02 at 2 23 56 AM" width="846" src="https://user-images.githubusercontent.com/29945147/187985942-b3b34b11-7b04-4325-98bc-1dd3c80c1b1a.png">

Hi Shenyi, yup I did, the tags on the merge commits were present on `master` (as well as my `week3` branches).

**Comment by RichDom2185** [comment]
> @RichDom2185 @deeyonn is it resolved now?

Hi Prof, yes it is, thank you! Closing the issue now.
