### ISSUE TITLE
FXML loading error

### ISSUE THREAD

**Issue by jchilling** [nus-cs2103-AY2223S1/forum#124]
Hi, I have followed the JavaFX tutorial and have faced this error when implementing FXML. Does anyone know how to fix it?

![issue6](https://user-images.githubusercontent.com/83859498/187976317-be211bb5-94da-4a09-8a21-77495943a232.png)

**Comment by kxrt** [comment]
An error in line 9/10 is probably an issue with your controller's location (incorrect declaration). In your `MainWindow.fxml` file, replace `fx:controller="MainWindow"` with `fx:controller="duke.gui.MainWindow"` at the end of line 9/10. If this is already done, could you push your current work on the branch up to GitHub?

**Comment by jchilling** [comment]
My controller's location is correct. After testing around a bit, I realized that fxml probably doesn't support .jpg files. My launcher works after I convert my image files into .png. Thanks for the help!
