### ISSUE TITLE
How do I correctly set up resources folder for JavaFX?

### ISSUE THREAD

**Issue by deeyonn** [nus-cs2103-AY2223S1/forum#126]
Hi, when following the tutorial for JavaFX setup, I encountered an issue with NullPointerException when I try to load my resource. Any advice on how I can resolve this?

![image](https://user-images.githubusercontent.com/41563700/188114910-512139c5-8f79-4748-bedb-801b8cea69d7.png)

The 3 things to take from the picture are:
- Resource folder structure and icon indicating that it's recognised
- The 2 lines of code copied from the tutorial
- The error message pointing to the NullPointerException

Things I've tried:
- Absolute path rather than relative path
- Restarting IntelliJ

**Comment by sltsheryl** [comment]
Not sure if it works but I think there's a missing / before images. 
```
private Image user = new Image(this.getClass().getResourceAsStream("/images/DaUser.png"));
private Image duke = new Image(this.getClass().getResourceAsStream("/images/DaDuke.png"));
```

**Comment by deeyonn** [comment]
> Not sure if it works but I think there's a missing / before images.
> 
> ```
> private Image user = new Image(this.getClass().getResourceAsStream("/images/DaUser.png"));
> private Image duke = new Image(this.getClass().getResourceAsStream("/images/DaDuke.png"));
> ```

omg i feel so foolish! good catch! thank you so much!
