### ISSUE TITLE
(JavaFX) Labels not showing full text once the messages exceed size of window and scrollbar appears

### ISSUE THREAD

**Issue by joosxi** [nus-cs2103-AY2223S1/forum#128]
Hello! Is there a way to show full text in a label all the time? Thank you!!

Here's a screenshot of when there is no need for the scrollbar. The full text of each label can be seen!
<img width="307" alt="ss1" src="https://user-images.githubusercontent.com/64764352/188140398-e2927243-2fa7-452a-991f-e333eac6c0bc.png">

And here's a screenshot of when the scrollbar appears! The labels no longer show the full text!
<img width="310" alt="ss2" src="https://user-images.githubusercontent.com/64764352/188140490-02fed711-ba0e-48cd-a377-dc6fddf5f0b8.png">

Below is the code for my fxml files:

DialogBox.fxml:
`<fx:root alignment="TOP_RIGHT" maxHeight="1.7976931348623157E308" maxWidth="1.7976931348623157E308" prefWidth="400.0" type="javafx.scene.layout.HBox" xmlns="http://javafx.com/javafx/18" xmlns:fx="http://javafx.com/fxml/1">
    <children>
        <Label fx:id="dialog" style="-fx-background-color: yellow; -fx-background-radius: 20; -fx-label-padding: 8;" text="Label" wrapText="true">
         <HBox.margin>
            <Insets />
         </HBox.margin></Label>
        <ImageView fx:id="displayPicture" fitHeight="99.0" fitWidth="99.0" pickOnBounds="true" preserveRatio="true">
         <HBox.margin>
            <Insets left="5.0" right="5.0" />
         </HBox.margin></ImageView>
    </children>
    <padding>
        <Insets bottom="5.0" left="15.0" right="5.0" top="15.0" />
    </padding>
</fx:root>`

MainWindow.fxml:
`<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="600.0" prefWidth="400.0" xmlns="http://javafx.com/javafx/18" xmlns:fx="http://javafx.com/fxml/1" fx:controller="duke.MainWindow">
    <children>
        <TextField fx:id="userInput" layoutY="558.0" onAction="#handleUserInput" prefHeight="41.0" prefWidth="324.0" style="-fx-background-radius: 20;" AnchorPane.bottomAnchor="1.0" />
        <Button fx:id="sendButton" layoutX="324.0" layoutY="558.0" mnemonicParsing="false" onAction="#handleUserInput" prefHeight="41.0" prefWidth="76.0" style="-fx-background-color: yellow; -fx-background-radius: 20;" text="Send">
         <opaqueInsets>
            <Insets />
         </opaqueInsets></Button>
        <ScrollPane fx:id="scrollPane" hbarPolicy="NEVER" hvalue="1.0" prefHeight="557.0" prefWidth="400.0" vvalue="1.0">
            <content>
                <VBox fx:id="dialogContainer" prefHeight="552.0" prefWidth="388.0" style="-fx-background-color: #FEFFBA;" />
            </content>
        </ScrollPane>
    </children>
</AnchorPane>`

**Comment by damithc** [comment]
@joosxi While waiting for peer help, note that you can use _fenced code blocks_ when posting code in the forum. See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by RussellDash332** [comment]
You need to set `minHeight="-Infinity"` for `DialogBox`. Hope this helps!

Edit: Just copy this FXML I updated for you. There should be a button to copy everything so no need to drag the whole thing.
```xml
<fx:root alignment="TOP_RIGHT" minHeight="-Infinity" maxHeight="1.7976931348623157E308" maxWidth="1.7976931348623157E308" prefWidth="400.0" type="javafx.scene.layout.HBox" xmlns="http://javafx.com/javafx/18" xmlns:fx="http://javafx.com/fxml/1"> <children> <Label fx:id="dialog" style="-fx-background-color: yellow; -fx-background-radius: 20; -fx-label-padding: 8;" text="Label" wrapText="true"> <HBox.margin> <Insets /> </HBox.margin></Label> <ImageView fx:id="displayPicture" fitHeight="99.0" fitWidth="99.0" pickOnBounds="true" preserveRatio="true"> <HBox.margin> <Insets left="5.0" right="5.0" /> </HBox.margin></ImageView> </children> <padding> <Insets bottom="5.0" left="15.0" right="5.0" top="15.0" /> </padding> </fx:root>
```

**Comment by joosxi** [comment]
Ohhh thank you so much! Can I just ask what does adding that setting do to the DialogBox and why it makes things work HAHA 

Does it like set the minimum height of the DialogBox to negative infinity and does that mean like infinitely small

**Comment by RussellDash332** [comment]
> Ohhh thank you so much! Can I just ask what does adding that setting do to the DialogBox and why it makes things work HAHA
> 
> Does it like set the minimum height of the DialogBox to negative infinity and does that mean like infinitely small

It's somewhat a long-term issue, even it can be discovered until [2 years ago](https://github.com/nus-cs2103-AY2021S1/forum/issues/125#issuecomment-683547168).

I didn't try to figure out the rigour on why is this the case but it seems that Slaw's comment on [StackOverflow](https://stackoverflow.com/questions/54441636/dynamically-changing-height-with-prefheight-is-not-working) kind of makes sense.

Speaking about this, I wonder why is this not set by default on the JavaFX tutorial's FXML? It would be a good thing 😄

**Comment by damithc** [comment]
> Speaking about this, I wonder why is this not set by default on the JavaFX tutorial's FXML? It would be a good thing 😄

If wasn't probably considered when writing the tutorial but now, I'd rather leave it be so that it creates these opportunities for troubleshooting and collaboration in the forum :-p

**Comment by joosxi** [comment]
Ah ok thank you Russell and Prof! I'll close this issue now :)
