### ISSUE TITLE
Clarification regarding the extent of customization of iP

### ISSUE THREAD

**Issue by zicotjia** [nus-cs2103-AY2223S1/forum#13]
The instruction said that we are allowed to customize the behavior of Duke such as name and command format. May I ask for clarification on how much we can customize. For example, am I allowed to change the way duke will take in input. For Example, instead of a single line with multiple commands such as `deadline do homework /by 31 Aug`, can I make it that Duke will take one command per line and gives the user instruction after each command.

I.e: 
input: `deadline`
output: `What Is the description of the deadline: `
input:  `do homework`
output: `Please specify the date of the deadline: `
...

**Comment by damithc** [comment]
@zicotjia Sure, you can follow this approach of inputs too. 

On a related note, this approach of taking one parameter at a time is like training wheels on a bicycle: it helps absolute beginners but slows down experienced users. 
It doesn't work well when there are many optional parameters too.

**Comment by zicotjia** [comment]
Thank you for the clarification Prof.
