### ISSUE TITLE
Number of stars does not match (Part 3)

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#130]
In CS2103/T Week 5 Admin Page, I found this three star heading with four star content: 

<img width="572" alt="image" src="https://user-images.githubusercontent.com/13196670/188166539-ea972541-07b2-4a0b-a563-c7679b64fc19.png">

**Comment by damithc** [comment]
Thanks for the bug report @cheeheng I'll fix it in the next update.
