### ISSUE TITLE
CheckStyle detecting wrong indentation level

### ISSUE THREAD

**Issue by ChongCheeKaiClarence** [nus-cs2103-AY2223S1/forum#131]
CheckStyle detected an indentation of level 8 even though my indentation is level 4. I accidentally followed both instructions and installed both Gradle and CheckStyle plugin. I am not sure if this might have accidentally caused a bug. Please help.

![image](https://user-images.githubusercontent.com/97396452/188174772-a36a01f7-342d-41d5-b98d-fc23f9d9d1c0.png)

IntelliJ version 2021.3.1.
Java 11.0.13
WinOS.

**Comment by teekaytai** [comment]
Sounds like this file has tabs in it instead of spaces so it's confusing CheckStyle. Replace the whitespace with spaces instead of tabs and everything should return to normal!
