### ISSUE TITLE
Bug: Cannot retake failed attempt (Week 5.3 Video)

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#132]
I can't retake the quiz even though I got the question wrong. This bug is similar to the issue #49.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/13196670/188180348-968be430-6b2f-4e8e-bbd6-e15f195095bd.png">

**Comment by damithc** [comment]
@cheeheng thanks for the bug report. Fixed.
