### ISSUE TITLE
Bug: Scrollbar disappears after I click on 'non-functional requirements'

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#133]
On [https://nus-cs2103-ay2223s1.github.io/website/schedule/week5/topics.html](https://nus-cs2103-ay2223s1.github.io/website/schedule/week5/topics.html), go to Week 5.3e, then click on link 'non-functional requirements'. Then, once the link is clicked, a popup modal shows. After the modal disappears, the scrollbar disappears, and I have to reload the page. This bug is similar to #1 and #109.

**Comment by damithc** [comment]
Fixed. Thanks for the bug report @cheeheng
