### ISSUE TITLE
Bug: Cannot retake failed attempt (Week 5.4 Video)

### ISSUE THREAD

**Issue by bensohh** [nus-cs2103-AY2223S1/forum#134]
I am unable to retake the In-Video Quiz after a failed attempt. 
![Screenshot 2022-09-03 at 12 35 01 AM](https://user-images.githubusercontent.com/97374822/188199368-40a76dad-b6fc-440f-b98b-1dad7468d312.png)

**Comment by damithc** [comment]
Thanks for the bug report @bensohh 
Fixed.
