### ISSUE TITLE
Failing build (ubuntu-latest) for CI

### ISSUE THREAD

**Issue by jetlfj** [nus-cs2103-AY2223S1/forum#135]
I am unable to complete **Build and check with Gradle** in **build (ubuntu-latest)** due to the following error, which then causes build (macos-latest) and build (windows-latest) to be cancelled as well.

Any idea what's causing this to happen?

[Here](https://github.com/jetlfj/ip) is my repository and I am on Windows if that matters.

Any help is greatly appreciated!

![image](https://user-images.githubusercontent.com/97273951/188211723-aa395d61-c067-4685-8ef7-07b369414c26.png)

**Comment by NicsunXnus** [comment]
Hi @jetlfj, maybe you can check out this solution provided on https://stackoverflow.com/questions/17668265/gradlew-permission-denied

**Comment by domlimm** [comment]
Hello @jetlfj, I'm a senior from a previous batch. You may look specifically at [this](https://stackoverflow.com/a/49072563/6550688) from the link that @NicsunXnus added. Then run make sure to commit and push after.

Also, I checked my `gradlew` and `.github/workflows/gradle.yml` files against yours and there isn't any difference. The above should help fix your issue.

Let us know how it goes! 👍🏻

**Comment by damithc** [comment]
@jetlfj `chmod` is a Unix command. If you are on Windows, you can run Unix commands using the Gitbash terminal or the WSL terminal.

**Comment by jetlfj** [comment]
Thank you all for the help!

![image](https://user-images.githubusercontent.com/97273951/188259111-8ff4a182-6bf0-438e-9844-183432e9047c.png)

Here's what I did:

1. Open the terminal in IntelliJ (Alt + F12).
2. Enter `git update-index --chmod=+x gradlew`.
3. Commit the changes in Sourcetree (It will say "No changes in this file have been detected, or it is a binary file or it is configured to be ignored by the File patterns").
4. Push the commit.
