### ISSUE TITLE
A-CodingStandard tag cannot be detected in iP progress dashboard 

### ISSUE THREAD

**Issue by qiaoen17** [nus-cs2103-AY2223S1/forum#137]
I have tagged A-CodingStandard as shown below, and merged all branches to master, but I'm still not sure why the tag isn't detected. Any help would be appreciated.

![Screenshot (218)](https://user-images.githubusercontent.com/92434807/188257450-fe7e0b31-4884-4095-aa45-59220626c266.png)

**Comment by nehcuy** [comment]
Can you check if the tags are reflected on your forked repo? If it is not there, maybe try pushing the individual branches up to your forked repo.

**Comment by damithc** [comment]
@qiaoen17 that tag is not in https://github.com/qiaoen17/ip/tags
Probably you forgot to push the tag? Pushing a commit/branch doesn't push the tags automatically.

**Comment by qiaoen17** [comment]
Ah okay, thank you for the help!
