### ISSUE TITLE
Issue when running .jar file after implementing GUI

### ISSUE THREAD

**Issue by xav168** [nus-cs2103-AY2223S1/forum#138]
Hi, so I first encountered this issue after I tried to create a new .jar file using gradle. Running my code through gradle works fine, and the GUI will appear. However, once i made it into jar file I get this error. I have ensured my build.gradle has the required dependencies and my .jar file size is 11mb so it should have the javaFX dependencies inside. Any help would be appreciated thanks!

```java
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Bubbl3T** [comment]
Have you tried to build the JAR file using IntelliJ instead of Gradle?

**Comment by damithc** [comment]
@xav168 perhaps push the code to a branch in your fork and give the link here so that others can try to reproduce it?


> Have you tried to build the JAR file using IntelliJ instead of Gradle?

The final JAR needs to be generated using Gradle though.

**Comment by AllardQuek** [comment]
Hi @xav168, I am a senior from a previous batch dropping in to see if I can help. Could you clarify:

1. By "However, once i made it into jar file I get this error.", do you mean that you got this error while trying to open the jar file, or right after the jar file is built?
2. What were the steps/commands you used to build the jar file?
3. Could you share your build.gradle (or a link to it)?

These points might not necessarily be the underlying issue, but it would be good to include more details where possible to help with others reproducing the bug 🙂

**Comment by RussellDash332** [comment]
Hi @xav168, I managed to fork your repository and here's what I did:
1. Add images to `src/main/resources/images` accordingly
2. Generate the JAR from command line, i.e. `./gradlew shadowJar`
3. Run the JAR file located at `build/libs/duke.jar` by double-clicking it

After step 3, I managed to get this
![image](https://user-images.githubusercontent.com/63991775/188287053-192b96bc-8a2e-4cdf-99a4-4540e9f1c177.png)

So I guess what @AllardQuek said is true, you might need to specify how did you build the JAR file, so you can compare with what I did. Hope this helps!

**Comment by xav168** [comment]
Hi all, thank you for your help. I figured out that the problem was because I did not install javaFX in my build.gradle file, furthermore i read up online that javaFX 11 had issues with m1 macs which was what I was using and hence specified to use javaFX 18. Once I had done so I managed to create the .jar file and run it successfully.

**Comment by damithc** [comment]
> furthermore i read up online that javaFX 11 had issues with m1 macs which was what I was using and hence specified to use javaFX 18.

@xav168 this should not be a problem if you follow this advisory https://nus-cs2103-ay2223s1.github.io/website/admin/programmingLanguages.html
