### ISSUE TITLE
Unable to retake in-video quiz for Week 5.

### ISSUE THREAD

**Issue by ErvinK123** [nus-cs2103-AY2223S1/forum#139]
Hi Prof, I am unable to resubmit the in-video quiz for Week 5.4. This issue is similar to issue #49. Thanks!
![image](https://user-images.githubusercontent.com/65859484/188263077-338dbf43-f998-4c3c-ac72-e76400d51d4c.png)

**Comment by damithc** [comment]
@ErvinK123 thanks for the bug report. Fixed.
