### ISSUE TITLE
[A-TextUiTesting] What should happen if ACTUAL.TXT is different from EXPECTED.TXT

### ISSUE THREAD

**Issue by cliftonfelix** [nus-cs2103-AY2223S1/forum#14]
https://se-education.org/guides/tutorials/textUiTesting.html#:~:text=If%20the%20actual%20output%20differs%20from%20the%20EXPECTED.TXT%2C%20the%20script%20will%20report%20a%20failure.

On the page above it says:
If the actual output differs from the EXPECTED.TXT, the script will report a failure.

I tried to make the EXPECTED.TXT different from the actual output but the script doesn't report any failure, ACTUAL.TXT was created (or recreated).

**Comment by RussellDash332** [comment]
I think this is the supposed workflow, CMIIW.
1. Fill in the input at input.txt
2. Run runtest and copy the actual execution result to expected text file
3. Rerun runtest, should be passing now

**Comment by cliftonfelix** [comment]
@RussellDash332 but the thing is on the website it says the script will report a failure when EXPECTED.TXT is different from ACTUAL.TXT but I don't see any failure produced by the script

**Comment by RezwanArefin01** [comment]
@cliftonfelix Can you verify that they are different by opening the two files?

**Comment by cliftonfelix** [comment]
@RezwanArefin01 Yes, I also tried to put an empty EXPECTED.TXT and after running runtest.bat ACTUAL.TXT was replaced with a new one and no error reported

**Comment by RezwanArefin01** [comment]
@cliftonfelix Can you post the output you get from running the script?
I tried running the tests from your repository. It seems to work fine on my end.

**Comment by cliftonfelix** [comment]
@RezwanArefin01 I figured out why. 
It's because I double-clicked on runtest.bat file directly on the folder, so cmd opened and closed directly. 
Just now I tried to open cmd and run the .bat on cmd and I can see the output.

Thanks @RezwanArefin01 @RussellDash332

**Comment by RezwanArefin01** [comment]
@cliftonfelix You can add the command `PAUSE` at the end of the `.bat` file in a newline. Then you'll be able to run it by double clicking and it won't close.

**Comment by cliftonfelix** [comment]
@RezwanArefin01 Oh yea it works. Thanks haha

**Comment by damithc** [comment]
Thanks for the help @RezwanArefin01 and @RussellDash332
