### ISSUE TITLE
class file for javafx.event.EventTarget not found

### ISSUE THREAD

**Issue by linuschui** [nus-cs2103-AY2223S1/forum#140]
I followed the guide [given](https://se-education.org/guides/tutorials/javaFxPart1.html) but am running into this error when i run `Launcher`.
Will appreciate any help, thank you ! 😸 

(using i5 Mac)

<img width="938" alt="Screenshot 2022-09-03 at 6 43 20 PM" src="https://user-images.githubusercontent.com/97402389/188266911-efed18d6-64a8-4308-9cd4-a23b608400b6.png">

**Comment by jetlfj** [comment]
Can you try adding a default constructor for Duke? One that does not take in any parameters.

**Comment by maryjess** [comment]
I tried moving the `start` method to another class `Main`.
Then I simply changed the parameter of `launch()` in `Launcher` to be `Main.class`.

Works on my side!

**Comment by Donovan9617** [comment]
I moved the `start` method to another class `Main` as well, then I created the Duke object containing the file path from there!

**Comment by YH-15** [comment]
sry I am also not very sure about this (but i guess it might be cos JavaFX packages are not loaded properly), cos I did not run into this error b4, 
but in the end, we will be required to switch to use fxml (which is the 4th part of this tutorial), and sample code is given in the 4th part tutorial, you may take a look if applicable, essentially we don't need to change our initial implementation of Duke class if we use fxml.

**Comment by lfrostbytee** [comment]
I encountered an error (though I'm not sure if it has the same error code as yours). Just like the others, I shifted my `start` method to a separate class called `Main` instead of leaving it in `Duke`.

**Comment by linuschui** [comment]
Thank you all for you help !! @maryjess @Donovan9617 @YH-15 @lfrostbytee 
However, I am still encountering the same error 😢 

<img width="1133" alt="Screenshot 2022-09-06 at 1 11 58 PM" src="https://user-images.githubusercontent.com/97402389/188551882-a25cba73-e5f3-47b2-a657-81a06212464a.png">

**Comment by damithc** [comment]
@linuschui perhaps push your code to a branch and give the link here?

**Comment by linuschui** [comment]
@jetlfj Thank you for your help too ! The default constructor did not help either 😢 

<img width="924" alt="Screenshot 2022-09-06 at 1 14 07 PM" src="https://user-images.githubusercontent.com/97402389/188552146-34a0e3c1-22b4-4512-ae58-5c6f19be8013.png">

**Comment by linuschui** [comment]
@damithc Thank you Prof for the suggestion. I have pushed it here! https://github.com/linuschui/ip/tree/A-Debug

**Comment by sikai00** [comment]
@linuschui I was able to successfully run your program.  

<img width="808" alt="image" src="https://user-images.githubusercontent.com/63795894/188556041-328443c1-e565-4225-aee4-0eec34c4b7d7.png">  

Apologies as I don't have a solution for you, but you might want to check if your project structure and gradle settings in IntelliJ are configured properly.

**Comment by sikai00** [comment]
@linuschui I was also able to google a [past student's user guide](https://russell-loh-nus.github.io/duke/#faq) who faced the exact same issue. You might also want to give this a try

**Comment by damithc** [comment]
@linuschui While waiting for inputs from others, here are some 'common remedies' one-at-a-time in this order:
  * File -> Invalidate caches
  * Delete the .idea folder -> Close and re import the project
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by linuschui** [comment]
Hi @sikai00 thank you for the recommendation. I deleted my modules following the website and i got classnotfound exception
<img width="1429" alt="Screenshot 2022-09-06 at 2 02 26 PM" src="https://user-images.githubusercontent.com/97402389/188558409-f1656ba3-f69a-435a-9534-6464906dbf95.png">

my project structure looks like this now
<img width="1440" alt="Screenshot 2022-09-06 at 2 03 15 PM" src="https://user-images.githubusercontent.com/97402389/188558526-73d1acfb-7d2c-459b-a8e7-769f2c8118c7.png">

thank you for all your help I am getting very stressed out as my friends have not encountered this problem.

**Comment by damithc** [comment]
@linuschui Also try running it using the following ways:

a. Click this green button:
![image](https://user-images.githubusercontent.com/1673303/188563398-10fd7cd3-d7f3-44ef-b66f-4c252ea9cecd.png)

b. Use the terminal to run the command `./gradlew run`

**Comment by linuschui** [comment]
Thank you prof @damithc and fellow batchies for helping with this ! I have finally resolved it after 10 days 😸
