### ISSUE TITLE
CheckStyle named constants warning

### ISSUE THREAD

**Issue by cadencjk** [nus-cs2103-AY2223S1/forum#141]
I'm in the midst of converting magic numbers/Strings into [named constants](https://nus-cs2103-ay2223s1.github.io/website/se-book-adapted/chapters/codeQuality.html#avoid-magic-numbers) using the recommended naming convention:

```
private final int MINIMUM_COMMAND_LENGTH = 9;
```

However, CheckStyle raised many warnings with this convention.

![image](https://user-images.githubusercontent.com/63772723/188278868-7cc4e137-6cd9-4f52-9325-96fe0108d32a.png)

Is there a way to disable this particular warning?

**Comment by kxrt** [comment]
Hi! Constants require the `static` keyword too.

**Comment by cadencjk** [comment]
> Hi! Constants require the `static` keyword too.

Oh right! Thanks for the swift reply!  😄
