### ISSUE TITLE
Typo in Using GitHub Actions @SE-EDU/guides?

### ISSUE THREAD

**Issue by Hikoya** [nus-cs2103-AY2223S1/forum#142]
In the guide on setting up Github Actions, it was mentioned that the .yml file should be placed in the `[root]\.workflows` folder. However, shouldn't it be in the `[root]\.github\workflows` folder instead?

![image](https://user-images.githubusercontent.com/13346668/188284332-4d3ae819-7f36-4422-8ed8-0cdb29d4d1b1.png)

![image](https://user-images.githubusercontent.com/13346668/188284368-e3ec18e3-fce0-4eca-afd3-59fa7112aa66.png)

**Comment by RussellDash332** [comment]
By right, it should be placed in `[root]\.github\workflows`. However, it's not a necessary condition.

[This repository](https://github.com/RussellDash332/test-repo/actions) tests how you can setup GitHub Actions without putting the YAML file on that directory structure.

You can do it manually by creating a workflow, choose "setup a workflow by yourself", and edit the YAML file as you wish.
![image](https://user-images.githubusercontent.com/63991775/188287343-38abf679-2458-4997-b6a7-2197b32402aa.png)

**Comment by damithc** [comment]
Thanks both @Hikoya @RussellDash332 for the inputs on this.
I've fixed it.
