### ISSUE TITLE
Gradle help

### ISSUE THREAD

**Issue by PokezardVGC** [nus-cs2103-AY2223S1/forum#144]
Added Gradle and having issue running my code. Works fine normally just after adding not sure what happen, in fact I am not too sure if I have install Gradle correctly
code has been pushed, refer to master branch

https://github.com/PokezardVGC/ip

Error that I gotten: 
Task 'Duke.main()' not found in root project 'Lab 2'.

**Comment by sltsheryl** [comment]
Hi it’ll be clearer if you can specify the issue or error, but it seems like you don't have the build.gradle file.
The other comments are referring to this, it really helped me so you can check it out too.
https://github.com/nus-cs2103-AY2223S1/forum/issues/55

**Comment by leonidas1712** [comment]
I think if you did it correctly, your root directory should have the build.gradle file from the [add-gradle-support](https://github.com/nus-cs2103-AY2223S1/ip/tree/add-gradle-support) branch of the original repo. 

Maybe you could delete the files you added (or [undo changes](https://www.atlassian.com/git/tutorials/undoing-changes) with Git) and try again?

**Comment by Eclipse-Dominator** [comment]
Hello, not sure if the issue has been resolved but I took a look at your `build.gradle`, reminder to update the `mainClassName` to point to the correct path based on your current pathing which should be `duke.Duke`

**Comment by PokezardVGC** [comment]
Hi guys, I've cleared the problem. Apprently I had 2 gradles installed. Thnaks for the inputs though

**Comment by yuehernkang** [comment]
> Hi guys, I've cleared the problem. Apprently I had 2 gradles installed. Thnaks for the inputs though

Hello Pokezard, may I know how did u check you had 2 gradles installed? I am having some issue with my gradle too. Thanks!
