### ISSUE TITLE
Requirements for clearing Use GFMD tag

### ISSUE THREAD

**Issue by deeyonn** [nus-cs2103-AY2223S1/forum#145]
Hi all, I've noticed on the iP dashboard that my progress for the `!Use GFMD` tag has not been completed even though I have edited my `README.md`.

Is there any additional task that I have to complete i.e., create and push a tag `Use GFMD` on the commit i made to edit `README.md`?

**Comment by t1mzzz** [comment]
Hi Deon, GFMD is meant to be used in your PR description, not your README.md. Hope this helps.

**Comment by deeyonn** [comment]
> Hi Deon, GFMD is meant to be used in your PR description, not your README.md. Hope this helps.

Thank you for the clarification, I will update the PR description.
