### ISSUE TITLE
Clarification regarding number of tasks done in PR

### ISSUE THREAD

**Issue by anuanas2007** [nus-cs2103-AY2223S1/forum#146]
![photo_2022-09-05_19-17-16](https://user-images.githubusercontent.com/97455187/188437204-1969ddf3-b451-490d-ae0a-5af81c3a4028.jpg)
![photo_2022-09-05_19-17-29](https://user-images.githubusercontent.com/97455187/188437212-1384d9f1-5de1-4793-8d43-8576eb5605be.jpg)
![photo_2022-09-05_19-25-55](https://user-images.githubusercontent.com/97455187/188438286-ca3c71ce-3500-4cbf-94e3-0af0fd57798d.jpg)

Could someone explain what the number of tasks represents in the PR? For a few students it's shown tasks are done and for a few, there is nothing written.

**Comment by riccqi** [comment]
It is displayed when there are checkboxes added to the PR description, and will update as you check items off. GitHub is quite smart with this haha

**Comment by anuanas2007** [comment]
Thank you for the clarification.
