### ISSUE TITLE
Wrong branch name for Level-10

### ISSUE THREAD

**Issue by april-anh** [nus-cs2103-AY2223S1/forum#149]
I accidentally named the branch `Level-10` instead of `branch-Level-10`. Hence, the merged branch was not detected in the IP dashboard. I just realized that but now it is already marked as overdue. Are there any things I can do to fix it?

**Comment by RussellDash332** [comment]
You can see [this comment](https://github.com/nus-cs2103-AY2223S1/forum/issues/89#issuecomment-1229195856) on how to rename a branch

**Comment by april-anh** [comment]
Thanks, @RussellDash332  But if I rename it now, the dashboard still reflects as overdue, is it?

**Comment by damithc** [comment]
> Thanks, @RussellDash332 But if I rename it now, the dashboard still reflects as overdue, is it?

@april-anh It will turn green at the next dashboard update.

**Comment by RussellDash332** [comment]
> Thanks, @RussellDash332 But if I rename it now, the dashboard still reflects as overdue, is it?

Yup, as Prof said, those are soft deadlines so that you can keep on track 💪🏻

**Comment by april-anh** [comment]
Thank Prof @damithc  and @RussellDash332. The problem is resolved.
