### ISSUE TITLE
'Next Week' button is not visible in mobile view

### ISSUE THREAD

**Issue by Punpun1643** [nus-cs2103-AY2223S1/forum#151]
Happened to encounter this when I looked at the website on my phone. The 'Next Week' button is not visible on mobile, making it quite difficult to navigate to next week's content. There are some workarounds though e.g. rotate to view in horizontal view, or navigate using the schedule dropdown 😄

<img src="https://user-images.githubusercontent.com/60144099/188866600-d0029bc5-683b-4112-be11-d1173633fcbe.jpeg"  width="300" height="600"/>

**Comment by RussellDash332** [comment]
You'r'e right 😮 the ad-hoc solution is to indeed rotate it into landscape mode, but still I suppose they need to make the div smaller in size 😅

**Comment by damithc** [comment]
Thanks for the @Punpun1643 @RussellDash332 
Will put on our todo list -- but low priority due to low incidence rate and the existence of a workaround
