### ISSUE TITLE
Codecov bot not commenting on TP pull request

### ISSUE THREAD

**Issue by vvidday** [nus-cs2103-AY2223S1/forum#154]
Hi all,

The Codecov bot didn't comment on [our team's PR](https://github.com/nus-cs2103-AY2223S1/tp/pull/9) (this is true for a few other teams as well).

The [Codecov page](https://app.codecov.io/gh/nus-cs2103-AY2223S1/tp/pulls) seems to not identify the affected PRs correctly (empty avatar & no title), and clicking on the PR displays "CI Failed" with no further information, even though the CI passes on github actions.

Would appreciate any help on this issue!

**Comment by damithc** [comment]
@vvidday from our side, we don't use the codecov data for anything. So, this doesn't affect anything related to grading. 

You can wait a while to see if this a temporary problem on codecov side that will get rectified after a while.

**Comment by vvidday** [comment]
Thanks Prof! Will close the issue for now.
