### ISSUE TITLE
./gradlew shadowbar

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S1/forum#155]
![image](https://user-images.githubusercontent.com/77482097/189088448-b3ef34ec-5f7a-4d9d-833a-f1f84009cee8.png)

i am trying to create a jar file using the gradle method. Any idea how to fix? 

here are my settings:
![image](https://user-images.githubusercontent.com/77482097/189089754-f71b6e7a-86f6-4b0b-aca6-1b62a0421a29.png)

:bulb: You can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format your text

**Comment by junlee1991** [comment]
https://github.com/junlee1991/ip/tree/Temp
I made a branch called temp

**Comment by lulucopter** [comment]
Hello, I took a look at your repo, and I suspect it is because of how your packages are structured, and gradle is unable to find your files. 
Perhaps you can consider nesting your non-main packages such as `commands` and `exceptions` into your main `duke` package? That might fix the issue

**Comment by junlee1991** [comment]
![image](https://user-images.githubusercontent.com/77482097/189479756-acffa219-9d05-4047-b5c7-ad4842127aa0.png)

I just had to change one line from gradle 6.2 to 6.3. Wasted a lot of time because of this. 
https://stackoverflow.com/questions/61289461/java-lang-noclassdeffounderror-could-not-initialize-class-org-codehaus-groovy-v
