### ISSUE TITLE
daemon, caches, native, wrapper

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S1/forum#156]
![image](https://user-images.githubusercontent.com/77482097/189090969-88f3faf4-ccb3-4fcd-809d-e7fd093675c8.png)

Do i stage daemon, etc. I am still new to gradle. I dont see anyone else doing it though.

**Comment by damithc** [comment]
@junlee1991 While waiting for peer help, perhaps it might help to state how did you add gradle support to your project. Did you merge the `add-gradle-support` branch as instructed (see below)?

![image](https://user-images.githubusercontent.com/1673303/189121135-4fe3c7ba-5c17-4e90-9991-f3f755e31b83.png)

**Comment by junlee1991** [comment]
Hi Prof, thank you for the prompt reply. I merged the branch according to https://github.com/nus-cs2103-AY2223S1/forum/issues/55  then git push. 

I find the gradle more laggy to run through though. 

My last resort will be to revert to pre -gradle and redo the whole thing again.

**Comment by damithc** [comment]
@junlee1991 Something is not right. Your master branch has only 7 commits! https://github.com/junlee1991/ip/commits/master

**Comment by junlee1991** [comment]
I already deleted the old Ip. Please check again. It should reflect more commits in my repo
https://github.com/junlee1991/ip/commits/master

**Comment by junlee1991** [comment]
https://github.com/junlee1991/ip/tree/Temp 
I made a branch called temp

**Comment by damithc** [comment]
@junlee1991 does the problem still remain?

**Comment by junlee1991** [comment]
@damithc I'm still figuring out how to remove it from untracked files.

**Comment by junlee1991** [comment]
git clean -fd
and committing from the IDE seem to be an easier solution.
