### ISSUE TITLE
JAR file getting weird characters

### ISSUE THREAD

**Issue by elizabethhky** [nus-cs2103-AY2223S1/forum#157]
Context: 
Mac M1 chip, Project SDK: OpenJDK version 11.0.2

When I run the new JAR file created for my GUI, my text field gets weird characters but the rest of the other components (the dialogbox) shows the text normally and an error pops up in the terminal.
The MainWindow run by java -jar:
<img width="401" alt="Screenshot 2022-09-08 at 6 21 32 PM" src="https://user-images.githubusercontent.com/97357632/189098528-a14b117a-8fa7-428a-9eb8-0d5ebef08883.png">
The Error:
<img width="1461" alt="Screenshot 2022-09-08 at 6 22 23 PM" src="https://user-images.githubusercontent.com/97357632/189098674-43b58236-6190-4b8e-bb81-bc8155c2d15b.png">

I suspected that it was my SDK version but I have already set it to be OpenJDK version 11.0.2. However, when I run `java -version` in my ip terminal, it says that my version is version 11.0.16.1
<img width="658" alt="Screenshot 2022-09-08 at 6 20 08 PM" src="https://user-images.githubusercontent.com/97357632/189098234-0187ebdf-dd6f-4b17-9b07-ae98197dd012.png">

I am quite confused because when I run my Launcher.main() normally, without java -jar, the weird characters do not appear.
The MainWindow ran by running Launcher.main():
<img width="400" alt="Screenshot 2022-09-08 at 6 24 04 PM" src="https://user-images.githubusercontent.com/97357632/189099014-db44a88e-645b-4259-a112-b566d512a2cd.png">

I also tried changing my fxml file to have the font Arial instead of Lucida Grande but it does not seem to work. Any help would be much appreciated!

**Comment by RussellDash332** [comment]
#104 #117 #125 might help you resolve the issue!

**Comment by linuschui** [comment]
I have not reached that stage yet but you can try changing your SDK to the Zulu one recommended by the module [here](https://nus-cs2103-ay2223s1.github.io/website/admin/programmingLanguages.html) then go to File -> Project Structure and change it to zulu !! 😸 
<img width="839" alt="Screenshot 2022-09-08 at 8 45 09 PM" src="https://user-images.githubusercontent.com/97402389/189125051-2c31834e-0265-4026-9c77-285e0b768a9f.png">
<img width="549" alt="Screenshot 2022-09-08 at 8 49 02 PM" src="https://user-images.githubusercontent.com/97402389/189125845-fd9eb343-ccfe-4137-bb28-006953222191.png">

**Comment by elizabethhky** [comment]
Thank you so much for the suggestions! It worked 😊
