### ISSUE TITLE
Minimal Requirement for Level-10

### ISSUE THREAD

**Issue by shawnkai** [nus-cs2103-AY2223S1/forum#158]
@damithc  Hi Prof, May I check the minimal requirements for Level 10- implementing a GUI and whether it is compulsory to use FXML? Cuz it's quite easy to just keep going and not knowing where to stop so just checking. Thanks in advance!

**Comment by damithc** [comment]
@shawnkai The minimum requirement is a working GUI. It is strongly recommended to use FXML, as the tP uses FXML (the aim of the iP is to prepare you for the tP).

**Comment by shawnkai** [comment]
ok thanks prof!
