### ISSUE TITLE
How to "change" our head

### ISSUE THREAD

**Issue by PokezardVGC** [nus-cs2103-AY2223S1/forum#159]
![image](https://user-images.githubusercontent.com/71965541/189163492-21fbd239-6628-4be0-8159-cb017df5069a.png)
Hi guys, wondering how do we "shift" our master to where we are now in github? I think I accidnetally left master out while merging

**Comment by damithc** [comment]
@PokezardVGC Perhaps you can tick this option and take the screenshot again so that others can see where the master branch is in your repo?

![image](https://user-images.githubusercontent.com/1673303/189167145-667aaf69-2b77-42c6-958d-3d015ecf7eb2.png)

**Comment by PokezardVGC** [comment]
![image](https://user-images.githubusercontent.com/71965541/189168040-6318c553-e03b-47cb-b599-224652620a83.png)

Attached is the remoted branches shown

Hi prof, I've actually created a branch form my current headless branch, checked out with the master branchm, deleted all the files in master branch and merged master branch to the current headless branch. Managed to get it settled but beleive this is far from the right way to do it

**Comment by damithc** [comment]
@PokezardVGC Glad to hear you fixed it. If there are remaining doubts about Git usage, you can post specific queries here (e.g., 'How to do X?') so that others can join in the discussion with their inputs.

**Comment by PokezardVGC** [comment]
Thanks prof, though was a rather improvised solution managed to get it to weork.
