### ISSUE TITLE
iP branches not detected in iP dashboard

### ISSUE THREAD

**Issue by drkkjh** [nus-cs2103-AY2223S1/forum#160]
Hi, I have merged via PR on my own fork and pushed the branches `branch-A-Assertions` and `branch-A-CodeQuality`. The tags on my main branches are detected but somehow the branches `branch-A-Assertions` and `branch-A-CodeQuality` are not detected. I have cloned my own repo and verified that I have pushed.

The screenshots below show that I have pushed my branches:
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/61372278/189279664-7162c981-ec15-416e-acb2-24124b8c015d.png">

However, for every pull request, I have also accidentally merged the branches `branch-A-Assertions` and `branch-A-CodeQuality` with main resulting in the following sourcetree graph:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/61372278/189280897-2115e76d-f37f-40b6-b7be-afe9dd603ac0.png">

Any help would be greatly appreciated! 🥲

**Comment by damithc** [comment]
@drkkjh Partial answer (leaving the rest for peers):

Only merged branches are counted by the dashboard. These are not considered merged, as the tip of the branch stands on its own.
![image](https://user-images.githubusercontent.com/1673303/189281830-8d015802-8861-42dd-8349-17a963c4f290.png)

**Comment by bryanngzh** [comment]
Hi @drkkjh, I think you can try merging the above 3 branches to your master branch.

**Comment by drkkjh** [comment]
Thanks prof and @bryanngzh for the help! I have merged and will wait for the next dashboard update to verify again.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/61372278/189284423-3d20016a-4d29-45a5-a1aa-58616ab609ae.png">
