### ISSUE TITLE
Seeking clarification regarding Luminus Quiz week 6 questions 27 and 30

### ISSUE THREAD

**Issue by Nephelite** [nus-cs2103-AY2223S1/forum#161]
The area of confusion for me is the line
'A call to f() can result in any of the following'.
which can be interpreted as
A call to f() can result in (any of the following) -> All listed results are valid outcomes of f()
or
A call to f() can result in any (of the following) -> At least 1 listed result is a valid outcome of f()

I believe the intention is the former, but I would just like a confirmation that the former interpretation is the intended one.

**Comment by damithc** [comment]
@Nephelite you are correct; it's the former.

**Comment by Nephelite** [comment]
@damithc Thank you for the clarification prof!
