### ISSUE TITLE
CI checks unsuccessful

### ISSUE THREAD

**Issue by Shawn532** [nus-cs2103-AY2223S1/forum#162]
<img width="1728" alt="first" src="https://user-images.githubusercontent.com/77186068/189378338-9a9a577e-389a-4c11-9032-367241d73def.png">
<img width="1630" alt="first 2" src="https://user-images.githubusercontent.com/77186068/189378396-71b0854c-feac-4ffc-b27f-f8680f52ff1e.png">

I couldn't pass the CI checks for the ip. It shows an error cannot find symbol Main.class, but I have class Main in my code, and when I run 
`./gradlew check`
in intellij it doesn't show an error message. I am very confused. Can someone please kindly help?

**Comment by damithc** [comment]
@Shawn532 you might want to give the link to the page shown in the second screenshot

**Comment by hauchongtang** [comment]
There is no Main class in your master branch, have u pushed it ?

**Comment by Shawn532** [comment]
> There is no Main class in your master branch, have u pushed it ?

I realized I somehow accidentally added the Main class in .gitignore file earlier. After fixing that, I passed the CI. Thank you very much!
