### ISSUE TITLE
Cannot seem to push my master branch with my tag

### ISSUE THREAD

**Issue by DarrenCsAcc** [nus-cs2103-AY2223S1/forum#163]
Hi all i was trying to push my commits into git and it gave me this error and i am not sure what it means.I cannot seem to push my master branch together with my tag.

I saw my current branch in the same repository but it says "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

Thank you!

![image](https://user-images.githubusercontent.com/89026703/189396924-1ef6cb01-da92-4c5b-a338-15ad996c88b0.png)

**Comment by DarrenCsAcc** [comment]
![image](https://user-images.githubusercontent.com/89026703/189397916-13b4d106-4aae-45ca-8cb1-e4885c895100.png)
My tag is available but it shows this and my master branch is not updated for some reason.It feels like only the tag is being pushed.

**Comment by seelengxd** [comment]
i was looking at this [commit](https://github.com/DarrenCsAcc/ip/commit/76bee7a8d4d81f6bd22961a8230489896e4c18a8) and can't find it on both `master` and `branch-level-7`

hmm

1. is the commit on your branch and not pushed / is branch-level-7 updated?
2. is this branch merged yet?

might be relevant but when i try to clone this repo and look at the graph i see this

<img width="710" alt="image" src="https://user-images.githubusercontent.com/34371483/189399666-67bb3fe9-4298-47f8-9b38-07dabd4b9183.png">

**Comment by lulucopter** [comment]
A quick fix/hack you can consider doing is doing a `git clone` to sync your local repo with your online repo. May not be the best method or address the problem at its root but it does fix the problem if you are desperate

**Comment by DarrenCsAcc** [comment]
Thanks @seelengxd and @lulucopter for the reply!

Sorry i am not super familiar with github and i am using sourcetree now.

This is what i see in sourcetree. @seelengxd 
![image](https://user-images.githubusercontent.com/89026703/189466867-7100dd6f-f3f4-42f9-a145-763e4ba9d7b0.png)

@lulucopter 
When i git-clone it will be my whole repository right?I will just do what i first did when i set up the ip?

Thank you.

**Comment by DarrenCsAcc** [comment]
I am trying to merge all the branch now. I did not do some properly so i think i have multiple merge conflict :( Will update you guys on how it goes

**Comment by DarrenCsAcc** [comment]
Hi all, 

I tried merging the branch now i seem able to do it.But i don't know if i am doing it correctly..
Was wondering is there some way to check if i am doing it the right way :(
This is my current Sourcetree

![image](https://user-images.githubusercontent.com/89026703/189467348-7a910b0c-0300-441d-8a73-6a7cf744c086.png)



Thank you!

**Comment by DarrenCsAcc** [comment]
Thank everyone for your help and time reading, for now, i think it is fine I will let you guys know if there are any more issues.
Once again thank you!
