### ISSUE TITLE
Can't seem to execute JAR file

### ISSUE THREAD

**Issue by tinenhao** [nus-cs2103-AY2223S1/forum#164]
I have successfully generated a jar file using Gradle shadowJar, however, the generated jar file can't seem to run (when I try to open it nothing happens). Not sure what I should do as I have included the relevant commands as instructed in the website,

**Comment by Echomo-Xinyu** [comment]
You may consider checking whether you can run your application via Gradle as mentioned in my earlier post #152

**Comment by tinenhao** [comment]
This was exactly my problem. Thank you!
