### ISSUE TITLE
Sourcetree cannot push gradle.yml to fork

### ISSUE THREAD

**Issue by Benjamin-Sim** [nus-cs2103-AY2223S1/forum#165]
When trying out A-CI, I created the gradle.yml file on my Master branch on my local machine (I'm using Windows). However, Sourcetree gave me this error when I tried to push the changes to my fork.

![Capture](https://user-images.githubusercontent.com/92283593/189474496-bac4cbcf-d238-4db4-8343-fa005d77cd12.PNG)

It seems that GitHub recognizes that the path `.github/workflows` contains workflow files and hence denies my Sourcetree client from pushing files to that directory since my Sourcetree client doesn't have the required 'workflow' scope permissions.

I tried looking in my GitHub settings to see if I can give Sourcetree 'workflow' scope permissions but I couldn't find anything.

Any help would be appreciated, thanks!

**Comment by damithc** [comment]
@Benjamin-Sim Something related: When you create a GitHub personal access token (PAT), you can specify which actions it can be used for.

**Comment by Benjamin-Sim** [comment]
> @Benjamin-Sim Something related: When you create a GitHub personal access token (PAT), you can specify which actions it can be used for.

Hi Prof @damithc, yes I've also tried creating a PAT with the 'workflow' permissions. But I couldn't find a place to enter it when linking my Sourcetree client with my GitHub account.

I followed Option 1 at [this guide](https://se-education.org/guides/tutorials/sourcetree.html#on-windows) to link Sourcetree with my GitHub account, and I was only prompted to enter my GitHub email and password to login. After that, my Sourcetree client was automatically linked and I wasn't asked to input any PAT.

Is there another way to link Sourcetree with GitHub that allows me to specify what PAT to use?

**Comment by kxrt** [comment]
[This](https://community.atlassian.com/t5/Sourcetree-questions/How-do-I-use-a-personal-access-token-PAT/qaq-p/1263836) and [this](https://community.atlassian.com/t5/Sourcetree-questions/Adding-a-github-personal-access-token-to-sourcetree/qaq-p/1755393) post from the Atlassian forums mention placing the PAT in your password field when using basic auth. Perhaps try that?

Alternatively, if all else fails, you could manually add the file from the GitHub website and pull to refresh changes.

**Comment by Benjamin-Sim** [comment]
> [This](https://community.atlassian.com/t5/Sourcetree-questions/How-do-I-use-a-personal-access-token-PAT/qaq-p/1263836) and [this](https://community.atlassian.com/t5/Sourcetree-questions/Adding-a-github-personal-access-token-to-sourcetree/qaq-p/1755393) post from the Atlassian forums mention placing the PAT in your password field when using basic auth. Perhaps try that?
> 
> Alternatively, if all else fails, you could manually add the file from the GitHub website and pull to refresh changes.

Hi @kxrt, I tried using basic auth using my PAT as the password and it works! Thanks for your help!

Although, I wonder how other students who use the regular OAuth push workflow files. I'm guessing there is a cleaner way of granting 'workflow' permissions?

The awkward thing I notice about PATs is that GitHub recommends that you create them with an expiry date. So it looks like I have to generate a new PAT and relink Sourcetree with GitHub everytime the PAT expires. In contrast, the regular OAuth doesn't seem to have this expiry date issue.

So I'm curious if there are any other solutions to this problem.

**Comment by kxrt** [comment]
Glad to see it worked!

One way to get past the PAT expiry issue is using Git CLI and connecting over SSH.

**Comment by Benjamin-Sim** [comment]
> Glad to see it worked!
> 
> One way to get past the PAT expiry issue is using Git CLI and connecting over SSH.

I see, but does that use OAuth? And does it give 'workflow' permissions too?

**Comment by kxrt** [comment]
> > Glad to see it worked!
> > One way to get past the PAT expiry issue is using Git CLI and connecting over SSH.
> 
> I see, but does that use OAuth? And does it give 'workflow' permissions too?

OAuth is a separate authentication system from SSH. SSH keys are generated on a different page from OAuth tokens in your Settings. And yep, it does give the `workflow` permission - I use it myself. I recommend reading up on [this](https://stackoverflow.com/questions/67077837/in-what-ways-is-an-ssh-key-different-from-tokens-for-git-authentication) post for a quick description of the differences in the two. PAT is probably safer since it's limited in comparison.

**Comment by Benjamin-Sim** [comment]
> > > Glad to see it worked!
> > > One way to get past the PAT expiry issue is using Git CLI and connecting over SSH.
> > 
> > 
> > I see, but does that use OAuth? And does it give 'workflow' permissions too?
> 
> OAuth is a separate authentication system from SSH. SSH keys are generated on a different page from OAuth tokens in your Settings. And yep, it does give the `workflow` permission - I use it myself. I recommend reading up on [this](https://stackoverflow.com/questions/67077837/in-what-ways-is-an-ssh-key-different-from-tokens-for-git-authentication) post for a quick description of the differences in the two. PAT is probably safer since it's limited in comparison.

Ah I see, thanks for explaining!
