### ISSUE TITLE
Error when using FXML 

### ISSUE THREAD

**Issue by ReubenChay** [nus-cs2103-AY2223S1/forum#166]
Hi! I followed the guide and everything seems to be in place. However, when I try to run Launcher, I get this error: 

`javafx.fxml.LoadException: `
(followed by a huge list of failure to load all the required variables) 
`Caused by: java.lang.reflect.InvocationTargetException`
`Caused by: java.lang.NullPointerException: Input stream must not be null`

I pushed my commit to my fork found here: https://github.com/ReubenChay/ip
Any help would be greatly appreciated!

**Comment by cliftonfelix** [comment]
Hi @ReubenChay, it seems like your dukeImage name is meseeks.png but inside your MainWindow.java, you put an extra "e" after "me" (meeseeks.png).

I tried to remove the extra e and it works fine

![image](https://user-images.githubusercontent.com/88199596/189488224-b3a273e9-db3d-4f81-a089-f567b00c99f6.png)

**Comment by ReubenChay** [comment]
oh i see, thanks for spotting this! @cliftonfelix
