### ISSUE TITLE
Typo in Week 6 Topics notes

### ISSUE THREAD

**Issue by nehcuy** [nus-cs2103-AY2223S1/forum#168]
Under Week 6's Topic of "Modeling: Sequence Diagrams",
`Tools → UML → Sequence Diagrams → Parallel paths`
I was just wondering if the `LocalServer#poll()` method was actually referring to the `poll()` method under `LocalData` instead?
I've attached an image to better illustrate the issue:
![image_2022-09-11_00-07-25](https://user-images.githubusercontent.com/94856691/189492034-78d157e9-fbbc-4ebb-becd-cee50b04a9e3.png)

CMIIW, but I believe `LocalServer#poll()` should have been `LocalData#poll()` instead.

**Comment by damithc** [comment]
Good catch @nehcuy 
Fixed.
