### ISSUE TITLE
cloning with SourceTree produces an error

### ISSUE THREAD

**Issue by rgonslayer** [nus-cs2103-AY2223S1/forum#17]
While cloning my repo using SourceTree after forking, I ran into this error and I am not sure how to resolve it even after googling the issue. 

'hg clone git@github.com:rgonslayer/jarvis.git /Users/dylenchew/jarvis 
Couldn't posix_spawn: error 2
Completed with errors, see above'

From what I can find, it has to do with my Python version being changed from an update on MacOS. For further diagnostic information, I am running an Intel Mac on version 12.5. 

Would appreciate any help as it is preventing me from starting on my ip!

**Comment by damithc** [comment]
>'hg clone [git@github.com](mailto:git@github.com):rgonslayer/jarvis.git /Users/dylenchew/jarvis

Two problems: 
1. `hg clone ...` means you are using Mercurial not Git (both are supported by Sourcetree). It should read `git clone ...`
2. Although not related to your current problem, the fork should keep the original name `ip`, not rename to `jarvis`.

**Comment by rgonslayer** [comment]
im not sure how to change from mercurial to git in sourcetree, it seems to default to mercurial as I clone

**Comment by damithc** [comment]
> im not sure how to change from mercurial to git in sourcetree, it seems to default to mercurial as I clone

@rgonslayer From what I remember, the choice of hg (hg is short for Mercurial) and/or git is made during the installation. Perhaps you can uninstall and install again, but this time omit hg and select the git option only?
