### ISSUE TITLE
Questions about Reuse Policy

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#170]
1. Is using code generated for Codecov badge considered reuse under reuse policy?
1. Is a separate credits file for where the third-party resources come from (e.g. profile pic images in iP), considered giving sufficient credit to the original author?

**Comment by damithc** [comment]
@cheeheng 

> * Is using code generated for Codecov badge considered reuse under reuse policy?

No

> * Is a separate credits file for where the third-party resources come from (e.g. profile pic images in iP), considered giving sufficient credit to the original author?

OK to use a separate file but the intention is to _openly_ and _visibly_ acknowledge reuse i.e., not don't hide them away somewhere in an obscure file

**Comment by cheeheng** [comment]
Thanks so much Prof. I have another question regarding the reuse policy:
Is reusing configuration file code (or parts of it) considered reuse under reuse policy (e.g. when using [this file](https://github.com/se-edu/duke/blob/full-template/.github/workflows/gradle.yml) to set up GitHub Continuous Integration)?

I believe it is important to make clear which is considered reuse and which is not so as to reduce the risk of miscommunication.

**Comment by damithc** [comment]
@cheeheng If in doubt, acknowledge as reuse as there is no harm in doing so.

**Comment by cheeheng** [comment]
Thanks prof!
