### ISSUE TITLE
[Week 6 quiz] Is the constructor's activation bar required to be connected to the entity box?

### ISSUE THREAD

**Issue by parnikkapore** [nus-cs2103-AY2223S1/forum#171]
Is the constructor's activation bar required to be connected to the entity box? All diagrams in the textbook excerpts have the bar connected, but the diagrams in the quiz have them disconnected.

Neither the textbook nor the video addresses this. I've looked at a few websites, and it looks like the representation of Java-style constructors is unspecified and there is no definite consensus on this point. I've seen both connected and disconnected bars on those sites.

**Comment by jhchee18** [comment]
Hi, I think Prof Damith does address this in this [video](https://mediaweb.ap.panopto.com/Panopto/Pages/Viewer.aspx?id=7aefe728-a7ad-4871-86b8-ac3000bcf7d1&start=691.104055) 11:30, where he mentioned the constructor's activation bar is connected to the entity box.

**Comment by damithc** [comment]
> but the diagrams in the quiz have them disconnected.

@parnikkapore this is not correct. Most likely you are mistaking activation bars of regular method as activation bars of constructors.

**Comment by parnikkapore** [comment]
The problematic bar is the red bar on question 20. Judging by jhchee18's comment, I think I lost a point for this quiz 😁

Closing as answered.

**Comment by damithc** [comment]
> The problematic bar is the red bar on question 20. Judging by jhchee18's comment, I think I lost a point for this quiz 😁

The correct answer is `False` :-)
