### ISSUE TITLE
storage and opening message issue with GUI 

### ISSUE THREAD

**Issue by ReubenChay** [nus-cs2103-AY2223S1/forum#172]
Hi! I'm facing some issues when using the GUI. Firstly, when the window opens, no opening message eg. "Hi, I'm Duke!" appears until I type in some command. Secondly, it keeps loading new storage files for the lists ie. doesn't re-load the old task lists stored in a file to use. 

These work when I run it normally in my CLI, but it doesn't work with the GUI. Anyone knows how to fix this? 
Your help is greatly appreciated :) 

Link to github: https://github.com/ReubenChay/ip

**Comment by jhchee18** [comment]
Hi, regarding the first issue, I think you should initialize the greeting by adding a new dialog box in the `public void initialize()` method in MainWindow.java.

For the second issue, when you construct the Duke instance, the Duke should read (by using `.load()` method in Storage class) the old task lists stored in the .txt file if the .txt file is not empty, else you should only initialize the taskList to be a new empty TaskList.

**Comment by ReubenChay** [comment]
@jhchee18 thanks! i managed to fix the first issue. The 2nd issue is a bit trickier, guess I didnt explain it well. 

When i load up the GUI and type "list" it will say there are no tasks in the list. When i add some tasks, and then type list, these tasks will appear. At the same time, if i look at my tasks.txt file, these tasks are actually being added to the file. If i reload the GUI again, it will start off with a new list that is empty, but adding further tasks will still modify this original tasks.txt file properly. It's like everytime i load the GUI it starts off with a new list but any actions will still modify tasks.txt 

For eg, if tasks.txt has 3 tasks in it and i run the GUI and type list, it will say no tasks in the list. If i add another 2 tasks to it and type list, on the GUI it will show i have these 2 tasks. But in the tasks.txt file there are now 5 tasks. If i re-load the GUI and start again it says no tasks. 

If i run it in intellij, all the tasks appear as per normal when reading from tasks.txt 
Not sure if this is related but if i input "bye" in intellij the program ends as intended. If i input "bye" in the GUI it will send the goodbye message but the GUI will not close 

Hope this doesn't sound too confusing..

**Comment by ReubenChay** [comment]
for reference, here it is working fine if i run it in intellij, loading up the tasks already stored in my file, and then when i load it using my GUI, it shows no tasks: 
<img width="426" alt="Screenshot 2022-09-11 at 11 44 08 PM" src="https://user-images.githubusercontent.com/77574488/189536520-f824bfd3-0289-48a8-97d8-18d96adf78aa.png">

<img width="399" alt="Screenshot 2022-09-11 at 11 44 48 PM" src="https://user-images.githubusercontent.com/77574488/189536556-6c77a36b-77c8-4611-9b05-3fe1d126420e.png">

**Comment by teekaytai** [comment]
Looks like you simply forgot to call `storage.openFile()` and `storage.listInit(taskList.getList())`. You only call it in your `run` method which is why it works for your CLI app. Meanwhile, `getResponse` doesn't call `run`.

Perhaps this is a sign that these methods should be called inside Duke's constructor instead?

**Comment by ReubenChay** [comment]
@teekaytai hi! i was under the impression that when Launcher launches, it actually calls the main method which will call run(), so I thought I didn't need to add it there. Thanks for clearing up this misconception. It's fixed now, thanks for the help!

**Comment by damithc** [comment]
> Looks like you simply forgot to call `storage.openFile()` and `storage.listInit(taskList.getList())`. You only call it in your `run` method which is why it works for your CLI app. Meanwhile, `getResponse` doesn't call `run`.
> 
> Perhaps this is a sign that these methods should be called inside Duke's constructor instead?

Thanks for the in-depth investigation, @teekaytai 💯
