### ISSUE TITLE
Clarification regarding the detection of final JAR release

### ISSUE THREAD

**Issue by Nephelite** [nus-cs2103-AY2223S1/forum#173]
In Week 5, the first task said that a JAR release was optional (and we were welcome to). I released by JAR file because I felt compelled to.

Now in Week 6, the progress tracker detected my Week 5 release before I finished by Week 6 release (which I have finished at the time of writing).

I just wanted to seek clarification if the JAR file marked is the latest release tied to A-Release and not the release titled v0.2, in the case where there are 2 releases in the stipulated detection period.

**Comment by damithc** [comment]
@Nephelite Not to worry. We use the latest JAR file for grading.

**Comment by Nephelite** [comment]
Thanks prof!
