### ISSUE TITLE
jar file works on mac but not on windows

### ISSUE THREAD

**Issue by kelvinou01** [nus-cs2103-AY2223S1/forum#176]
- Issue: [jar file](https://github.com/kelvinou01/ip/releases/tag/A-Release) works fine on mac, even if the jar file is run in a new empty directory. However, it throws the following error on windows:
  
  ```bash
  Error: JavaFX runtime components are missing, and are required to run this application
  ```
  
- Jar file is ~8mb in size, so it likely contains all the dependencies. 

- Jar file was built using `bash ./gradlew shadowJar` on mac
  
- Using OpenJDK 11 JDK FX version
  
- `java --version` prints the following:
  
  ```bash
  openjdk 11.0.16 2022-07-19 LTS
  OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
  OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)
  ```
  
- `build.gradle` file is as follows:
  
  ```java
  plugins {
      id 'java'
      id 'application'
      id 'com.github.johnrengelman.shadow' version '5.1.0'
      id 'checkstyle'
  }
  
  repositories {
      mavenCentral()
  }
  
  dependencies {
      testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
      testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'
  
      String javaFxVersion = '11'
  
      implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
      implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
      implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
      implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
      implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
      implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
      implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
      implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
      implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
      implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
      implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
      implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
  }
  
  test {
      useJUnitPlatform()
  
      testLogging {
          events "passed", "skipped", "failed"
  
          showExceptions true
          exceptionFormat "full"
          showCauses true
          showStackTraces true
          showStandardStreams = false
      }
  }
  
  application {
      mainClassName = "duke.Launcher"
  }
  
  shadowJar {
      archiveBaseName = "duke"
      archiveClassifier = null
  }
  
  checkstyle {
      toolVersion = "10.2"
      sourceSets = []  // Only run checkstyle when we explicitly call it
  }
  
  run{
      standardInput = System.in
  }
  ```
  
- Tried the following alternative `build.gradle` file corresponding to the [alternative JavaFX installation method](https://openjfx.io/openjfx-docs/#gradle) provided in [SE-Edu](https://se-education.org/guides/tutorials/javaFxPart1.html). It doesn't work as well.
  
  ```java
  plugins {
      id 'java'
      id 'application'
      id 'com.github.johnrengelman.shadow' version '5.1.0'
      id 'checkstyle'
      id 'org.openjfx.javafxplugin' version '0.0.10'
  }
  
  repositories {
      mavenCentral()
  }
  
  dependencies {
      testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
      testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'
  }
  
  test {
      useJUnitPlatform()
  
      testLogging {
          events "passed", "skipped", "failed"
  
          showExceptions true
          exceptionFormat "full"
          showCauses true
          showStackTraces true
          showStandardStreams = false
      }
  }
  
  application {
      mainClassName = "duke.Launcher"
  }
  
  shadowJar {
      archiveBaseName = "duke"
      archiveClassifier = null
  }
  
  checkstyle {
      toolVersion = "10.2"
      sourceSets = []  // Only run checkstyle when we explicitly call it
  }
  
  javafx {
      version = "18.0.2"
      modules = [ 'javafx.controls', 'javafx.fxml' ]
  }
  
  run{
      standardInput = System.in
  }
  ```
  
- Tried [this fix](https://github.com/nus-cs2103-AY2223S1/forum/issues/169) provided on the forum. Jar file still doesn't work on windows.

- Any help is appreciated 🥲

**Comment by pyk595** [comment]
Hi @kelvinou01 , I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). I suspect that the problem is that your windows machine does not have Java Runtime Environment 11. Can you check if you installed on your machine? Instructions can be found [here](https://docs.oracle.com/goldengate/1212/gg-winux/GDRAD/java.htm#BGBFHBEA). Hope it helps!

**Comment by jamietan2002** [comment]
^I agree, I think you need to make sure your Windows machine has the correct Java version installed.

**Comment by damithc** [comment]
> * Issue: [jar file](https://github.com/kelvinou01/ip/releases/tag/A-Release) works fine on mac, even if the jar file is run in a new empty directory. However, it throws the following error on windows:

Doesn't run on my Windows machine either. So, it's not related to @kelvinou01 's Windows machine. 

>C:\Downloads>java -jar roger.jar
Sep 12, 2022 4:20:27 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @71211259'
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:253)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:266)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:834)

Perhaps others can check if this JAR file works on their Macs? It's possible that it works only on the author's Mac and nowhere else.

---

> * Jar file is 11.3mb in size, so it likely contains all the dependencies.

The one given in the above link is only 8mb.

**Comment by kynapy** [comment]
Ran the 8mb jar file on my M1 Macbook, works fine for me!

**Comment by kelvinou01** [comment]
Jar file runs on my friend's mac too.

**Comment by vimuthm** [comment]
Hey @kelvinou01! I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems).

I'm on a Windows machine as well

```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)
```

and get the same error as prof @damithc.

I think it's likely to do with the fact that java version 9 is now using `Java Platform Module System (JPMS)` but your jdk being used might not have the JavaFX packaged in (more current versions don't anymore). 

Can you trying building the jar with a different jdk that has the JavaFX packaged (you can find some Zulu versions [here](https://www.azul.com/downloads/?package=jdk-fx)) and see if the same error persists? (Maybe a mac user can pitch in on how exactly to change the jdk in detail as well)

[This SO post](https://stackoverflow.com/a/67854230/10996783) has more detail.

**Comment by kelvinou01** [comment]
Hi @VimuthM, thank you for taking a look into my problem. I've double checked which JDK my Gradle wrapper is using. 

`./gradlew -version` returns the following:
```
Revision:     61d3320259a1a0d31519bf208eb13741679a742f

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.16.1 (Azul Systems, Inc. 11.0.16.1+1-LTS)
OS:           Mac OS X 12.1 aarch64
```

Also, I've set `JAVA_HOME` to the azul/zulu jdk:
```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
```

Unfortunately, my jar files are still not working on windows. I'm still trying and I'd be very grateful for any more suggestions :)

**Comment by kelvinou01** [comment]
I've also tried adding these lines to my build.gradle as per [this SO post](https://stackoverflow.com/a/21212790), to no avail.
```
compileJava.options.fork = true
compileJava.options.forkOptions.executable = '/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac'
```

I've also tried executing my gradle wrapper as follows:
```
 ./gradlew shadowJar -Dorg.gradle.java.home=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/  
```

**Comment by damithc** [comment]
@kelvinou01 As a drastic measure, provided you don't need other Java versions, you can try uninstalling all Java versions and then installing the exact version we have recommended for Macs.

**Comment by kelvinou01** [comment]
I have it fixed now. Basically, I changed the class I start the program with from Launcher to Main.

My Launcher essentially acted as a main class before I made this fix.

Thank you everyone who stopped by to look into my problem, really appreciate it :)
