### ISSUE TITLE
Skipped a Step when Add Increments as PRs

### ISSUE THREAD

**Issue by shawnkai** [nus-cs2103-AY2223S1/forum#177]
![image](https://user-images.githubusercontent.com/70712915/189605247-db9549ec-0f29-48f7-bf8b-8b473e43afbc.png)

Hi prof, I accidentally skipped the highlighted step "Pull the updated master branch from your fork to your Computer."
when I was adding increment as PR, so what I did was:

Create PR respectively for code quality and assertion
Merge the Assertion PR on GitHub
Here, instead of Pulling the updated master branch from my fork to my Computer
I directly Merged the Assertion branch and Code Quality branch on my source tree and resolved any conflicts shown.

As of here I am having difficulty pushing the master branch to github. This is a photo of my graph and the error I'm facing when I attempt to push the master branch or assertion branch to github.

![image](https://user-images.githubusercontent.com/70712915/189606066-4e639f43-c7bd-4c73-a12c-5cd96b39d363.png)
![image](https://user-images.githubusercontent.com/70712915/189606167-ebabe5e7-87c3-43ef-a875-844367173ec5.png)

May I know how do I remedy this?

Thank you in advance

**Comment by damithc** [comment]
Partial answer:
@shawnkai One solution is to _undo_ the local merges that you did (but shouldn't have done).

**Comment by deeyonn** [comment]
Perhaps you could explore using the `git reset` or `git revert` commands depending on your situation. IIRC merge commits that have not been pushed are much easier to revert.

**Comment by shawnkai** [comment]
I managed to solve that part but it seems like I'm facing another problem when I'm trying to push after doing the AddAnExtension exercise. 

![image](https://user-images.githubusercontent.com/70712915/189652719-354aafa3-daa4-4ae0-bd7b-da3ff2efba62.png)

**Comment by shawnkai** [comment]
Am I supposed to remove a tag from Github?

**Comment by damithc** [comment]
> Am I supposed to remove a tag from Github?

If there is a tag conflict, you need to delete one or the other.

**Comment by deeyonn** [comment]
@shawnkai delete the tag in the previous commit and add it back after you've merged worked for me

**Comment by shawnkai** [comment]
ok thank you the problem has been resolved
