### ISSUE TITLE
Unable to set up JavaFXML in step 4 of GUI

### ISSUE THREAD

**Issue by gabyang** [nus-cs2103-AY2223S1/forum#179]
As stated in the title I am unable to get my Program to run JavaFXML even though I followed the tutorial. Attached is a picture of the current error message when I run the Launcher program. 
![image](https://user-images.githubusercontent.com/88603547/189692928-c85a91a1-8751-4395-b795-74c14ac22e96.png)

Running it with stacktrace leads me to this error: 
![image](https://user-images.githubusercontent.com/88603547/189693372-a700130f-fac3-43cf-b1da-afd101c368d1.png)

Some things I have tried for debugging include:
1) Ensuring that build.gradle is accurate
2) Ensuring that my run configurations are running Java-11
3) Ensuring that my project configurations are set at the latest Java-11
4) Asking my groupmates to help me debug the error 
5) Taking a look at issue #111 

Any help on this matter will be appreciated!

**Comment by damithc** [comment]
@gabyang perhaps you can share the full code here? e.g., push to Githhub and share the link here

**Comment by gabyang** [comment]
hi @damithc thanks for taking a look! 

This is the link to my ip, I have opened a PR to merge the JavaFXML changes with the rest of my code. I didn't immediately merge it with the rest of my code because I didn't want to screw up my current ip
https://github.com/gabyang/ip

If you would like me to merge it, let me know!

**Comment by sarrrdin** [comment]
Hello! Hmm that error indicates that the execution has failed for Gradle. However, was having a quick glance at your code and I notice that there are two 
```
public static void main(String[] args){}
```
in your Duke class and Launcher class respectively. Potentially, you can try the stacktrace debugging option, it may be due to an error in the path for the Main class. 

Hope this helps!

**Comment by parth-io** [comment]
Hmm, I cloned your repo to figure out why this is happening.

I got rid of the deprecation warning by changing line 3 of `/gradle/wrapper/gradle-wrapper.properties` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-bin.zip` - basically you need to downgrade your Gradle version.

Also, lines 25-26 in `MainWindow.java` has incorrect file names. They should be:
```
private Image userImage = new Image(Objects.requireNonNull(this.getClass().getResourceAsStream("/images/User.png")));
private Image dukeImage = new Image(Objects.requireNonNull(this.getClass().getResourceAsStream("/images/Duke.png")));
```

Also, I tried commenting out code - a blank stage does show up if you comment out the preceding code in `Main.java`.

I'm not sure what could be causing this issue.

**Comment by deeyonn** [comment]
I left a PR review but was unable to identify the problem.

**Comment by domlimm** [comment]
Hi @gabyang, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems).

I cloned your `ip` repo and found there is a conflicting declaration regarding `JavaFX` in your `build.gradle` file.

At the dependencies declaration in your `build.gradle` file, [here](https://github.com/gabyang/ip/blob/Integrate-JavaFXML/build.gradle#L16-L29) v.s the explicit versioning of `JavaFX` at the [bottom](https://github.com/gabyang/ip/blob/Integrate-JavaFXML/build.gradle#L59-L62).

I believe we do not need the one at the bottom as it could mess up when building with gradle. I compared to what I had when I was doing ip and I did not need to add the explicit config as it's handled by your dependencies list.

However, as of now, still unable to run your project. I did not get any errors running your project after making the change in the `build.gradle` file.

Should I be expecting a GUI window to pop up?

**Comment by gabyang** [comment]
Hi all, thanks very much for your time and efforts in helping me! I really appreciate it! @sarrrdin @parth-io @deeyonn @domlimm 

Regarding the changes I have made/tried for my JavaFXML integration, I have tried all of your suggestions, namely:
1) Running stacktrace debugging option - error is still the same as before, there is no more elaboration on that
2) Commenting out the main function of Duke.java - unlikely the issue of multiple main methods
3) Downgrade my gradle version and changed the path for the jpg files for Duke and User
4) Resolved the conflict in build.gradle file and also tried commenting out the code for explicit config for JavaFX

And yes, a GUI window is supposed to pop up once the code is running, but there is nothing as of now. Once again thanks to all who took the time to look at my code!

**Comment by nopehax** [comment]
Hi @gabyang, the GUI is not popping up because in Main.java when creating a new instance of Duke, that instance will be run i.e. the old CLI duke. Since the CLI doesn't show, you're not able to exit it and that instance will always be running and so, your program is forever stuck at line 15 of Main.java.

Thus the solution is to remove the line `run();` in line 46 of Duke.java

**Comment by gabyang** [comment]
Thanks! That managed to solve it! Appreciate all of your help!

**Comment by damithc** [comment]
Thanks for the investigation and the solution @nopehax 

![image](https://user-images.githubusercontent.com/1673303/190148860-ab7acd79-ae4b-4406-9e1b-a0274532737c.png)

I have no doubt you can 💯
