### ISSUE TITLE
Skipped the "Practice using parallel git branches and PRs" In Week 5

### ISSUE THREAD

**Issue by johnrhimawan** [nus-cs2103-AY2223S1/forum#181]
Hi prof, I already finished the tasks up to Week 5; however, I accidentally skipped through the instruction that explains that we should practice using parallel git branches and PRs since I was trying to complete the iP tasks quickly. Thus, my progress for Week 5 was submitted the same way as previous weeks (merge from other branch to master without PR). The "Merging PRs" tag is still active in the dashboard because I merged a PR for gradle support. May I please ask how I can resolve this issue?

This is the part I skipped:

![image](https://user-images.githubusercontent.com/65337049/189795603-c23e86ea-e62b-440e-8bf0-52fac632837a.png)

**Comment by damithc** [comment]
@johnrhimawan it should be fine if you practice merging of parallel branches as you do future increments (e.g., week 6 increments) to the code, as the main objective of the iP is to ensure you know how to certain things that will be required for the tP.

**Comment by johnrhimawan** [comment]
Ok thanks for the information Prof!
