### ISSUE TITLE
Library request: SnakeYAML

### ISSUE THREAD

**Issue by BlopApple** [nus-cs2103-AY2223S1/forum#182]
### Library
[SnakeYAML](https://mvnrepository.com/artifact/org.yaml/snakeyaml)

### Purpose
To use the yaml parser provided to load a yaml file containing all preset phrases for the chat bot.

### License
Apache 2.0 - See [https://bitbucket.org/snakeyaml/snakeyaml/src/master](https://bitbucket.org/snakeyaml/snakeyaml/src/master/LICENSE.txt)

**Comment by damithc** [comment]
Approved
