### ISSUE TITLE
Request to use AIML-related libraries for better user interaction

### ISSUE THREAD

**Issue by e1010101** [nus-cs2103-AY2223S1/forum#183]
## Library

Project AB, an ALICE chatbot implementation [(Library URL)](https://mvnrepository.com/artifact/org.goldrenard/ab)
Sanmoku, dependency for Project AB [(Library URL)](https://mvnrepository.com/artifact/net.reduls.sanmoku/sanmoku)
Sanmoku-feature-ex, dependency for Project AB [(Library URL)](https://mvnrepository.com/artifact/net.reduls.sanmoku/sanmoku-feature-ex)
SLF4J, dependency for Project AB [(Library URL)](https://mvnrepository.com/artifact/org.slf4j/slf4j-api)
Log4J over SLF4J, dependency for Project AB [(Library URL)](https://mvnrepository.com/artifact/org.slf4j/log4j-over-slf4j)

## Purpose

AIML (Artificial Intelligence Markup Language) is an XML language for specifying chatbot content. By using AIML files, I can customize my chatbot's responses to various questions easily. AIML also allows for other functionalities such as remembering/teaching certain words to my chatbot.

## License

Project AB is covered by the [GNU Lesser GPL license](http://www.gnu.org/licenses/lgpl.html), as outlined in the website [here](https://code.google.com/archive/p/program-ab/).

**Comment by damithc** [comment]
@e1010101 Approved. Note that it is your responsibility to comply with the license terms. 
Perhaps you can post here at a later time the concrete benefits (e.g., additional features you were able to implement using this library) -- I'm curious to know :-)

**Comment by e1010101** [comment]
Thank you prof, I will update in the future!
