### ISSUE TITLE
Reporting spelling error on DevOps guide

### ISSUE THREAD

**Issue by ThomasHoooo** [nus-cs2103-AY2223S1/forum#185]
[
![image](https://user-images.githubusercontent.com/78606832/189887734-725aa376-0a69-496e-af36-039f61e7be14.png)
](url)

test is misspelled as testes.

**Comment by damithc** [comment]
@ThomasHoooo good catch (and a funny typo too 😆 ). Could you report it at https://github.com/se-edu/addressbook-level3/issues ?

**Comment by ThomasHoooo** [comment]
Sure Prof!
