### ISSUE TITLE
Jar file able to open on Mac and Windows, but fonts do not show up 

### ISSUE THREAD

**Issue by sltsheryl** [nus-cs2103-AY2223S1/forum#186]
Hello, I've pushed my latest version v0.4 for my .jar file in my repo. While asking my friends to test my programs on their computers (Mac and Windows), they can open it, but the fonts that I have included in the .fxml file and shown on my side are not shown on theirs. I am not sure what is the cause of this. Thanks!

The fonts are rendered correctly on my side.
<img width="597" alt="Ui" src="https://user-images.githubusercontent.com/96589109/189917475-64aedf17-d412-47d1-80a9-986d44ba2061.png">

This is what shows up on others' computers.
![photo_2022-09-13 21 45 15](https://user-images.githubusercontent.com/96589109/189917850-312f0a96-a299-4712-9ce9-83a10148c04d.jpeg)

**Comment by waynezsy** [comment]
What font are you using? Is there a possibility that your friends do not have the same font installed in their computers?
Maybe you can try switching it to something everyone has (like Times New Roman) and see if it defaults back anyway.

**Comment by NicsunXnus** [comment]
Hi @sltsheryl, manage to get some fix on your problem. 
1) I have downloaded the monofur font from https://www.dafont.com/monofur.font but which did not have *monofur for powerline* or *monofor   bold for powerline* unfortunately.
2) I am running this on the latest Windows version and I got this display after changing the font value inside the KirbyDialogBox.fxml file to *monofur*. For some reason the kirby emoji part didnt get displayed for me.
![image](https://user-images.githubusercontent.com/77189033/190083052-18bd9076-86a4-4630-a95f-ec182ac12e6b.png)

3) This is my display for *monofur    italic*
![image](https://user-images.githubusercontent.com/77189033/190082959-617c65e9-abc3-401d-b86b-20585c748bd3.png)

I assume that the code will be tested on a java 11 environment so I changed the settings in the fxml files to follow java 11. I guess what you can consider is to inform users to download the required fonts for your program or like what @waynezsy has mentioned, to use an OS common font to avoid font not displaying issues. Hopefully this has helped you.

**Comment by sltsheryl** [comment]
> I assume that the code will be tested on a java 11 environment so I changed the settings in the fxml files to follow java 11. I guess what you can consider is to inform users to download the required fonts for your program or like what @waynezsy has mentioned, to use an OS common font to avoid font not displaying issues. Hopefully this has helped you.

Oh I see, thanks! @NicsunXnus @waynezsy
I added the font via Scene Builder so I thought it was one of those standard fonts like Comic Sans but it makes sense it's not an OS common font. 

Yup, I'll heed your advice to give an option to download or change to another font. 
Or per prof advice, https://guigarage.com/2014/10/integrate-custom-fonts-javafx-application-using-css/

Thanks both!

**Comment by damithc** [comment]
> I guess what you can consider is to inform users to download the required fonts for your program or like what @waynezsy has mentioned, to use an OS common font to avoid font not displaying issues. Hopefully this has helped you.

I don't think we can expect users to download a font when running this app. It's best to use a common font or package the required font with the application.

**Comment by sltsheryl** [comment]
> 

👍 Thanks prof

**Comment by Eclipse-Dominator** [comment]
I know this issue is closed but you can actually package the jar with the font that you want to include. 
(though just make sure the font you choose have the appropriate liscence so that you can actually use them)
For example, if I wanted to use UbuntuMono font type
```
resources/
├── fonts
│   └── UbuntuMono-Regular.ttf
├── images
│   ├── DaDuke.png
│   └── DaUser.png
└── ...
```
I can then access these fonts via 
```java
Font font = Font.loadFont(DialogBox.class.getResource("/fonts/UbuntuMono-Regular.ttf").toString(), 15);
```
and I can now apply the font to the dialog box with
```java
dialog.setFont(font);
```
shadowJar will package this font together inside the jar so you no longer need to depend on the end user to have the corresponding font.
