### ISSUE TITLE
Unable to run jar file due to java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by ytingtan** [nus-cs2103-AY2223S1/forum#189]
Details: 
* IntelliJ version: Community Ediiton 2021.3.1, OS: Windows 
* Issue: Created jar file and ran `java -jar ip.jar`, but error message shown: 
```
Error: Could not find or load main class duke.Launcher
Caused by: java.lang.ClassNotFoundException: duke.Launcher
```

Attached below is my file structure.
![image](https://user-images.githubusercontent.com/95749518/190103342-f63ee9da-2f65-45d2-9f8a-6fa2da726a31.png)

I set `Launcher.java` as the main point of entry of the code, and `Launcher.java` launches `Duke.java` which extends `Application`. 

I have followed the LPT at #169 but it shows the same error. Appreciate any help!

**Comment by rui-han-crh** [comment]
Hi, I could launch your file with no issues (apart from the single warning related to JavaFX versions). I'm not exactly sure what is being typed into the terminal, but I'm suspecting that the input may have been typed as 

```
java duke.Launcher
```
which will throw a ClassNotFoundException
```
Error: Could not find or load main class duke.Launcher
Caused by: java.lang.ClassNotFoundException: duke.Launcher
```


Instead, in the terminal, use `cd` to navigate to the libs folder (after exporting with `gradle shadowJar`):
```
cd build/libs
```

then do:

```
java -jar duke.Launcher.jar
```

Alternatively, we can also do
```
java -jar build/libs/duke.Launcher.jar
```
from the topmost level directory. (The name of the jar file is `duke.Launcher`, if you want to change its name, it's in the `build.gradle` file under the `shadowJar` section -> `archiveBaseName`)

**Comment by ytingtan** [comment]
It works now, thank you so much! 😸
