### ISSUE TITLE
Help for smoke testing (MAC OS)

### ISSUE THREAD

**Issue by jovitaanderson** [nus-cs2103-AY2223S1/forum#191]
Hello! I need some help with smoke testing for my JAR file (preferably with macOS) as me and my friends are all Windows users. :sweat_smile: The link to my ip JAR for download is [here](https://github.com/jovitaanderson/ip/releases/tag/A-Release). Here is the [user guide](https://jovitaanderson.github.io/ip/) as well.

Any feedback is appreciated, Thank you :blush:

**Comment by yuehernkang** [comment]
Hello @jovitaanderson, I have just tested on macOS and it is working well!

**Comment by jovitaanderson** [comment]
Okay, thank you for the help! @yuehernkang
