### ISSUE TITLE
WARNING: Loading FXML document with JavaFX API of version 18

### ISSUE THREAD

**Issue by april-anh** [nus-cs2103-AY2223S1/forum#193]
After changing the background color of the GUI using Scene Builder, I got the following warning:
```
Sep 15, 2022 1:16:55 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 18 by JavaFX runtime of version 11
```
FYI, I simply changed the default color (white) to "#05445E".

**Comment by RezwanArefin01** [comment]
If you are not using any JavaFX 18 / advanced features, then you can manually remove the `/18` part from `xmlns="http://javafx.com/javafx/18` in the `.fxml` files. Scene builder automatically adds this, which is probably tied to the version of scene builder app. I could not find a way to specify the version of JavaFX to use.
