### ISSUE TITLE
Help for smoke test for WIndows and Linux users

### ISSUE THREAD

**Issue by CeereeC** [nus-cs2103-AY2223S1/forum#194]
Hello, here is my [Jar](https://github.com/CeereeC/ip/releases) and [User Guide](https://ceereec.github.io/ip/), would appreciate help to test if the jar file works on Windows and Linux. Thank you!

**Comment by RussellDash332** [comment]
Works on my Windows 10, good work! 🚀

**Comment by jovitaanderson** [comment]
Hello @CeereeC , you application works fine on my Windows as well!

**Comment by RezwanArefin01** [comment]
Works OK on Linux (Arch), but text seems broken?:  
![Screenshot_20220916_010259](https://user-images.githubusercontent.com/22095441/190466314-fec3c48a-c8e4-4b8c-a8c7-5bf0f8062030.png)
However, resizing the window seems to break everything :laughing: Check if this is the correct behavior: 
![Screenshot_20220916_010416](https://user-images.githubusercontent.com/22095441/190466727-8b86e179-7d94-42c5-abe1-b31c83b0c2db.png)
(command box not visible, text got broken)
