### ISSUE TITLE
Help with smoke test on Windows

### ISSUE THREAD

**Issue by ngshijun** [nus-cs2103-AY2223S1/forum#195]
This is the [jar](https://github.com/ngshijun/ip/releases/download/v0.3/LaMDA.jar) file and [user guide](https://ngshijun.github.io/ip/). Appreciate for your help.

**Comment by LianGuoYang** [comment]
Your jar file is working on my Windows 10. I like how you have LAMDA as your header, looks really cool!

**Comment by RussellDash332** [comment]
Works on my Windows 10 as well! 🚀

**Comment by ngshijun** [comment]
Noted. Thanks guys!
