### ISSUE TITLE
Help for smoke test for Mac users

### ISSUE THREAD

**Issue by LianGuoYang** [nus-cs2103-AY2223S1/forum#196]
Here is my [jar](https://github.com/LianGuoYang/ip/releases/download/A-Release/duke.jar) file and user [guide](https://lianguoyang.github.io/ip/). Can someone help for smoke test please. Thanks for your help.

**Comment by jeromepui** [comment]
Your application works fine on my Mac 👍

**Comment by ngshijun** [comment]
Works fine on my Mac too. 💯

**Comment by LianGuoYang** [comment]
Appreciated. Thanks guys.
