### ISSUE TITLE
Help for smoke test for Mac and Linux users

### ISSUE THREAD

**Issue by RussellDash332** [nus-cs2103-AY2223S1/forum#197]
JAR file and user guide are given [here](https://github.com/RussellDash332/ip/releases/tag/A-Release). Appreciate any help!

**Comment by Evande1** [comment]
Hello @RussellDash332, all your commands in your UG works on macOS, just remove the comma for deadline and event example in your UG and should be good to go.
``` 
event Go to Jurong /at Aug 10 2022 13:30
```

**Comment by RussellDash332** [comment]
> Hello @RussellDash332, all your commands in your UG works on macOS, just remove the comma for deadline and event example in your UG and should be good to go.
> 
> ```
> event Go to Jurong /at Aug 10 2022 13:30
> ```

Great, thanks for your help!
