### ISSUE TITLE
Azulu JDK download

### ISSUE THREAD

**Issue by adeearyaa** [nus-cs2103-AY2223S1/forum#198]
![Screenshot 2022-09-15 at 8 01 09 PM](https://user-images.githubusercontent.com/87979157/190398564-85635f6c-289e-4d15-9bf1-7a8730baf728.png)
Hi my Mac is not M1 but im stil facing the gibberish issues when running my project from gradle but not when i run from intellij can anyone help me with this

**Comment by damithc** [comment]
@adeearyaa it might help if you run  the `java -version` command in the same terminal you run the Gradle commands and share the output here.

**Comment by Bubbl3T** [comment]
You are probably still running the old java version on your terminal. I face the same issue before and you can try these few steps
1. Go to terminal and type `java -version` to check what java version you are running with
1. If the java version is not the desired version, go to `Macintosh HD > Library > Java > JavaVirtualMachines` and you should a few java versions.
1. Let's say you want to disable your jdk-11.0.13.jdk, from where you are, go to `jdk-11.0.13.jdk > Contents` and find the file called `Info.plist`, rename it to `Info.plist.disabled`

That should be enough for you to disable your that version of java and for your computer to detect the zulu version of java.

**Comment by adeearyaa** [comment]
Hi it works now thanks!
