### ISSUE TITLE
Jar file not creating `data` folder on Mac

### ISSUE THREAD

**Issue by Bubbl3T** [nus-cs2103-AY2223S1/forum#199]
Hi, does anyone face the same issue with your jar file running fine on Windows but not creating a `data` folder at the location on Mac? If that happens, does anyone have an idea where the problem may lie?

Also, while the data folder is not created, the data is still stored correctly and is still there when the application close and reopens. Anyone knows where the data folder went? Thank you!

**Comment by Bubbl3T** [comment]
![image](https://user-images.githubusercontent.com/72196376/190408123-93b9a45e-6fb7-4542-b656-c27702ca0713.png)

Further investigations show that this is where the data file is. Will look into it to see if an actual fix can be found.

**Comment by RezwanArefin01** [comment]
> `private static final Path DIRECTORY_PATH = Paths.get(System.getProperty("user.dir"), "data");`

Try replacing the `System.getProperty("user.dir")` with a `"."`. The `"user.dir"` on OSX is not defined properly. With `"."` you will be getting the location from where the jar was executed. So, if you call `java -jar folder/duke.jar`, the data folder will be `./data` not `./folder/data`. 
There is also a way to get [the location of the jar file](https://stackoverflow.com/questions/320542/how-to-get-the-path-of-a-running-jar-file), but that is a bit more complex. 
EDIT: It seems `user.dir` is set properly, but double-clicking on Mac may not set it properly. Has something to do with java permissions.

**Comment by ryanlml** [comment]
I offer an ad-hoc solution: making a directory and the data file if it doesn't exist.
```
try {
    if (!file.exists()) {
        Files.createDirectories(Paths.get(filePath).getParent());
        file.createNewFile();
    }
} catch (IOException e) {
    //...
}
```

**Comment by RezwanArefin01** [comment]
@ryanlml I believe he is already doing that. The problem is that the `filePath` is created by concatenating `user.dir` and `/data/data.txt`. But the `user.dir` returns some weird location on OSX; works fine on Windows / Linux.

**Comment by Bubbl3T** [comment]
> > `private static final Path DIRECTORY_PATH = Paths.get(System.getProperty("user.dir"), "data");`
> 
> Try replacing the `System.getProperty("user.dir")` with a `"."`. The `"user.dir"` on OSX is not defined properly. With `"."` you will be getting the location from where the jar was executed. So, if you call `java -jar folder/duke.jar`, the data folder will be `./data` not `./folder/data`. There is also a way to get [the location of the jar file](https://stackoverflow.com/questions/320542/how-to-get-the-path-of-a-running-jar-file), but that is a bit more complex.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/72196376/190425465-00568512-4126-4801-9a37-665287318b76.png">
Tried your suggested fix, this is what is happening now. The path kinda changed, but there is still no folder created. My program somehow still reference to the same old data file even if I move it around to other folders.

It works fine on Windows and Linux, just having some problems with Mac. I guess Mac just likes to do things differently lol.

**Comment by Bubbl3T** [comment]
@ryanlml Yeah I have already done that, but still thanks for the suggestion! \:D

**Comment by damithc** [comment]
@Bubbl3T See if [this post](https://github.com/nus-cs2103-AY2122S1/forum/issues/221#issuecomment-921100456) (from a previous semester) helps.

**Comment by Bubbl3T** [comment]
@damithc Thanks prof, this helped! By opening the jar file using the command `java -jar <FILE_NAME>` it created a data folder and data file successfully. :)
