### ISSUE TITLE
Test case passed but with dos2unix: command not found error (MAC OS)

### ISSUE THREAD

**Issue by Jo3LW** [nus-cs2103-AY2223S1/forum#20]
<img width="1512" alt="Screenshot 2022-08-18 at 10 29 57 AM" src="https://user-images.githubusercontent.com/97379359/185279771-47d38576-cd7f-4317-b5c5-f415a5fed454.png">

The test case passes but it comes with this line ./runtest.sh: line 27: dos2unix: command not found. Is this alright or is there some issue with the runtest.sh file. Thank you :) 

This is my runtest.sh file below.

<img width="1512" alt="Screenshot 2022-08-18 at 10 29 00 AM" src="https://user-images.githubusercontent.com/97379359/185279548-8b27d5d6-734d-40f7-bb7a-4f7163f812da.png">

**Comment by sltsheryl** [comment]
Hi I faced the same issue and I followed these steps.
https://macappstore.org/dos2unix/
And afterwards that line went away

**Comment by Jo3LW** [comment]
Thanks it works :)

**Comment by damithc** [comment]
> The test case passes but it comes with this line ./runtest.sh: line 27: dos2unix: command not found. Is this alright or is there some issue with the runtest.sh file. Thank you :)

@Jo3LW This can be safely ignored if the tests are passing.
