### ISSUE TITLE
Request for smoke testing help (Mac/Linux)

### ISSUE THREAD

**Issue by ConradLew** [nus-cs2103-AY2223S1/forum#200]
Hi, would appreciate if any Mac/Linux users can help me test my JAR file. The release can be found [here](https://github.com/ConradLew/ip/releases/tag/A-Release). Thanks!

**Comment by yuehernkang** [comment]
Hi @ConradLew I have just tested on my Mac and it is working fine. Cute Pepper robot picture haha

**Comment by RezwanArefin01** [comment]
Some pictures are not being loaded on Linux (ArchLinux with KDE). 
![Screenshot_20220915_223508](https://user-images.githubusercontent.com/22095441/190432193-3bd7a36e-01ef-454f-ae46-af808fe88bcb.png)

**Comment by ConradLew** [comment]
> Some pictures are not being loaded on Linux (ArchLinux with KDE). ![Screenshot_20220915_223508](https://user-images.githubusercontent.com/22095441/190432193-3bd7a36e-01ef-454f-ae46-af808fe88bcb.png)

Hi @RezwanArefin01 I've reuploaded the bot image in my latest jar file [here](https://github.com/ConradLew/ip/releases/tag/A-Release). Could you try it again to see if the image is fixed? Thanks!

**Comment by ConradLew** [comment]
Re-tested on Linux (Ubuntu), problem fixed after redownloading image. Thanks for earlier help @yuehernkang @RezwanArefin01.
