### ISSUE TITLE
Checkstyle test failed (Unable to create root module)

### ISSUE THREAD

**Issue by ketamethane** [nus-cs2103-AY2223S1/forum#202]
I'm using Windows 10 and the latest version of Intellij.
I've followed the instructions in the issue #35 and I have fetched the external resources as well.
Yet, my code failed the checkstyle section of the Java CI.

This is what is shown in the command prompt.
![cmd](https://user-images.githubusercontent.com/88729540/190425771-61e84db3-4912-4406-b4b2-b28760153011.jpg)

Any help is appreciated, thank you,

**Comment by hauchongtang** [comment]
I think your `build.gradle` is missing `checkstyleMain`.

```
checkstyleMain {
    source = 'src/main/java'
}
```

**Comment by ketamethane** [comment]
I added it in as well, but I still faced the same error in the command prompt. When I ran `checkstyleMain` in the `build.gradle` file, this is what I saw
![ss](https://user-images.githubusercontent.com/88729540/190431803-16913165-b5cb-4e94-99b4-a0cef7ea31c0.jpg)

**Comment by hauchongtang** [comment]
You are missing a directory for ur `config` folder. It should be --> `config/checkstyle`

![image](https://user-images.githubusercontent.com/56034480/190436494-d460db7b-bc83-4a8f-86e4-94d55ff2c718.png)

Here is the checkstyle results after a run.

![image](https://user-images.githubusercontent.com/56034480/190436815-706750b2-9dc2-4afc-ba3a-3a94b0d85f83.png)

**Comment by ketamethane** [comment]
Hmm... It was strange. I had the same directory as you. However, after some refactoring and undoing those refactoring, the issue sort of resolved by itself. I can see all my checkstyle issues now. Thank you @hauchongtang 😄
