### ISSUE TITLE
Request for smoke testing help (Mac/Linux)

### ISSUE THREAD

**Issue by marclzh** [nus-cs2103-AY2223S1/forum#203]
Hello, would appreciate if any Mac/Linux users can help me test my JAR file. The release can be found [here](https://github.com/marclzh/ip/releases). Thanks!

**Comment by RezwanArefin01** [comment]
Not working on Linux (Arch). Getting a 0 width/height window and cannot even resize. Maybe something wrong with the resources? 
![Screenshot_20220916_004308](https://user-images.githubusercontent.com/22095441/190460629-ca336a44-9581-417d-9812-4d39935fde2b.png)

**Comment by marclzh** [comment]
Thanks for the smoke test @RezwanArefin01! I've made some changes to the scripts, hopefully its working fine now.

**Comment by zlimez** [comment]
Works fine on Mac 👍

**Comment by RezwanArefin01** [comment]
@marclzh Still having the same issue on Linux. I tried compiling it locally from master branch but still got the same result.
