### ISSUE TITLE
Request for smoke testing help on Mac/Linux OS

### ISSUE THREAD

**Issue by L1uY1jun** [nus-cs2103-AY2223S1/forum#204]
Hello, would appreciate if any Mac/Linux users can help me test my JAR file. The release can be found [here](https://github.com/L1uY1jun/ip/releases/tag/A-Release). Thanks!

**Comment by edricyeo** [comment]
Works fine for mac! 👍🏻

**Comment by RezwanArefin01** [comment]
Works OK on Linux (Arch): 
![Screenshot_20220916_004621](https://user-images.githubusercontent.com/22095441/190461213-1b43c663-9917-44ee-8bdb-4e60d49e23d9.png)
However, a little bit of problem: the text is not wrapped properly when width is small. Is this the correct behavior? 
![Screenshot_20220916_004713](https://user-images.githubusercontent.com/22095441/190461379-f65306e8-5e7b-458f-a3a9-eb9b127c80f6.png)

**Comment by L1uY1jun** [comment]
@RezwanArefin01 Yep it is correct behavior because i set the text bubble to have a minimum width. Thanks for the smoke test on linux, much appreciated!

**Comment by L1uY1jun** [comment]
Thanks for pointing it out though, I have fixed the stage so it does not go below minimum width

**Comment by carriezhengjr** [comment]
Resizing issue is fixed now and works fine on Mac!

<img width="735" alt="Screenshot 2022-09-16 at 16 44 50" src="https://user-images.githubusercontent.com/97394017/190596708-aa4aa30a-8e90-4ed2-a9a1-4fafb4b6a0b5.png">
<img width="396" alt="Screenshot 2022-09-16 at 16 45 04" src="https://user-images.githubusercontent.com/97394017/190596742-eb0ec76b-90d3-40b9-89a2-fe032d2bcd96.png">
