### ISSUE TITLE
Screenshot appears on README preview, but not on deployed page

### ISSUE THREAD

**Issue by ketamethane** [nus-cs2103-AY2223S1/forum#205]
As the title goes.
Here is the code for my README editing page.

![edit](https://user-images.githubusercontent.com/88729540/190452199-05ffbf21-8df6-436d-9af1-805204197b52.jpg)

This is the preview page with the directory of docs included.

![preview](https://user-images.githubusercontent.com/88729540/190452490-9b1c88f2-37c2-4a35-8d3f-259d0227860b.jpg)

And this is the deployed website.

![deployed page](https://user-images.githubusercontent.com/88729540/190449612-e9458767-c56f-4fb5-b228-95d4be892363.jpg)

I've tried looking through the past issues and googling it, but to no avail. Changing the image file path to become relative (`/docs/Ui.png`) did not work either. Would appreciate any help, thank you!

**Comment by RezwanArefin01** [comment]
Just use `![](Ui.png)`. Github pages will just build the site from `/docs` directory, so no need to include the `/docs` in the path. So you may assume your site's root directory is the `/docs` directory.

**Comment by ketamethane** [comment]
Issue solved, thank you so much! @RezwanArefin01
