### ISSUE TITLE
Request for Smoke Test Help on Mac and Linux

### ISSUE THREAD

**Issue by johnrhimawan** [nus-cs2103-AY2223S1/forum#206]
Hi, can I ask for help to run smoke tests on Mac and Linux?

The JAR file can be found [here](https://github.com/johnrhimawan/ip/releases/tag/A-Release).

Thanks!

**Comment by RezwanArefin01** [comment]
Worked OK on Linux (Arch) until I resized the window: 
![Screenshot_20220916_021344](https://user-images.githubusercontent.com/22095441/190479179-327840bc-5cbc-4225-97e2-473b69a107b9.png)

**Comment by zlimez** [comment]
Works fine on Mac aside from the resizing problem pointed out. 👍

**Comment by RezwanArefin01** [comment]
For a quick fix of the window resize problem, you can add `stage.setResizable(false);` in `Main`.
