### ISSUE TITLE
Request for smoke testing help (Mac/Linux)

### ISSUE THREAD

**Issue by Rachel-AG** [nus-cs2103-AY2223S1/forum#207]
Hi! Would appreciate it if anyone can help me test my JAR file on Mac/Linux. 
The release can be found [here](https://github.com/Rachel-AG/ip/releases/tag/v0.2). 
Thanks!

UPDATE: Most recent release can be found [here](https://github.com/Rachel-AG/ip/releases/tag/v0.3).

**Comment by RezwanArefin01** [comment]
Did not work on Linux (Arch): 
![Screenshot_20220916_021630](https://user-images.githubusercontent.com/22095441/190479710-d05cc371-5d44-4e72-893d-1d8d289744a8.png)

In `build.gradle`: 
```
javafx {
    version = "11.0.2"
    modules = [ 'javafx.base', 'javafx.controls', 'javafx.fxml', 'javafx.graphics' ]
}
```
is not enough to include all modules for win/mac/linux (even though the [linked page](https://openjfx.io/openjfx-docs/#gradle) in javafx tutorial gave this approach). Try including each one of them individually for different OSs as done in the [se-edu page tutorial](https://se-education.org/guides/tutorials/javaFxPart1.html#setting-up-java-fx).

**Comment by Rachel-AG** [comment]
I see. Thank you so much for your help @RezwanArefin01! 
Here is my updated [release](https://github.com/Rachel-AG/ip/releases/tag/v0.2).  
Would really appreciate it if anyone can test it again!

**Comment by Rachel-AG** [comment]
I see! Thank you for your help @RezwanArefin01
Here is my updated [release](https://github.com/Rachel-AG/ip/releases/tag/v0.3).
Would really appreciate it if anyone can test it again. Thanks!

**Comment by zlimez** [comment]
Works fine on Mac, though GUI gets distorted when resized. 
<img width="494" alt="Screenshot 2022-09-16 at 12 31 54 PM" src="https://user-images.githubusercontent.com/39835365/190557499-5c4a4fa7-b40d-4b2a-9c17-b2ef1717f143.png">

**Comment by RezwanArefin01** [comment]
Working fine on Linux (Arch) now: 
![Screenshot_20220916_152021](https://user-images.githubusercontent.com/22095441/190580607-307e953a-80aa-47cc-b481-b1448484e5ed.png)

For the window distortion problem, you can add `stage.setResizable(false);` in `Main` for a quick fix. Wrapping the text with window resize is a bit more complex.

**Comment by Rachel-AG** [comment]
I see! Thank you everyone @RezwanArefin01 @zlimez 😄
