### ISSUE TITLE
Including font inside jar vs asking users to install fonts

### ISSUE THREAD

**Issue by RezwanArefin01** [nus-cs2103-AY2223S1/forum#208]
I am using a specific font (albeit very common) as the main font in my iP. However, the user may not have the font installed. In that case I think he won't be able to view it properly, since I don't see the font being shipped with the jar. However, I think including the font inside the jar may have some LICENSE issues, which I know nothing of. 

Also I use some unicode emojis as the task type symbols. Some people are also not being able to view them (and some can)! It is most likely caused by not having a font that can render those specific unicodes. What should I do in this case? I cannot find the font that contains the emojis.

For iP grading, is this considered a defect? In case the user don't have proper fonts installed. Some systems (at least some linux fontconfig) define an order in which fonts are tried. So, it may happen the emoji is not rendering even though the user has the proper fonts for it. So I think if the fonts are not working properly, it is a fault of the user's system and not mine?

**Comment by damithc** [comment]
@RezwanArefin01 iP grade will not be affected if the product is usable even if the UI is slightly different than intended.
But you are encouraged to solve these problems as best as you can e.g., use a font that is common in all three OS'es, package the font with the app (if the license allow it), avoid using emojis etc.
