### ISSUE TITLE
Upstream ip repository has ACTUAL.txt in .gitignore

### ISSUE THREAD

**Issue by RezwanArefin01** [nus-cs2103-AY2223S1/forum#21]
Should be `ACTUAL.TXT`, as in the scripts. Otherwise `git` would prompt to add the file `ACTUAL.txt`.

**Comment by damithc** [comment]
Good catch @RezwanArefin01. Probably went unnoticed because doesn't affect Windows users. Reported at the main upstream repo https://github.com/se-edu/duke/issues/72
