### ISSUE TITLE
Bugs on Week 7 Topics

### ISSUE THREAD

**Issue by RussellDash332** [nus-cs2103-AY2223S1/forum#211]
- [x] Section 7.1, word 'UML' makes the page not scrollable upon embed preview
- [x] Cannot retake quizzes at 7.1, 7.3, and 7.7

**Comment by damithc** [comment]
Thanks @RussellDash332  for the bug reports

> * Section 7.1, word 'UML' makes the page not scrollable upon embed preview

Reported to the MarkBind team. Waiting for a solution.

> *  Cannot retake quizzes at 7.1, 7.3, and 7.7

Fixed

**Comment by damithc** [comment]
> * Section 7.1, word 'UML' makes the page not scrollable upon embed preview

Fixed.
