### ISSUE TITLE
Unable to open JAR file on Windows. Unable to open jar file by double-clicking on Mac

### ISSUE THREAD

**Issue by edricyeo** [nus-cs2103-AY2223S1/forum#213]
Details: MacOS Monterey 12.1
Code: Download my release [here](https://github.com/edricyeo/ip/releases/tag/A-Release)
Issue: Only able to open JAR file on mac. Unable to double-click to run the jar file on my mac, but able to open jar file using:
```java
java -jar duke.jar
```
When double-clicking the jar file on my mac, the jar file does not open but does not show any error.
When running the jar file using `java -jar duke.jar` on Windows OS, gets this error:

![IMAGE 2022-09-16 10:26:45](https://user-images.githubusercontent.com/80802319/190543333-14409289-630f-49b1-b2e0-60f85abeceb3.jpg)

**Comment by myangat0343** [comment]
I am using my mac, and I download your .jar file, I can double-clicking and open it.

**Comment by edricyeo** [comment]
@myangat0343 Oh thank you! Is there any setting you need to enable to get it to do so? I'm able to open some jar files by double clicking it on my mac but i cant open my own duke.jar file. Was wondering if there was something I was missing out, appreciate any help!

**Comment by Bubbl3T** [comment]
Testing on macOS, able to open file with double click.

For your Mac, you can try to right-click your jar file and hover over the "Open With" option to see if you are opening jar files with JavaLauncher as default.

For your Windows, not exactly sure why this happens, but you might consider checking if you have javafx (not just java) properly installed and used as the default java version. Else, you can try to copy-paste the error message onto google and try your luck.

**Comment by RezwanArefin01** [comment]
I also get the same error in Linux (Arch). For fixing the issue: remove the `javafx {}` block at the end of `build.gradle`. That part is actually restricting the packages. 

After that it runs, but the images are not being loaded: 
![Screenshot_20220916_155239](https://user-images.githubusercontent.com/22095441/190586950-0f261a83-01ea-41a0-80a7-dae399f38436.png)

**Comment by edricyeo** [comment]
@Bubbl3T Thank you! I am using JavaLauncher as default but can't seem to open it. Thanks for your help though!

**Comment by edricyeo** [comment]
@RezwanArefin01 Thank you for your help! You get the pipeline error on Linux as well? Not sure how to test the issue about the images not being loaded though... Please let me know if you find out how though! Appreciate it :)
