### ISSUE TITLE
Is it ok the input is only in GUI?

### ISSUE THREAD

**Issue by bokun2** [nus-cs2103-AY2223S1/forum#214]
Is it ok the app is without command line input? And in this case can I just delete the text-ui-test?

**Comment by damithc** [comment]
> Is it ok the app is without command line input?

@bokun2 Yes, it's OK for the iP (but not for the tP)

> And in this case can I just delete the text-ui-test?

Yes, you may (and should) delete stuff not used any more.

**Comment by bokun2** [comment]
Thank you prof.
