### ISSUE TITLE
Can we delete the readme file in the root of the repository?

### ISSUE THREAD

**Issue by pratham31012002** [nus-cs2103-AY2223S1/forum#215]
Are we required to delete the readme file in the root of the repository, so that the readme file in the docs folder(user guide) appears when someone visits the repository?

**Comment by damithc** [comment]
@pratham31012002 Isn't the former meant for developers visiting the repo and the latter is meant for users?

**Comment by pratham31012002** [comment]
Okay understood prof, thanks!
