### ISSUE TITLE
Request for smoke testing help (Linux)

### ISSUE THREAD

**Issue by ketamethane** [nus-cs2103-AY2223S1/forum#216]
Hi, I need smoke testing help on the Linux OS. The [jar](https://github.com/ketamethane/ip/releases/tag/A-Release) file and [UG](https://ketamethane.github.io/ip/) are here. Will appreciate any help, thank you!

**Comment by RezwanArefin01** [comment]
Tested on Linux (Arch). Deku's picture is not being loaded. Also can resize the window beyond the preferred size. 
![Screenshot_20220916_151257](https://user-images.githubusercontent.com/22095441/190578693-45aac61e-4181-456f-b1cc-22d03edfa753.png)

**Comment by ketamethane** [comment]
Noted, thanks for helping with the check! @RezwanArefin01 😃
