### ISSUE TITLE
Request for smoke testing help (Windows/Linux)

### ISSUE THREAD

**Issue by carriezhengjr** [nus-cs2103-AY2223S1/forum#219]
Hello! Could anyone help to test for Linux and Windows? Here is the [latest release](https://github.com/carriezhengjr/ip/releases/tag/A-Release). Thank you so much!

**Comment by RezwanArefin01** [comment]
Tested on Linux (Arch). Some images are not being loaded: 
![Screenshot_20220916_172730](https://user-images.githubusercontent.com/22095441/190605552-efbcfae3-aebd-4423-8c3f-72a324f37a18.png)
Read [this thread](https://github.com/nus-cs2103-AY2223S1/forum/issues/217) for possible fix.

**Comment by xhphoong** [comment]
I tested using windows. Everything is fine and the data folder is created. 
![Screenshot (402)](https://user-images.githubusercontent.com/92239144/190607796-bdbde77b-543a-4db3-9253-69d746d286a0.png)
![Screenshot (403)](https://user-images.githubusercontent.com/92239144/190607830-7e724c84-dfce-497a-a781-7f37c4f05835.png)

**Comment by RussellDash332** [comment]
Works on Windows 10! The quick start and detailed guide also works adding on to the previous comment
<img src="https://user-images.githubusercontent.com/63991775/190646208-dd2c8410-c561-4dd1-b9d9-156f51d325b9.png" width=40%>

**Comment by carriezhengjr** [comment]
> Tested on Linux (Arch). Some images are not being loaded: ![Screenshot_20220916_172730](https://user-images.githubusercontent.com/22095441/190605552-efbcfae3-aebd-4423-8c3f-72a324f37a18.png) Read [this thread](https://github.com/nus-cs2103-AY2223S1/forum/issues/217) for possible fix.

Thank you for helping! I have converted the images to png. Do you mind helping to test it again, especially the chatbot profile picture, user profile picture, quick start and detailed guide images? Here is the [new release](https://github.com/carriezhengjr/ip/releases/tag/A-Release). Really appreciate your help!

**Comment by carriezhengjr** [comment]
Thank you @xhphoong and @RussellDash332 for helping to test on Windows! 😄 

I have uploaded a new [jar file](https://github.com/carriezhengjr/ip/releases/tag/A-Release) to fix the image issues. If you don't mind, could you help to check if the new jar can be opened and is working fine? Really appreciate your help!

**Comment by RussellDash332** [comment]
Resizing is disabled now so that's good. The application title seems to be weird now
![image](https://user-images.githubusercontent.com/63991775/190655017-8697e629-54bd-4864-9036-b00df22ca64e.png)

**Comment by carriezhengjr** [comment]
> Resizing is disabled now so that's good. The application title seems to be weird now ![image](https://user-images.githubusercontent.com/63991775/190655017-8697e629-54bd-4864-9036-b00df22ca64e.png)

Alright! I have just updated the release by removing the emoji, since it also doesn't show properly on Linux previously. Thank you so much for your help! 😄

**Comment by RezwanArefin01** [comment]
Working as expected on Linux: 
![Screenshot_20220916_223547](https://user-images.githubusercontent.com/22095441/190664471-d31c3a7c-0e91-4cba-8e77-49d96c6b2fed.png)

**Comment by carriezhengjr** [comment]
> Working as expected on Linux: ![Screenshot_20220916_223547](https://user-images.githubusercontent.com/22095441/190664471-d31c3a7c-0e91-4cba-8e77-49d96c6b2fed.png)

Thank you so much! 😄
