### ISSUE TITLE
How to change the name to a old fork

### ISSUE THREAD

**Issue by Lan-Jingbo** [nus-cs2103-AY2223S1/forum#22]
I delete my original IP folders in my computer and create a new one with different name, and I re-fork with the nus-cs2103-AY2223S1 and completed codes and pushed them into github. I am able to see the code updating but the prof cannot see the updated version -- but the version with old name.

Could anyone teach my how to change name in fork and make it available to grader?

**Comment by damithc** [comment]
@Lan-Jingbo More generally, you are looking for 'How to rename a GitHub repository'. The same mechanism is likely to work whether it is a fork or a regular repository.

**Comment by Hikoya** [comment]
To respond to Prof's answer, here is how to rename a GitHub repository 

First, go to your repository, and click on the settings button

![image](https://user-images.githubusercontent.com/13346668/185308299-aaece240-ab34-4b1c-ab22-b93104e07c94.png)

Then, you will be able to rename your repository to 'ip' . Make sure to click the rename button!

![image](https://user-images.githubusercontent.com/13346668/185308444-6e758ab7-cbbc-41ca-a9f8-d83683beb0a9.png)

**Comment by Lan-Jingbo** [comment]
Thank you Hikoya, and by the way, how to send photo in this forum?

**Comment by Hikoya** [comment]
For me, I simply dragged and dropped the image into the input box directly. Github would automatically generate the markdown and upload the image to their server. 

For instance, the images uploaded in my previous comment were of :
https://user-images.githubusercontent.com/13346668/185308444-6e758ab7-cbbc-41ca-a9f8-d83683beb0a9.png
