### ISSUE TITLE
Gradle help

### ISSUE THREAD

**Issue by DarrenCsAcc** [nus-cs2103-AY2223S1/forum#220]
Hi all,

Previously i forked my cs2103 project from the wrong directory(1 or 2 semesters ago)i cannot remember.Gradle 
I am trying to install the gradle now but i am not sure how to do it.

I am unable to perform:
Gradle support is provided as a separate branch (named add-gradle-support) in the Duke repo. Therefore, you can follow the scenario 2 in the guide below.

So i was wondering how should i go about it?

Can i do this?

https://www.jetbrains.com/help/idea/gradle.html#convert_project_to_gradle

under the 
"Convert a regular project into a Gradle project"

Thank you.

**Comment by DarrenCsAcc** [comment]
Hi i ran into this error and have difficulty proceeding.I added this info into the gradle file

plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}
sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}
dependencies {
    compile 'junit:junit:4.12'
}


![image](https://user-images.githubusercontent.com/89026703/190626725-9e73f89e-1cbb-4bd3-8b9a-158d35251526.png)

**Comment by damithc** [comment]
> So i was wondering how should i go about it?
> 
> Can i do this?
> 
> https://www.jetbrains.com/help/idea/gradle.html#convert_project_to_gradle

@DarrenCsAcc No, you need to pull the `add-gradle-support` branch from the upstream repo and merge it to your master branch.

**Comment by DarrenCsAcc** [comment]
@damithc 
Hi prof unfortunately i proceeded  with this -> https://www.jetbrains.com/help/idea/gradle.html#convert_project_to_gradle
i cannot run my files for now at all.

![image](https://user-images.githubusercontent.com/89026703/190630049-27176ac8-76dd-4e44-965b-0ff8467d1bfb.png)


If i use -> you need to pull the add-gradle-support branch from the upstream repo and merge it to your master branch.
Will it fix the problem i just created?

Thank you

**Comment by damithc** [comment]
> If i use -> you need to pull the add-gradle-support branch from the upstream repo and merge it to your master branch.
> Will it fix the problem i just created?

@DarrenCsAcc Assuming the version you pushed to your fork last doesn't have this problem, you can clone your fork to a different location in your computer and resume the project from there.

**Comment by DarrenCsAcc** [comment]
@damithc 

Thanks prof.

This actually worked. Luckily i did not push or commit my problematic files.I will not try to be adventurous again. :(

**Comment by DarrenCsAcc** [comment]
![image](https://user-images.githubusercontent.com/89026703/190638901-b632b0f7-dbda-4113-a273-912b177c5c14.png)

Hi all,

So what i am trying to do now is i firstly added the branch add-gradle-support from the currrent upstream repo to my own branch.Then i am trying to pull it to my own local before merging it with my master.Somehow i am running into this error.Was wondering if anyone can help.

Edit *
I found i actually had the original gradle branch now i am trying to merge it


Thank you.
