### ISSUE TITLE
Request for Help to Smoke Test (Linux)

### ISSUE THREAD

**Issue by Nephelite** [nus-cs2103-AY2223S1/forum#221]
Hello, could anyone help me to test my [Jar file](https://github.com/Nephelite/ip/releases/tag/A-Release) in Linux? 
Here is the [User Guide](https://nephelite.github.io/ip/).

Thanks in advance!

**Comment by RezwanArefin01** [comment]
Some images not being loaded on Linux (Arch):
![Screenshot_20220917_013150](https://user-images.githubusercontent.com/22095441/190698700-0bef6a26-3ce9-4d5b-a296-971d463d158f.png)
Also got the following error in terminal: 
```
Sep 17, 2022 1:31:31 AM com.sun.javafx.css.StyleManager$ImageCache getCachedImage
WARNING: Error loading image: jar:file:/home/rezwanarefin01/Downloads/duke.jar!/images/starry_sky.jpg
Sep 17, 2022 1:31:32 AM com.sun.javafx.css.StyleManager$ImageCache getCachedImage
WARNING: Error loading image: jar:file:/home/rezwanarefin01/Downloads/duke.jar!/images/starry_sky.jpg
```
[This thread](https://github.com/nus-cs2103-AY2223S1/forum/issues/217) might be useful.

**Comment by Nephelite** [comment]
@RezwanArefin01 Thanks for the help! In accordance with your recommendation in that thread, I have tried converting the images to .png. I have thus updated my [jar file](https://github.com/Nephelite/ip/releases/tag/A-Release). Could you check this new jar file? Thanks!

**Comment by Nephelite** [comment]
Nevermind, I went and installed a Linux VM to test it and it should be working now. Thanks for the alert though!
