### ISSUE TITLE
Request for Smoke Test Help on Mac/Linux

### ISSUE THREAD

**Issue by johnrhimawan** [nus-cs2103-AY2223S1/forum#224]
Hi, can I ask for help to run smoke tests on Mac and Linux? I updated my previous release.

The JAR file can be found [here](https://github.com/johnrhimawan/ip/releases/tag/A-Release).

Thanks!

**Comment by seetohjinwei** [comment]
![image](https://user-images.githubusercontent.com/47915290/190638436-7a6c92a7-592a-42b4-89a4-e06867d75626.png)

Seems to work fine for me on macos!

**Comment by zhongfu** [comment]
seems to work fine (Linux, sway); force-resizing breaks layout

![image](https://user-images.githubusercontent.com/1695582/190890426-f3a1a5f2-6b51-44d4-a8eb-0a364831af75.png)
