### ISSUE TITLE
Request for Smoke-Test on Windows/Linux

### ISSUE THREAD

**Issue by EmilyOng** [nus-cs2103-AY2223S1/forum#225]
Hi! Here is my [application jar](https://github.com/EmilyOng/ip/releases/tag/A-Release) and [User Guide](https://emilyong.github.io/ip/), and I would appreciate any Smoke-Test help on Windows/Linux. Thanks!

**Comment by RussellDash332** [comment]
<img src="https://user-images.githubusercontent.com/63991775/190643198-14f812c6-649e-4e24-9519-90bd1be380f5.png" width="40%">
Works on Windows 10!

**Comment by EmilyOng** [comment]
Thanks!

**Comment by cheeheng** [comment]
I tested this on Windows 11: It works, but with the following warning:
```
Sep 16, 2022 9:46:46 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 18 by JavaFX runtime of version 11
```

**Comment by RezwanArefin01** [comment]
Everything seems to be working correctly on Linux (Arch): 
![Screenshot_20220916_223848](https://user-images.githubusercontent.com/22095441/190665101-0a3f5768-0b29-49f9-beb3-eca98c0d2446.png)

**Comment by EmilyOng** [comment]
Thanks everyone!
