### ISSUE TITLE
Gradle help

### ISSUE THREAD

**Issue by DarrenCsAcc** [nus-cs2103-AY2223S1/forum#226]
![image](https://user-images.githubusercontent.com/89026703/190649440-36bf2d2f-9455-478f-af6e-238ac26decb5.png)

Hi all,

I cannot seem to find the .idea folder and does step 2 means close the project and find the folder?
I am abit lost at this step.

Thank you!

**Comment by damithc** [comment]
> I cannot seem to find the .idea folder and does step 2 means close the project and find the folder?
> I am abit lost at this step.

@DarrenCsAcc  If you didn't open this project in IDEA before, there will not be any .idea folder. Otherwise it can be found in your project root folder.
If there is no such folder, you can skip step 3.

**Comment by DarrenCsAcc** [comment]
@damithc 
Thank you finally got it sorted out 

![image](https://user-images.githubusercontent.com/89026703/190678344-e737c7a7-6588-4df1-bb24-c745be70a4b6.png)
