### ISSUE TITLE
Requesting for smoke testing help (Windows/Linux)

### ISSUE THREAD

**Issue by kxrt** [nus-cs2103-AY2223S1/forum#229]
Hi! I’d appreciate some help getting this tested. My release is [here](https://github.com/kxrt/ip/releases/tag/A-Release) and my user guide can be found [here](https://kxrt.github.io/ip). 

Thank you!

**Comment by xhphoong** [comment]
Yes it works fine in windows and the data file is created as well. 
![Screenshot (404)](https://user-images.githubusercontent.com/92239144/190671310-f0fc7f32-e145-40a8-8480-625141d5ef7a.png)

**Comment by kxrt** [comment]
> Yes it works fine in windows and the data file is created as well. 
> 
> ![Screenshot (404)](https://user-images.githubusercontent.com/92239144/190671310-f0fc7f32-e145-40a8-8480-625141d5ef7a.png)
> 
> 

Thanks mate!

**Comment by RezwanArefin01** [comment]
Works as expected on Linux (Arch): 
![Screenshot_20220917_013949](https://user-images.githubusercontent.com/22095441/190700114-1f79f2d9-40ee-49d2-b6c1-51a6384e148c.png)

Minor issue: It keeps printing the following in terminal: 
```
Sep 17, 2022 1:39:43 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 18 by JavaFX runtime of version 11
```
This issue can be fixed as described in [this thread](https://github.com/nus-cs2103-AY2223S1/forum/issues/193).

**Comment by RussellDash332** [comment]
Works for me as well, even when I try to resize the window. Awesome work, Artemis!

![image](https://user-images.githubusercontent.com/63991775/191033933-49603964-90bc-4084-bf7a-335eaa7c0cd3.png)

**Comment by kxrt** [comment]
Thank you for the further testing @RezwanArefin01 @RussellDash332! It's a bit too late to fix that terminal warning, but I'll keep it in mind for the future. :)
