### ISSUE TITLE
Clarification of definition of single-level design

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#231]
The quiz in Week 6 Question 31 claims that the statement is "given" or at least implied in the textbook. However, in the textbook (at least for Week 6 content), I can't find the precise definition of "single-level" design under the section "Multi-level Design". Does a single-level design mean that the UML class diagram can fit within a page without the text getting too small? 

<img width="878" alt="image" src="https://user-images.githubusercontent.com/13196670/190660325-7f02c211-7b01-4741-99bb-5897aae58c97.png">

**Comment by damithc** [comment]
@cheeheng It is true that the _single-level design_ is not defined precisely but it can be inferred from the definition of the _multi-level design_ -- which is a design described at multiple levels i.e., a high-level design (e.g., the architecture diagram) and some lower level designs to go with it (e.g., the detailed design of each component). So, a single-level design is one that is not multi-level i.e., the whole design is given at once as a single diagram, as is done for AB2.
