### ISSUE TITLE
Request for Smoke Test Help (Mac/Linux)

### ISSUE THREAD

**Issue by Rachel-AG** [nus-cs2103-AY2223S1/forum#232]
Hi, I've just updated my previous release and I would really appreciate it if anyone can help me run some smoke tests on Mac/Linux. 

The JAR file can be found [here](https://github.com/Rachel-AG/ip/releases/tag/A-Release).

Thanks you!

**Comment by sltsheryl** [comment]
Working fine on Mac
<img width="395" alt="Screenshot 2022-09-16 at 11 06 01 PM" src="https://user-images.githubusercontent.com/96589109/190670978-6751047b-47e1-4df9-add1-89f2d73085d6.png">

**Comment by RezwanArefin01** [comment]
Working as expected on Linux (Arch): 
![Screenshot_20220917_014604](https://user-images.githubusercontent.com/22095441/190701188-1bd1c8f0-9ab2-4cf3-87fa-d3dba800747e.png)

**Comment by Rachel-AG** [comment]
Thank you!! @RezwanArefin01 @sltsheryl
