### ISSUE TITLE
Cannot build JAR filed

### ISSUE THREAD

**Issue by DarrenCsAcc** [nus-cs2103-AY2223S1/forum#235]
![image](https://user-images.githubusercontent.com/89026703/190699196-ebfe99c4-60b8-45b4-95b5-919b41bdbc25.png)

Hi i am trying to build the JAR file from this video.Everything works until when i click build artifact it throws me this error.

https://se-education.org/guides/tutorials/jar.html

Was wondering if anyone knows how to solve this.

Thank you!

**Comment by DarrenCsAcc** [comment]
I tried restarting my intelliJ IDE for now hopping it works

**Comment by RussellDash332** [comment]
As stated, you need to set up the JDK first for this current project.

**Comment by DarrenCsAcc** [comment]
@RussellDash332 
For some reason when I restart my IDE somehow it works.
Thanks for the help though appreciate it!
