### ISSUE TITLE
Unable to open jar file on my own computer

### ISSUE THREAD

**Issue by qiaoen17** [nus-cs2103-AY2223S1/forum#236]
I built my jar file using shadowJar and tried opening it using Java(TM) Platform Binary, but it does not open. So I tried launching it through intelliJ and it gives me the following error: 

![Screenshot (232)](https://user-images.githubusercontent.com/92434807/190697800-490af049-2bab-4f2c-958e-de36acc3b955.png)

I went to check for the suggested fix from another post but I already fixed it:

![Screenshot (233)](https://user-images.githubusercontent.com/92434807/190698150-b3e7bfff-e588-4213-ab7a-c0f3c662cd6c.png)

The error says it was caused by `NullPointerException` so I tried looking into the line where it says it has an error.

![Screenshot (231)](https://user-images.githubusercontent.com/92434807/190698804-3627de9a-e10e-4c79-b409-e686c04a145b.png)

I tried removing line 20, but it still gives me the same error message` NullPointerException` occurred at line 20, so I'm not sure what to do now. I have tried searching online and found the following website:
[Stackoverflow link](https://stackoverflow.com/questions/55123711/javafx-error-exception-in-application-start-method)

But I'm not sure how to follow the fix there. If anyone has encountered this issue and solved it, please help.

**Comment by RezwanArefin01** [comment]
The thing being null means it couldn't get the image from the directory specified. The path specified is `/image/kiwi.png`. But as I can see from the left bar: the folder is named `Images`, with capital `I`. 

I have cloned and fixed it. Then I can build and run the Duke, on Linux (Arch): 
![Screenshot_20220917_015902](https://user-images.githubusercontent.com/22095441/190702965-7a9a0104-a061-4b97-9a96-eb973f2bbd35.png)

Also nice aesthetics! The KIWI logo on the top makes it stand out from other Dukes.

**Comment by qiaoen17** [comment]
It works now 👍 Thank you so much!
