### ISSUE TITLE
Change repo name to original?

### ISSUE THREAD

**Issue by kianseong** [nus-cs2103-AY2223S1/forum#237]
I have renamed my forked repo to something else not iP. Should I change it to iP or leave it?

**Comment by RussellDash332** [comment]
According to [this](https://stackoverflow.com/questions/5751585/how-do-i-rename-a-repository-on-github), it's fine since you're the only one working on that particular repo, but do take a look on how to reconfigure the git configs correctly

**Comment by kianseong** [comment]
Thank you @RussellDash332! But I was wondering if this was a CS2103T requirement?

**Comment by RussellDash332** [comment]
> Thank you @RussellDash332! But I was wondering if this was a CS2103T requirement? 

What do you mean with requirement? The repo name should be "ip" only so

**Comment by damithc** [comment]
> The repo name should be "ip" only so

Yup, it must be `ip` for our scripts to detect it.
