### ISSUE TITLE
Pull request to team's TP repo failing codecov check 

### ISSUE THREAD

**Issue by sltsheryl** [nus-cs2103-AY2223S1/forum#239]
Hi I was following this week's tutorial to add a Remark feature to addressbook and create a PR to the team's repo from my fork. 
However, I'm failing this check. My team has set up codecov already. This is found in the branch `tutorial-adding-command` in my fork of my team's repo. Thanks!
<img width="1104" alt="Screenshot 2022-09-17 at 11 02 19 AM" src="https://user-images.githubusercontent.com/96589109/190838203-b36b3dba-0b12-4dfe-b693-fd56caa4ba34.png">

**Comment by damithc** [comment]
@sltsheryl It might help to post a link to the page shown in the screenshot.

**Comment by sltsheryl** [comment]
Ah okay, [here](https://github.com/AY2223S1-CS2103T-T11-4/tp/actions/runs/3071873273/jobs/4962935988) is the page showing the logs.

**Comment by seelengxd** [comment]
This is kinda a guess (i might be wrong)

https://codecov.io/gh/AY2223S1-CS2103T-T11-4/team-repo

so the name is `team-repo` on code-cov

but your team repo name is `tp`...

```
Pinging Codecov: https://codecov.io/upload/v4?package=github-action-2.1.0-uploader-0.3.1&token=*******&branch=tutorial-adding-command&build=3071873273&build_url=https%3A%2F%2Fgithub.com%2FAY2223S1-CS2103T-T11-4%2Ftp%2Factions%2Fruns%2F3071873273&commit=c355cf412815532ec32ef29d9bf3b05517bdf2db&job=Java+CI&pr=4&service=github-actions&slug=AY2223S1-CS2103T-T11-4%2Ftp&name=&tag=&flags=&parent=
[2022-09-17T03:01:18.215Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Could not find a repository, try using repo upload token', code='not_found')}
```

and the error is it cannot find the repo and it is trying to find `tp`

i think this is a codecov repo name wrong problem and not really your code

**Comment by sltsheryl** [comment]
> This is kinda a guess (i might be wrong)
> 
> https://codecov.io/gh/AY2223S1-CS2103T-T11-4/team-repo
> 
> so the name is `team-repo` on code-cov
> 
> but your team repo name is `tp`...
> 
> ```
> Pinging Codecov: https://codecov.io/upload/v4?package=github-action-2.1.0-uploader-0.3.1&token=*******&branch=tutorial-adding-command&build=3071873273&build_url=https%3A%2F%2Fgithub.com%2FAY2223S1-CS2103T-T11-4%2Ftp%2Factions%2Fruns%2F3071873273&commit=c355cf412815532ec32ef29d9bf3b05517bdf2db&job=Java+CI&pr=4&service=github-actions&slug=AY2223S1-CS2103T-T11-4%2Ftp&name=&tag=&flags=&parent=
> [2022-09-17T03:01:18.215Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Could not find a repository, try using repo upload token', code='not_found')}
> ```
> 
> and the error is it cannot find the repo and it is trying to find `tp`
> 
> i think this is a codecov repo name wrong problem and not really your code

Hmm thanks for helping to look at this, I'm still abit confused.

I think my team named our repo as `team-repo` but yup, that one member forked it from the CS2103T's `tp` repo. So I thought the naming (`team-repo`) matches? Or is our repo supposed to be named `tp` because its default is to find a repo called `tp` (?) or can/should we change it to find `team-repo` instead? (currently, we only modified `index.md` to display the codecov badge but I'm not sure if we are to change other areas)

**Comment by damithc** [comment]
> Or is our repo supposed to be named `tp` because its default is to find a repo called `tp` (?) or can/should we change it to find `team-repo` instead?

It should be `tp`.

**Comment by sltsheryl** [comment]
> > Or is our repo supposed to be named `tp` because its default is to find a repo called `tp` (?) or can/should we change it to find `team-repo` instead?
> 
> It should be `tp`.

Alright I will make the necessary changes and see if it works. Thanks!

**Comment by sltsheryl** [comment]
Thank you both for troubleshooting! It's working now, we will read more carefully next time.
