### ISSUE TITLE
A-TextUiTesting

### ISSUE THREAD

**Issue by SpecOps2016** [nus-cs2103-AY2223S1/forum#24]
![image](https://user-images.githubusercontent.com/76586680/185320487-1031a7d1-3a2c-4000-bf69-a0310917eecd.png)

Can someone tell me whether this indicates whether the test has passed or failed? I am running this on Windows

**Comment by RussellDash332** [comment]
Have you fed `input.txt` some input commands?

**Comment by SpecOps2016** [comment]
Yes I did

**Comment by parnikkapore** [comment]
This is a test failure. EXPECTED.TXT is the expected (correct) output -  three blank lines (??), while ACTUAL.TXT is the actual output of your program - completely empty.

[Apparently](https://www.howtogeek.com/206123/) FC will say "no differences encountered" if there are no differences, i.e. a test pass.

**Comment by SpecOps2016** [comment]
![image](https://user-images.githubusercontent.com/76586680/185368142-49e1efcc-08a7-4252-a054-8db1628d2749.png)
Any reason why EXPECTED.TXT is showing up as three blank lines?

**Comment by SpecOps2016** [comment]
![image](https://user-images.githubusercontent.com/76586680/185368556-ffe59312-3e09-4554-91c7-0f80187e77f6.png)
This is my input.txt

**Comment by neosunhan** [comment]
Try removing the empty lines at the bottom of your EXPECTED.TXT.

**Comment by gunbux** [comment]
I think the issue here is that both `diff` and `fc` are really not suited to comparing differences between the two .txt files. What I found worked for me is right clicking the file in intellij, then select `Compare With`, and compare the ACTUAL.txt to EXPECTED.txt
![image](https://user-images.githubusercontent.com/46131429/185444280-b99256df-4b1f-40db-a056-3e364b05c5a2.png)

**Comment by SpecOps2016** [comment]
> I think the issue here is that both `diff` and `fc` are really not suited to comparing differences between the two .txt files. What I found worked for me is right clicking the file in intellij, then select `Compare With`, and compare the ACTUAL.txt to EXPECTED.txt ![image](https://user-images.githubusercontent.com/46131429/185444280-b99256df-4b1f-40db-a056-3e364b05c5a2.png)

Thank you! This helped with my issue.
