### ISSUE TITLE
Request for smoke test for MacOS/Linux

### ISSUE THREAD

**Issue by nehcuy** [nus-cs2103-AY2223S1/forum#240]
Could anyone help me run my [jar](https://github.com/nehcuy/ip/releases/tag/v1.0) file? I'm currently facing the problem of my background image not displaying on my jar file application.  
However, it works fine when I run my launcher in Intellij. I've already tried it by double-clicking the duke.jar file, and also running `java -jar duke.jar`.
Both times my background image does not show up, even though I did not edit my sourcecode. Just wanted to check if it was a Windows problem or it's shared across other OS.

**Edit:**
Background image should look like this:
![image](https://user-images.githubusercontent.com/94856691/190840630-c0ff1722-bd6f-41ab-8d71-5e06550119e8.png)

**Comment by RezwanArefin01** [comment]
~~How is your jar 52.9MB... are you giving us some malware~~
The background image did not show up in Linux (Arch): 
![Screenshot_20220917_123924](https://user-images.githubusercontent.com/22095441/190840727-0c3480cb-f32c-4e62-99f2-bf8457004c39.png)
Try re-downloading the background image / convert it to another format and back. This problem happens mostly due to some sort of corruption in the image file.

**Comment by damithc** [comment]
> How is your jar 52.9MB... ?

Yup, this should not be the case. Check the size of resource files used and use smaller versions if the files are too big.

**Comment by nehcuy** [comment]
@RezwanArefin01 It's due to the background image being too large. 😅 Apologies for the scare! If I were to replace it with another image of lower resolution, however, the same problem arises.
I've already updated my duke.jar to remove the high resolution image with a simpler background image.
**Edit**: Same [jar file](https://github.com/nehcuy/ip/releases/tag/v1.0) link used.

Desired output should now be like this:
![image](https://user-images.githubusercontent.com/94856691/190841657-37526c7e-3106-4d2a-8b7d-e2181efa1b77.png)

**Comment by carriezhengjr** [comment]
Hi, this is what's shown on my Mac, background image cannot be displayed:
<img width="397" alt="Screenshot 2022-09-17 at 13 21 22" src="https://user-images.githubusercontent.com/97394017/190841845-3c6d9763-5b27-4c24-bfe8-9486ff87ccf0.png">

**Comment by nehcuy** [comment]
@carriezhengjr Oh dear, thanks for checking! I think the problem arises from not being able to set the ScrollPane to be transparent, as I've already checked that the filepath to the image is correct.
Apparently there's a similar issue found [online](https://stackoverflow.com/questions/28324578/javafx-deployment-images-get-lost), but trying it does not remedy my issue. 😞
