### ISSUE TITLE
Request smoke test for Linux system

### ISSUE THREAD

**Issue by dexter-sim** [nus-cs2103-AY2223S1/forum#241]
Hi, I would really appreciate it if anyone can help me run some smoke tests on Linux.

https://github.com/dexter-sim/ip/releases/tag/v0.3

Thank you!

**Comment by Nephelite** [comment]
As far as I can tell, your jar file works fine on Linux. However, I ran your jar file via a VIrtualBox Linux VM, so it might be best if someone else with an actual Linux system also tests this.

**Comment by RezwanArefin01** [comment]
Tested on Linux (Arch). Works as expected: 
![Screenshot_20220917_174034](https://user-images.githubusercontent.com/22095441/190850534-5a2a9373-7b9b-4614-a04a-0bb3a64df2fd.png)

**Comment by dexter-sim** [comment]
Thank you for testing.
