### ISSUE TITLE
CI unsuccessful IO redirection test due to file not found error

### ISSUE THREAD

**Issue by Bubbl3T** [nus-cs2103-AY2223S1/forum#243]
My Gradle can't seem to find my Java files, anyone knows how to solve this?
[Here](https://github.com/Bubbl3T/ip) is my repository, any help is appreciated!

![image](https://user-images.githubusercontent.com/72196376/190849813-db8805a6-f7d4-4c35-8f19-9dae71a88f6b.png)

**Comment by RussellDash332** [comment]
Change line 16 of `runtest.sh` to
```sh
if ! javac -cp ../src/main/java -Xlint:none -d ../bin ../src/main/java/duke/*.java
```
and line 23 to this.
```sh
java -classpath ../bin duke/Duke < input.txt > ACTUAL.TXT
```

Similarly, line 10 in `runtest.bat`
```bat
javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\duke\*.java
```
and line 18.
```bat
java -classpath ..\bin duke\Duke < input.txt > ACTUAL.TXT
```

Let me know if this works 😁

**Comment by Bubbl3T** [comment]
@RussellDash332 Yep this works! I guess this happened because I did not make changes here when I refactored duke. Thanks for the detailed help! 😄

Now I at least I know where to debug the program. Let me just fix some minor issues and I should be done :)

![image](https://user-images.githubusercontent.com/72196376/190859817-0656f3ae-6a7e-4472-858a-5e7b9edf6cd5.png)

**Comment by RussellDash332** [comment]
Yup, that seems like an unsupported GUI issue, and since this test is just for text UI testing, it should run the non-GUI version instead.

**Comment by Bubbl3T** [comment]
Yeah, but because I kinda removed the text UI features, I guess I won't be able to run this without errors now :( But well, at least learnt something new, thanks! :)
