### ISSUE TITLE
Request for Smoke-Test on Windows/Linux

### ISSUE THREAD

**Issue by chloeelim** [nus-cs2103-AY2223S1/forum#244]
Hello! Here is my [JAR file](https://github.com/chloeelim/ip/releases/tag/A-Release) and [User Guide](https://chloeelim.github.io/ip/), any help in doing a smoke test on the JAR file on Windows/ Linux would be greatly appreciated. Thank you! : )

**Comment by ReaganTan00** [comment]
Works fine on windows!

![image](https://user-images.githubusercontent.com/97376457/190854276-23b22180-5cec-4678-a9dc-56cccc106789.png)

**Comment by RussellDash332** [comment]
Works like a charm! Nice header btw!
![image](https://user-images.githubusercontent.com/63991775/190854561-4402ec1c-eb84-4ea5-904c-0e398c79917a.png)

**Comment by chloeelim** [comment]
Thanks for the help! (Have a great recess week ^^)
