### ISSUE TITLE
Request smoke test for MacOS/Linux 

### ISSUE THREAD

**Issue by ReaganTan00** [nus-cs2103-AY2223S1/forum#245]
Hi, would appreciate help with running smoke test for MacOS and Linux users. The jar file is [here](https://github.com/ReaganTan00/ip/releases/tag/A-Release) and the user guide is [here](https://github.com/ReaganTan00/ip/blob/master/docs/README.md).

Thank you!

**Comment by seetohjinwei** [comment]
![image](https://user-images.githubusercontent.com/47915290/190860425-09a49cab-6314-4902-abeb-744f395d1618.png)


Hi! Seems to work fine on macos (except resizing the window).

**Comment by zhongfu** [comment]
seems to run fine in Linux (sway). force-resizing app breaks window layout though, and it seems like your fxml files have the wrong version (perhaps because of scenebuilder)

![image](https://user-images.githubusercontent.com/1695582/190890258-3e2c8485-5753-4dbc-9bd4-9864d1aa6bd2.png)

**Comment by ReaganTan00** [comment]
@zhongfu @seetohjinwei Thank you both!
