### ISSUE TITLE
Request smoke test for MacOS/Linux

### ISSUE THREAD

**Issue by gerardstevan** [nus-cs2103-AY2223S1/forum#247]
Hi all, I need help to test my [app](https://github.com/gerardstevan/ip/releases) on Mac and Linux. 

Would appreciate any help. Thank you!

**Comment by sltsheryl** [comment]
Can open on Mac! But doesn't support resizing
<img width="389" alt="Screenshot 2022-09-18 at 8 31 22 AM" src="https://user-images.githubusercontent.com/96589109/190880626-071e0871-7c24-4947-9fd8-7b36b319422b.png">

**Comment by zhongfu** [comment]
seems to work fine on Linux (sway), though if I force-resize your app, the elements don't resize to fit

(also, `bye` doesn't cause the app to exit, and the task list gets saved in `src/main/java/data/`, or something like that)

![image](https://user-images.githubusercontent.com/1695582/190890069-5e10a037-d86d-43f0-b063-e693772eb54a.png)
