### ISSUE TITLE
Request smoke test for MacOS/Linux

### ISSUE THREAD

**Issue by wweqg** [nus-cs2103-AY2223S1/forum#248]
Hi, I need help to test my [app](https://github.com/wweqg/ip/releases/tag/v0.2) on Mac/Linux. The user guide is [here](https://wweqg.github.io/ip/).

**Comment by zhongfu** [comment]
looks ok on Linux (sway), except for the font size of the "Send" (?) button being a little too big. (scaling issue?)

![image](https://user-images.githubusercontent.com/1695582/190889985-124c1f59-0931-433c-9d4a-64eac05e8e7b.png)

**Comment by wweqg** [comment]
> looks ok on Linux (sway), except for the font size of the "Send" (?) button being a little too big. (scaling issue?)
> 


Thank for check, I will fix the font size issue 👍
