### ISSUE TITLE
Request smoke test for MacOS/Linux

### ISSUE THREAD

**Issue by Elben85** [nus-cs2103-AY2223S1/forum#250]
Hello, I need help testing my [app](https://github.com/Elben85/ip/releases/tag/A-Release).

Any help would be appreciated. Thank you!!

**Comment by RezwanArefin01** [comment]
Working as expected on Linux (Arch). But resize doesn't work properly. You may disable it by `stage.setResizable(false);`. 
![Screenshot_20220918_164209](https://user-images.githubusercontent.com/22095441/190893568-ed9fe4d1-5987-4fc8-8eb0-0fa598d805a6.png)

**Comment by Elben85** [comment]
> Working as expected on Linux (Arch). But resize doesn't work properly. You may disable it by `stage.setResizable(false);`. 

Thanks!! appreciate the help.
