### ISSUE TITLE
Library request: org.json

### ISSUE THREAD

**Issue by leonidas1712** [nus-cs2103-AY2223S1/forum#251]
## Library

[org.json](https://mvnrepository.com/artifact/org.json/json/20220320)

## Purpose

Used to implement saving and loading tasks to/from disk in Level-7. 
(I did not realise we had to request for permission to use third-party libraries for the iP, so my tutor said I should clarify before submitting)

## License

Public Domain -  see [repo](https://github.com/stleary/JSON-java/blob/master/LICENSE).

**Comment by damithc** [comment]
Approved.
