### ISSUE TITLE
Request smoke test for Linux

### ISSUE THREAD

**Issue by leonidas1712** [nus-cs2103-AY2223S1/forum#252]
Hello, I need help to test my iP on Linux. My release is [here](https://github.com/huzaifa1712/ip/releases/tag/v0.2) and my user guide is [here](https://huzaifa1712.github.io/ip/). Thanks.

**Comment by RezwanArefin01** [comment]
Getting a window like this on Linux (Arch), with no way to resize too: 
![Screenshot_20220918_212114](https://user-images.githubusercontent.com/22095441/190904271-9c1aae99-1359-46d2-8054-1eef9ecfd091.png)
