### ISSUE TITLE
Request smoke test for MacOS

### ISSUE THREAD

**Issue by sugiyem** [nus-cs2103-AY2223S1/forum#253]
Hi all, would really appreciate if anyone can help me test my [app](https://github.com/sugiyem/ip/releases) on MacOS. You can view my User Guide [here](https://sugiyem.github.io/ip).

Thank you!

**Comment by leonidas1712** [comment]
<img width="398" alt="Screenshot 2022-09-18 at 10 45 24 PM" src="https://user-images.githubusercontent.com/20151382/190913027-c68486e6-6d35-453a-8f53-7432d928624e.png">

Works on macOS Monterey. Loading existing tasks also works.

**Comment by sugiyem** [comment]
@huzaifa1712 thanks!!
