### ISSUE TITLE
Request for Smoke Test Help on Mac and Linux

### ISSUE THREAD

**Issue by WR3nd3** [nus-cs2103-AY2223S1/forum#256]
Hi guys,

Can I have help with testing my jar file on Mac and Linux?
The release can be reached [here](https://github.com/WR3nd3/ip/releases/tag/v0.2) and my user guide can be reached [here](https://wr3nd3.github.io/ip/). 
Thanks so much!

**Comment by RezwanArefin01** [comment]
Working as expected on Linux (Arch): 
![Screenshot_20220919_010152](https://user-images.githubusercontent.com/22095441/190919329-27b51709-c73d-49b4-9164-1af212845bd0.png)

**Comment by albertZhangTJ** [comment]
Works on Ubuntu 20.04:
![Kazam_screenshot_00025](https://user-images.githubusercontent.com/72067599/190936854-ce885ef1-795e-4c24-98fc-9896532e95d7.png)

**Comment by optionalemon** [comment]
Works fine on Mac (Doesn't have the font for user input and enter button if that matters)
<img width="401" alt="Screenshot 2022-09-19 at 14 04 15" src="https://user-images.githubusercontent.com/86706511/190957880-743431c4-e656-40fd-8838-f7f49d0f402e.png">

**Comment by WR3nd3** [comment]
Thanks for helping me out guys!
