### ISSUE TITLE
Requesting Permission to use Jackson 2.10

### ISSUE THREAD

**Issue by rui-han-crh** [nus-cs2103-AY2223S1/forum#257]
## Library

[jackson-databind](https://mvnrepository.com/artifact/com.fasterxml.jackson.core)
[jackson-datatype-jsr310](https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310)

## Purpose

Intended to be used for serialising and deserialising classes (jackson-databind) and Java Date and Time API objects (jackson-datatype-jsr310). I saw these were used in the tp source code to save and load data into json files and I wanted to use them for my ip.

## License

[Apache 2.0](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind)

**Comment by damithc** [comment]
Approved.
