### ISSUE TITLE
Requesting for smoketest for windows

### ISSUE THREAD

**Issue by crvstalphua** [nus-cs2103-AY2223S1/forum#259]
Hi, need help testing my iP on windows!

Here's my [release](https://github.com/crvstalphua/ip/releases/tag/A-Release), any help would be great! Thanks!

**Comment by RussellDash332** [comment]
<img src="https://user-images.githubusercontent.com/63991775/190926187-9804e5bc-8b35-40a1-aae8-6b0c4e7e4dde.png" width="50%">
Works on Windows, but this is what happens when I resize it.
