### ISSUE TITLE
Question about A-TextUiTesting

### ISSUE THREAD

**Issue by johnrhimawan** [nus-cs2103-AY2223S1/forum#26]
How comprehensive should the testing be? How many test cases are we recommended to use?

**Comment by damithc** [comment]
@johnrhimawan 

From a grading point of view, in this specific case, it's good enough if you can demonstrate that you are able to use the technique.
But if you have the time, try to push the technique to the limits and observe costs/benefits. You will learn more that way.
From an SE point of view, as is the case for many such questions, the general answer is "it depends" (on costs, benefits, aims, resource constraints etc.). Anyway, we'll be learning more about various aspects of testing in later weeks.

**Comment by johnrhimawan** [comment]
Ok, thanks for the clarification Prof!
