### ISSUE TITLE
Request for smoketest on Mac

### ISSUE THREAD

**Issue by albertZhangTJ** [nus-cs2103-AY2223S1/forum#260]
Hi guys!

Can anyone help test out the [jar for my ip](https://github.com/albertZhangTJ/ip/releases/tag/A-Release-updated) on Mac? Thanks in advance!

**Comment by albertZhangTJ** [comment]
For any questions related to command syntax, please type `help` in the application. A help message will be displayed. Thank you!

**Comment by optionalemon** [comment]
<img width="401" alt="Screenshot 2022-09-19 at 13 58 21" src="https://user-images.githubusercontent.com/86706511/190957322-74711c13-84fd-436f-90d9-bad1252c9e00.png">
Works on Mac, but is the right sidebar intended to have a gap over there?

**Comment by WuHaohui1231** [comment]
![Screenshot 2022-09-19 at 3 43 46 PM](https://user-images.githubusercontent.com/95847459/190971382-a6456a2a-c436-40ac-be62-a07bc03c6bba.png)
Works well on my Mac!

**Comment by albertZhangTJ** [comment]
@optionalemon Noted with thanks, it is indeed a small mismatch in width setting. Already corrected.

**Comment by albertZhangTJ** [comment]
@WuHaohui1231 Thank you for your help!
