### ISSUE TITLE
Request for smoketest on Windows and Linux

### ISSUE THREAD

**Issue by WuHaohui1231** [nus-cs2103-AY2223S1/forum#261]
Anyone with Windows or Linux machine can help test my JAR? Here is the [release](https://github.com/WuHaohui1231/ip/releases/tag/v1.0)
You can try resizing the window
Thanks in advance!

**Comment by JasonYapzx** [comment]
Hey, everything seems to be working fine on my windows 10 machine (reading and writing of save files, commands, and erroneous commands), just the resizing of the application does not follow for the main chat itself. Only the input text field adjusts accordingly. Hope this helps!

![image](https://user-images.githubusercontent.com/63844743/190971453-da8570c8-624b-4a35-8c58-45f90647b6a1.png)

**Comment by albertZhangTJ** [comment]
Seems to work fine on Ubuntu 20.04 (other than the previously mentioned problem with resizing).
![Kazam_screenshot_00026](https://user-images.githubusercontent.com/72067599/190971571-7f020774-5ebd-4211-9aa8-7ff82319909b.png)

**Comment by Eclipse-Dominator** [comment]
GUI works fine on Windows and WSL for me. 
However there is a bug when the save file is corrupted and the program tries to save an entry.
i.e. 
Content of save file:
```
T|0|hello
T|0test 123
```
____
When running with the above corrupted save file, you are now unable to add any new task to the save file.
Attempting to add a new task will throw the error below
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/4567895/190980622-73dcb84a-20fb-4dad-8e2e-d275bfdb9bfe.png">
