### ISSUE TITLE
What to do if edit userguide

### ISSUE THREAD

**Issue by shawnkai** [nus-cs2103-AY2223S1/forum#262]
Hi Prof @damithc , I pushed a commit with the tag A-userguide to github, but i realised there were some errors when reviewing the HTML version of the user guide and I pushed another commit to rectify the errors. Is there a need to move the tag to the later commit and if there is such a need may I know how should I be doing that? Thank you!

**Comment by damithc** [comment]
@shawnkai To answer the first question, moving the tag is optional. Our script checks only for the existence of the tag, not the location.

**Comment by shawnkai** [comment]
ok thanks prof!
