### ISSUE TITLE
Request for smoke test help (Linux)

### ISSUE THREAD

**Issue by ish1506** [nus-cs2103-AY2223S1/forum#263]
Hi, could someone with Linux help me test my [app](https://github.com/ish1506/ip/releases/tag/A-Release) please.
User guide [here](https://ish1506.github.io/ip/).

Thanks!

**Comment by RezwanArefin01** [comment]
Working as expected on Linux (Arch). Turn off the resizeability though: 
![Screenshot_20220919_210021](https://user-images.githubusercontent.com/22095441/191022980-e1571227-93db-4c4a-82fd-61c919847bad.png)

**Comment by ish1506** [comment]
Thank you!
