### ISSUE TITLE
Request for help for smoke test for Linux and Mac

### ISSUE THREAD

**Issue by shawnkai** [nus-cs2103-AY2223S1/forum#264]
Hi guys,

Can I have help with testing my jar file on Mac and Linux?
The release can be reached [here](https://github.com/shawnkai/ip/releases/tag/v0.2) and my user guide can be reached [here](https://shawnkai.github.io/ip/).
Thanks so much!

**Comment by drkkjh** [comment]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/61372278/191011823-8db77208-71b7-455d-b2e6-aa7ee0cf3e4e.png">

Seems to work fine for me on macOS, however, not sure if the gap between the send and the user input is intended?

**Comment by shawnkai** [comment]
ok thanks! it wasn't intended but i think it'd be good if there was a gap haha
