### ISSUE TITLE
Request for smoke test on Windows 

### ISSUE THREAD

**Issue by DarrenCsAcc** [nus-cs2103-AY2223S1/forum#265]
Albeit my quality is not very good.
Hope someone can help me test.

I deleted my previous release.
Jar file is here -> look for the latest release it should be version 0.2 and the file size is about 10.9mb
[](https://github.com/DarrenCsAcc/ip/releases/tag/A-Jar)

Here is my user guide.
https://github.com/DarrenCsAcc/ip/blob/master/docs/README.md

Thank you!

**Comment by rui-han-crh** [comment]
I've tried opening the file on two computers, but the jar file won't open. 

Using `java -jar ip.jar` gives `no main manifest attribute, in ip.jar`. Double clicking the file doesn't open the file either.

I took a look at your `build.gradle` file, you've set `mainClassName` under `application` to `seedu.duke.Duke`. Try changing this to your package names and launcher class. For example, for mine, my entry point is the Launcher class in the dukeprogram package, so my `mainClassName` is `dukeprogram.Launcher`.

**Comment by RussellDash332** [comment]
[This is the JAR](https://github.com/DarrenCsAcc/ip/releases/tag/A-Jar) for quick reference.

Same as @rui-han-crh, I have the same issue so the JAR doesn't open. The suggestion given above might help fixing it!

**Comment by DarrenCsAcc** [comment]
thank you for your help! 
@rui-han-crh 

and thanks for helping me check
@RussellDash332 

Here is the changes proposed by @rui-han-crh
[Ammended file ](https://github.com/DarrenCsAcc/ip/releases/tag/A-Jar)

**Comment by RussellDash332** [comment]
It creates a text file `help.txt` right away and the application doesn't open on my end. Let me see what happens and get back to you.

**Comment by DarrenCsAcc** [comment]
@rui-han-crh 
@RussellDash332 
[I fixed the delete here is there newest release](https://github.com/DarrenCsAcc/ip/releases/tag/A-Jar-v0.4)

**Comment by DarrenCsAcc** [comment]
@rui-han-crh 
Thanks for finding a bug that needs fixing .i will work on it

**Comment by rui-han-crh** [comment]
> It creates a text file `help.txt` right away and the application doesn't open on my end. Let me see what happens and get back to you.

@RussellDash332 
Yea I told Darren it's presently an issue with event and deadline tasks not being able to be deserialised from single word names. If we try
```
deadline abc /by 2022-12-12
```
or
```
event abc /at 2022-12-12
```
Both will stop the jar file from opening again, but names with more than two letters work properly, like

```
deadline watch lecture /by 2022-12-12
```
or
```
event eat food yum /at 2022-12-12
```

**Comment by RussellDash332** [comment]
Fixed by changing the application name on `build.gradle`
```
application {
    mainClassName = "duke.Launcher"
}
```

Once changed, this happens on my end.
![image](https://user-images.githubusercontent.com/63991775/191043781-322e50ca-1357-4b73-821e-53cd853ab170.png)

**Comment by DarrenCsAcc** [comment]
@rui-han-crh @RussellDash332 
Thanks guys for putting in so much effort in helping me i will work on it and get back to you guys.

**Comment by RussellDash332** [comment]
> @rui-han-crh @RussellDash332 Thanks guys for putting in so much effort in helping me i will work on it and get back to you guys.

No problem, pleasure to help!

**Comment by DarrenCsAcc** [comment]
@nus-se-bot 
Sorry did not notice. Thank you for closing it has been resolved.
