### ISSUE TITLE
Request for smoke test help (Linux)

### ISSUE THREAD

**Issue by drkkjh** [nus-cs2103-AY2223S1/forum#266]
Hi! I need help to test my iP on Linux. My user guide is [here](https://drkkjh.github.io/ip/) and the release can be found [here](https://github.com/drkkjh/ip/releases/tag/A-Release).

Thanks!

**Comment by RezwanArefin01** [comment]
Getting an unresizable window like this on Linux (Arch): 
![Screenshot_20220920_183434](https://user-images.githubusercontent.com/22095441/191236185-17b164e7-d9fe-42e4-8b9c-3ba138e821ae.png)

**Comment by drkkjh** [comment]
Thanks @RezwanArefin01! I'll try to fix it
