### ISSUE TITLE
A grammar mistake

### ISSUE THREAD

**Issue by Hongyi6328** [nus-cs2103-AY2223S1/forum#267]
![image](https://user-images.githubusercontent.com/58073006/191017699-d3f3a2cb-f45c-4930-becf-7ec0d953d157.png)
https://nus-cs2103-ay2223s1.github.io/website/schedule/week7/project.html

**Comment by RezwanArefin01** [comment]
Where is the mistake?

**Comment by RussellDash332** [comment]
Seems correct to me if you're referring to `reasonable` as it's for `tasks`, a plural.

**Comment by damithc** [comment]
Is `reasonably sized, standalone tasks` better?

**Comment by RussellDash332** [comment]
> Is `reasonably sized, standalone tasks` better?

Agree, this sounds better 😆

**Comment by damithc** [comment]
> Is `reasonably sized, standalone tasks` better?

Updated as above. If there are other alternative suggestions, let me know.
