### ISSUE TITLE
Incorrect hyperlink in Week 7 topics

### ISSUE THREAD

**Issue by teekaytai** [nus-cs2103-AY2223S1/forum#268]
Under Week 7's Topics, W7.7b, Step 3.4 of the forking workflow, one of the hyperlinks appears to be incorrect. The hyperlink labelled "this GitHub help page" links to the [Week 7 Topics page](https://nus-cs2103-ay2223s1.github.io/website/schedule/week7/topics.html). 

The same link in the full textbook correctly goes to the page about [Git and GitHub](https://nus-cs2103-ay2223s1.github.io/website/se-book-adapted/chapters/gitAndGithub.html). Other nearby hyperlinks in the topics page appear to be correct too.

![image](https://user-images.githubusercontent.com/90845551/191077061-f49bcddf-2cb4-46d8-80f3-9e2c5e18ab8d.png)

**Comment by damithc** [comment]
Thanks for the bug report @teekaytai 
Fixed.
