### ISSUE TITLE
JAR file too big

### ISSUE THREAD

**Issue by ChongCheeKaiClarence** [nus-cs2103-AY2223S1/forum#269]
Hi, my JAR file is around 34MB, which is very large.
Here is my [release](https://github.com/ChongCheeKaiClarence/ip/releases/tag/A-Release).

I have checked my library/resource files, but I am unsure if there are any unnecessary ones.

**Comment by RezwanArefin01** [comment]
I think it is because you included `javafx.web`. Are you using that anywhere? If not you may just remove the `javafx {}` block from `build.gradle`. The lines in `dependencies` is sufficient for the app to run.

**Comment by ChongCheeKaiClarence** [comment]
It works! Thanks alot!
