### ISSUE TITLE
text-ui testing

### ISSUE THREAD

**Issue by adeearyaa** [nus-cs2103-AY2223S1/forum#27]
Hi i used the dosunix command to fix the possible line error even though my expected and actual files look the same , however its still saying test case failed?
![Screenshot 2022-08-18 at 5 45 23 PM](https://user-images.githubusercontent.com/87979157/185365503-0006f6c4-ded4-4504-9b4b-dc6ab1bdf54c.png)

**Comment by leonidas1712** [comment]
Just in case you haven't seen it, does the fix from this issue help?: #19

**Comment by adeearyaa** [comment]
oh where do i need to add the -w?

**Comment by leonidas1712** [comment]
@adeearyaa At the end of `text-ui-test/runtest.sh`, like this:

<img width="417" alt="Screenshot 2022-08-18 at 6 04 17 PM" src="https://user-images.githubusercontent.com/20151382/185369577-c09cf5f6-5691-4a11-978d-d576dd0c0873.png">

**Comment by adeearyaa** [comment]
Ah okay , actually in my case i used diff -B to help it pass the test case diff -w did not seem to resolve my issue. Thanks for the help!
