### ISSUE TITLE
Requesting smoke test for MacOS/Linux 

### ISSUE THREAD

**Issue by rui-han-crh** [nus-cs2103-AY2223S1/forum#271]
Hi, here's my [release](https://github.com/rui-han-crh/ip/releases/tag/v1.0.4).

Here's my [user guide](https://rui-han-crh.github.io/ip/). The commands are a little longer because I have `D-Loans` implemented in this program.

Thanks in advance! :> (I hope it works 🙏 )

**Comment by sltsheryl** [comment]
It's working fine on mac, nicely done design and transitions! 
I think there's a slight typo in a few examples in the user guide under Adding Loans. It should be ```loans add Lynette /amount $50``` instead of ```loans add Lynette -amount $50```. A small nitpick is marking the task via the GUI doesn't update the checkbox if I do ```tasks list``` again.


<img width="772" alt="Screenshot 2022-09-20 at 9 30 04 PM" src="https://user-images.githubusercontent.com/96589109/191270886-a21e395b-5d26-48d8-8929-4c01ff92062b.png">

**Comment by rui-han-crh** [comment]
@sltsheryl thanks for the test and feedback!

**Comment by Yongbeom-Kim** [comment]
Works on Ubuntu WSL. UI Looks very nice!

![image](https://user-images.githubusercontent.com/63487502/191414998-5772e3a4-402c-4174-b87d-5c580d3d3964.png)

Upon opening the app, I'm hit with a
```
Deserialization error, see below:
/root/CS2103T/DukeData/savefile.json (No such file or directory)
```
I'm not sure if this is intended, so pointing it out here.

There is a checkbox next to the TODO, but clicking it does nothing - is this meant to be interactive?
![image](https://user-images.githubusercontent.com/63487502/191415267-bf9649bd-b317-408c-8e82-93ff4513c17e.png)

Also, your file IO works, but it does _not_ save the file to the relative file path, but **instead saves the file to the `/root` directory**.  Not that this **may not work** on all machines if you don't have permission to write there (correct me if I'm wrong)

Also why are you writing `Duke.png` and `User.png` to `/root`? The other apps don't write the files there - are you copying your entire resources directory over?

Directory tree for reference:
```
root@MSI:~# tree
.
└── CS2103T
    └── DukeData
        ├── Resources
        │   └── ProfilePictures
        │       ├── Duke.png
        │       └── User.png
        └── savefile.json
```

**Comment by rui-han-crh** [comment]
@Yongbeom-Kim Thanks! 

I wrote that error message for corruption detection if the save file cannot be detected properly. It should go away if the application is opened after the initial start (since now the save file exists) and should only appear on initial start up. I'm saving to the `user.home` directory, I should have write permissions to the home directory on most machines, if I’m not wrong

Writing the images to the save file is a feature! Try changing the Duke.png or User.png images to any pictures of your choice to customise the profiles (the file names must remain the same), this feature can be read more about [here](https://rui-han-crh.github.io/ip/#setting-profile-pictures).

**Comment by rui-han-crh** [comment]
Thank you all for the tests!
