### ISSUE TITLE
Request for help with smoke test errors

### ISSUE THREAD

**Issue by guokweijie** [nus-cs2103-AY2223S1/forum#272]
hi guys, did anyone experience these errors and possibly know how to fix them? These errors were found with the automated smoke test from the teaching team.

On Linux, using Java 11, for the duke.jar uploaded on 09-16-2022 (MM-DD-YYYY) at 23:21:45:
Sep 20, 2022 2:56:13 PM com.sun.javafx.application.PlatformImpl startup WARNING: Unsupported JavaFX configuration: classes were loaded from \'unnamed module @2b3f0ec9\' Graphics Device initialization failed for : es2, sw Error initializing QuantumRenderer: no suitable pipeline found java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283) at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:253) at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:266) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163) at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659) at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679) at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95) at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125) ... 1 more Exception in thread "main" java.lang.RuntimeException: No toolkit found at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163) at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659) at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679) at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196) at java.base/java.lang.Thread.run(Thread.java:829)

On Mac, using Java 11, for the duke.jar uploaded on 09-16-2022 (MM-DD-YYYY) at 23:21:45:
Sep 20, 2022 2:40:53 PM com.sun.javafx.application.PlatformImpl startup WARNING: Unsupported JavaFX configuration: classes were loaded from \'unnamed module @b3b47b3\' Graphics Device initialization failed for : es2, sw Error initializing QuantumRenderer: no suitable pipeline found java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283) at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:253) at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:266) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163) at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659) at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679) at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95) at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125) ... 1 more Exception in thread "main" java.lang.RuntimeException: No toolkit found at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291) at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163) at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659) at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679) at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196) at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by clarence-chew** [comment]
Try #213, removing the javafx block from build.gradle?

**Comment by guokweijie** [comment]
> Try #213, removing the javafx block from build.gradle?

yes i just did, seems to work fine now on mac and windows, how do i know if these errors still exist tho?

**Comment by damithc** [comment]
> yes i just did, seems to work fine now on mac and windows, how do i know if these errors still exist tho?

If the JAR can work on all three OS'es, should be OK. If not sure, you can ask here for someone to help test your JAR on a specific OS.

**Comment by guokweijie** [comment]
> > yes i just did, seems to work fine now on mac and windows, how do i know if these errors still exist tho?
> 
> 
> 
> If the JAR can work on all three OS'es, should be OK. If not sure, you can ask here for someone to help test your JAR on a specific OS.

hi prof, I tried on windows and mac os which worked fine but somehow the automated smoke test from the teaching team identified errors when opening for mac os and linux. that said, how do I know now if it would work with mac os and linux if my app still doesn't give any error messages when i test myself?

**Comment by damithc** [comment]
> hi prof, I tried on windows and mac os which worked fine but somehow the automated smoke test from the teaching team identified errors when opening for mac os and linux. that said, how do I know now if it would work with mac os and linux if my app still doesn't give any error messages when i test myself?

@guokweijie Getting someone else to test it can increase the confidence level, especially if the other person can replicate the error using the old JAR but can run the new JAR without a problem. As you didn't test on Linux, you can ask here if someone can help with that.

**Comment by guokweijie** [comment]
thank you prof!
