### ISSUE TITLE
Request for help for smoke testing on Linux and Mac OS

### ISSUE THREAD

**Issue by guokweijie** [nus-cs2103-AY2223S1/forum#273]
need help for smoke testing on these 2 platforms, help is much appreciated!!

[here](https://github.com/guokweijie/ip/releases/tag/v0.2(fixed))

**Comment by Yongbeom-Kim** [comment]
Works fine on Ubuntu WSL.
![image](https://user-images.githubusercontent.com/63487502/191414531-ed144ab3-abd0-4541-a6e4-199cbd1d0d05.png)

Note that I am able to resize the window and this breaks the UI:
![image](https://user-images.githubusercontent.com/63487502/191414641-d8461f27-d1b1-4e25-8498-89be21ddf7eb.png)

File IO works fine as well

Also your app suffers from https://github.com/nus-cs2103-AY2223S1/forum/issues/246

**Comment by guokweijie** [comment]
hi prof, can I check if the resizing of window is a requirement? @Yongbeom-Kim i checked with my friend on linux and he can run using java -jar duke.jar

**Comment by RussellDash332** [comment]
> hi prof, can I check if the resizing of window is a requirement? @Yongbeom-Kim i checked with my friend on linux and he can run using java -jar duke.jar

Not Prof but I don't think so, it's up to us how we want to optimize the GUI

**Comment by damithc** [comment]
> I don't think so, it's up to us how we want to optimize the GUI

@RussellDash332 is correct.

**Comment by Yongbeom-Kim** [comment]
@guokweijie sflr! I added the comment because if you're not planning to support resizing, then it can be disabled with `stage.setResizable(false);`

I tried again, it doesn't work. Which linux distro is your friend on? I'm on Ubuntu 20.04.5 - seems to be a ubuntu-specific problem. Bumping JavaFX version should solve the issue

EDIT: Sorry, the resizing thing looks like a linux-specific thing? For some reason ubuntu still lets me resize apps that are set to not-resizable, my bad. ignore that part

**Comment by guokweijie** [comment]
> @guokweijie sflr! I added the comment because if you're not planning to support resizing, then it can be disabled with `stage.setResizable(false);`
> 
> I tried again, it doesn't work. Which linux distro is your friend on? I'm on Ubuntu 20.04.5 - seems to be a ubuntu-specific problem. Bumping JavaFX version should solve the issue
> 
> EDIT: Sorry, the resizing thing looks like a linux-specific thing? For some reason ubuntu still lets me resize apps that are set to not-resizable, my bad. ignore that part

hi, do u happen to know which version of JavaFX I need to bump to to make it work?

**Comment by Yongbeom-Kim** [comment]
11.02

**Comment by guokweijie** [comment]
hi, i have updated my javaFx version to 11.0.2 in my build gradle, could you help to test if this works now? @Yongbeom-Kim 
[smoke testing.zip](https://github.com/nus-cs2103-AY2223S1/forum/files/9630452/smoke.testing.zip)

**Comment by Yongbeom-Kim** [comment]
Yep, works
![image](https://user-images.githubusercontent.com/63487502/191886268-922ba105-3815-401e-ac83-12b1f9b40b0a.png)

**Comment by guokweijie** [comment]
thank you! @Yongbeom-Kim @damithc
