### ISSUE TITLE
Automated Smoke Test Reports Invalid/Corrupt Jar Files

### ISSUE THREAD

**Issue by Nephelite** [nus-cs2103-AY2223S1/forum#274]
This is my [jar file](https://github.com/Nephelite/ip/releases/tag/A-Release) and my [user guide](https://nephelite.github.io/ip/).

These are the errors reported by the automated smoke tests in the email.
>    An automated smoke testing of your iP JAR file found the application crashes with the following error(s) upon launching:
>    On Windows, using Java 11, for the duke.jar uploaded on 09-18-2022 (MM-DD-YYYY) at 19:04:43:
>    Error: Invalid or corrupt jarfile duke.jar
>    On Linux, using Java 11, for the duke.jar uploaded on 09-18-2022 (MM-DD-YYYY) at 19:04:43:
>    Error: Invalid or corrupt jarfile duke.jar
>    On Mac, using Java 11, for the duke.jar uploaded on 09-18-2022 (MM-DD-YYYY) at 19:04:43:
>    Error: Invalid or corrupt jarfile duke.jar

The email, in short, informs me that my jar file fails to run in any of the 3 environments due to an invalid or corrupt jar file.

In spite of what the email says though, I can run it fine on my Windows environment, and my Linux VM. My friends can also run it fine on their Windows, MacOS and Linux systems as well. I do not see these errors anywhere. 

Can someone check if my jar file works on their system? Does anyone know of what could possibly be the issue that the automated smoke tests are detecting?

I have performed all the checks I can think of on my end. My Java environment is 11.0.13. My `./gradlew run` in IntelliJ opens the jar file properly. My file on Windows opens on double click, and `java -jar duke.jar` works fine for all 3 systems from my friends. 

I'm at my wits' end and don't know what could be the cause of the errors that the automated smoke tests are detecting.

**Comment by damithc** [comment]
@Nephelite it appears there was a problem during the downloading of your JAR file (only 4MB was downloaded), resulting in a corrupted JAR file. You can ignore the said email.

**Comment by Nephelite** [comment]
@damithc Will my jarfile be retested?

**Comment by damithc** [comment]
> @damithc Will my jarfile be retested?

Yes, we'll let you know if we found any issues in the correct file.

**Comment by Nephelite** [comment]
@damithc Thank you prof!
