### ISSUE TITLE
Evaluation of effort for modification of AB3

### ISSUE THREAD

**Issue by yixiann** [nus-cs2103-AY2223S1/forum#275]
We are morphing our AB3's. May we know how effort is quantified?

In the case of the new feature, we believe it will be more straightforward as we can count lines of code or count features of equivalent work.

However, in the case of modifications, how are these modifications measured since a portion of this code has been written before or our functionalities are similar to what AB3 is currently doing?

**Comment by damithc** [comment]
@yixiann Effort estimation of SE work is not easy but it is also a learning outcome. In the recent tP briefing, I talked about how  the effort of your tP work will be estimated, based on peer inputs. 

Short answer: After having worked in the AB3 codebase for half a semester, and after using your product intensively during the PE, we expect those who tested your product during the PE to be able to give a rough estimate of how much effort your product must have taken, compared to the AB3 effort.
