### ISSUE TITLE
Request help for smoke testing mac and linux OS

### ISSUE THREAD

**Issue by janelleljt** [nus-cs2103-AY2223S1/forum#277]
You can find the latest version [here](https://github.com/janelleljt/ip/releases/tag/v.02) and the user guide [here](https://janelleljt.github.io/ip/). Thanks in advance!

**Comment by Yongbeom-Kim** [comment]
Works on Ubuntu WSL.

Note that I am able to resize the window and this breaks the UI.
![image](https://user-images.githubusercontent.com/63487502/191414114-2ff372bc-94f1-4af1-b95d-349fa862a257.png)

Also note that I am not seeing the relevant emojis in text - but I think this might be a WSL problem.

File IO works fine

Also, your app suffers from https://github.com/nus-cs2103-AY2223S1/forum/issues/246.
