### ISSUE TITLE
Request for smoke test help (Windows/Mac/Linux)

### ISSUE THREAD

**Issue by t1mzzz** [nus-cs2103-AY2223S1/forum#279]
Hi, can I ask for help to run smoke tests? My release can be found [here](https://github.com/t1mzzz/ip/releases/tag/A-Release).

Thanks in advance!

**Comment by RussellDash332** [comment]
Everything works fine in Windows, but I managed to "crash" the app by typing this input, I suppose it happens analogously to deadlines.

<img src="https://user-images.githubusercontent.com/63991775/191353874-719969bd-ea83-4e0b-a1f3-a9f0812a5366.png" width="45%">

**Comment by Yongbeom-Kim** [comment]
Works on Ubuntu WSL as well.

Note that I am able to resize and this breaks the UI:
![image](https://user-images.githubusercontent.com/63487502/191413287-daceffa2-e282-4737-a707-eab9f9da9825.png)

Please note that data saving **fails** to save & retrieve tasks - it creates a `task.txt`, but does not write to the file. There is no stack trace or log files produced, so I don't think this is a permissions or file IO problem.

Also, your app suffers from https://github.com/nus-cs2103-AY2223S1/forum/issues/246

**Comment by yuehernkang** [comment]
![](https://i.imgur.com/4CtCp2J.png)
works fine in macos!

**Comment by t1mzzz** [comment]
Thanks for the help! @RussellDash332 @Yongbeom-Kim @yuehernkang
