### ISSUE TITLE
JavaFX Error running JAR file

### ISSUE THREAD

**Issue by SpecOps2016** [nus-cs2103-AY2223S1/forum#283]
![image](https://user-images.githubusercontent.com/76586680/191409372-0717aec7-3e8c-46db-b1a4-dd06ec0cf77d.png)

Hi I am having this problem when running the JAR file.

Anyone can help on this? Thanks!

**Comment by RussellDash332** [comment]
Can you try changing [this line](https://github.com/SpecOps2016/ip/blob/master/build.gradle#L44) to `Launcher`?

Source: #111 #176 #190

**Comment by SpecOps2016** [comment]
it worked. Thanks!
