### ISSUE TITLE
Sizable Dialog Box 

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S1/forum#286]
![image](https://user-images.githubusercontent.com/77482097/191566834-74bccdc2-9187-4c6e-8582-b961efc2caac.png)

Any idea how to make this dialog box adjustable to length of list?
if not the later indexes get cut off.

**Comment by RussellDash332** [comment]
#128 might help you!

**Comment by junlee1991** [comment]
Thank you! Problem solved
