### ISSUE TITLE
Bye and system.exit(0);

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S1/forum#287]
I want to: 
return ByeString 
System.exit(0); // exit the program

After you return, the below statement doesnt execute.
If you put the return at the end, the program will exit first. 

Any ideas?

**Comment by RussellDash332** [comment]
You can do it in another class method. It shows the bye string first aka printing the function's return value, then it exits.

**Comment by rui-han-crh** [comment]
I can suggest two other ways to do this, 

Firstly, we may use `Platform.exit()`, which executes as a non-blocking code. The execution passes through the line containing `Platform.exit()` as prepares to close the application but still allows following code to be executed. Then we may call `System.exit(0)` under the `Application::launch` method

```java
private String leaveProgram() {
    Platform.exit();
    return "bye"
}
```

called within some other method

```java
    String byeString = leaveProgram();
    System.out.println(byeString) // We may observe this line to be executed, despite Platform::exit being called previously
```

Then we close the program after the launch method in the `Launcher` class

```java
public static void main(String[] args) {
    Application.launch(Main.class, args);
    System.exit(0); //Exit program with status 0
    System.out.println("This line will not be printed");
}
```

Also, note that Platform.exit() will call `Main::exit`, if it exists, so we can also perform any additional cleanup right before the close in this method, if we have any.

```java
public class Main extends Application {
    public void stop() {
        System.out.println("Preparing to stop");
    }
    ...
}
```


The second way is that we use a `Timer` object to close the application after a period of time has passed. For example, if I have something to do that I know can be completed under 2 seconds, we can do

```java
    new Timer().schedule(new TimerTask() {
        @Override
        public void run() {
            Platform.exit();
            System.exit(0);
        }
    }, 2000);
    System.out.println("Closing program after 2 seconds");
```

The above will close the program after 2000 milliseconds, but will still allow any actions after to be performed up to the 2 seconds.

**Comment by junlee1991** [comment]
Thank you for the brilliant ideas! I like the second idea better because I can set the timer to my liking.
