### ISSUE TITLE
Typo in Tutorial: Adding a command

### ISSUE THREAD

**Issue by jasonqiu212** [nus-cs2103-AY2223S1/forum#288]
Hello! I believe I found a typo in [Tutorial: Adding a command](https://nus-cs2103-ay2223s1.github.io/tp/tutorials/AddRemark.html) under the section **Parse user input**.

In the code snippet for `RemarkCommandParser.java`, the website displays the following:
```java
public RemarkCommand parse(String args) throws ParseException {
    requireNonNull(args);
    //...
}
```

However, `requireNonNull` is not defined in the `tp` codebase. Is this a typo? Does it refer to the `requireAllNonNull` method instead?

Thank you!

**Comment by lesterong** [comment]
In this case, it refers to the `requireNonNull(T obj)` method found in `java.util.Objects`. All you need to do is import it.
```java
import static java.util.Objects.requireNonNull;
```

That said, you can use `requireAllNonNull(Object... items)` as well, since it takes in a variable number of arguments.

**Comment by jasonqiu212** [comment]
Ah yes, I just realized too, after referring from the sample code. Thanks for the reply!
