### ISSUE TITLE
Request for smoke test help (Windows, Mac, and Linux)

### ISSUE THREAD

**Issue by JonathanWiguna** [nus-cs2103-AY2223S1/forum#289]
Hi, can anyone help me test out my JAR file? My release can be found [here](https://github.com/JonathanWiguna/ip/releases/download/v0.2/duke.jar) and the User Guide [here](https://github.com/JonathanWiguna/ip/blob/master/docs/README.md). 

Thank you in advance!

**Comment by RussellDash332** [comment]
Overall, the happy path works for me, but `find a` seems to not return the correct list, unless you're including the time as well.

The window seems to be weird when I resize it.

![image](https://user-images.githubusercontent.com/63991775/191690127-f2c1686f-c918-457f-ac19-c722e3b08eb5.png)

**Comment by RezwanArefin01** [comment]
On Linux (Arch) one of the picture is not being loaded. 
![Screenshot_20220922_155647](https://user-images.githubusercontent.com/22095441/191690489-af058ad2-c0f5-4995-a578-3549245d68a0.png)
For a fix, you may try converting the `.png` to a `.jpg`, then convert back to `.png`. It likely that the `.png` is not in correct format.

**Comment by JonathanWiguna** [comment]
Thanks for the help @RussellDash332 and @RezwanArefin01! I have fixed the bug in "find", disabled resizing, and changed the Duke image to .png. Do you guys mind helping me check one more time to see if all's good? The newest release is [here](https://github.com/JonathanWiguna/ip/releases/download/v0.2/duke.jar). 
Thank you so much!

**Comment by RussellDash332** [comment]
> Thanks for the help @RussellDash332 and @RezwanArefin01! I have fixed the bug in "find", disabled resizing, and changed the Duke image to .png. Do you guys mind helping me check one more time to see if all's good? The newest release is [here](https://github.com/JonathanWiguna/ip/releases/download/v0.2/duke.jar). Thank you so much!

LGTM!
