### ISSUE TITLE
Requesting help for smoke testing Linux and Mac 

### ISSUE THREAD

**Issue by zicotjia** [nus-cs2103-AY2223S1/forum#290]
Can someone check if there is an issue with my current release in Linux and Mac? The current release is [here](https://github.com/zicotjia/ip/releases/download/v0.2/Duke.jar) and user guide is [here](https://zicotjia.github.io/ip/)

**Comment by RezwanArefin01** [comment]
Tested on Linux (Arch). On of the pictures did not load, and the window can be resized weirdly: 
![Screenshot_20220922_155847](https://user-images.githubusercontent.com/22095441/191690912-c3e699d2-61e1-422d-99f0-afa6d72f9d0c.png)

**Comment by cheeheng** [comment]
I found a copy-paste bug on the user guide.
<img width="363" alt="image" src="https://user-images.githubusercontent.com/13196670/191690145-bd84db6e-7e1b-4410-99cb-ea0499d4df35.png">

Update: The bug has been mostly fixed except for this part
The command should be `deadline` not `event`.
<img width="325" alt="image" src="https://user-images.githubusercontent.com/13196670/191760623-17c13987-d19d-44f5-bd62-aae641a41b41.png">

**Comment by zicotjia** [comment]
Thanks for the help. Do you mind doing one more smoke test? Just to check if the image will load or not. The newest release is [here](https://github.com/zicotjia/ip/releases/download/v0.2/Duke.jar).

**Comment by yuehernkang** [comment]
![](https://i.imgur.com/9yzhAu9.png)

Works on my mac
