### ISSUE TITLE
Requesting for help in smoke testing (Windows, Mac, and Linux)

### ISSUE THREAD

**Issue by TheSoggy** [nus-cs2103-AY2223S1/forum#291]
You can find the latest version [here](https://github.com/TheSoggy/ip/releases/tag/A-Release) and the user guide [here](https://thesoggy.github.io/ip/). Thanks in advance!

**Comment by RussellDash332** [comment]
![image](https://user-images.githubusercontent.com/63991775/191751452-6712d944-facf-4ddb-ad02-3da5e36aca22.png)

Works like a charm on Windows!

**Comment by izzahaj** [comment]
<img width="714" alt="Screenshot 2022-09-22 at 10 56 15 PM" src="https://user-images.githubusercontent.com/88933129/191781633-99bbfa15-6ad4-4384-b225-4da8e900b506.png">

Hi, it works well on Mac!

**Comment by Yongbeom-Kim** [comment]
I am on Ubuntu 20.04.5 WSL.

Note that your app suffers from https://github.com/nus-cs2103-AY2223S1/forum/issues/246:
```
dernbu@MSI:/mnt/c/users/Dernbu/Downloads/CS2103 Testing$ java -jar duke.jar

(java:28121): Gdk-CRITICAL **: 01:00:23.107: gdk_x11_display_set_window_scale: assertion 'GDK_IS_X11_DISPLAY (display)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000002, pid=28121, tid=28156
#
# JRE version: Java(TM) SE Runtime Environment (18.0.2.1+1) (build 18.0.2.1+1-1)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (18.0.2.1+1-1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  0x0000000000000002
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /mnt/c/users/Dernbu/Downloads/CS2103 Testing/hs_err_pid28121.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted
```

Otherwise, adding todos and file IO works well! 
![image](https://user-images.githubusercontent.com/63487502/191808383-10d9a6bd-671b-46bb-ad6d-ae7a325417f3.png)

**Comment by TheSoggy** [comment]
Thanks for the help guys! @Yongbeom-Kim I have fixed the bug mentioned in your comment, would you mind helping me test again? The release is [here](https://github.com/TheSoggy/ip/releases/tag/A-Release). Thank you so much!

**Comment by Yongbeom-Kim** [comment]
New version works well!
