### ISSUE TITLE
Request for test in ip(linux/win)

### ISSUE THREAD

**Issue by bokun2** [nus-cs2103-AY2223S1/forum#292]
Here is my [ip!]( https://github.com/bokun2/ip/releases) Thank you in advance!

**Comment by RussellDash332** [comment]
Works on Windows! I was confused on why one of the commands that you provide didn't work until I realize I had an extra leading space. Would suggest to strip them but other than that the syntax is friendly enough to me as you provided multiple prefixes!

<img src="https://user-images.githubusercontent.com/63991775/191791379-78315461-8a3b-4326-a4f7-79ed73c733c0.png" width=40%>

**Comment by Yongbeom-Kim** [comment]
I am on Ubuntu 20.04.5 WSL,

Note that your app suffers from https://github.com/nus-cs2103-AY2223S1/forum/issues/246:
```
dernbu@MSI:/mnt/c/users/Dernbu/Downloads/CS2103 Testing$ java -jar duke.jar

(java:27939): Gdk-CRITICAL **: 00:55:51.436: gdk_x11_display_set_window_scale: assertion 'GDK_IS_X11_DISPLAY (display)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f0031eec420, pid=27939, tid=27975
#
# JRE version: Java(TM) SE Runtime Environment (18.0.2.1+1) (build 18.0.2.1+1-1)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (18.0.2.1+1-1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libX11.so.6+0x29420]  XInternAtom+0x40
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /mnt/c/users/Dernbu/Downloads/CS2103 Testing/hs_err_pid27939.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted
```
I can confirm that basic task-adding and file IO works when run with `java -Djdk.gtk.version=2 -jar duke.jar`
![image](https://user-images.githubusercontent.com/63487502/191807660-57f9f217-8404-48a9-ab59-57aa08f5c0d3.png)
