### ISSUE TITLE
Request for smoke test help (Linux, MacOS, Windows)

### ISSUE THREAD

**Issue by tsammeow** [nus-cs2103-AY2223S1/forum#295]
I would appreciate help in smoke testing my [release](https://github.com/tsammeow/ip/releases/tag/v0.3) on Linux, MacOS and Windows. Thank you in advance!

**Comment by RussellDash332** [comment]
![image](https://user-images.githubusercontent.com/63991775/191826133-d0932da8-f5ae-414c-b4e6-574e8fc5f584.png)
Works fine on Windows!

**Comment by Yongbeom-Kim** [comment]
I am on Ubuntu 20.04.5 WSL,

For some reason, your app by default has some sizing/resolution issues when I run it (I didn't resize the window):
![image](https://user-images.githubusercontent.com/63487502/191878679-83e8e079-343e-4ade-ac71-ecc5371f5a6e.png)

Everything else works well!
![image](https://user-images.githubusercontent.com/63487502/191878821-263e6f09-3dbb-4902-84e5-b42756afec30.png)

**Comment by yuehernkang** [comment]
![](https://i.imgur.com/BhHFiPX.png)

Works well on my mac when running from the terminal

**Comment by tsammeow** [comment]
Thank you everyone!
