### ISSUE TITLE
Request for smoke-test help on Windows and Linux

### ISSUE THREAD

**Issue by Aishwarya-Hariharan-Iyer** [nus-cs2103-AY2223S1/forum#296]
Hello,
I am currently using MacOS to write and test code. My JAR release is found here:
https://github.com/Aishwarya-Hariharan-Iyer/ip/releases/tag/A-Release
If someone could please help me test it on Windows and Linux OS, I would be really grateful...
Thanks!

**Comment by Yongbeom-Kim** [comment]
I am on Ubuntu 20.04.5 WSL.

App runs fine. I don't know why, your app looks like this when run:
![image](https://user-images.githubusercontent.com/63487502/191886414-488a2499-680a-46d1-8c0d-0d9f0790d126.png)

File IO and adding tasks work, but I have no idea where you're saving the tasks to:
![image](https://user-images.githubusercontent.com/63487502/191886608-c317db8c-c34c-4793-aa1a-89cc329a5be5.png)

Also console gives me this, if it is of any concern to you:
```
dernbu@MSI:/mnt/c/Users/Dernbu/Downloads/CS2103 Testing$ java -jar duke.jar
Sep 23, 2022 11:21:47 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @1cf89471'
```

**Comment by Aishwarya-Hariharan-Iyer** [comment]
Thanks a lot @Yongbeom-Kim !!! It is really kind of you to help!
Hmm...ok for the file location, if Duke.jar is in Desktop, then DukeList.txt should also be saved there. I am not sure about the UI and console parts though? Does anyone have any suggestions/faced something similar?
Thanks!

**Comment by RussellDash332** [comment]
Works fine on Windows except I don't see where my file is saved and I can say goodbye multiple times.
Update: found the file, it's at its parent directory 😅 

![image](https://user-images.githubusercontent.com/63991775/191909373-5d1f0bde-f66c-4020-bd6b-cbdca41baabf.png)

**Comment by Aishwarya-Hariharan-Iyer** [comment]
Thanks a lot @RussellDash332 !!! Will change the goodbye design to perhaps close the tab ... thanks a lot for bringing that up!

**Comment by Aishwarya-Hariharan-Iyer** [comment]
Thanks, @Yongbeom-Kim @RussellDash332 really appreciate your time and suggestions/comments!!! :)
