### ISSUE TITLE
Push keeps failing

### ISSUE THREAD

**Issue by SpecOps2016** [nus-cs2103-AY2223S1/forum#297]
![image](https://user-images.githubusercontent.com/76586680/191930929-1959c19a-2ae0-4455-b129-857850d01dad.png)

I keep getting this error message whenever I try to push on SourceTree.

If someone can help me with this I woudl greatly appreciate it. Thanks!

**Comment by damithc** [comment]
@SpecOps2016 the screenshot is missing

**Comment by SpecOps2016** [comment]
My apologies. I have updated the post. Thank you!

**Comment by lulucopter** [comment]
Perhaps you want to explore more into the bottom 3 rows which source tree indicated they already exist

**Comment by SpecOps2016** [comment]
Thanks! Solved

**Comment by misterpuffin** [comment]
It seems as though it is failing because you're trying to push tags already in your remote repository. Glad you managed to solve the issue, reminder to close the issue if everything is okay!
