### ISSUE TITLE
./gradlew shadowJar

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S1/forum#298]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/77482097/191892602-60eef6ff-88f5-440d-9d1e-1e2a106f8adf.png">

Issue1: I am trying to rebuild jar file. Last time, it worked but somehow now it doesn't 
I've tried: 
./gradlew shadowJar
gradlew shadowJar
any ideas?

Issue 2: the current jar file i have, when clicked, nothing comes out. Maybe i need to rebuild?

**Comment by rui-han-crh** [comment]
Can you try `Ctrl-Shift-A` or go to the Help in the task bar on top and press the `Find Action` tab and try typing `gradle` into the help bar here

![image](https://user-images.githubusercontent.com/15359033/191896379-26f0ab65-0308-4659-a400-f8e93dcec3e4.png)

Select this elephant icon and a new tab should appear

![image](https://user-images.githubusercontent.com/15359033/191896431-46074456-0d2c-49c7-b476-8932bef468d0.png)

Press the elephant icon here for execute gradle task and try `clean shadowJar`

![image](https://user-images.githubusercontent.com/15359033/191896546-a597ee6f-2e60-4bec-a5ea-e9981ce48d70.png)

Select the first option. (Clean shadowJar will delete your existing built files and rebuild from a cleaned folder again)

EDIT:
Okay, the `./gradlew` command has to be executed from where the gradlew file is in the directory. In this care it's in your root directory, but you're currently somewhere deeper in the libs directory. Try going back up to the root directory where your gradlew file is, (I think it's ipNew, check by `ls` to see the file exists in this directory) and run `./gradlew` commands from there

**Comment by junlee1991** [comment]
Ctrl-Shift-A method you mentioned solved the issue! Many thanks! No more issues with jar file!

**Comment by damithc** [comment]
> EDIT:
> Okay, the `./gradlew` command has to be executed from where the gradlew file is in the directory. In this care it's in your root directory, but you're currently somewhere deeper in the libs directory. Try going back up to the root directory where your gradlew file is, (I think it's ipNew, check by `ls` to see the file exists in this directory) and run `./gradlew` commands from there

Yup, that seems to be the problem as per the initial screenshot. Good catch @rui-han-crh
