### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S1/forum#299]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/77482097/191892774-3b336a64-625b-4997-885a-1e256026d018.png">

How do i remove this error? any ideas? 
my chat bot still runs though

**Comment by misterpuffin** [comment]
hey! from your ip repo, it seems like the `MainWindow.fxml` in `src/main/resources/view` folder has JavaFX version set to 18. 

You can see this in `xmlns="http://javafx.com/javafx/18"`. Instead, you can try changing it to  `xmlns="http://javafx.com/javafx/8.0.171"` , which is the same version used in your `DialogBox.fxml`

hope this helps!

**Comment by junlee1991** [comment]
Thank you! Problem solved!
