### ISSUE TITLE
Question about coding standards in individual project

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#3]
I read that one of the criteria of the individual project is that coding styles need to fit standards. After some searching, I realised that the standard used in the module is this one: [https://se-education.org/guides/conventions/java/intermediate.html](https://se-education.org/guides/conventions/java/intermediate.html)

I have also done a quick search on the module website and found out that coding standards will only be covered on Week 3. Do I have to worry about fitting coding standards for the individual project milestone on Week 2? If so, will linters be provided to check coding standard compliance?

**Comment by damithc** [comment]
@cheeheng Good job looking into this aspect and locating the coding standard used by the module. You are welcome to follow it form the start but that is not required. We only start enforcing it after it has been introduced, in a later week. Similarly, you can start using CheckStyle to check coding standard compliance, after we introduce it in a later week.
