### ISSUE TITLE
[A-TextUiTesting] FC: Cannot open ACTUAL.txt

### ISSUE THREAD

**Issue by jasonchristopher21** [nus-cs2103-AY2223S1/forum#30]
Hi, I currently encounter a problem with the automated text UI testing, when I run the `runtest.bat` file in the IntelliJ terminal, it displays an error message that the system cannot find the file specified. I have tried by changing the path of the `..\src\main\java\*.java` to using the absolute path, but now it seems that the ACTUAL.txt file cannot be found.-

The problem that made me confused, is that when I actually run the runtest.bat by executing it from file explorer, the application runs for a short while before exiting the terminal on itself. In that case, the ACTUAL.txt file was actually generated. I am not quite sure why I can't run it on IntelliJ terminal to get the success/fail message.

I have deleted JDK 17 and currently only use Java 11, but the problem still persists.
IntelliJ version: 2021.3.1, OS version Windows 10 Home 21H2.

Thank you in advance!

![image](https://user-images.githubusercontent.com/96954436/185428861-89f33bc1-6ca7-4b51-b6d7-792b15824869.png)

**Comment by Berted** [comment]
Hi Jason, to my knowledge it seems that script was made with it being run from the `text-ui-test` directory in mind.

Try changing directories to `text-ui-test` by performing `cd text-ui-test`, then run the `runtest.bat` script. Hopefully this works.

GL!

**Comment by jasonchristopher21** [comment]
Hi Edbert @Berted, the problem was solved with your method. Thank you very much for your help!

**Comment by damithc** [comment]
Thanks for helping @Berted
