### ISSUE TITLE
Request for smoke test help ( Windows, Linux or Mac)

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S1/forum#300]
My release can be found [here](https://github.com/junlee1991/ip/releases/tag/A-ReleaseThird). Could you please help me test the jar file?

**Comment by RussellDash332** [comment]
Normal scenarios work well on Windows, except for this: the month of deadline/event.
<img src="https://user-images.githubusercontent.com/63991775/191920883-6d20f402-64cf-44f9-918b-e1ce51f70f1b.png" width=40%>

Is this error message supposed to be exposed to the user?
<img src="https://user-images.githubusercontent.com/63991775/191920770-3f2eb45b-4476-4e8d-9e8a-ed8889da9abd.png" width=40%>

**Comment by junlee1991** [comment]
it should be 15/**03**/2022 not 15/**3**/2022. 
That's why it caused that error. It has to be specifically that way. I should write this clearer in the UG. 
Thank you for testing

**Comment by RussellDash332** [comment]
> it should be 15/03/2022 not 15/3/2022. That's why it caused that error. It has to be specifically that way. I should write this clearer in the UG. Thank you for testing

No problem. Yup, it's `15/3/2022` in your UG.

**Comment by Yongbeom-Kim** [comment]
On ubuntu, your app suffers from https://github.com/nus-cs2103-AY2223S1/forum/issues/246, try bumping your JavaFX version to 11.0.2

Other than that, everything works well.

**Comment by junlee1991** [comment]
> On ubuntu, your app suffers from #246, try bumping your JavaFX version to 11.0.2
> 
> Other than that, everything works well.

@Yongbeom-Kim Hello, thank you for the feedback. I have bumped JavaFX version to 11.0.2. May I trouble you to try it again [here](https://github.com/junlee1991/ip/releases/tag/A-ReleaseThird)? Thank you!

**Comment by yuehernkang** [comment]
Not working on MacOS. Getting this error
`Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class duke.Main
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:891)
`

not sure if its just me

**Comment by RezwanArefin01** [comment]
Tested on Linux (Arch). The images did not load, and also the window can be resized weirdly: 
![Screenshot_20220926_015544](https://user-images.githubusercontent.com/22095441/192157988-598a6b1a-5409-4edf-b286-0e51a449d20f.png)
Try looking into solved issues. These problems are very common.
