### ISSUE TITLE
A-Release

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S1/forum#301]
Can I clarify every time i make small minor changes/commits, i have to make new releases, hence a new tag.

eg. A-ReleaseOne , A-ReleaseTwo, A-ReleaseThree, etc. 

At this rate, ill probably have 10 or so releases and 10+ new tags. Any ideas to streamline or cut down the process?

like is there a way to have one release, but i can still add one or two minor commits into it later. replace the jar?

**Comment by damithc** [comment]
> Can I clarify every time i make small minor changes.commits, i have to make new releases, hence a new tag.

From the module's side, we need to see only one `A-Release` tag. The remaining releases can be tagged anyway you like e.g,, v0.1 etc.

**Comment by xhphoong** [comment]
@damithc Hi Prof, I wan to clarify about this: does our latest version need to have A-Release tag or it can have other tag name? Because my **latest version (to be mark)** is the one with **v0.2 A-Release tag** not A-Release tag?  Thank you

**Comment by damithc** [comment]
@xhphoong The two things are independent. We take the latest release for grading. The A-Release tag (like other required tags) is simply an indication that you've done that increment. It doesn't need to be attached to the latest release.

**Comment by xhphoong** [comment]
> @xhphoong The two things are independent. We take the latest release for grading. The A-Release tag (like other required tags) is simply an indication that you've done that increment. It doesn't need to be attached to the latest release.

Thank you for the clarification!
