### ISSUE TITLE
Request for smoke test help (Windows, MacOS, Linux)

### ISSUE THREAD

**Issue by waynezsy** [nus-cs2103-AY2223S1/forum#302]
Hi, I'm looking for help to smoke test my latest release [here](https://github.com/waynezsy/ip/releases/tag/v1.0).

Would greatly appreciate any help, thank you!😄

- [X] Windows
- [X] MacOS
- [X] Linux

**Comment by RussellDash332** [comment]
Works well on Windows!
![image](https://user-images.githubusercontent.com/63991775/192029669-55bd826f-af1c-42a9-8243-b67c94a6f153.png)

This is what happens when I mess with the task data file.
![image](https://user-images.githubusercontent.com/63991775/192029884-44dd44bd-c016-4244-8363-9127e329396a.png)

**Comment by waynezsy** [comment]
Thanks Russell! Checked off Windows in the task list.

**Comment by rui-han-crh** [comment]
On Linux (Ubuntu) VM, everything works properly with reference to your user guide, no images issues. Although, I'm not sure if the font has loaded properly, it looks a bit different from the images on top.

<img src="https://user-images.githubusercontent.com/15359033/192132053-42c6e581-c7d4-47c1-baca-565ad9abfbf4.png" widht = "300">


But there is an issue with the jar file not opening properly on double clicking or using the plain `java -jar` command, it's a Wayland compatibility issue on Ubuntu 22.04 with JavaFX 11. With `java -Djdk.gtk.version=2 -jar NyanDuke.jar`, it opens normally.

![image](https://user-images.githubusercontent.com/15359033/192131915-5a4ea57e-1778-47f0-a2a0-d195d0698689.png)

Try upgrading your version by replacing `String javaFxVersion = '11'` under the `dependencies` section in your `build.gradle` file with `String javaFxVersion = '11.0.2'`. This usually fixes this error.

**Comment by yuehernkang** [comment]
![](https://i.imgur.com/g0ntXVa.png)

runs on mac. can add tasks and load tasks

**Comment by waynezsy** [comment]
Thanks everyone!

**Comment by waynezsy** [comment]
@rui-han-crh I've updated my build.gradle, could I please trouble you to test my latest release to see if it runs on double-click now? Thank you so much!
Unfortunately the font problem stems from Linux not having Courier New and I'm not aware of a suitable monotype font available on all platforms, so the Nyan will remain misaligned 😞

**Comment by rui-han-crh** [comment]
@waynezsy 
All good now, double clicking now works and the program runs and saves as normal.

**Comment by waynezsy** [comment]
Thanks for your help!
