### ISSUE TITLE
Request for smoke test help ( Windows, Linux or Mac)

### ISSUE THREAD

**Issue by kangqiao322** [nus-cs2103-AY2223S1/forum#303]
Hi, I'm looking for help to smoke test my release [here](https://github.com/kangqiao322/ip/releases/tag/A-Release).

Thank you in advance!

**Comment by RussellDash332** [comment]
Works fine in Windows but I have these issues:
- Resize issue + broken Duke logo?
  <img src="https://user-images.githubusercontent.com/63991775/192108069-f20daf1a-8065-46ad-bc1d-8eab61ec14a5.png" width=50%>
- Some bugs on event and deadline, where the error message doesn't really match the input's intention
  <img src="https://user-images.githubusercontent.com/63991775/192108149-382b955b-f1dd-4861-bff5-92f42dd6cfe3.png" width=50%>

Also tried to mess up the data file and the JAR doesn't open.

**Comment by kangqiao322** [comment]
Thank you very much! I fixed  the reply issues but I'm not sure about the messing up data file part.

**Comment by emptygx** [comment]
Works fine on mac with similar issues as mentioned by @RussellDash332. Reply issues verified to be fixed.

Resize issue:
<img width="616" alt="Screenshot 2022-09-27 at 12 30 21 PM" src="https://user-images.githubusercontent.com/88984742/192432555-a692a67d-2086-444c-bd9e-48b4e4f59b6e.png">
