### ISSUE TITLE
Test cases fail for tP, preference file location error.

### ISSUE THREAD

**Issue by kangqiao322** [nus-cs2103-AY2223S1/forum#304]
Currently, my testcases for tP fails even though I have not changed anything. I feel that it might be a directory rooting problem in Intellij but I have no idea on how to fix it. Any help will be appreciated thank you!
![image](https://user-images.githubusercontent.com/93211040/192107453-fbbef0f3-0528-4621-9e42-204e5150f505.png)
![image](https://user-images.githubusercontent.com/93211040/192107486-5c69af78-9577-470e-9642-2243186577f8.png)
The main can run but I get this error too.
![image](https://user-images.githubusercontent.com/93211040/192108528-b5fcad18-9487-4853-b816-581b72864df9.png)

I think it is a file path problem but I am unsure how to fix it since the preferences.json file that is generated seems to have the wrong path.
![image](https://user-images.githubusercontent.com/93211040/192132212-88c69301-aed8-45e4-b845-e699147fb1dd.png)

**Comment by damithc** [comment]
@kangqiao322 On a related note, it's best not to use OneDrive and similar online drives for the project, as their file synchronization mechanisms can interfere with our tools, such as Git.

**Comment by kangqiao322** [comment]
I have changed my directory by disabling onedrive but it still does not seem to fix the issue.

**Comment by damithc** [comment]
@kangqiao322 While waiting for inputs from others, here are some things you can try (one at a time):
* run `gradlew clean` before running tests
* delete the new config files created by AB3 e.g., preferences.json
* clone the fork again to a new location and run the tests

**Comment by kangqiao322** [comment]
Problem seems to be fixed after changing the build.gradle.
