### ISSUE TITLE
Unable to run jar file

### ISSUE THREAD

**Issue by Isaaclhy00** [nus-cs2103-AY2223S1/forum#305]
Able to run the jar file inside IntelliJ, however unable to run it from the terminal.
* Ran using java 11 inside IntelliJ

Error message when running from terminal as follows
* WARNING: Unsupported JavaFX configuration: classes were loaded from \'unnamed module @4b4d0112\' 
* Graphics Device initialization failed for : d3d, sw 
* Error initializing QuantumRenderer: no suitable pipeline found 
* Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /Users/iz/.openjfx/cache/11/libprism_es2.dylib: dlopen(/Users/iz/.openjfx/cache/11/libprism_es2.dylib, 0x0001): tried: '/Users/iz/.openjfx/cache/11/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

**Comment by lulucopter** [comment]
Try #213, perhaps removing the JavaFx block from `build.gradle` might help

**Comment by Isaaclhy00** [comment]
The same issue used to appear when I run it in IntelliJ, however I have already removed it and rebuilt the jar file, now it runs fine in IntelliJ. But I can't get it to run after uploading the jar file to GitHub, or from the terminal.

**Comment by lulucopter** [comment]
Sounds like a possible dependency issue. Are your project SDKs updated and correct ?  (Can be found in `file > project structure` )

**Comment by Isaaclhy00** [comment]
Hi I've attempted to fix it, any kind soul would help with a simple smoke test [here](https://github.com/Isaaclhy00/ip/releases) ?

**Comment by RussellDash332** [comment]
> Hi I've attempted to fix it, any kind soul would help with a simple smoke test [here](https://github.com/Isaaclhy00/ip/releases) ?

JAR file can be opened now!
Here's some snapshots of the test that I did and see whether it's a feature or not.
By the way, `mark/unmark <invalid index>` will not give me anything. It could be an error reflected on the logger, e.g. `mark 0`

<img src="https://user-images.githubusercontent.com/63991775/192828617-af86ce19-2536-4e28-ab3d-29bf6243233f.png" width=40%>
<img src="https://user-images.githubusercontent.com/63991775/192828663-f52de22a-8e71-4eed-9060-a3e1083025c3.png" width=40%>

Typing `bye` will give you the OOPS idk what it means but it closes the app. Furthermore it doesn't save the task list.

**Comment by Isaaclhy00** [comment]
Thank you so much @RussellDash332 :)
