### ISSUE TITLE
Smoke Test Remedy

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S1/forum#306]
Hello everybody, 

Apparently my duke chatbot only works on windows. Ubuntu, linux and mac have issues. Any idea what is the appropriate fix to make? Which file to look at? Thank you!

**Comment by damithc** [comment]
@junlee1991 What's the error on Mac/Linux?

**Comment by junlee1991** [comment]
@damithc 
I posted my smoke test [here](https://github.com/nus-cs2103-AY2223S1/forum/issues/300)

Some issues: 
Mac:
Not working on MacOS. Getting this error
Exception in Application constructor Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class duke.Main at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:891)

Linux: 
The images did not load, and also the window can be resized weirdly
![image](https://user-images.githubusercontent.com/77482097/192278846-66928d14-8d65-487b-9d9b-098a1a853400.png)

My idea is to look at closed comments and see if i can find a remedy there.

**Comment by RussellDash332** [comment]
@junlee1991

- Windows: no issue other than the functionalities (#300)
- Linux-Ubuntu: #246 (as said by @Yongbeom-Kim)
- Mac:
  This depends on what the error below what is stated by @yuehernkang is. It can be either of these issues: #88, #190, #234, #276
- Linux-Arch:
  - You can set the stage to be unresizable by adding the line `stage.setResizeable(false);` at `Main.java`
  - Image not loading: [this comment](https://github.com/nus-cs2103-AY2223S1/forum/issues/217#issuecomment-1249137283), credits to @RezwanArefin01

All the best on fixing them!

**Comment by tanhl2000** [comment]
@junlee1991 
For Mac side, I had to change my JavaFX version to 17 in order to fix some errors on my end (fonts not showing etc), might want to try upgrading to 17 or 18 at least especially if on the new M1/M2 chips.

**Comment by junlee1991** [comment]
Alright thank you to all who have contributed. 

[here](https://github.com/junlee1991/ip/releases/tag/A-Release-v.5) is my final release (i hope). 

If it doesn't work, then I have nothing to say. I am so done with this.
