### ISSUE TITLE
Junit Test Problem

### ISSUE THREAD

**Issue by lizekai-richard** [nus-cs2103-AY2223S1/forum#307]
Hi, I'm here to ask for help with Junit test.

Currently, this is my file structure. I created a test folder and a java folder within it. However, I'm unable to create any packages inside the java folder, only other directories instead. I thought it's because I didn't set the java folder as the root of test so I did it. But after that, errors occurred as below
<img width="348" alt="Screenshot 2022-09-26 at 3 50 07 PM" src="https://user-images.githubusercontent.com/88566387/192223199-ffd293b6-101a-45ae-94b1-f924225d23b5.png">
<img width="486" alt="Screenshot 2022-09-26 at 3 50 12 PM" src="https://user-images.githubusercontent.com/88566387/192223212-8118eac6-222c-4bc7-b0d7-a1eda0726f68.png">
In the gradle.build, I already added the dependencies 
<img width="792" alt="Screenshot 2022-09-26 at 3 50 19 PM" src="https://user-images.githubusercontent.com/88566387/192223373-c143623f-a046-47d6-a432-836b7af6f881.png">
After I unmarked the java as the test source root and added test files in the corresponding directories, the gradle can run all the tests.
<img width="331" alt="Screenshot 2022-09-26 at 3 49 26 PM" src="https://user-images.githubusercontent.com/88566387/192224020-ed73eb06-faee-4ded-8e0f-5b3ee8ba99f3.png">

<img width="487" alt="Screenshot 2022-09-26 at 3 49 30 PM" src="https://user-images.githubusercontent.com/88566387/192223723-6f8c9739-3070-4866-aac4-0b8e64c334f5.png">
However, I think there shouldn't be an issue if I mark the java as the source root of test (and I think it should be done). Can anyone help with this?

**Comment by damithc** [comment]
@lizekai-richard While waiting for inputs from others, here are some things you can try:
* If using Intellij, try these 'common remedies' one-at-a-time in this order:
  * File -> Invalidate caches
  * Delete the .idea folder -> Close and re import the project
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.
 * Push the code to a branch and share here so that other can try to replicate the problem.

**Comment by AshiqurRah** [comment]
The way I created packages in my test.java folder is by creating a test file first. I included at the top of the file,  `package duke;` and IntelliJ alerted me with a red lightbulb at the start of the line (when hovered over the squiggly red-lined code) to create a package named duke. 

You could try re-creating another file in test.java and try the above steps and see whether it works as well

**Comment by lizekai-richard** [comment]
Some updates:

I tried invalidating caches and re import. And below is what I got:
<img width="337" alt="Screenshot 2022-09-27 at 2 20 06 PM" src="https://user-images.githubusercontent.com/88566387/192448419-f9f363e6-5a35-4595-889e-4669014b55b6.png">
<img width="601" alt="Screenshot 2022-09-27 at 2 20 15 PM" src="https://user-images.githubusercontent.com/88566387/192448440-f39cc296-e601-4fa8-a35a-0367b3142cb4.png">
I still cannot import Junit test package. However, I used Gradle to run test and got this:
<img width="1232" alt="Screenshot 2022-09-27 at 2 20 35 PM" src="https://user-images.githubusercontent.com/88566387/192448616-a43c4dd2-dcd6-40e5-96d3-aaba4c63b971.png">
Seems these test are unable. How could this happen?

**Comment by damithc** [comment]
Looks like an issue with the IDEA configuration. You can try the remaining suggestions. Some of them set up IDEA from a clean slate.

**Comment by lizekai-richard** [comment]
So can I just leave this and push it to my remote repo?

**Comment by damithc** [comment]
> So can I just leave this and push it to my remote repo?

Yes, if the code works, OK to push.

**Comment by lizekai-richard** [comment]
Okay, thank you prof.
