### ISSUE TITLE
How to undo old merge commit

### ISSUE THREAD

**Issue by bryanngzh** [nus-cs2103-AY2223S1/forum#308]
Hi guys, while doing `tutorial-adding-command`, I accidentally merged the 'tutorial-adding-command' branch with my master branch and I'm unsure how to undo it. 

This was what I did:
1. Create branch 'tutorial-adding-command'
2. Add code stuff into that branch
3. git add -u on 'tutorial-adding-command' branch
4. git commit -m  on 'tutorial-adding-command' branch 
5. git checkout master
6. git merge --no-ff tutorial-adding-command
7. git push origin master 

So what I essentially did was to merge my master branch with 'tutorial-adding-command' branch and pushed my master branch to my tP fork. 

Now my master branch on both github and local has the remark functionality and I can't do any new branches since new branches would have the remark functionality as well. 

How should I go about reverting back my master branch back to the way it was?

Thanks!

--------
Edit: I was thinking maybe I could replace the source folder on my master branch locally and then push it onto github again?

**Comment by RussellDash332** [comment]
What's currently on top of my head is to reset by (your number of commits in tutorial-adding-command) + 1 commits (the merge commit), then push force.

Edit: However since it's not your team repo, there's no harm repulling the master branch from the team repo (by force), which is unmodified, and make a PR directly from the tutorial-adding-command branch

**Comment by bryanngzh** [comment]
Hi @RussellDash332, thanks for the suggestion! How do you pull the master branch from the team repo (by force)?

**Comment by leonidas1712** [comment]
@bryanngzh You could try looking at this [link](https://stackoverflow.com/questions/1125968/how-do-i-force-git-pull-to-overwrite-local-files) for pulling from the team repo by force

**Comment by misterpuffin** [comment]
I think it might be more convenient and safer to `git reset` to the last commit before the merge. You can use `git log` to find the hash of the commit. 

As to how to pull the master branch, assuming you've added your team repo as a remote repo named 'upstream', you can `git fetch upstream` and then `git reset --hard upstream/master`. I don't really recommend this though in case you lose work that's on your master branch.

**Comment by bryanngzh** [comment]
Thank you all for your help! Managed to resolve this by the `git fetch upstream` method.
