### ISSUE TITLE
Commits failing codecov checks

### ISSUE THREAD

**Issue by carriezhengjr** [nus-cs2103-AY2223S1/forum#309]
My team has set up codecov already and all the checks seem to pass for my [team's repo](https://github.com/AY2223S1-CS2103T-T11-4/tp).

However, my [own fork](https://github.com/carriezhengjr/tp) is failing codecov checks and I'm not sure why is that so.
All [my branches](https://github.com/carriezhengjr/tp/branches) also show the red crosses.

<img width="1302" alt="Screenshot 2022-09-26 at 22 58 19" src="https://user-images.githubusercontent.com/97394017/192313195-514bc6bc-8e72-4554-81cf-b738e43d87f0.png">

**Comment by hauchongtang** [comment]
I had the same issue, what I did was to refresh the token via the codecov dashboard, hope it helps.

1. Go to [https://app.codecov.io/gh](https://app.codecov.io/gh)
2. Click on your Team Repo.
3. Go to settings and hit regenerate.
![image](https://user-images.githubusercontent.com/56034480/192319835-844a5abc-f8da-45cd-ad6c-76b5fc8f3dec.png)

5. Back to Github Actions and re-run all build processes.

Took reference from [stackoverflow](https://stackoverflow.com/a/67862043)

**Comment by carriezhengjr** [comment]
> I had the same issue, what I did was to refresh the token via the codecov dashboard, hope it helps.
> 
> 1. Go to https://app.codecov.io/gh
> 2. Click on your Team Repo.
> 3. Go to settings and hit regenerate.
>    ![image](https://user-images.githubusercontent.com/56034480/192319835-844a5abc-f8da-45cd-ad6c-76b5fc8f3dec.png)
> 4. Back to Github Actions and re-run all build processes.
> 
> Took reference from [stackoverflow](https://stackoverflow.com/a/67862043)

It's working now after following the steps. Thank you so much 😄 !
