### ISSUE TITLE
Unable to import from java after installing gradle

### ISSUE THREAD

**Issue by tinenhao** [nus-cs2103-AY2223S1/forum#31]
![image](https://user-images.githubusercontent.com/88677292/185468818-05335a58-e0a4-4be6-94ae-5e81cdca6502.png)
![image](https://user-images.githubusercontent.com/88677292/185468873-39dffcb4-2bca-457e-9fae-c21a13c7b2de.png)

**Comment by damithc** [comment]
@tinenhao As adding Gradle is a week 3 task, you might have to wait a bit longer until you receive some inputs for this from others. In the meantime, perhaps explain what exactly you did to 'install' Gradle?

**Comment by tinenhao** [comment]
I did the following steps
1. pull from the gradle branch
2. delete the IDEA file
3. restart project in IDEA

**Comment by damithc** [comment]
I assume you also merged the branch.

Anyway, for a cleaner start, you can also try to clone your fork to a new location, pull the gradle branch (and merge), and set up the project in Intellij. Post here if the problem persists.

**Comment by tinenhao** [comment]
The problem was resolved after I recloned from the repo. Thank you for your help
