### ISSUE TITLE
Gradle Wrapper issue causing CI to Fail

### ISSUE THREAD

**Issue by Devanshshah1309** [nus-cs2103-AY2223S1/forum#310]
After making changes to some .md file and creating a PR (can be found [here](https://github.com/AY2223S1-CS2103T-W13-4/tp/pull/5)), the CI is failing because of the following issue:

<img width="1044" alt="Screenshot 2022-09-27 at 9 03 46 PM" src="https://user-images.githubusercontent.com/59191109/192534837-def303a0-88ea-4111-9625-e99e840fe326.png">

I built gradle again but there was no change to the .jar file and the CI still fails. Here's the [link to the CI job](https://github.com/AY2223S1-CS2103T-W13-4/tp/actions/runs/3135646944/jobs/5091574695).

Any help is appreciated.

**Comment by RussellDash332** [comment]
Have you tried rerunning your jobs? It seems indeterministic

**Comment by marcuspang** [comment]
Ah yes, the issue is resolved after running the lint job again. Thanks!

**Comment by RussellDash332** [comment]
> Have you tried rerunning your jobs? It seems indeterministic

The same thing goes to Codecov issue with an extra step of regenerating the API token

**Comment by Devanshshah1309** [comment]
Thanks @RussellDash332 👍
