### ISSUE TITLE
Cause: zip END header not found

### ISSUE THREAD

**Issue by ytingtan** [nus-cs2103-AY2223S1/forum#313]
Details:
* IntelliJ version: Community Ediiton 2021.3.1
* OS: Windows
* Tried to run Main, but `Cause: zip END header not found` error is shown 

I have referred to this stackoverflow post such as https://stackoverflow.com/questions/52411697/intellij-compilation-error-zip-end-header-not-found, but when i run `./gradlew --version` I do not get any errors. In fact, I can still see that my Gradle version 7.4.2. 

I have also tried to Unlike Gradle project and Link again, but it still does not work. 

Attached is my project structure: 
![image](https://user-images.githubusercontent.com/95749518/192929126-0d4929fe-c69d-43e8-bba5-0022df2b9b30.png)

Appreciate any help! 🙏

**Comment by damithc** [comment]
@ytingtan While waiting for inputs from others, here are some things you can try:
* Push the code to a branch and share here so that other can try to replicate the problem.
* Try these 'common remedies' one-at-a-time in this order:
   * File -> Invalidate caches
   * Delete the .idea folder -> Close and re import the project
   * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by ytingtan** [comment]
Thanks Prof! I have tried all 3 actions above. However, the error still persists. The code can be found in my fork [here ](https://github.com/ytingtan/tp/tree/update-UserGuide)

**Comment by ytingtan** [comment]
Update: I tried to run `./gradlew wrapper --gradle-version=7.4.2` to reinstall gradle 7.4.2 but instead I got a 
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ClassLoaderRegistry using GlobalScopeServices.createClassLoaderRegistry().
```

**Comment by ytingtan** [comment]
YOOOOO I GOT IT 

Solution: 
1. Go to C:\Users\yourname\.gradle\wrapper\dists and delete the folder labelled gradle 7.4.2 
2. Go to [gradle website](https://services.gradle.org/distributions/) to download the distribution (7.4.2 used for tp) into the same place as Step 1 
3. Unzip folder 
4. Restart IntelliJ 
5. DONE!!!!! 

😸

**Comment by damithc** [comment]
Nice work @ytingtan 
This will be useful if others encounter a similar problem in future.

**Comment by damithc** [comment]
> Tagging a few other students (randomly selected) who have completed related increments, in case they can help: @Bacon-Strips @Neethesh26 @ee-suan @paullee18 @LianGuoYang @lilythchu @Hongyi6328 @Dilysss @ruiqi7 @junweimoo
> Others are welcome to pitch in too.

Sorry, please ignore. Tagged the wrong issue.
