### ISSUE TITLE
Configure project : Project : => no module-info.java found

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S1/forum#314]
Anybody knows how to solve this? i was trying to fix things in my IP for smoke test then i messed up. 
![image](https://user-images.githubusercontent.com/77482097/193029919-b598ec2a-dc3b-4475-be00-57e30a8d9204.png)

**Comment by xiaobill8** [comment]
@junlee1991 Hi Junlee, I'm getting `no module-info.java found` too. Is this breaking anything in your ip? Otherwise, I don't think that this is an issue.

**Comment by junlee1991** [comment]
Ok then i shall close this. thank you!
