### ISSUE TITLE
Unable to merge pull requests into team's repo

### ISSUE THREAD

**Issue by PeiYee88** [nus-cs2103-AY2223S1/forum#315]
<img width="686" alt="image_2022-09-29_23-35-04" src="https://user-images.githubusercontent.com/77477618/193075921-1ac60c88-d760-48c2-9bd9-e7fa480ebcab.png">

Attached is a screenshot while I try merging pull requests into the master branch of my team's repo. Anyone has any idea what the issue is here? Thanks in advance!

Here's the link to the page: https://github.com/AY2223S1-CS2103T-W16-3/tp/pull/9

**Comment by damithc** [comment]
@PeiYee88 it might help if you post the link to the page in the screenshot

**Comment by RussellDash332** [comment]
Have you tried re-running the CI on your own tp repo? I don't see the github-pages workflow as well. This is what I see from your AboutUs branch
![image](https://user-images.githubusercontent.com/63991775/193078124-31711548-f405-4120-be8a-1e7b83187b4d.png)

This is from your PPP branch
![image](https://user-images.githubusercontent.com/63991775/193078200-961f1962-4f50-4222-bbaf-c4276931c8fd.png)

**Comment by PeiYee88** [comment]
@RussellDash332 yep it failed when i try running ci tests.
<img width="733" alt="image_2022-09-29_23-57-06" src="https://user-images.githubusercontent.com/77477618/193080935-9e38d297-7246-4e48-ad43-2efd904610c2.png">

**Comment by RussellDash332** [comment]
See #309.

**Comment by PeiYee88** [comment]
@RussellDash332 Thanks for the help! My CI passes but now the PR request page still shows unable to merge due to missing deployment page. I have already configured it under Settings > Page and set it to master /doc, and there is a Github page for my repo.

**Comment by kxrt** [comment]
> See #309.

@RussellDash332 I tried following that on the main repo itself and it didn't fix the PR issue. PR in question is [here](https://github.com/AY2223S1-CS2103T-W16-3/tp/pull/9) but the same issue stands with all the current PRs from her.

It's also interesting to note that [her fork](https://github.com/PeiYee88/tp) shows an X for CI even though all checks are passing, as visible in the screenshot below. Super confused here.
<img width="612" alt="Screenshot 2022-09-30 at 10 20 28 AM" src="https://user-images.githubusercontent.com/73589885/193176352-9689cef6-ad29-4a41-a388-28d2431d7b92.png">

(Tagging @MarcusPeh for reference)

**Comment by damithc** [comment]
> PR in question is [here](https://github.com/AY2223S1-CS2103T-W16-3/tp/pull/9) but the same issue stands with all the current PRs from her.

It is also 'unusual' that other team members have no PRs so far. Otherwise we could have at least figured out if the problem is specific to one team member or common to all members of the team.

**Comment by seelengxd** [comment]
https://github.com/AY2223S1-CS2103T-W16-3/tp/pull/9/files

![image](https://user-images.githubusercontent.com/34371483/193179468-484a1b2c-3ddd-47aa-936b-7848bbb94e8e.png)

This looks kinda suspicious.

Jekyll seems to want a [front matter](https://jekyllrb.com/docs/front-matter/) for markdown - [stated here](https://jekyllrb.com/tutorials/orderofinterpretation/#:~:text=Files%20must%20have%20a%20Markdown%20file%20extension%20and%20front%20matter%20in%20order%20for%20Jekyll%20to%20convert%20them.) 

maybe try to add that part back and see if it fixes 🤔

**Comment by kxrt** [comment]
> It is also 'unusual' that other team members have no PRs so far. Otherwise we could have at least figured out if the problem is specific to one team member or common to all members of the team.

@damithc I understand, we were erroneously waiting for the first PR to go through as confirmation before making each of our own. I have made a pull request with the same error being encountered here, though: https://github.com/AY2223S1-CS2103T-W16-3/tp/pull/16 
@seelengxd The PR above includes the front matter for Markdown too.

**Comment by kxrt** [comment]
Just a slight update: Unchecking the option in the image below seems to fix the issue.

I believe this is because while setting up branch protection rules in the repository, I had checked this without being required to as additional protection outside of the scope of the instructions, yet didn't set up deployment testing leading to blocked merges. Unchecked it and we can merge now!

<img width="763" alt="Screenshot 2022-09-30 at 2 44 42 PM" src="https://user-images.githubusercontent.com/73589885/193207945-08a1ffa8-aeed-40a4-b52e-55e790a380d2.png">
