### ISSUE TITLE
build logs error

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S1/forum#316]
![image](https://user-images.githubusercontent.com/77482097/193183413-37d5fb61-4202-45ce-9780-25169ffffbc5.png)
Submodule tp got error, check the build logs.

what does this even mean? 

Adding some documentation so there can't be any error.

**Comment by connlim** [comment]
Your logs were deleted so we can't see the error. Try changing your log retention settings to a least a month so you can see what went wrong. [You can follow this guide here.](https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization) After that try rerunning the build to generate a new log.
