### ISSUE TITLE
AB3 `getImage_exitingImage()` test failing due to java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by pratham31012002** [nus-cs2103-AY2223S1/forum#317]
I tried running the already written test cases for AB3. It passed all the test cases except the one for `getImage_exitingImage()` in the `AppUtilTest` class. 
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/71367149/193197122-401ec49f-c1ae-4aaf-a13c-335bae97ae5d.png">
The error message continues for a few more pages.

I am running it on M1 Macbook Air.

Java version I am using:
```
openjdk 11.0.16.1 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+23-CA (build 11.0.16.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+23-CA (build 11.0.16.1+1-LTS, mixed mode)
```

I am able to run the application and see the GUI and the commands also seem to work properly.
Kindly help me with this issue.

**Comment by jasonqiu212** [comment]
Hi @pratham31012002,

I cloned your [repository](https://github.com/pratham31012002/tp) onto my machine and all tests seem to work fine. 

For the `getImage_exitingImage()` in the `AppUtilTest` class, it also passes.

![Screen Shot 2022-10-02 at 5 46 36 PM](https://user-images.githubusercontent.com/25262042/193448058-d52c1b9a-7e28-48c6-a354-309ce567c28e.png)

Perhaps you would want to try cloning your repo again and try running the tests on a fresh build?

My computer specs:
- M1 Pro MacBook Pro
- Same Java version
```
openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)
```
