### ISSUE TITLE
Library Request: `swagger-codegen`

### ISSUE THREAD

**Issue by shenyih0ng** [nus-cs2103-AY2223S1/forum#318]
## Library

[swagger-codegen](https://github.com/swagger-api/swagger-codegen)

> This is more of a CLI tool rather than a project dependency.

## Purpose

Due to goal of our `tp` project, we will need to interface with NUSMods' API. `swagger-codegen` is used to generate the necessary `.java` files for the data models used in the API. It also provides a convenient way to generate boiler code for network requests etc. 

## License

Apache License (https://github.com/swagger-api/swagger-codegen/blob/master/LICENSE)

**Comment by damithc** [comment]
Approved.
