### ISSUE TITLE
Library Request: commons-cli

### ISSUE THREAD

**Issue by SeekSaveServe** [nus-cs2103-AY2223S1/forum#319]
## Library

[commons-cli](https://commons.apache.org/proper/commons-cli/usage.html)

## Purpose
commons-cli: A library for CLI command parser instead of using the current command parser in AB3 to allow for more flexible parsing. Our project requires a more flexible use of command line flags and arguments and we intend to use commons-cli to parse commands.
 
## License
[Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0)

**Comment by damithc** [comment]
Approved.
