### ISSUE TITLE
Git conventions for tp

### ISSUE THREAD

**Issue by jasonqiu212** [nus-cs2103-AY2223S1/forum#320]
Hello everyone! I was wondering if there's a strict guideline for the commit messages in our `tp`.

In the [Git conventions](https://se-education.org/guides/conventions/git.html) site, it provides a format of `{Optional scope}: {description of change}`. However, the site also mentioned about the usage of [Conventional Commits Format](https://www.conventionalcommits.org/en/v1.0.0/), which looks like `commit type(optional scope): description of change`.

Our group wants to use the conventional commit format. Thus, we were wondering if there is a strict requirements on the commit message format for the `tp` (i.e. There's a script that's marking the format).

Thank you!

**Comment by damithc** [comment]
@jasonqiu212 our format `scope: change` is compatible (close enough) with the `<type>[optional scope]: <description>` format of the _[Conventional Commits Format](https://www.conventionalcommits.org/en/v1.0.0/)_ format. So, you may follow the latter too. You may adopt other additional rules/formats from CCF too, as long as they don't conflict with our rules.

**Comment by jasonqiu212** [comment]
Okay, thank you for clarifying prof!
