### ISSUE TITLE
tP Task - v1.1 PR

### ISSUE THREAD

**Issue by rgonslayer** [nus-cs2103-AY2223S1/forum#321]
I noticed in week 7, my v1.1 PR is marked as overdue although I have created PRs and it was successfully merged by my teammates. It was also tagged as milestone v1.1. I was wondering if there was anything I may have missed out which caused it to be marked as overdue?

**Comment by damithc** [comment]
@rgonslayer can you give the link to those PRs?

**Comment by rgonslayer** [comment]
@damithc I managed to resolve the issue! thank you!
