### ISSUE TITLE
"website-adapted" Increment describes nonexistent problems

### ISSUE THREAD

**Issue by e1010101** [nus-cs2103-AY2223S1/forum#322]
Under the tP dashboard (team view), the tracker describes issues regarding my team's (CS2103T-T08-1) website-adapted increment, despite them already being fixed. For example, one issue mentioned was `[README.md] CI banners not pointing to own project;`. 

However, this has already been amended.

Is this error due to syncing issues, or is there some other reason?

**Comment by malwaregarry** [comment]
Hi, had a quick look at your website. I think the problem is that clicking on the Github logo on the top right is not linking to your team's Github repo

**Comment by damithc** [comment]
@e1010101 `website-adapted` seems to be green for your team now.

**Comment by e1010101** [comment]
Thanks all, closed as the issue is resolved.
