### ISSUE TITLE
Question about entry/exit coverage

### ISSUE THREAD

**Issue by malwaregarry** [nus-cs2103-AY2223S1/forum#323]
Hi, I would like seek clarification on what is meant by entry/exit coverage.

![image](https://user-images.githubusercontent.com/43949290/193392936-b44b2200-ef7e-47f8-97ef-b141291a34b8.png)

Does all _possible calls_ mean all possible values the parameter of the function can have? 
Or does it mean all control paths that can be taken? In this case what's the difference between this and path coverage?

Thanks!

**Comment by damithc** [comment]
Good question @malwaregarry 
As this is not urgent, I'll leave it here for a while for others to weigh in on what they think about this.

**Comment by clarence-chew** [comment]
Path coverage seems to cover entry/exit coverage. I think one distinction can happen in multithreaded operations where the order of operations may not be determined, in which there can be way more paths based on the ordering of concurrent operations, however, all of them use the same entry/exit.

**Comment by kxrt** [comment]
Not sure if I've understood this perfectly here, but I believe if multiple paths result in the same exit route, then path coverage might differ from entry/exit coverage. 

```java

void doSomething() {
  ... // internal computation to obtain conditions
  if (condition1 && condition2) {
    route();
  } else if (!condition1 && !condition2) {
    route();
  } else {
    differentRoute();
  }
}
```
In the above example, two paths have the same exit route. However, this might change depending on how you structure your code.

**Comment by damithc** [comment]
> Does all _possible calls_ mean all possible values the parameter of the function can have?

@malwaregarry it refers to all possible places from which the method is called within the system. If `foo()` can be called from three places in the code but it is called from only two of those places during testing, the testing does not have full entry coverage for `foo()`.

Yes, path coverage will ensure entry/exit coverage as well.
