### ISSUE TITLE
Workflow of tp

### ISSUE THREAD

**Issue by Shawn532** [nus-cs2103-AY2223S1/forum#329]
I am a bit confused about the workflow of the tp. I want to add two commands. The first is adding students, and the second is deleting students. Should I do these on two separate branches, or is one okay?

Also, if I do it on two separate branches,  the second command depends on the first. Do I create another branch from the first branch?

**Comment by damithc** [comment]
@Shawn532 Adding and deleting go together, so it should be fine to do as one PR, providing you aim to merge the PR within the span of one iteration.

**Comment by Shawn532** [comment]
> @Shawn532 Adding and deleting go together, so it should be fine to do as one PR, providing you aim to merge the PR within the span of one iteration.

Okay thank you prof! Let's say I want to add another command which is not so related, like adding a question, then I need to create a separate branch and do two PRs right?

**Comment by damithc** [comment]
> Okay thank you prof! Let's say I want to add another command which is not so related, like adding a question, then I need to create a separate branch and do two PRs right?

@Shawn532 Yes that's right, PRs that does one thing each is preferred over PRs that do multiple things.
