### ISSUE TITLE
Failing codecov/patch check

### ISSUE THREAD

**Issue by carriezhengjr** [nus-cs2103-AY2223S1/forum#330]
My recent commit is failing a check in my repo: codecov/patch — 0.00% of diff hit (target 72.15%).
However, the pull request was already merged to our team's repo because it passes all the checks present in team's repo.

I'm not sure why the codecov/patch check fails. I have changed `HelpWindow.java` and `HelpWindow.fxml` in that commit.

Is this of a concern, and how I can resolve this?

Checks in [my repo](https://github.com/carriezhengjr/tp):
<img width="495" alt="Screenshot 2022-10-06 at 16 38 02" src="https://user-images.githubusercontent.com/97394017/194264603-8ae61dcd-f696-4390-82f7-d443e5d26a1a.png">

Checks in my [team's repo](https://github.com/AY2223S1-CS2103T-T11-4/tp):
<img width="491" alt="Screenshot 2022-10-06 at 16 44 34" src="https://user-images.githubusercontent.com/97394017/194265790-bc44d48e-fa7c-42db-931e-f598025cf2e8.png">
<img width="495" alt="Screenshot 2022-10-06 at 16 39 00" src="https://user-images.githubusercontent.com/97394017/194264704-d27509d5-50ea-4a52-9639-784dc5995505.png">

The [Codecov Report](https://codecov.io/gh/AY2223S1-CS2103T-T11-4/tp/pull/60?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=AY2223S1-CS2103T-T11-4) found in my [pull request](https://github.com/AY2223S1-CS2103T-T11-4/tp/pull/60):
<img width="822" alt="Screenshot 2022-10-06 at 17 40 19" src="https://user-images.githubusercontent.com/97394017/194280740-c5210b94-0146-4af4-9e0e-aa763b2cd0b1.png">

**Comment by nealetham** [comment]
@carriezhengjr From the codecov [documentation](https://docs.codecov.com/docs/commit-status#patch-status), it seems to suggest that the codecov/patch check checks for any test coverage for the new lines of code you've added for that particular commit/pr. 
i.e. the lines of code you've added in `HelpWindow.java` were uncovered as you have not added any tests for them, therefore it fails the check.

I also faced the same situation in my individual repo and my pr, and I think the reason why it's not flagged out in the pr is because that it does not run the codecov/patch, though it still flag it under the impacted files table. I could be wrong, but that's just my interpretation of it.

**Comment by carriezhengjr** [comment]
> @carriezhengjr From the codecov [documentation](https://docs.codecov.com/docs/commit-status#patch-status), it seems to suggest that the codecov/patch check checks for any test coverage for the new lines of code you've added for that particular commit/pr. i.e. the lines of code you've added in `HelpWindow.java` were uncovered as you have not added any tests for them, therefore it fails the check.
> 
> I also faced the same situation in my individual repo and my pr, and I think the reason why it's not flagged out in the pr is because that it does not run the codecov/patch, though it still flag it under the impacted files table. I could be wrong, but that's just my interpretation of it.

Oh I see! Did you resolve the issue in the end?

**Comment by nealetham** [comment]
Hmm, personally, I wouldn't see it as an critical issue per se but more of a warning. I have not resolved it, but I'm guessing that in the same commit/pr you just have to write test cases which tests the lines of code that you have written.

You might not know which lines of code that you have to test before making the commit. But once you fail the check you can use codecov to see the lines that's required of you to test. For your `HelpWindow.java` file, [here](https://app.codecov.io/gh/carriezhengjr/tp/commit/332f56579f48794b5a4c9f24280cc4bf895a28fc/src/main/java/seedu/address/ui/HelpWindow.java) are the lines u have to test.

Hope this helps!

**Comment by damithc** [comment]
> Hmm, personally, I wouldn't see it as an critical issue per se but more of a warning.

Yup, the module doesn't have a specific code coverage bar to meet. It is up to you to use coverage info to improve your own testing. You are free to tweak CI settings for CodeCov, or even remove it from CI.

**Comment by carriezhengjr** [comment]
> Hmm, personally, I wouldn't see it as an critical issue per se but more of a warning. I have not resolved it, but I'm guessing that in the same commit/pr you just have to write test cases which tests the lines of code that you have written.
> 
> You might not know which lines of code that you have to test before making the commit. But once you fail the check you can use codecov to see the lines that's required of you to test. For your `HelpWindow.java` file, [here](https://app.codecov.io/gh/carriezhengjr/tp/commit/332f56579f48794b5a4c9f24280cc4bf895a28fc/src/main/java/seedu/address/ui/HelpWindow.java) are the lines u have to test.
> 
> Hope this helps!

Alright thank you 😄 !

**Comment by carriezhengjr** [comment]
> > Hmm, personally, I wouldn't see it as an critical issue per se but more of a warning.
> 
> Yup, the module doesn't have a specific code coverage bar to meet. It is up to you to use coverage info to improve your own testing. You are free to tweak CI settings for CodeCov, or even remove it from CI.

Ok thank you prof 😃 !
