### ISSUE TITLE
Does anyone meet error of codecov with this pls help sos

### ISSUE THREAD

**Issue by bokun2** [nus-cs2103-AY2223S1/forum#335]
![3931665286644_ pic](https://user-images.githubusercontent.com/97288772/194736738-b65b1169-ed8f-42b6-a069-32c79cab01c4.jpg)

I think I haven't deleted any related files...

**Comment by kxrt** [comment]
Could you try manually [generating a coverage report](https://www.jetbrains.com/help/idea/generating-code-coverage-report.html) and see if that fixes the issue?

**Comment by chunkhaik** [comment]
The way our group solved it was by re-running the job. Maybe you'll find [this](https://github.com/codecov/codecov-action/issues/598) thread helpful

Alternatively you can try a dummy commit to re-trigger codecov, that worked for us too

**Comment by nehcuy** [comment]
I've actually gotten the same error a few times and it was because I have cleared my cache and browser history, logging me out of codecov. You might want to check if you are logged into [codecov](https://about.codecov.io/).

**Comment by RussellDash332** [comment]
Codecov errors are actually nondeterministic. Another job retry or refresh on codecov token will fix.

**Comment by jamietan2002** [comment]
U can try rerunning the job, it worked for me

**Comment by deeyonn** [comment]
I've been experiencing the same issue from time to time. Re-running the failed task after awhile seems to work.
