### ISSUE TITLE
Line ending issue for CI \r\n

### ISSUE THREAD

**Issue by clarence-chew** [nus-cs2103-AY2223S1/forum#336]
I'm using Windows and this is part of the ubuntu CI, and I'm not sure how to resolve this error message. There's some issue with line endings in the files, that I can tell.

Abridged error message:
```
Run ./run-checks.sh
ERROR:../src/main/java/foodwhere/storage/JsonAdaptedReview.java:1: prohibited \r\n line ending, use \n instead.
```

Full error message is here, essentially the same thing repeated across multiple files:
https://github.com/AY2223S1-CS2103-W14-2/tp/actions/runs/3213682841/jobs/5253716347

What processes can I try, to deal with the issue?

**Comment by ketamethane** [comment]
For some reason, Window line endings are in \r\n . 
Could you try going into IntelliJ `File` > `Settings` > `Code Style` > `Line Separator` and set it to \n ?
![image](https://user-images.githubusercontent.com/88729540/194757205-78aa6370-3833-4993-ab56-eeb3276a1330.png)

Then highlight all the lines with the issue flagged out by the CI.
Click on `CRLF` or whatever is showing and change it to \n format
![image](https://user-images.githubusercontent.com/88729540/194757273-7b732f70-fc08-422a-bd0b-ecf95dcebbcb.png)

**Comment by clarence-chew** [comment]
Thanks, clicking the CRLF button to change it helped.
