### ISSUE TITLE
Question about the tP workflow 

### ISSUE THREAD

**Issue by xhphoong** [nus-cs2103-AY2223S1/forum#337]
Hi, I want to check with you about the workflow. So, I have open a pull request on my team then when I am doing halfway, my teammates merge new code into the team master then when I push another commit to my branch, in the pull request it shows up sth like this: 
![Screenshot (425)](https://user-images.githubusercontent.com/92239144/194788764-eeeb0569-f290-4209-8e44-90d419da00f3.png)

Then, I try to resolve the conflicts and it merges the master branch into my own branch:
![Screenshot (426)](https://user-images.githubusercontent.com/92239144/194788827-bbc68cb3-e568-4f99-9cad-0e61f71babfb.png)

I thought I am doing it wrongly then I reopen a branch doing the same commit of my previous branch and push it again and it still shows up the need to resolve conflict issue and when resolving, it only have the option for merging master into my branch.

So I want to ask whether is it okay to **merge master into my branch and continue to add other stuff into that branch** or I have to **pull the new codes into the master and create a new branch and update my code accordingly** or is there any other way to resolve this? 

Thank you!

**Comment by Puakii** [comment]
Yes, you can merge master into your branch and continue to add things into that branch. Pulling from the upstream master into your branch allows you to fix any merge conflicts and be updated with the latest code as well as keep whatever you are doing in that branch

**Comment by Aishwarya-Hariharan-Iyer** [comment]
As @Puakii mentioned, that seems ok! You can also merge the upstream master to your master and then merge your master with your branch since for future PRs, you will be creating new branches from your master. So it's good to have your master synced with the upstream master.

**Comment by damithc** [comment]
A visual explanation is in Week 7 lecture, around 18 minutes mark

![image](https://user-images.githubusercontent.com/1673303/194804546-179d0b48-00b1-4bfe-9085-dbcabfc07913.png)

**Comment by xhphoong** [comment]
Thank you!  @damithc @Puakii @Aishwarya-Hariharan-Iyer
