### ISSUE TITLE
Bug: wrong activity diagram

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#338]
I tried this exercise, and when I wanted to check my answer, I found out that the activity diagram does not correspond to the question.

<img width="247" alt="image" src="https://user-images.githubusercontent.com/13196670/194854356-94e7d7a9-92d4-4370-a1cb-9364cbe3eb44.png">

**Comment by nealetham** [comment]
I think the diagram serves to remind students what an activity diagram is. If I'm not wrong, this question will be discussed during tutorial. You can check your answer then.

**Comment by damithc** [comment]
> I think the diagram serves to remind students what an activity diagram is. If I'm not wrong, this question will be discussed during tutorial. You can check your answer then.

@nealetham  is correct :-)

**Comment by cheeheng** [comment]
Thanks so much. So this is not a bug.
