### ISSUE TITLE
💡 how to set Intellij not using wildcard import

### ISSUE THREAD

**Issue by Echomo-Xinyu** [nus-cs2103-AY2223S1/forum#339]
For those who suffered from Intellij automatically replacing multiple import statements with a wildcard import like me, I think this article can be useful!

https://stackoverflow.com/questions/3348816/intellij-never-use-wildcard-imports

**Comment by damithc** [comment]
More intellij setting relevant to AB3:

https://nus-cs2103-ay2223s1.github.io/tp/SettingUp.html#before-writing-code (see point `Configure the coding style`)
