### ISSUE TITLE
Unable to push to github 

### ISSUE THREAD

**Issue by ReubenChay** [nus-cs2103-AY2223S1/forum#34]
Hi! I can't seem to push my commits to github, this is the error that I receive. I've tried googling and using all the suggested methods that I found but they all don't seem to work. 

Pushing to https://github.com/ReubenChay/ip.git
remote: Permission to ReubenChay/ip.git denied to ReubenChay.
fatal: unable to access 'https://github.com/ReubenChay/ip.git/': The requested URL returned error: 403
Completed with errors, see above

**Comment by damithc** [comment]
@ReubenChay Are you using Sourcetree? If you are, have you tried these? https://se-education.org/guides/tutorials/sourcetree.html

**Comment by kxrt** [comment]
@ReubenChay If you're using CLI, maybe [this](https://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed) will be helpful. Alternatively, have you recently changed your GitHub username and are on MacOS? If so [this](https://stackoverflow.com/questions/47465644/github-remote-permission-denied) might be worth looking into.

**Comment by ReubenChay** [comment]
@damithc @kxrt thanks for the help! I realised I was using my password for authentication instead of a PAT which resulted in the denied permission.

**Comment by myangat0343** [comment]
With great thanks for @damithc @kxrt @ReubenChay. I also encountered the same problem. And for me(Mac user), the SourceTree user account must be login with Auth Type(Basic) and PAT.
