### ISSUE TITLE
Library request: `JCommander` for command parsing

### ISSUE THREAD

**Issue by jontmy** [nus-cs2103-AY2223S1/forum#340]
## Library

[JCommander](https://jcommander.org)

## Purpose

A CLI command parsing library instead of using AB3's argument tokenizer, as it has better support for optional and required arguments. While `commons-cli` has already been approved in #319, we prefer JCommander as it has support for parameter validation, converters into complex objects, and nicer syntax with annotations and such.

## License

[Apache License 2.0](https://github.com/cbeust/jcommander/blob/master/license.txt)

**Comment by damithc** [comment]
Approved.
