### ISSUE TITLE
Unable to retake Week 10 in-video quizzes

### ISSUE THREAD

**Issue by nehcuy** [nus-cs2103-AY2223S1/forum#342]
Same issue as previous weeks, in-video quizzes unable to be retaken. Instances of quizzes occur at:
- [W10.1] Design Patterns
- [W10.2] Defensive Programming
- [W10.4b] Quality Assurance → Test Case Design → Equivalence Partitions → Basic
- [W10.5b] Quality Assurance → Test Case Design → Boundary Value Analysis → How

**Comment by damithc** [comment]
@nehcuy Thanks for the alert. The Panopto platform that hosts these videos seems to be facing some difficulties. Will try again a while later.

**Comment by damithc** [comment]
Managed to sort out the platform issue. I've reconfigured the quizzes  to allow retaking.

**Comment by nehcuy** [comment]
Thanks for always fixing this problem every week prof!
