### ISSUE TITLE
Test Cases video has question but no Q+ indicator

### ISSUE THREAD

**Issue by clarence-chew** [nus-cs2103-AY2223S1/forum#343]
The [W10.4] Test Cases: Equivalence Partitioning -> What section of the notes has a video with a question but it doesn't have the Q+ indicator. This is to check if this is intended.

**Comment by damithc** [comment]
@clarence-chew Yes, I might have omitted the Q+ from some videos intentionally, to reduce the number of in-video quizzes that count for participation in this week (no Q+ markers means any quiz in that video will not be used for participation).

**Comment by clarence-chew** [comment]
Thanks for clarifying!
