### ISSUE TITLE
TP progress dashboard captures the wrong release

### ISSUE THREAD

**Issue by ThomasHoooo** [nus-cs2103-AY2223S1/forum#344]
My group released v1.2 on our repo but the dashboard captures as v1.3.
![image](https://user-images.githubusercontent.com/78606832/195889919-626fe4dc-dd6f-4943-bbd2-4ca340a0eca5.png)
![image](https://user-images.githubusercontent.com/78606832/195889973-0e8376ce-e887-4cd1-a448-10903abd2339.png)

**Comment by damithc** [comment]
@ThomasHoooo It's fine. As long as you've already done a release, it meets our objective of this particular deliverable.

**Comment by ThomasHoooo** [comment]
@damithc I see. Thanks for the clarification!
