### ISSUE TITLE
Precise definition of boundaries

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#345]
What is the precise definition of boundaries? I would like to clarify on some questions:

1. Does boundaries need to be with respect to a contiguous range, or can it be further generalised?
2. Is null a boundary value of the equivalence partition [null]?
3. It is mentioned in the textbook that the equivalence partition of prime numbers has no specific boundary, but I could argue that 2 is the smallest prime number, and hence can be considered a boundary. What is wrong with this argument? In the same token, I could argue that numbers which are products of two prime numbers (not necessarily distinct) can be considered boundaries within the equivalence partition of positive non-prime integers not lesser than 2 because those numbers must be the product of at least two prime numbers (not necessarily distinct) whereas prime numbers are the product of exactly one prime number.

**Comment by damithc** [comment]
@cheeheng When doing a boundary value analysis, our goal is to catch cases where a programmer could have made a mistake on  an input data point at which the behavior of the program changes (compared to its adjacent data points). That's more important than trying to define boundaries precisely. BVA is a heuristic after all, not a precise science.


> * Does boundaries need to be with respect to a contiguous range, or can it be further generalised?

the edge of a contiguous data range is the typical example of a boundary. But I suppose there can be other cases where the behavior of the program such that it forms a 'boundary' in the input space (i.e., there is potential for programmer errors at those specific points).

> * Is null a boundary value of the equivalence partition [null]?

As it is a value, we typically consider them a separate partition with one value. In the end, what matters is deciding whether we _should_ test with null as input, not so much if it is a boundary value or a partition.

> * It is mentioned in the textbook that the equivalence partition of prime numbers has no specific boundary, but I could argue that 2 is the smallest prime number, and hence can be considered a boundary. What is wrong with this argument? In the same token, I could argue that numbers which are products of two prime numbers (not necessarily distinct) can be considered boundaries within the equivalence partition of positive non-prime integers not lesser than 2 because those numbers must be the product of at least two prime numbers (not necessarily distinct) whereas prime numbers are the product of exactly one prime number.

Depending on what the SUT is supposed to do with these prime numbers, 2 _can_ be considered a 'boundary'. Again, the question is whether there is a higher potential for the programmer to make a mistake at 2 compared to other inputs. Similarly, there can be other values that are 'special' (based on what the SUT is supposed to do) that are worthy of testing.

**Comment by cheeheng** [comment]
Thanks prof
