### ISSUE TITLE
Query on time-sensitive deadlines for project tasks

### ISSUE THREAD

**Issue by tantzeyeong** [nus-cs2103-AY2223S1/forum#348]
For this week's project tasks below, the website says they are time-sensitive and should not be done later than the deadline. There's a similar description for Week 11's "Update user docs" task as well. Can I check when are these deadlines referring to? Is it by the end of each respective week, or by the end of v1.3?

![image](https://user-images.githubusercontent.com/87800869/196158279-cabac21b-c582-4b97-b012-9a4b798709c2.png)
![image](https://user-images.githubusercontent.com/87800869/196158346-26c28185-a272-401e-ab0f-bd42a69da5c0.png)

**Comment by deeyonn** [comment]
![image](https://user-images.githubusercontent.com/41563700/196160171-89ab1cb4-9896-4ecb-82da-c78a364c5c04.jpeg)

Seems that it would be before the next lecture.

**Comment by damithc** [comment]
> ![image](https://user-images.githubusercontent.com/41563700/196160171-89ab1cb4-9896-4ecb-82da-c78a364c5c04.jpeg)
> 
> Seems that it would be before the next lecture.

@deeyonn is correct 👍

**Comment by tantzeyeong** [comment]
Thanks!
