### ISSUE TITLE
Policy regarding reuse of your own code

### ISSUE THREAD

**Issue by e1010101** [nus-cs2103-AY2223S1/forum#349]
I was wondering what the necessary steps were to use my code in the TP. I have a code snippet from one of my other projects that I would like to use, but I could not find any information regarding this on the module website (or I missed it). 

What is the policy regarding this?

**Comment by damithc** [comment]
@e1010101 treat it as other cases of reuse but you can mention that the work was done by you for a different project.

**Comment by e1010101** [comment]
Ok, will do! Closed as this is answered.
