### ISSUE TITLE
Library request: OpenCSV

### ISSUE THREAD

**Issue by leecaregene** [nus-cs2103-AY2223S1/forum#351]
## Library

[OpenCSV](https://opencsv.sourceforge.net/)

## Purpose

For easier reading and writing of CSV files.

OpenCSV is an easy-to-use CSV (comma-separated values) parser library for Java.

## License

[Apache 2](https://opencsv.sourceforge.net/licenses.html)

**Comment by damithc** [comment]
Approved.
