### ISSUE TITLE
Updating the DG: Other Member's Implementation

### ISSUE THREAD

**Issue by sltsheryl** [nus-cs2103-AY2223S1/forum#353]
Hi for updating of the DG Implementation, it says that we should do a writeup for a feature we have implemented ourselves. Could I ask if a member can do a write-up for another member's implemented feature? Because some features are quite similar and we feel it's better to include the features that may have been done by the same person.

Eg. Person X implemented a feature similar to Person Y, but Person Y has written about that feature already and has other more worthy features to be written in the DG), can Person X do the writeup for other features implemented by Person Y?

Thanks!

<img width="688" alt="Screenshot 2022-10-19 at 2 22 07 PM" src="https://user-images.githubusercontent.com/96589109/196612632-a567cf4a-de8f-4475-98ba-1cb03941b8fe.png">

**Comment by damithc** [comment]
@sltsheryl It should be fine, provided,
1. each person has room to contribute enough to the DG (e.g., you describing someone else's feature should not result in that member not having enough contributions to the DG).
2. your team has consensus on who will take the responsibility for the bugs found in the DG later (i.e., the person who wrote that part, the person who implemented that part, or both?).

**Comment by sltsheryl** [comment]
Alright thank you!
