### ISSUE TITLE
Library Request: picocli

### ISSUE THREAD

**Issue by marcuspang** [nus-cs2103-AY2223S1/forum#354]
## Library

[picocli](https://github.com/remkop/picocli)

## Purpose

A CLI command parsing library instead of using AB3's parsing, as it has support for subcommands, optional/required, as well as interactive commands. While commons-cli and JCommander have already been approved, we realised that support for subcommands were lacking in these libraries. Specifically, the picocli library has great flexibility in allowing users to create commands with the syntax we wish to achieve (similar to `git` and `docker` style commands).

## License

[Apache License 2.0](https://github.com/remkop/picocli/blob/main/LICENSE)

**Comment by damithc** [comment]
Approved.
