### ISSUE TITLE
Library request: Password4j

### ISSUE THREAD

**Issue by leecaregene** [nus-cs2103-AY2223S1/forum#358]
## Library

[Password4j](https://password4j.com/)

## Purpose

For easier handling of passwords.

Password4j is a Java fluent cryptographic library for encrypting and checking passwords with different [Key derivation functions](https://en.wikipedia.org/wiki/Key_derivation_function) (KDFs) and [Cryptographic hash functions](https://en.wikipedia.org/wiki/Cryptographic_hash_function) (CHFs).

## License

[Apache 2](https://github.com/Password4j/password4j/blob/master/LICENSE)

**Comment by damithc** [comment]
Approved.
