### ISSUE TITLE
Is UI update considered a feature? (Will it be affected by feature freeze?)

### ISSUE THREAD

**Issue by sharmaine1028** [nus-cs2103-AY2223S1/forum#360]
My group was wondering if updating the UI is considered a feature? We were thinking it isn't since it's not part of the user stories or give any added functionality. But just in case, we wanted to confirm that it will not be affected by the feature freeze.

**Comment by lesterong** [comment]
Yes, UI updates are affected by the feature freeze in v1.4. You can find more information [here](https://nus-cs2103-ay2223s1.github.io/website/admin/tp-w12.html#2-start-fixing-ped-bugs-before-the-tutorial).

<img width="762" alt="image" src="https://user-images.githubusercontent.com/84223259/196902339-1e290fb9-04e5-4e75-8689-97c42c96f4a6.png">

**Comment by damithc** [comment]
@lesterong is correct. UI changes are not allowed either, as they are very visible behavior changes.
