### ISSUE TITLE
PlantUML restrictions

### ISSUE THREAD

**Issue by kxrt** [nus-cs2103-AY2223S1/forum#366]
Given that we're required to follow the pre-defined style guide for PlantUML in `style.puml`, and the file [hides members](https://github.com/nus-cs2103-AY2223S1/tp/blob/77a32bf67b69274221eb3a6b3b1db2a16683ee46/docs/diagrams/style.puml#L74) from being visible in diagrams, would it be alright to have a `show members` line for class diagrams within the feature section to show methods and attributes?

The diagram looks like this if the above is possible:
![AppointmentClassDiagram](https://user-images.githubusercontent.com/73589885/197226731-676268ce-361d-4bf0-b045-d3119ae012f9.png)

`skinparam classAttributeIconSize 0` sets the visibility identifiers to +, -, ~, # instead of icons, for anyone else wondering.

**Comment by damithc** [comment]
> Given that we're required to follow the pre-defined style guide for PlantUML in `style.puml`, and the file [hides members](https://github.com/nus-cs2103-AY2223S1/tp/blob/77a32bf67b69274221eb3a6b3b1db2a16683ee46/docs/diagrams/style.puml#L74) from being visible in diagrams, would it be alright to have a `show members` line for class diagrams within the feature section to show methods and attributes?

@kxrt Yes, that's fine. While you are required to follow the notation used in them module, you are not required to follow the style.puml strctly.
