### ISSUE TITLE
Use of assert x != null and requireNonNull(x)

### ISSUE THREAD

**Issue by sltsheryl** [nus-cs2103-AY2223S1/forum#367]
Could I clarify more about the use of ```assert x != null``` and ```requireNonNull(x)```?
I think a few differences between them are 
1. ```requireNonNull(x)``` throws a NullPointerException when x is null instead of an assertion (assertion handles more of developer side errors while exceptions include users input errors)
2. ```assert``` will work only if we put ```-ea```/enable assertions but ```requireNonNull``` will always work

But I'm still not entirely sure when we use which. Is it right to think in this way,

For instance, in the current ```EditCommand``` in ab3, 
for ```Index``` in ```EditCommand(Index index, EditPersonDescriptor editPersonDescriptor)```, we will do ```requireNonNull(Index)```.

But after we have gotten the ```personToEdit``` from ```Index```, we will then do ```assert personToEdit != null``` in the method ```createEditedPerson``` given.

Thanks!

**Comment by kxrt** [comment]
I feel like you've answered your own question with:
```
assertion handles more of developer side errors while exceptions include users input errors
```

Your example should be correct. The `index` input being `null` would be a user-side error (missing index value in the CLI input) whereas `personToEdit` being null would be a developer-side error in obtaining the desired `Person` from the stored list.

**Comment by damithc** [comment]
Keep in mind that NullPointerException is an unchecked exceptions, which are not typically caught and handled (although they can be). So, in this case both,  `assert x != null` and `requireNonNull(x)` have the same end result.

Related issue #311

**Comment by sltsheryl** [comment]
Ah I see, sorry I missed the duplicate question. Thank you
