### ISSUE TITLE
Definition of "programmatically accessible services" for service-oriented architecture

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#369]
I am confused about the definition of programmatically accessible services. From the textbook, I can infer that programmatically accessible services include web APIs. Are there any other examples of programmatically accessible services? If possible, is there a precise definition of programmatically accessible services?

**Comment by damithc** [comment]
@cheeheng SOA used to be a hot architecture style about a decade ago, but not so much nowadays. For this module, it is good enough if you are aware of the high-level approach of SOA. The typical SOA uses a concept called 'Service Bus' and a protocol called SOAP to handle services but that's beyond this module's scope.
That said, it is understandable that you wonder about the difference between SOA and Web APIs as they are not totally disjoint. In fact, Microservices are related to these two concepts as well. As this is a common confusion, there are good writeups comparing and contrasting them e.g., https://www.devteam.space/blog/microservices-vs-soa-and-api-comparison/

**Comment by cheeheng** [comment]
Thanks so much prof! This is very informative.
