### ISSUE TITLE
How to approach reloading the application with a command?

### ISSUE THREAD

**Issue by deeyonn** [nus-cs2103-AY2223S1/forum#373]
Hi, I would like to explore the idea of reloading the application using a `Command`.

I would like to initialize new instances of the following classes in the reload `Command`.
* `JsonUserPrefsStorage`
* `UserPrefs`
* `JsonAddressBookStorage`
* `StorageManager`
* `ModelManager`
* `LogicManager`
* `UiManager`

and reload `MainApp` using these new instances.

Since the current `Command::execute` function only takes in `Model` as its parameter, what are some ways I can expose the current instances of the above classes for modification, and then reloading the application if needed.

**Comment by damithc** [comment]
@deeyonn Out of curiosity, what's the purpose of reloading the app using a command?

**Comment by deeyonn** [comment]
> @deeyonn Out of curiosity, what's the purpose of reloading the app using a command?

Hi Prof, I would like to achieve the result of allowing the user to specify a json file to load using a command, then loading that file. Though a majority of that logic falls under `JsonAddressBookStorage`, it seems that there are many other classes listed above that are interdependent on each other.

The ideal solution would be to change the instance of as little objects as possible. The worst case would be to reload the entire application specifying all the new instances.

**Comment by damithc** [comment]
> I would like to achieve the result of allowing the user to specify a json file to load using a command, then loading that file.

I see. There is chance of other teams doing similar things. Let's see if anyone has any suggestions. I suspect that this doesn't require reloading of the entire application.

**Comment by Yongbeom-Kim** [comment]
It seems to me that you just need to empty current, and load new data into the relevant observable lists? Maybe you can expose a reload method in Model that fetches data and re-constructs relevant objects?

**Comment by teekaytai** [comment]
I think you can add a separate flag to the `CommandResult` class that signals whether a reload is required (similar to the flags for opening the help window or for exiting the app). Then as the `CommandResult` is passed back up the "chain of command", the relevant classes can perform the necessary actions. So for example, when the command is executed and the `CommandResult` is returned to the `LogicManager`, the `LogicManager` can do a check for this flag. `LogicManager` has access to the `Storage`, so `LogicManager` can ask the `Storage` to do a reload.

**Comment by damithc** [comment]
> I think you can add a separate flag to the `CommandResult` class that signals whether a reload is required (similar to the flags for opening the help window or for exiting the app). Then as the `CommandResult` is passed back up the "chain of command", the relevant classes can perform the necessary actions. So for example, when the command is executed and the `CommandResult` is returned to the `LogicManager`, the `LogicManager` can do a check for this flag. `LogicManager` has access to the `Storage`, so `LogicManager` can ask the `Storage` to do a reload.

Alternatively, the `Storage` object can be given to the `Command#execute()` as another parameter.

**Comment by deeyonn** [comment]
Thank you all for the insightful feedback!! I think everyone's suggestions has its pros and cons. I have decided to modify the method signature of `Command#execute(Model model)` to `Command#execute(Model model, Storage storage)`. Though I am facing new issues regarding updating displays, I will discuss these issues with my team and see how we can move forward. Or maybe open a new issue if there is time.
