### ISSUE TITLE
JUnit Test Issues

### ISSUE THREAD

**Issue by t1mzzz** [nus-cs2103-AY2223S1/forum#374]
I'm having issues with JUnit tests. The code is basically a pop-up for the user's email client. The tests were all successful in Intellij, but the CI has some errors (as seen below). I think it's because of the libraries I'm using ([`java.awt.Desktop`](https://docs.oracle.com/javase/7/docs/api/java/awt/Desktop.html) and [ `java.net.URI`](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html)). Does anyone have any ideas regarding this? Is this a UI issue and is similar to #328?

<img width="374" alt="image" src="https://user-images.githubusercontent.com/97350034/197788954-904f27ca-8d60-4cba-b073-4b43c0a68747.png">

**Comment by johnrhimawan** [comment]
From reading the documentation at https://docs.oracle.com/javase/7/docs/api/java/awt/HeadlessException.html, maybe you can try see first if the code works if you remove the ```mail()``` method? The ```HeadlessException``` might be result of the pop-up after the method ```mail()``` is called since it might not be supported.

**Comment by damithc** [comment]
@t1mzzz note that the CI is run in 'headless' environment (i.e., there is no display device) and therefore, might not support things such as pop-up dialogs.

**Comment by t1mzzz** [comment]
Thanks @johnrhimawan for the reply I'll try it out.

**Comment by t1mzzz** [comment]
Thanks for reply prof @damithc. So what is the best course of action?

**Comment by damithc** [comment]
> Thanks for reply prof @damithc. So what is the best course of action?

Options;

1. Omit GUI related actions from tests run by CI. This is the reason why AB3 omits any automated GUI tests.
2. IIRC, we used TestFX library in [AB4](https://github.com/se-edu/addressbook-level4) to do GUI testing in headless mode, but this was sometime back

**Comment by t1mzzz** [comment]
> > Thanks for reply prof @damithc. So what is the best course of action?
> 
> Options;
> 
> 1. Omit GUI related actions from tests run by CI. This is the reason why AB3 omits any automated GUI tests.
> 2. IIRC, we used TestFX library in [AB4](https://github.com/se-edu/addressbook-level4) to do GUI testing in headless mode, but this was sometime back

How do I delete the GUI related actions from tests run by CI? By that do you mean completely deleting the below in the .yml file?

<img width="185" alt="image" src="https://user-images.githubusercontent.com/97350034/197922447-c1cb921e-b752-4ff5-88c2-5c27647a1190.png">

**Comment by damithc** [comment]
> How do I delete the GUI related actions from tests run by CI? By that do you mean completely deleting the below in the .yml file?
> 
> <img alt="image" width="185" src="https://user-images.githubusercontent.com/97350034/197922447-c1cb921e-b752-4ff5-88c2-5c27647a1190.png">

The simplest way is to not write such JUnit tests that involve the GUI (i.e., test such behavior manually instead).

**Comment by t1mzzz** [comment]
> The simplest way is to not write such JUnit tests that involve the GUI (i.e., test such behavior manually instead).

Alright prof, but how should that means the method and line coverage may not be 100%. That's still okay right?

**Comment by damithc** [comment]
> Alright prof, but how should that means the method and line coverage may not be 100%. That's still okay right?

@t1mzzz 100% coverage was never a requirement https://nus-cs2103-ay2223s1.github.io/website/admin/tp-expectations.html#individual-expectations-on-testing

**Comment by t1mzzz** [comment]
> @t1mzzz 100% coverage was never a requirement https://nus-cs2103-ay2223s1.github.io/website/admin/tp-expectations.html#individual-expectations-on-testing

Okay, prof! Thanks so much for the help and clarification!
