### ISSUE TITLE
Library request: zxcvbn4j

### ISSUE THREAD

**Issue by leecaregene** [nus-cs2103-AY2223S1/forum#375]
## Library

[zxcvbn4j](https://github.com/nulab/zxcvbn4j)

## Purpose

For estimating the strength of passwords.

This is a java port of [zxcvbn](https://github.com/dropbox/zxcvbn), which is a password strength estimator inspired by password crackers written on JavaScript.

## License

[MIT](https://github.com/nulab/zxcvbn4j/blob/master/LICENSE.txt)

**Comment by damithc** [comment]
Approved. On a related note, try not to put in **unnecessary** security measures into the app as it can make the app hard-to-test, which is considered a design flaw.
