### ISSUE TITLE
PlantUML Sequence Diagram: Destroyed object

### ISSUE THREAD

**Issue by sltsheryl** [nus-cs2103-AY2223S1/forum#376]
In this [section](https://nus-cs2103-ay2223s1.github.io/website/se-book-adapted/chapters/uml.html#object-deletion) of the textbook, it says the lifeline should end where the object is deleted. 

<image src="https://user-images.githubusercontent.com/96589109/197993714-82bc014c-ad35-447a-963e-c2f1b0d31413.png" height="100">

However, I think [PlantUML doesn't support ending the lifeline](https://forum.plantuml.net/9324/end-participant-line-after-destroy) and the given `DeleteSequenceDiagram` in AB3 does not align with the textbook, where the lifeline for ```DeleteCommandParser``` is extended till the bottom after it is destroyed. 

<image src ="https://user-images.githubusercontent.com/96589109/197995104-978e3db9-f19e-44e6-a6cb-e27f81a71f16.png" height="450">

Could I ask if there is a way around this? Thanks!

**Comment by nehcuy** [comment]
> Could I ask if there is a way around this? Thanks!

IIRC it was mentioned during my tutorial that due to restraints with PlantUML, it is fine to leave it as it is and that it is for our learning that the textbook sticks with the version where the lifeline should end where the object is deleted. This is just a vague memory, so someone please correct me if I'm wrong.

**Comment by sltsheryl** [comment]
> > Could I ask if there is a way around this? Thanks!
> 
> IIRC it was mentioned during my tutorial that due to restraints with PlantUML, it is fine to leave it as it is and that it is for our learning that the textbook sticks with the version where the lifeline should end where the object is deleted. This is just a vague memory, so someone please correct me if I'm wrong.

Ah I see thanks for replying, yep just checking so this won't count as a documentation bug. Thank you!

**Comment by damithc** [comment]
> IIRC it was mentioned during my tutorial that due to restraints with PlantUML, it is fine to leave it as it is and that it is for our learning that the textbook sticks with the version where the lifeline should end where the object is deleted.

Yes, @nehcuy is correct. While this is not the correct syntax, we have no choice but to use it as long as we are using PlantUML. It will not be considered a DG bug. **At other places (e.g., during the exam), you should use the correct syntax.**

**Comment by sltsheryl** [comment]
Noted thanks!
