### ISSUE TITLE
Clarification regarding feature freeze

### ISSUE THREAD

**Issue by pratham31012002** [nus-cs2103-AY2223S1/forum#378]
Are the following things allowed in v1.4?

- Changing feedback messages (especially error handling messages)
- Changing implementation of a function to make it more clean and/or efficient

**Comment by damithc** [comment]
@pratham31012002 

> * Changing feedback messages (especially error handling messages)

Only if the current message is incorrect i.e., there is a bug. Otherwise it would be just an enhancement to the behavior, not a bug fix.


> * Changing implementation of a function to make it more clean and/or efficient

Refactoring the code to improve the code quality is fine i.e., no change in external behavior

**Comment by pratham31012002** [comment]
Okay understood, thanks prof!
