### ISSUE TITLE
PPP meaning

### ISSUE THREAD

**Issue by Thing1Thing2** [nus-cs2103-AY2223S1/forum#38]
Minor issue, what does PPP mean here: 
![image](https://user-images.githubusercontent.com/93027319/185729960-86e931ff-c08d-41ad-9746-93bd267388c6.png)
Thank you

**Comment by kxrt** [comment]
It stands for `Project Portfolio Page` - more info here: https://nus-cs2103-ay2223s1.github.io/website/admin/tp-deliverables.html#deliverable-project-portfolio-page-ppp

**Comment by domlimm** [comment]
Hello @Thing1Thing2! I'm a senior from a previous batch, dropping by to look at the issues posted by you guys. Just a gentle reminder to close the issue once your query has been resolved. Have a great day! 😄
