### ISSUE TITLE
Enquiry about v1.4

### ISSUE THREAD

**Issue by xhphoong** [nus-cs2103-AY2223S1/forum#381]
Hi , may I ask if 

1. I not able to add a test for the new feature, can I add the test for the new feature at v1.4? and if I find bug when writing the test code, can I fix the new feature? 
2. Can I create new class such as a manager class to manage something to reduce code duplication in different classes in v1.4 or like create new method to shorten another method length in v1.4? 

Thank you!

**Comment by damithc** [comment]
@xhphoong 
1. Yes, you can add tests, and fix bugs you find (but only if they are strictly bugs).
2. Yes, you can refactor code.

More info https://nus-cs2103-ay2223s1.github.io/website/schedule/week12/project.html#tp-mid-v1-4

**Comment by xhphoong** [comment]
Thank you! @damithc
