### ISSUE TITLE
Clarification on v1.3's deadline

### ISSUE THREAD

**Issue by kxrt** [nus-cs2103-AY2223S1/forum#385]
Does v1.3 end at 10am or at 3pm today? 

If the latter, are we allowed to play around with UI/features up until 3pm and close v1.3 then? I'm aware the mock PE will be based on the jar released by 10am, however.

**Comment by damithc** [comment]
@kxrt The feature freeze takes effect with the release of the JAR. But you can do other v1.3 stuff (e.g., issue tracker housekeeping) until 4pm.

**Comment by kxrt** [comment]
Thanks prof! @damithc

**Comment by nehcuy** [comment]
Hi prof, just to clarify, if we have changes to UI that was under v1.3, is it still possible to push these changes?

**Comment by damithc** [comment]
> Hi prof, just to clarify, if we have changes to UI that was under v1.3, is it still possible to push these changes?

@nehcuy Normally, no, unless it was a bug fix. Email me if there is special circumstance that you think justify a late submission.

**Comment by nehcuy** [comment]
@damithc Alright prof, I have sent you an email regarding this. Thanks!
