### ISSUE TITLE
Clarification on Constraint-Typing-Preferred

### ISSUE THREAD

**Issue by onepersonhere** [nus-cs2103-AY2223S1/forum#386]
Is it okay to use a GUI input for the help screen? This is so that all the commands are listed and the user is able to find the commands and not refer to the User Guide.
This is how it is implemented:
![image](https://user-images.githubusercontent.com/51043502/198421076-0d7c4b61-5144-4a25-bf48-e91dd0ab518b.png)

Thank you for your feedback!

**Comment by damithc** [comment]
@onepersonhere OK to use _some_ GUI integrations, provided the app as a whole is optimized for CLI users. More info https://nus-cs2103-ay2223s1.github.io/website/admin/tp-constraints.html#recommendation-cli-first

**Comment by onepersonhere** [comment]
Thanks prof!
