### ISSUE TITLE
Clarification of LumiNUS Week 11 Quiz Q29

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#387]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/13196670/198564665-a7a3a395-25fe-4297-ba81-6ac368ad8c20.png">

Test case heuristics are not exact hard-and-fast rules, hence I thought that in some cases it might be ok to test multiple invalid inputs. In fact, I have seen multiple invalid input values testing for AB3 so as to enforce which particular invalid error message will be returned.

When the question was asked, is the intended context 'based on only heuristics covered in the textbook'?

**Comment by damithc** [comment]
> When the question was asked, is the intended context 'based on only heuristics covered in the textbook'?

Yes, @cheeheng 

And yes, it is not a strict rule and there are situations where you may want to use multiple incorrect inputs (at least no harm doing so).

**Comment by cheeheng** [comment]
Thanks prof. Perhaps it would be better to make the context more explicit for future semesters.
