### ISSUE TITLE
Use of external Java libraries in iP?

### ISSUE THREAD

**Issue by zbz-lvlv** [nus-cs2103-AY2223S1/forum#39]
Are we allowed to use external Java libraries in the iP? For example, I want to include something to process csv files.

**Comment by damithc** [comment]
@zbz-lvlv Yes, you can use external libraries in the iP, provided you package the library in the final .jar file (otherwise users will not be able to run the application). You can use Gradle to achieve that -- as you'll learn in the coming weeks.
