### ISSUE TITLE
Is this considered as a bug or a UI enhancement?

### ISSUE THREAD

**Issue by midnightfeverrr** [nus-cs2103-AY2223S1/forum#393]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/97276815/198866064-f0a11579-ca8b-4331-b87f-b39af158b0c3.png">

User cannot read task description when the description is too long. Our team is planning to use the 'Wrap text' for this issue. Is this allowed in v1.4?

**Comment by damithc** [comment]
@midnightfeverrr if this problem happens in normal usage  (i.e., not due to users inputting unusual/extreme inputs), you can fix it. The input in the screenshot seems like an 'extreme' input one wouldn't expect in normal usage.

**Comment by Nephelite** [comment]
@damithc What exactly constitutes as extreme input in this context? For my group, dates are appended at the end of the description, making it fairly likely that the user will overrun the box.

My group wants to enable line wrapping (and also mention that the user can resize the window if needed in the UG)

**Comment by damithc** [comment]
> @damithc What exactly constitutes as extreme input in this context? For my group, dates are appended at the end of the description, making it fairly likely that the user will overrun the box.
> 
> My group wants to enable line wrapping (and also mention that the user can resize the window if needed in the UG)

@Nephelite Based on the screenshot, this problem seems to occur when a word (not the entire description) is longer than the width of the card. If that is the case, would the user normally enter such super long words into the description? If the answer is no, we can consider it as an extreme situation.

**Comment by Nephelite** [comment]
@damithc Then in the case where our tP does not wrap lines even if there are multiple words, that is not an extreme situation and my team is allowed to fix it?

**Comment by midnightfeverrr** [comment]
@damithc 

<img width="249" alt="image" src="https://user-images.githubusercontent.com/97276815/198868255-2bbf7f93-bd3f-4f6a-ab9f-f9939657d4ad.png">

This problem will still occur when the description is long, even though it is not one super long word. Does this mean that my team can fix this (since this is a bug)?

**Comment by damithc** [comment]
> <img alt="image" width="249" src="https://user-images.githubusercontent.com/97276815/198868255-2bbf7f93-bd3f-4f6a-ab9f-f9939657d4ad.png">
> 
> This problem will still occur when the description is long, even though it is not one super long word. Does this mean that my team can fix this (since this is a bug)?

@midnightfeverrr Yes, if you expect the description to be longer than the display area under normal usage.
