### ISSUE TITLE
Are these issues considered UI bugs, and will fixing them be considered as enhancements?

### ISSUE THREAD

**Issue by melissaharijanto** [nus-cs2103-AY2223S1/forum#394]
Hello Prof, I would like to ask whether we are allowed to modify a few UI issues we received in our bug report:

1. There are extra panels (lines) when there is only one or two items in the list. They seem to appear after a user deletes the data in the `Orders` list. Are we allowed to modify the UI to remove this?
Link to issue: https://github.com/AY2223S1-CS2103T-W15-3/tp/issues/153

**With two items**
![image](https://user-images.githubusercontent.com/97304787/198868275-b7aedc9b-bb6b-4a7a-9757-5c6c6d3f0e3b.png)

**With one item**
![image](https://user-images.githubusercontent.com/97304787/198868283-27a712d5-a944-429e-964d-defdf52a070d.png)

2. Including many item tags will lead to less readability of the items. I believe this is not a test of extreme inputs, and can be changed by setting `HBox` to `FlowPane` instead. Will this modification be allowed?
Link to issue: https://github.com/AY2223S1-CS2103T-W15-3/tp/issues/164
![image](https://user-images.githubusercontent.com/97304787/198868707-57a1baef-080a-43f2-b513-338a3e7aa09d.png)

**Comment by damithc** [comment]
@melissaharijanto 
1. First one is clearly a bug, and can be fixed.
2. This one is less clear cut, but looks like the tags appearing in vertical orientation can be considered an 'incorrect' behavior and can be considered a bug.

**Comment by melissaharijanto** [comment]
Thank you for the confirmation, prof!
