### ISSUE TITLE
Reusing Minecraft assets in AB3?

### ISSUE THREAD

**Issue by zbz-lvlv** [nus-cs2103-AY2223S1/forum#395]
Hi guys, are we allowed to reuse 3rd party assets when they have been mentioned to be available for non-commercial reuse? Our program is not a independently created mod.

From [Mojang's website](https://www.minecraft.net/en-us/terms), under the `Brand and Asset Guidelines section`:
> We are also quite relaxed about other non-commercial things so feel free to create and share videos, screen shots, independently created mods (that don't use any of our Assets), fan art, machinima, etc.

We have used some of Minecraft's textures, fonts and a computer graphic of a creeper in our program.

**Comment by damithc** [comment]
@zbz-lvlv It is fine if the license allow it (you are responsible for ensuring this), but do acknowledge the reuse in the appropriate places (e.g., in the DG).
