### ISSUE TITLE
Set minimum window size?

### ISSUE THREAD

**Issue by onepersonhere** [nus-cs2103-AY2223S1/forum#396]
![image](https://user-images.githubusercontent.com/51043502/198872035-5ffd7ded-a4e4-4fca-96d2-646cd6e1f188.png)

Can we set a minimum window size? (Also what is the recommended minimum size)
This is to address this form of bug reports so as to prevent them from appearing in the PE. Not really sure if it is considered a feature flaw since the string is not that long (it's just the window being too small!)

**Comment by damithc** [comment]
> Can we set a minimum window size? (Also what is the recommended minimum size)
> This is to address this form of bug reports so as to prevent them from appearing in the PE. Not really sure if it is considered a feature flaw since the string is not that long (it's just the window being too small!)

@onepersonhere While it is good to accommodate small Window sizes, it if fine for you to decide that it is a 'nice to have' feature that will be implemented in a future version. Hence, it is not a bug, provided it doesn't affect typical usage.

**Comment by onepersonhere** [comment]
Thanks prof!
