### ISSUE TITLE
UG Draft is not captured accurately

### ISSUE THREAD

**Issue by onepersonhere** [nus-cs2103-AY2223S1/forum#397]
![image](https://user-images.githubusercontent.com/51043502/198876083-845709b3-3f7e-4cfc-82fe-eadc42b1de76.png)
This is reflected in the tP progress Dashboard even though I have added more than 3 lines to the UG in week 11.
Will I be penalised in terms of grade?

**Comment by damithc** [comment]
@onepersonhere cross-check with the tP code dashboard. As of now, it's showing only one (empty) line. Perhaps someone else updated those lines after you, transferring the authorship to that person?

![image](https://user-images.githubusercontent.com/1673303/198879836-6a1517a4-f20f-4437-a20e-b3858ac5f329.png)

See https://nus-cs2103-ay2223s1.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking to find how to override the authorship auto-detected by RepoSense.

**Comment by onepersonhere** [comment]
Hi prof @damithc, I checked the RepoSense according to this [link](https://nus-cs2103-ay2223s1.github.io/tp-dashboard/?search=onepersonhere&sort=groupTitle&sortWithin=title&timeframe=day&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=docs&since=2022-10-22&tabOpen=true&tabType=zoom&until=2022-10-28&zFR=false&zA=onepersonhere&zR=AY2223S1-CS2103T-T10-4%2Ftp%5Bmaster%5D&zACS=4&zS=2022-10-22&zFS=onepersonhere&zU=2022-10-28&zMG=false&zFTF=day&zFGS=groupByRepos): 


![image](https://user-images.githubusercontent.com/51043502/198883002-d70a1706-3791-491f-8081-2153d145d521.png)

I think my teammate has overridden my commit according to the commit history, however the RepoSense seems to detect it but not the dashboard script? (not really sure how it works)

Is there a possible way to fix it on my side since I can't find a way to assign the @@author tag in markdown for UG?

**Comment by damithc** [comment]
> I think my teammate has overridden my commit, however the RepoSense seems to detect it but not the dashboard script?
> 

@onepersonhere yes, the commit it detected. However, RepoSense assigns a line to whoever edited it last. So, if someone else edited those lines after your edited them, that person will be assigned as the author of those lines.

> Is there a possible way to fix it on my side since I can't find a way to assign the @@author tag in markdown for UG?

Markdown files are compatible with HTML comment syntax. So, `<!-- @@author onepersonhere -->` should work.

**Comment by onepersonhere** [comment]
Thanks prof! I will try it out hopefully RepoSense will detect it.

**Comment by onepersonhere** [comment]
Hi prof @damithc , 
I added the @@author tag and the RepoSense is able to assign the lines to me:
![image](https://user-images.githubusercontent.com/51043502/199020405-7f922403-d2c3-4d42-ad97-125d56af85b0.png)

However, I waited after the daily refresh of the tP progress dashboard but it still says the same thing unfortunately :(
![image](https://user-images.githubusercontent.com/51043502/199020943-25c3d60b-02c0-432f-b96b-c5490a9ae644.png)

Is there a way to fix the tag on the tP progress dashboard?

**Comment by damithc** [comment]
@onepersonhere technically, it will remain red as the item is auto-detected based on the code at its deadline (which didn't have `@@author` tags, not the current code). I've changed it manually to green.

**Comment by onepersonhere** [comment]
Thanks prof!

**Comment by EmilyOng** [comment]
Hi Prof @damithc, could I check with you about the detection of PPP draft?

> However, RepoSense assigns a line to whoever edited it last. So, if someone else edited those lines after your edited them, that person will be assigned as the author of those lines.

I have added a commit which contains >5 lines at https://github.com/AY2223S1-CS2103T-W17-2/tp/commit/f7e957c1d90f3ae5defb9ab8ee6e1e79c1ddb61f on last Thursday, but the result is not captured on the TP dashboard. There were no others who override my lines too. Thanks!

**Comment by damithc** [comment]
> I have added a commit which contains >5 lines at [AY2223S1-CS2103T-W17-2/tp@f7e957c](https://github.com/AY2223S1-CS2103T-W17-2/tp/commit/f7e957c1d90f3ae5defb9ab8ee6e1e79c1ddb61f) on last Thursday, but the result is not captured on the TP dashboard. There were no others who override my lines too. Thanks!

@EmilyOng did you mean the `PPP Draft` item? It is based on the code that there in your master branch at Friday 4pm deadline. Perhaps your commit ~~wasn't~~ was merged to master later than that deadline?

**Comment by EmilyOng** [comment]
I see, thanks!
