### ISSUE TITLE
Code reuse declaration form points to wrong semester

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#398]
Code reuse declaration form points to wrong semester, it should be AY22/23 Semester 1 instead.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/13196670/198876193-8d377634-00d1-4513-915d-cf777200c738.png">

**Comment by damithc** [comment]
Oops. Fixed. Thanks for the bug report @cheeheng

**Comment by cheeheng** [comment]
I did not see the fix. Did you change the wrong survey, prof?

**Comment by damithc** [comment]
> I did not see the fix. Did you change the wrong survey, prof?

Try now. Probably didn't save last time.

**Comment by cheeheng** [comment]
It's correct. Thanks prof for fixing the bug.
