### ISSUE TITLE
Bug: number of stars do not match

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#4]
In this website: [https://nus-cs2103-ay2223s1.github.io/website/schedule/week2/project.html](https://nus-cs2103-ay2223s1.github.io/website/schedule/week2/project.html)

Scroll down to the following appendix, which is labelled as 4 stars on the header, but the content shows 2 stars.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/13196670/184499478-154980c8-927b-4da2-a39d-9ef4e6dddade.png">

**Comment by damithc** [comment]
Good catch, @cheeheng Thanks for reporting it. Fixed.
