### ISSUE TITLE
Can we amend commits but maintain the same SHA id?

### ISSUE THREAD

**Issue by onepersonhere** [nus-cs2103-AY2223S1/forum#40]
I encountered this problem whereby I tagged the unamended, unpushed commit with a tag, then I amend the commit, causing it to disappear on github desktop.
 
Afterwards I tried to tag the amended commit but was unsuccessful because the tag was assigned to the original commit. 

I was able to delete the original tag and the unamended commit through Git Bash, however I felt that this is too much work for just amending a single commit and expecting the tag to be retagged on it.

Therefore, I was wondering if there is any commands/ways where we can change the title/description of the commit without changing the SHA of the commit?

**Comment by RussellDash332** [comment]
The question is answered [here](https://stackoverflow.com/questions/23791999/why-does-git-commit-amend-change-the-hash-even-if-i-dont-make-any-changes).

However, you can force push the tags because they are just your own bookmarks for the project, and just add a new commit instead of overwriting the previous one.
```
git tag -f Level-x
git push -f --tags
```
(assuming you only want to change the tag)

**Comment by onepersonhere** [comment]
> The question is answered [here](https://stackoverflow.com/questions/23791999/why-does-git-commit-amend-change-the-hash-even-if-i-dont-make-any-changes).
> 
> However, you can force push the tags because they are just your own bookmarks for the project, and just add a new commit instead of overwriting the previous one.
> 
> ```
> git tag -f Level-x
> git push -f --tags
> ```
> 
> (assuming you only want to change the tag)

Hi. Does the answer suggests that the only way to change the title or description of the commit is to create a new commit with a different timestamp?

**Comment by RussellDash332** [comment]
> Hi. Does the answer suggests that the only way to change the title or description of the commit is to create a new commit with a different timestamp?

You mean the same timestamp, in order not to change the commit ID? I believe so.

**Comment by onepersonhere** [comment]
> > Hi. Does the answer suggests that the only way to change the title or description of the commit is to create a new commit with a different timestamp?
> 
> You mean the same timestamp, in order not to change the commit ID? I believe so.

Ah I see thanks.
