### ISSUE TITLE
Minor issues on Week 12 Project page

### ISSUE THREAD

**Issue by RussellDash332** [nus-cs2103-AY2223S1/forum#400]
- Duplicate QnA as seen in the image below.
  ![image](https://user-images.githubusercontent.com/63991775/198904499-bc8a9806-300f-43f3-bcc1-77442118e7eb.png)

- This should be "all (or almost all) the PE-D **bugs**" instead.
  ![image](https://user-images.githubusercontent.com/63991775/198904537-3e5d75fd-630f-423e-a955-6e88c9656077.png)

**Comment by damithc** [comment]
@RussellDash332 thanks for the bug report. Fixed.
