### ISSUE TITLE
To fix or not? Bug that is also a UI issue

### ISSUE THREAD

**Issue by Thing1Thing2** [nus-cs2103-AY2223S1/forum#402]
We have some confusion if a bug we have can be addressed in v1.4 since it falls under being a UI issue as well.

In our user guide, we stated that a client's **address** should be shown after executing a command.
However, our implementation does not show a client's **address** after executing that command.
Fixing this issue will cause a minor change to UI, which is not allowed.

Should we continue with the fix or drop it?

**Comment by damithc** [comment]
@Thing1Thing2 If the feature was actually implemented in the UI but was buggy, you can fix it. But if it was left out entirely from the UI, we can consider it a UG bug and rectify the UG.
Would that work?

**Comment by Thing1Thing2** [comment]
Yes, that would work ... thank you for the clarification!
