### ISSUE TITLE
Is this considered a bug or an enhancement?

### ISSUE THREAD

**Issue by pratham31012002** [nus-cs2103-AY2223S1/forum#403]
We allow users to create different categories (for eg. Education, Grade, Skills, etc.) for all persons in the addressbook, and the user can add information under these categories for any person.
However, currently there is no way to see the names of all categories created i.e. the only way for them to see the categories created is by going to the json file (which is not ideal or expected from the user).
This was reported as a feature flaw during the PED and we were wondering if we are allowed to display the names of the categories created in the welcome message or somewhere.

**Comment by damithc** [comment]
@pratham31012002 this is a case of 'missing feature' and adding it now goes against the feature-freeze. Perhaps you can document clearly in the UG how to find the category list, to mitigate the situation. You can also mention that a way to view the list of categories will be added in a future version.

**Comment by pratham31012002** [comment]
Okay thank you prof!
