### ISSUE TITLE
Are we allowed to make changes to these UI components that could possibly be bugs?

### ISSUE THREAD

**Issue by fannyjian** [nus-cs2103-AY2223S1/forum#405]
1. Can I make changes to the css and javafxml files as some styles are causing warning messages to be displayed in the terminal?
<img width="564" alt="Screenshot 2022-11-01 at 11 06 21 AM" src="https://user-images.githubusercontent.com/97325835/199149964-e9a77945-01d1-47a8-880d-49b9b4de2373.png">

2. As there were bugs reported in PED that the help table was unclear, we were wondering if we could change it too?
<img width="544" alt="Screenshot 2022-11-01 at 11 07 34 AM" src="https://user-images.githubusercontent.com/97325835/199150089-f5d10f9e-1cd9-478b-a401-5cb60f3905eb.png">

**Comment by damithc** [comment]
@fannyjian 
1. Should be fine, provided the changes is limited to getting rid of the warning.
2. You are allowed to change the UG as you wish, but this help Window will have to remain the same for v1.4 (but can fix errors in the text).
