### ISSUE TITLE
Can I make the following UI change?

### ISSUE THREAD

**Issue by fannyjian** [nus-cs2103-AY2223S1/forum#406]
Hi Prof, can I also ask if I am allowed to make changes to the UI as the copy button (on the bottom left of the screen) was truncated in v1.3 and was reported as a bug?
![image](https://user-images.githubusercontent.com/97325835/199152514-202b854f-dd23-4ad9-b1cf-0c4101f984cf.png)

**Comment by damithc** [comment]
> Hi Prof, can I also ask if I am allowed to make changes to the UI as the copy button (on the bottom left of the screen) was truncated in v1.3 and was reported as a bug?
> ![image](https://user-images.githubusercontent.com/97325835/199152514-202b854f-dd23-4ad9-b1cf-0c4101f984cf.png)

@fannyjian Yes, this can be allowed.
