### ISSUE TITLE
Does code quality (length) matter for test cases?

### ISSUE THREAD

**Issue by nitant-p** [nus-cs2103-AY2223S1/forum#409]
I have some test cases that perform a general test on each field.

This test was already present in AB3, but there were only 3 to 4 fields. Now we have over 10 fields and the test method is quite long.

Will test cases be considered when marking code quality?

**Comment by damithc** [comment]
@nitant-p Should be fine. We don't check the length of test methods.

**Comment by nitant-p** [comment]
@damithc Thank you prof!
