### ISSUE TITLE
Unable to retake in-video quiz for W3.5b

### ISSUE THREAD

**Issue by Bubbl3T** [nus-cs2103-AY2223S1/forum#41]
There seems to be a problem with trying to retake the quiz for questions in the video under the topic W3.5b. Is this intentional or just a bug?

![image](https://user-images.githubusercontent.com/72196376/185751381-7e199b6d-681d-44f5-8077-e9590067dca9.png)

**Comment by damithc** [comment]
@Bubbl3T I've updated the quiz setting to allow retaking.
