### ISSUE TITLE
Are we allowed to make changes to components that could potentially have a bug?

### ISSUE THREAD

**Issue by TheSoggy** [nus-cs2103-AY2223S1/forum#410]
1. When we merged the pull request that changed the GUI, we intended for the GUI to keep track of the user's expanded tab. All our commands are currently implemented such that after execution, the previous list is kept so we thought that the the list (including expansions) will continue to be kept. <br>
We did not expect that when a command is entered, it would reset the tabs and close all of them. We had a pull request to fix this at 28 Oct 12pm, which was after the v1.3 jar deadline. Can this be considered a bug even though we did not explicitly state what the intended behavior of the component would be? <br>
![image](https://user-images.githubusercontent.com/8470009/199199389-01b56b5f-071f-4dfb-a82e-7f9f39e41ce6.png)

1. Before we updated the GUI in the pull request, there was a "No Debts" placeholder in our simple text UI. But after we updated the UI, the placeholder was no longer available. Would this be considered as a bugfix to fix the functionality that was available in our v1.3 demo and unintentionally missing in v1.3.2 after we updated the GUI?
![image](https://user-images.githubusercontent.com/8470009/199201708-abe2ceb8-9fe0-4dbc-ab93-71516e38d986.png)
![image](https://user-images.githubusercontent.com/8470009/199203151-54d10472-e4da-4f6a-bceb-1f8eec82b08d.png)

1. Is updating a error message when the error message is being used on a wrong error counted as correcting a misbehaviour? Currently when we catch a invalid date it says "Dates should be in yyyy-mm-dd" instead of "That's not a valid date".  <br>
![image](https://user-images.githubusercontent.com/8470009/199200634-cb361116-8eaa-4070-b8f0-274c712cea57.png)

**Comment by damithc** [comment]
@TheSoggy 
1. Please give the link to the following PR
   > We had a pull request to fix this at 28 Oct 12pm, which was after the v1.3 jar deadline. 
2. Looks like a regression bug. Can fix.
3. This is tricky, as it can be argued as increasing the specificity of the error message rather than a bug fix. Perhaps you can change the error message to `valid dates in yyyy-mm-dd format ...` so that the error message is now correct but not more specific than before.

**Comment by TheSoggy** [comment]
@damithc Here you go: https://github.com/AY2223S1-CS2103T-W13-3/tp/pull/206. We had already merged a fix but are now worried if it violates anything so we will revert the merge if its not allowed.

**Comment by damithc** [comment]
> @damithc Here you go: [AY2223S1-CS2103T-W13-3/tp#206](https://github.com/AY2223S1-CS2103T-W13-3/tp/pull/206). We had already merged a fix but are now worried if it violates anything so we will revert the merge if its not allowed.

Looks like you had already identified them as bugs even before the PE-D. So, can allow to be fixed.
