### ISSUE TITLE
Are input validations catching visually similar symbols with a different unicode a bug? And if so can we modify the error message to include more details?

### ISSUE THREAD

**Issue by yixiann** [nus-cs2103-AY2223S1/forum#411]
This is with reference to : https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/397

In a more extreme case

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/78332456/199273149-af36e57b-aaf6-45e2-9d26-eed816a5810f.png">

V.S.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/78332456/199272297-973f61b8-6303-4a8f-9f9e-79e68685fbdb.png">

Our application current is able to differentiate both symbols but it looks like a bug. 

<img width="923" alt="image" src="https://user-images.githubusercontent.com/78332456/199273238-e1879ca9-d9b9-4a89-a863-7238b6198da4.png">

Are we then allowed to modify the error message as such:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/78332456/199273399-bc2aa749-a7e9-4b5b-8d30-29afbd24f29b.png">

**Comment by RichDom2185** [comment]
I think to clarify, there are 2 areas of improvement:
* UG: Make it more clear that `(` and `（` different characters, and provide a troubleshooting step to diagnose this potential source of the error message showing up, especially when copying text from external sources
* JAR file: Update the error message to also provide a troubleshooting step.

I think it's clear that the first point is a UG bug and can be addressed (but we would still like your clarification to be sure). However with regards to the second point, technically speaking, our code worked correctly and caught the unaccepted character, and displayed the correct corresponding error message. So we felt that adding additional paragraphs to the error message may constitute an "enhancement", not a bug fix, so we would like to clarify on whether this is allowed. Thank you prof!

**Comment by damithc** [comment]
@RichDom2185 @yixiann For v1.4, you guys can update the UG with these additional details. Updating the error message will be an enhancement (as you feared), so, it needs to postponed to a subsequent version.

**Comment by RichDom2185** [comment]
Noted, thanks Prof!

**Comment by yixiann** [comment]
Thank you prof!
