### ISSUE TITLE
Is adding extra input checks considered a change to the feature?

### ISSUE THREAD

**Issue by crvstalphua** [nus-cs2103-AY2223S1/forum#414]
In the recent PE-D, there was a bug reported for my group where our application would not take in an ID input that is beyond our list index. The command simply wont run (you cannot click enter). For example, something like the case below.
I was wondering if adding checks within the classes, to check for invalid id and throw an exception, was allowed? or whether it's considered changing the feature. 

![image](https://user-images.githubusercontent.com/89404671/199492805-7b828c3c-3c2f-437e-ad0c-be8fe8b37780.png)

**Comment by damithc** [comment]
@crvstalphua Not providing _any_ information about the problem to the user can be considered an 'incorrect' behavior. So, a fix can be allowed.
