### ISSUE TITLE
Is this a case of buggy feedback message?

### ISSUE THREAD

**Issue by Aishwarya-Hariharan-Iyer** [nus-cs2103-AY2223S1/forum#415]
Good evening,
We were wondering if making the following modification to the displayed feedback message is part of bug-fixing or an enhancement: 
While the addition of exact clients as ones present on the list is not allowed, we can add a client with the same name, email, and phone as a client on the list but under a different project. (Each client has a list of projects and each project has exactly one client)
As was noticed in the PE-D, this addition still gives the success message "New client added: ---" when in fact no new item is shown on the client list but the projects shown under the specified client are changed to include the latest addition as well. 
In this case, can we change the feedback message as it is incorrect?
Thank you!

**Comment by damithc** [comment]
> "New client added: ---" when in fact no new item is shown on the client list but the projects shown under the specified client are changed to include the latest addition as well.

@Aishwarya-Hariharan-Iyer This can be considered as showing incorrect information. A fix can be allowed.

**Comment by Aishwarya-Hariharan-Iyer** [comment]
Thank you Prof @damithc!
