### ISSUE TITLE
Are new error messages allowed in bug-handling?

### ISSUE THREAD

**Issue by Yongbeom-Kim** [nus-cs2103-AY2223S1/forum#416]
I am asking the question with respect to this issue:

https://github.com/AY2223S1-CS2103-F13-1/tp/issues/195

Our AddressBook identifies object by an integer ID, and it seems that there is a bug where if there is an ID with value MAX_INT, and another object is added, the app adds an ID with MAX_INT+1, and on next load, the app throws away the save file (since it's overflowed to negative now).

```json
{
  "projects" : [ {
    "name" : "Individual Project",
    "repository" : "johndoe/ip",
    "deadline" : "2022-03-03",
    "client" : {
      "name" : "Alex Yeoh",
      "mobile" : "87438807",
      "email" : "alexyeoh@example.com",
      "clientId" : "1",
      "projects" : [ ],
      "pin" : "false"
    },
    "issues" : [ ],
    "projectId" : "2147483647",
    "pin" : "false"
  } ],
  "issues" : [ ]
}
```
![image](https://user-images.githubusercontent.com/63487502/199641249-20b48213-030b-4707-ab1d-c971640557fc.png)

This is definitely unintended behaviour, so I'd argue that it is a bug.

But to which extent are we allowed to fix this? I'm seeing some 'partial' fixes:
- We can simply throw an error with no feedback to user (logged to console) - in this case UG will be updated to reflect the bug
- We can throw an error with a new error message to user - but is the new error message considered 'adding' a feature?

**Comment by damithc** [comment]
@Yongbeom-Kim Not error-handling an invalid input is a bug, and can be allowed to fix anyway you want.
Also, if this can be considered an extreme situation that will not happen unless the user deliberately sabotages the application, you can even leave it as is.

**Comment by Yongbeom-Kim** [comment]
Ah I see, thank you for the input - I think it can definitely be considered an extreme situation, but I've written a fix for it anyways, so I guess it will be fixed 🤷
