### ISSUE TITLE
Class diagram question about multiple instances for 2 variables.

### ISSUE THREAD

**Issue by zbz-lvlv** [nus-cs2103-AY2223S1/forum#417]
How to indicate in a class diagram a scenario like this?
`C` can have `0..*` of `A`, `0..*` of `B`, but must have at least one of either `A` or `B` present?

So the only illegal scenario is having 0 `A` and 0 `B`.

**Comment by damithc** [comment]
@zbz-lvlv When the standard multiplicity notation is not enough, you can add a UML note to provide additional information.
