### ISSUE TITLE
Optional parameters not displayed in Command Error Message

### ISSUE THREAD

**Issue by crvstalphua** [nus-cs2103-AY2223S1/forum#418]
For my groups application, when there is an invalid command format error, we display an error message which shows the correct format of the command (e.g. project -a n/NAME d/DEADLINE). However, for some of the commands, some of the parameters are optional and we have displayed that in our ug (e.g. project -a n/NAME [d/DEADLINE]), but missed that out in the error message.

Since the parameter should be optional and not putting the brackets [] would be considered providing incorrect information, is this considered an error and can thus be edited and fixed?

**Comment by damithc** [comment]
> Since the parameter should be optional and not putting the brackets [] would be considered providing incorrect information, is this considered an error and can thus be edited and fixed?

@crvstalphua Yes, this is a bug. Allowed to fix in v1.4

**Comment by crvstalphua** [comment]
Okay thank you!
