### ISSUE TITLE
Requesting confirmation on whether this is an enhancement

### ISSUE THREAD

**Issue by Aishwarya-Hariharan-Iyer** [nus-cs2103-AY2223S1/forum#419]
Good evening Prof,
In our product, a bug reported was that if `project -e p/1 m/12345678` is entered, it throws an error saying that the Project ID (`p/PROJECT_ID`) must be a positive integer (`m/` is an invalid prefix for this command). It seems that it parses `1 m/12345678` as part of the arguments for `p/`. ([Issue: #181](https://github.com/AY2223S1-CS2103-F13-1/tp/issues/181))
We documented this as part of the UG mentioning that everything after the last valid prefix (here, `p/`) shall be parsed as part of that prefix. Here, we felt that the error message is not exactly wrong as it parses all invalid flags at the tail end of the input to be a part of the arguments of the last valid prefix.
A few alternatives we came up with were:
1. Special error messages for invalid prefixes in the command that are valid in some other command for the product. (e.g. `m/` is used in client commands)
2. Parse only the first or so words for the index prefixes.

However, after reading forum post #392, we were worried that these two approaches shall be considered feature enhancements instead.
Could we please seek guidance on the same?
Thank you.

**Comment by damithc** [comment]
> We documented this as part of the UG mentioning that everything after the last valid prefix (here, `p/`) shall be parsed as part of that prefix.

@Aishwarya-Hariharan-Iyer Was this done before the PE-D or after?

**Comment by Aishwarya-Hariharan-Iyer** [comment]
Prof @damithc, After PE-D because we were not sure if we are allowed to fix it without it being considered an enhancement. However, we can fix it using either of the alternates, whichever is allowed, if it's permitted as part of v1.4.
Moreover, it also seems to be general to other prefixes - not just index prefix - and thus seems to be a behavior. For example, `project -a n/Name t/invalid prefix` would parse everything after `n/` as part of the Name argument. Nonetheless, we are not sure if documentation is justified in this case, as re-reading this now, it seems like the documentation is explaining/justifying a behavior that is potentially buggy.

**Comment by damithc** [comment]
@Aishwarya-Hariharan-Iyer In a case like `project -e p/1 m/12345678`, the normal user expectation is to use `1` as the value of `p` (as it is supposed to be a one-word value). So, the current parser behavior can be considered incorrect. In other words, while the current error message is correct from the parser's point of view, it is not correct from the user's point of view. Therefore, we can allow a fix.

**Comment by Aishwarya-Hariharan-Iyer** [comment]
Noted Prof.! Thank you so much!
