### ISSUE TITLE
Would the following issues be considered bugs and the proposed fixes valid bug fixes?

### ISSUE THREAD

**Issue by xinbei-shen** [nus-cs2103-AY2223S1/forum#420]
1. Currently, in the case there is integer overflow for the index number, our application will display an incorrect error message. For this issue, the website states that 

> A product is allowed to have 'known limitations' (e.g., a daily expense tracking application meant for students is unable to handle expenses larger than $999) as long as they don't degrade the product's use within the intended scope.

Would it be considered a bugfix to change the error message (by changing how the index is parsed) that is shown upon identifying an index that is too large? Or would it be sufficient to mention this limitation in our user guide?

2. As our application allows for profiles to have the same name with the exact same spelling and capitalization, this causes ambiguity when adding profiles with the same name to the same event. An example is shown below:

<img width="589" alt="Screenshot 2022-11-03 at 6 51 53 PM" src="https://user-images.githubusercontent.com/90245904/199706825-789472cd-2604-43c0-8853-4871006293db.png">

Would it be allowed to change the UI such that a distinguishing field is shown beside the names, such as the phone number of the profile?

3. This issue is similar to the first one. Another bug we noticed is that the phone number in the UI is truncated when users enter a very long phone number. Again, the website states that 

> Only if the behavior hinders normal usage i.e., not showing the text fully/properly under normal usage can be considered an 'incorrect' behavior, and hence, a bug.

May I know if we need to clarify what we consider "normal usage"? And if so, can we clarify it via error messages i.e. changing the parsing of phone numbers, or is the user guide sufficient?

4. Just to double confirm, would the following bugfix be allowed? Currently, when the user enters an email of an incorrect local domain, this error message is shown

> The local-part should only contain alphanumeric characters and these special characters, excluding the parentheses, (+_.-). The local-part may not start or end with any special characters.

However, our regex does not allow for consecutive special characters so we feel that our error message is incorrect and we would like to modify it.

**Comment by damithc** [comment]
@ichigh0st 
1. Either option is fine, if the index is not expected to reach such a high number under normal usage.
2. This lack of a distinguishing between duplicate entries hinders the user. So, a fix can be allowed.
3. Normal usage here is normal telephone numbers that users are expected to enter. Again, either option is fine.
4. An update to the error message can be allowed, as the current error message is not entirely accurate.

**Comment by xinbei-shen** [comment]
Thank you prof for the prompt reply. 😊
