### ISSUE TITLE
Queries about `PRODUCT_NAME`

### ISSUE THREAD

**Issue by ElginL** [nus-cs2103-AY2223S1/forum#424]
I have just seen the required files name format for submission. However, does the `PRODUCT_NAME` refer to the exact name within **tP Teams List**?

Because our team have changed the product name to deviate away from what is listed in the tp Teams List. Furthermore, how do we change the product name, target user, and value proposition in tp Teams List? I can't seem to find it anywhere.

**Comment by damithc** [comment]
@ElginL It should be a close match, if not an exact match. Please send me the new product name (and other details) so that I can update the team list.

**Comment by ElginL** [comment]
> @ElginL It should be a close match, if not an exact match. Please send me the new product name (and other details) so that I can update the team list.

Hi prof, should I send it to you through email? Or which platform should I use to send the updated details?

**Comment by damithc** [comment]
> Hi prof, should I send it to you through email? Or which platform should I use to send the updated details?

@ElginL send via email.
