### ISSUE TITLE
Query on substituting long command input in DG diagrams with placeholder text

### ISSUE THREAD

**Issue by Ssatu** [nus-cs2103-AY2223S1/forum#425]
This query is about the use of placeholder text to substitute loooong commands in DG diagrams in order to increase readability.

Taking sequence diagrams for example, certain commands tend to clutter the limited space for method calls between objects as seen below.
![image](https://user-images.githubusercontent.com/69383469/200107911-4ff32944-685f-42a0-b633-8413034a8c16.png)

I would like to ask if it would go against any good practices to substitute the command text with something like `command details`
It would look something like this.
![image](https://user-images.githubusercontent.com/69383469/200107985-cf4cd507-3ba9-48a9-8538-4de95baa4ff6.png)

This would have to be accompanied by a small explainer on what it substitutes i.e.:
![image](https://user-images.githubusercontent.com/69383469/200108012-cec4a3a2-506c-4da6-a886-f38caf148c2a.png)

Hopefully this makes sense! Is this practice acceptable?

**Comment by damithc** [comment]
@Ssatu Yes, that's better than a cluttered diagram. Use something like `command_details` instead of `"command details"` (so that it doesn't appear like a String literal).
You can also use UML notes feature to add additional details to the diagram itself.
