### ISSUE TITLE
Are we allowed to change the format of the data file?

### ISSUE THREAD

**Issue by ConradLew** [nus-cs2103-AY2223S1/forum#426]
Is it allowed under the feature freeze to modify the data file into a more suitable format, since it does not change the external behaviour of the application?

**Comment by damithc** [comment]
> Is it allowed under the feature freeze to modify the data file into a more suitable format, since it does not change the external behaviour of the application?

@ConradLew Allowed. But proceed with caution, as the whole point of the feature freeze is to avoid introducing new bugs. Changing the data format might result in new bugs too.

**Comment by ConradLew** [comment]
Noted, thanks prof!
