### ISSUE TITLE
Overlapping arrows and lines in PlantUML generated diagram

### ISSUE THREAD

**Issue by seanmanik** [nus-cs2103-AY2223S1/forum#427]
Are overlapping arrows and lines as seen in this diagram a valid bug to report? If so, what are some ways we can consider to prevent this? (I've tried to extend certain arrow lengths, but that leads to the entire diagram being very messy)
![UiClassDiagram](https://user-images.githubusercontent.com/52826683/200128261-ac11298c-f981-4bb0-b205-144b9e5831f9.png)

**Comment by damithc** [comment]
@seanmanik It's not always possible to get the exact layout you want with PlantUML. 
Keeping that restriction in mind, overlapping lines in not necessarily a bug unless it makes the diagram ambiguous or misleading. 
Some PlantUML tips/tricks https://se-education.org/guides/tutorials/plantUml.html#tips-and-tricks
Using different colors might help to differentiate between overlapping lines too.

**Comment by ee-suan** [comment]
Not sure if it will work here, but I managed to declutter the arrows pointing to UiPart by specifying direction of a newly added class as 'up'

**Comment by seanmanik** [comment]
> @seanmanik It's not always possible to get the exact layout you want with PlantUML. Keeping that restriction in mind, overlapping lines in not necessarily a bug unless it makes the diagram ambiguous or misleading. Some PlantUML tips/tricks https://se-education.org/guides/tutorials/plantUml.html#tips-and-tricks Using different colors might help to differentiate between overlapping lines too.

Thank you for the response

**Comment by seanmanik** [comment]
> Not sure if it will work here, but I managed to declutter the arrows pointing to UiPart by specifying direction of a newly added class as 'up'

Thank you for the tip, it helped to declutter the diagram a bit.
