### ISSUE TITLE
Upgrading JavaFX version

### ISSUE THREAD

**Issue by RichDom2185** [nus-cs2103-AY2223S1/forum#428]
Are we allowed to upgrade JavaFX to the latest version (17)?

Context: There is a GUI scaling/rendering issue when testing on Linux (Wayland) that is fixed simply by updating the version of JavaFX that is packaged.

Thank you!

**Comment by damithc** [comment]
@RichDom2185 If the 'scaling/rendering issue' hinders the user (e.g., some information on the UI cannot be seen), you can fix it using JavaFX upgrade or some other means. But it's not allowed if you are simply enhancing the UI to make it look better when resized.

**Comment by RichDom2185** [comment]
Noted Prof, thank you!
