### ISSUE TITLE
Bug: Number of stars do not match

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#43]
On this webpage (which was in Week 12 but I found it while searching for code reuse policy) [https://nus-cs2103-ay2223s1.github.io/website/schedule/week12/admin.html#policy-on-reuse](https://nus-cs2103-ay2223s1.github.io/website/schedule/week12/admin.html#policy-on-reuse), I found another case where the number of stars of the headers do not match.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/13196670/185759076-eef859ff-2c1a-4a87-92a3-605ddbf08cd7.png">

**Comment by damithc** [comment]
Thanks for the bug report, @cheeheng 
Fixed.
