### ISSUE TITLE
How to export colorful version of activity diagram (Plant UML)?

### ISSUE THREAD

**Issue by april-anh** [nus-cs2103-AY2223S1/forum#430]
The color scheme in my `.pulm` is gray when I use `save diagram` I get the same picture in `png` format. I wonder how I can expert it to the colorful scheme `.png` file (red, yellow same as the one given in AB3)

Current:
![image](https://user-images.githubusercontent.com/88279850/200242743-d6832414-ca9b-4c10-ab52-929f8ea14b80.png)

What I need:
![image](https://user-images.githubusercontent.com/88279850/200242839-f9b35b20-c866-4e75-b775-618a484064fe.png)

**Comment by damithc** [comment]
@april-anh The yellow/red used to be the default colors in earlier versions of PlantUML that AB3 used. Perhaps they changed that in the new version. It's fine to use the current default colors for your PlantUML diagrams if you can't find a way to change it.

**Comment by april-anh** [comment]
Thanks, Prof!
