### ISSUE TITLE
Clarification on bug fixes VS enhancement

### ISSUE THREAD

**Issue by EmilyOng** [nus-cs2103-AY2223S1/forum#431]
# Issue

Currently, in our application, issuing a successful `view` command displays the `Show graphically all expenditure by category` in the command result display.

![Screenshot 2022-11-07 at 6 05 24 PM](https://user-images.githubusercontent.com/21200681/200283063-6f804a0b-6388-4f78-9174-82d27cc82a2f.png)

As users are able to toggle to another tab by means of clicking as well, the command result display is not refreshed and remains at `Show graphically all expenditure by category`.

![Screenshot 2022-11-07 at 6 06 01 PM](https://user-images.githubusercontent.com/21200681/200283224-68eba8fc-6268-4ba5-b49e-db9de9572bdc.png)

# What we think

1. This is a hindrance to the user because they can be confused by the wrong visual feedback provided in the command result box. Thus, we want to update the text in the command box to `Show graphically all income by category` (which is an existing message for `view` command if viewing income entries). Is this considered a violation of feature freeze?
2. When there is no entry found in the application, the size for the list panel enlarges, which is an inconvenience to the user. Can we resize the list panel back to its supposed size?

![Screenshot 2022-11-07 at 6 16 46 PM](https://user-images.githubusercontent.com/21200681/200285788-a3d9bce3-4f26-4990-939d-03a57bd78bc5.png)

**Comment by damithc** [comment]
@EmilyOng

> * This is a hindrance to the user because they can be confused by the wrong visual feedback provided in the command result box. Thus, we want to update the text in the command box to `Show graphically all income by category` (which is an existing message for `view` command if viewing income entries). Is this considered a violation of feature freeze?

If one part of the UI shows information that is inconsistent with another part, it can be considered a bug. So, OK to fix.

> * When there is no entry found in the application, the size for the list panel enlarges, which is an inconvenience to the user. Can we resize the list panel back to its supposed size?

This is a cosmetic enhancement, as the current UI doesn't have anything 'incorrect' in it. So, should not be allowed during the feature freeze.

**Comment by EmilyOng** [comment]
Thanks Prof :)
