### ISSUE TITLE
PPP pdf having a blank third page

### ISSUE THREAD

**Issue by Aishwarya-Hariharan-Iyer** [nus-cs2103-AY2223S1/forum#432]
I have been trying to fix the PPP for a while now but it keeps having a blank third page though I followed the steps on https://se-education.org/guides/tutorials/savingPdf.html. Can I extract that blank page out of the PDF and use it?

I have tried adding sections, reducing content, increasing content, etc.

**Comment by damithc** [comment]
@Aishwarya-Hariharan-Iyer It's fine to have a blank page at the end. It will not be penalized.

**Comment by Aishwarya-Hariharan-Iyer** [comment]
Thanks a lot Prof.!
