### ISSUE TITLE
Penalties for medium to high severity bug

### ISSUE THREAD

**Issue by parth-io** [nus-cs2103-AY2223S1/forum#435]
Hi guys, does anybody know what the penalties for bugs of `severity.High` and `severity.Medium` are? We discovered a bug of medium to high severity and are considering updating the JAR release despite the late penalty of -2 per team member. We understand the exact penalties are not released to the students, but if anybody has a rough estimation, it would help us make a decision.

An additional consideration is that the effort marks are likely to be impacted, if testers for the PE are unable to test the feature fully due to the bug (thus affecting the peer tester's evaluation of effort).

If this issue is not ok to be maintained on the forum, we will close it and we can directly email you @damithc .

**Comment by damithc** [comment]
@parth-io Confirm no single bug will incur a penalty as high as `-2*(team size)`, unless the bug is a 'show stopper' that makes the application mostly unusable.

**Comment by parth-io** [comment]
Ok thank you for the reply Prof!
