### ISSUE TITLE
Clarifications Regarding Practical Exam Readiness Quiz Answers

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#436]
For the practical exam, there are some questions which I would like to clarify because of some edge cases not explicitly mentioned. May I know the rationale behind excluding such edge cases?

<img width="881" alt="image" src="https://user-images.githubusercontent.com/13196670/200486418-261cc4da-b5d3-4cbf-b39c-3741fa896f7f.png">

While this is true in general, there is a rare case when I have to report to the head TA.
<img width="460" alt="image" src="https://user-images.githubusercontent.com/13196670/200487026-c46c2bb9-5530-445f-9ae0-c45867f288f8.png">

<img width="881" alt="image" src="https://user-images.githubusercontent.com/13196670/200487191-9ca81f1e-094b-4091-9189-e17e629125ea.png">
In Phase 4, there is no need to use CATcher because the tutors will decide on whether to side with the tester or the developer team, but it is true that I should not use the GitHub interface because there is no need to, as shown below:
<img width="524" alt="image" src="https://user-images.githubusercontent.com/13196670/200487341-e8279777-fbc1-4beb-b04c-d9429353caf0.png">
Perhaps it would be clearer to explictly exclude Phase 4?

<img width="880" alt="image" src="https://user-images.githubusercontent.com/13196670/200487811-74126d9c-4a98-4e15-b929-9f9013967722.png">
First, should I login to MS teams just before the PE (because logging in during the PE will eat up into the time I have for finding bugs)?
Is there a reason why MS teams is not explicitly written in the list of allowed websites here? 
<img width="474" alt="image" src="https://user-images.githubusercontent.com/13196670/200487901-2b5d09b9-11fe-4f93-8ffe-d7f74c5f0ca0.png">

**Comment by damithc** [comment]
Thanks for catching these edge cases @cheeheng 
I've done slight tweaks to them. In some cases it is better to omit edge cases as covering all edge cases can make the question harder to read and take attention away from the main point of the question.
Yes, you can login to MS Teams in advance.

**Comment by cheeheng** [comment]
Thanks so much for fixing it, prof. It was very frustrating for me to take the question very literally and get it wrong. Hopefully, those who will do the quiz afterwards will not face this issue.
