### ISSUE TITLE
Should we rank PE-D Testers who have not submitted any bugs?

### ISSUE THREAD

**Issue by Aishwarya-Hariharan-Iyer** [nus-cs2103-AY2223S1/forum#437]
Could I request confirmation on whether we should rank PE-D testers who have not reported any bugs?
We initially did not rank a Tester in Q2 (the corresponding response for Q1 was N/A) but as we are going through the evaluation once more after bug-fixing to see if we need to change anything, we wondered if we should rank the Tester as 7/last instead.
Thanks!

**Comment by damithc** [comment]
@Aishwarya-Hariharan-Iyer either way is fine, as in such cases we can figure out the performance of the tester from Q1 and other data (e.g., 0 bug count).

**Comment by Aishwarya-Hariharan-Iyer** [comment]
Thanks Prof.!
