### ISSUE TITLE
UG bugs in PE

### ISSUE THREAD

**Issue by Puakii** [nus-cs2103-AY2223S1/forum#440]
Should you report UG bugs in phase 1 or 2? It seems like both phase can report UG bugs?

**Comment by damithc** [comment]
Can report in both. But keep in mind that part 2 is solely for documentation bugs. So, you might want to take a note of UG bugs during part 1 and report them during part 2, which will give you more time to find/report functionality bugs during part 1.

**Comment by Puakii** [comment]
okay thanks prof!
