### ISSUE TITLE
Total number of marks does not add up?

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#441]
In [this website](https://nus-cs2103-ay2223s1.github.io/website/admin/tp-grading.html), I found out that the sum of team and individual marks does not sum to 50. 

When I checked the bottom sections, it looks like 45 marks are individual marks, while the last 5 marks are team marks.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/13196670/201367878-f25623ae-878d-4c6b-9c31-56c9f2492f5d.png">

Should this be considered a very low severity documentation bug?

**Comment by damithc** [comment]
Fixed. Thanks for the bug report @cheeheng 👍
