### ISSUE TITLE
Can the following issues be counted as not in scope?

### ISSUE THREAD

**Issue by lesterong** [nus-cs2103-AY2223S1/forum#443]
1. <img width="1317" alt="image" src="https://user-images.githubusercontent.com/84223259/201468645-28e8daaf-d3a9-4088-9a9b-dbb4e0d60b61.png">

nus-cs2103-AY2223S1/pe-dev-response#4848: The bug reported did not mention how it was reproduced. However after investigating, we realised that it might be due to the way the user opened the program. Opening the program by double clicking and opening it by `java -jar` command saves to a different data json file. The respective json files are updated correctly, depending on how the application was launched. Since the tester used two different methods of launching the jar file, it appeared to the tester that the json file was not being updated correctly. We also found that AB3 has the same behaviour as this. Hence, we feel that this might be 'not in scope' as you didn't break something that worked already. 

2. <img width="1228" alt="image" src="https://user-images.githubusercontent.com/84223259/201468672-a74c1623-bff0-4703-9ae8-6dbae780eec4.png">

nus-cs2103-AY2223S1/pe-dev-response#4847: We find that it may be not in scope, as the instructions for PE specify:
> Launch the jar file using the java -jar command rather than double-clicking (reason: to ensure the jar file is using the same java version that you verified above). Use double-clicking as a last resort.

However, if it is not considered out of scope, since we did mention it in our UG, we were wondering if we could lower the severity as we don't think this is a major issue, as it only happens on the first initial launch, and only for MacOS users. The subsequent launches will not cause the same prompt to the user.

**Comment by damithc** [comment]
@lesterong 
1. Kudos for figuring out a possible way to reproduce the behavior mentioned in the bug report. In the context of the PE, I think this bug report is not specific enough to link to that behavior you found, as there is no mention of launching the JAR file in different ways. If there is a more specific bug report for the behavior you mentioned, you can argue as 'not in scope' or accept it as a documentation bug (i.e., not mentioning this pitfall in the UG). BTW, I suspect this behavior is specific to certain OS.
2. A lower priority documentation bug might be a good fit for this case.

**Comment by lesterong** [comment]
Thanks Prof!
