### ISSUE TITLE
Between 'Reject' and 'Cannot Reproduce', which should take precedence?

### ISSUE THREAD

**Issue by Nephelite** [nus-cs2103-AY2223S1/forum#448]
In this bug report, the tester both provided steps that do not accurately reflect how to achieve the bug they found (task description of added task is different from the command they claimed to have inputted), and also tested the product using extreme user input that is not expected in normal usage.

I would like to pin this as both 'CannotReproduce' and 'Rejected', but am not sure which is more applicable in this context.

Issue in question: https://github.com/nus-cs2103-AY2223S1/pe-dev-response/issues/1406

**Comment by damithc** [comment]
@Nephelite Either one is fine, as they are treated the same way for PE grading. You can explain why it cannot be reproduced and why the input is 'extreme' in the comment.

**Comment by Nephelite** [comment]
@damithc In the end, I chose 'cannot reproduce', explained all the attempts I made to reproduce the bug, and just to cover every base, also mentioned that the inputs were extreme and why.

My only worry is if the tester rejects, and the tutor somehow manages to find out how to reproduce the bug. In that case, would I be marked down still, or can I then change the label to 'Rejected'?

**Comment by damithc** [comment]
> @damithc In the end, I chose 'cannot reproduce', explained all the attempts I made to reproduce the bug, and just to cover every base, also mentioned that the inputs were extreme and why.
> 
> My only worry is if the tester rejects, and the tutor somehow manages to find out how to reproduce the bug. In that case, would I be marked down still, or can I then change the label to 'Rejected'?

@Nephelite It should be fine, provided you explain that if the bug can be reproduced, it should still be rejected. Still, perhaps it is more fitting to mark it as Rejected -- as you stance is that 'it should be rejected even if it can be reproduced'?

**Comment by Nephelite** [comment]
@damithc Ok, I will mark as rejected then. Thank you!
