### ISSUE TITLE
Duplicate issues with differing severity levels

### ISSUE THREAD

**Issue by Nephelite** [nus-cs2103-AY2223S1/forum#449]
For the same exact documentation bug, one tester reported it as a medium severity bug, and another reported it as very low. Funnily enough, our team feels that the bug is of low severity, right in the middle. 

Medium: https://github.com/nus-cs2103-AY2223S1/pe-dev-response/issues/5645

Very Low: https://github.com/nus-cs2103-AY2223S1/pe-dev-response/issues/2891

What is the right action in this scenario, after reporting one of them as a duplicate? And for that matter, which should be the duplicate?

**Comment by damithc** [comment]
> What is the right action in this scenario, after reporting one of them as a duplicate? And for that matter, which should be the duplicate?

@Nephelite You can set either one as the duplicate of the other, and set the correct response/type/severity in the remaining (i.e., the 'original') one. Whatever severity/type/response you choose for the 'original' bug will be copied over to all the 'duplicates' of that bug when we transfer the bugs to the next phase (reason: if they are duplicates, they all must have the same type, severity, response).

**Comment by Nephelite** [comment]
@damithc I see, thanks!
