### ISSUE TITLE
In-Video Quizzes Participation points

### ISSUE THREAD

**Issue by guokweijie** [nus-cs2103-AY2223S1/forum#45]
Hi, can I ask if our scores in the in-video quizzes of the videos in the textbook affect the amount of participation marks that we get? Or do we get the 2 bonus points as long as we answer all of the questions in the quizzes?

**Comment by damithc** [comment]
@guokweijie for in-video quizzes, we only check if you have answered. We don't check if the answer is correct.

**Comment by guokweijie** [comment]
@damithc ok thank you Prof!
