### ISSUE TITLE
Number of bugs allowed as a group

### ISSUE THREAD

**Issue by notle1706** [nus-cs2103-AY2223S1/forum#450]
Hi, according to the email sent out by prof, 
> you can likely accept 5+ minor bugs before even it starts affecting your marks (because a certain amount of bugs are forgiven) 

Does this also mean that a group can accept 25+ minor bugs before it starts to affect our marks or 5 minor bugs as a whole? Our team is planning to split all the bugs found

**Comment by damithc** [comment]
> Does this also mean that a group can accept 25+ minor bugs before it starts to affect our marks

Yes, for a 5-person team, assuming all are minor bugs. Note that this is a rough estimate only (it varies based on bug type too), and 'minor' bugs refer to `severity.VeryLow` bugs.

**Comment by notle1706** [comment]
Thank you prof for the reply. Also, would the penalty be evenly distributed among all group members should we decide to leave all accepted bug reports unassigned?

**Comment by damithc** [comment]
> Thank you prof for the reply. Also, would the penalty be evenly distributed among all group members should we decide to leave all accepted bug reports unassigned?

@notle1706 yes, divided evenly.

**Comment by notle1706** [comment]
Thank you!
