### ISSUE TITLE
Calculating percentage of bugs accepted by triage

### ISSUE THREAD

**Issue by ElginL** [nus-cs2103-AY2223S1/forum#451]
Hi, I would like to ask how the percentage of bugs accepted by triage is calculated.

For example (not factual data):
If I have 4 bugs accepted, 2 bugs rejected, 2 not in scope, and 1 duplicate (duplicated myself), how do I calculate the percentage accepted?

**Comment by damithc** [comment]
![image](https://user-images.githubusercontent.com/1673303/201536967-6a8e4c7f-b8a5-4564-b6ba-bb0ea35a17de.png)

@ElginL `accepted as triaged` in the above means whichever severity/type/response you chose were eventually accepted by the tester or the teaching team. In other words, how correct your triaging decisions were. It is not linked to how many bugs you accepted.

e.g., if you rejected all bugs, and the tester agreed with all of those rejections, your triaging was 100% accurate. Alternatively, the tester did not agree with half of those rejections but the teaching team ruled in your favor or all of them, you still have 100% accuracy.

**Comment by ElginL** [comment]
Okay, thank you prof
