### ISSUE TITLE
Bug Report may be correct but for a different reason

### ISSUE THREAD

**Issue by nitant-p** [nus-cs2103-AY2223S1/forum#452]
I got a bug report stating that the UG is too long for a certain command, because there are too many things to take note of.

I disagree with the reason the tester stated, but there are a few repeated examples which does make it longer than it needs to be.

In this case, would the bug report be considered valid even though the reasoning is incorrect?

**Comment by damithc** [comment]
@nitant-p I think it is best to accept it, as the bug report points to a valid issue. Even partially correct bug reports can help us improve the software.

**Comment by nitant-p** [comment]
Okay thanks prof!
