### ISSUE TITLE
Severity for similar diagrams

### ISSUE THREAD

**Issue by ThomasHoooo** [nus-cs2103-AY2223S1/forum#454]
May I know what is the severity for similar diagrams? The tester put as low but I think it is veryLow as it doesn't hinder the user and it is a cosmetic issue.

**Comment by damithc** [comment]
@ThomasHoooo Depends on the case. Having many similar diagrams _can_ hinder the reader as it is difficult to see which parts are similar and which parts are different, causing misunderstandings such as thinking something is similar when actually there is a subtle difference.

**Comment by ThomasHoooo** [comment]
There are only 1-2 similar diagrams and what they perform are quite similar as well.

**Comment by damithc** [comment]
> There are only 1-2 similar diagrams and what they perform are quite similar as well.

You can make a judgement call, based on the potential of this similarity to hinder readers. In the explanation, you can justify your decision e.g., why you think there is minimal hindrance to the reader.
If the tester object to your decision, the teaching team will look at the actual situation and make a final decision.

**Comment by ThomasHoooo** [comment]
Thanks Prof!
