### ISSUE TITLE
Can this bug be considered as Response.NotInScope

### ISSUE THREAD

**Issue by Sampy147** [nus-cs2103-AY2223S1/forum#455]
Our app is a task, exam and module manager, and currently one task is linked to one exam. One tester reflected that one task should be able to link to more than one exam, as some tasks might be in preparation for more than one exam. This appears to be like a extension of a feature but we did not mention this in the UG as a future extension. 

We feel that this can be considered as Response.NotInScope as per the definition below, as the app is reasonably useful and rectifying the feature is less important than the work that has been done already.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/87646810/201607632-c41c5c9a-fbb3-4d3d-ae79-54647f31ab61.png">

Implementing tasks that can be linked to more than 1 exam would require a lot more work and is non-trivial, as the completion bars for tasks and modules would have to change accordingly to account for this. The completion bars being referred to are the ones in the exam panel below.

<img width="548" alt="image" src="https://user-images.githubusercontent.com/87646810/201598024-5e1662ba-83f2-4d87-bd24-4901a25abd87.png">

Furthermore, the deletion and editing of tasks and exams would have to take this into account, given that tasks are linked to exams. For example, when an exam is deleted/edited, all the tasks with this exam should be deleted/edited as well. This implementation is non-trivial and requires comprehensive redesigning of multiple other crucial features for this purpose. In this case, we were wondering if this comment to implement tasks linked to multiple exams can be considered Response.NotInScope. 

The link to the bug report is here:
https://github.com/nus-cs2103-AY2223S1/pe-dev-response/issues/1607

**Comment by damithc** [comment]
@Sampy147 Yes, there is some merit in that argument, although it will also depends on what other features you have. You can explain your argument when you respond to the bug report, and hope the tester agrees (given the tester is familiar with the other features). If the tester doesn't agree, the teaching team will consider your justification and the tester's counter argument to make a final decision.

**Comment by Sampy147** [comment]
Okay thanks Prof! Appreciate the help!
