### ISSUE TITLE
Do rejecting an issue assigned to me might affect the rest of my team in the tutor moderation phase?

### ISSUE THREAD

**Issue by gerardstevan** [nus-cs2103-AY2223S1/forum#456]
If the assignee of an issue is me and I decided to reject it, can it affect my teammates in the tutor moderation phase if the tutor decided to accept the issue?

**Comment by damithc** [comment]
@gerardstevan In that case only the assignees of the but will be affected. If there are no assignees, the effect will be divided among all team members.

**Comment by gerardstevan** [comment]
Ok, thanks prof!
