### ISSUE TITLE
Can this bug be considered as response.NotInScope?

### ISSUE THREAD

**Issue by dlimyy** [nus-cs2103-AY2223S1/forum#457]
Our group has received a bug report on write-only json files and we would like to clarify with regards to the handling of write-only json files:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/97420966/201611179-8da46807-b050-4853-8c20-1bdbd5399140.png">

Given that the json file created by our application is by default granted with both write and read permissions, would it be fine to consider this as notInScope as it is unusual for the file to be changed to be only write-only and the console does still throw a warning that the file cannot be read.

**Comment by damithc** [comment]
@dlimyy Yes, that sounds like a reasonable course of action, although the final decision will also depend on the counter arguments from the tester, should there be any.
