### ISSUE TITLE
Bug when double clicking vs launching the jar using the terminal

### ISSUE THREAD

**Issue by mjgui** [nus-cs2103-AY2223S1/forum#458]
### Question

Hi CS2103T team! Our team was wondering whether the following scenario would be considered a bug:

For reference, here is the original bug report
https://github.com/nus-cs2103-AY2223S1/pe-dev-response/issues/2713

After a (extremely interesting) debugging deep dive where we attempted to replicate the issue, we identified the issue to be our cli library (`picocli`) **outputting escape characters for text formatting** (bold/colors) on certain machines. With the assistance of the [documentation](https://picocli.info/#_heuristics_for_enabling_ansi) and according to our testing, this will happen if

1. The user is running a non-Windows system (most commonly MacOS, but we have not tested it on linux systems)
2. The user **does not double click the program**, but instead **runs it via the terminal** (i.e. `java -jar truthtable.jar`)

We did not catch this during our testing as the problem **does not occur** when running the program via IntelliJ or via double clicking the jar file. (We have confirmed this by installing Java 11 from scratch and double clicking the jar file on a new Mac system)

We refer to the CS2103T website here:
<img alt="image" src="https://user-images.githubusercontent.com/9080115/201629614-c601810a-5f72-4277-a84b-f484d9e6087c.png">

In particular, our user guide also states:
<img alt="image" src="https://user-images.githubusercontent.com/9080115/201630092-e9509938-9fa8-4b2f-88e6-32e184c500a4.png">

Note that we do not support running the jar file via the command line. **Would it be valid to therefore reject this bug?**

### Summary of Original Problem

To restate the problem, there is weird output when the `help` command is run

![image](https://user-images.githubusercontent.com/9080115/201628345-d5195f09-d9bd-484c-ba21-f25aa7e58c59.png)

**Expected:**
![image](https://user-images.githubusercontent.com/9080115/201628383-a806929d-5489-44a7-9408-a3f9a63f0a89.png)

**Comment by damithc** [comment]
> Note that we do not support running the jar file via the command line. **Would it be valid to therefore reject this bug?**

@mjgui Given the below, I think it's not appropriate to reject the bug entirely :-(
1. UG doesn't prohibit the use of command line 
2. the two forms of running a JAR file are generally interchangeable 
3. our target user prefers CLI
5. the PE recommends using CLI

**Comment by Devanshshah1309** [comment]
Thanks for the prompt response Prof :)
