### ISSUE TITLE
How does CS2103T get priority for GitHub CI workflow?

### ISSUE THREAD

**Issue by zbz-lvlv** [nus-cs2103-AY2223S1/forum#459]
Hi guys, I'm building my own project in Python and have just set up a CI pipeline with GitHub actions. However, the check is extremely slow (queueing for more than 1 hour already), so I was wondering if there is a way to speed it up? Do CS2103T projects get priority when it comes to the GitHub CI side, and if so, is there any way for me to configure it for my own project?

**Comment by RichDom2185** [comment]
Maybe the runners are just down? My projects run just fine on GitHub Actions

**Comment by zbz-lvlv** [comment]
![image](https://user-images.githubusercontent.com/9377433/201647295-a639ebc4-d60c-4290-aa05-3b9b016254d6.png)

I only added a `requirements.txt` with some Python modules to be installed. Could that be the issue?

**Comment by damithc** [comment]
> Do CS2103T projects get priority when it comes to the GitHub CI side, and if so, is there any way for me to configure it for my own project?

No, we don't get any additional priority.

@zbz-lvlv perhaps you can share the link to the project so that others can have a look?

**Comment by zbz-lvlv** [comment]
It's a private project for my freelance work, so I won't be able to share the details here. Thanks for your help anyways!
