### ISSUE TITLE
iP Level-8 Duke behaviour clarification

### ISSUE THREAD

**Issue by waynezsy** [nus-cs2103-AY2223S1/forum#46]
Hi, I have 2 questions related to clarifying the minimal expected behaviour of Duke at Level-8.

1. Currently, my Duke is able to recognise a specific input format i.e. `2/12/2019 1800` as a date/time (stored using LocalDateTime) but not another input format e.g. `2-12-2019 1800` as a date/time. Is this the expected minimal behaviour of the level-8 increment, or am I supposed to have Duke be able to recognise multiple types of date/time input?

![image](https://user-images.githubusercontent.com/97035005/185791454-163229c7-956c-418d-97f9-15a0a0d8e4a2.png)

2. The requirements for Level-8 are somewhat ambiguous. In the minimal version, we are told to store dates as a LocalDate. Are we also (concurrently) required to detect and store date/times as LocalDateTime?

**Comment by damithc** [comment]
> 1. Currently, my Duke is able to recognise a specific input format i.e. `2/12/2019 1800` as a date/time (stored using LocalDateTime) but not another input format e.g. `2-12-2019 1800` as a date/time. Is this the expected minimal behaviour of the level-8 increment, or am I supposed to have Duke be able to recognise multiple types of date/time input?

@waynezsy recognizing one date format is enough to meet the minimal requirement. As usual, you are welcome to do more.


> 2\. The requirements for Level-8 are somewhat ambiguous. In the minimal version, we are told to store dates as a LocalDate. Are we also (concurrently) required to detect and store date/times as LocalDateTime?

You can use either one, whichever suits your implementation.
