### ISSUE TITLE
[PE] Documentation for a feature missing completely

### ISSUE THREAD

**Issue by xiaobill8** [nus-cs2103-AY2223S1/forum#460]
If the documentation for a feature is missing completely, would it be considered a Documentation bug or a Feature flaw?
From the tester's perspective, there is no information in the User Guide whatsover regarding the feature, so it would seem as a Feature Flaw.

For context, a parameter for a command was missing in both the error message and documentation, so a feature in the UI could not be changed at all without prior knowledge of the parameter.
Would it also be considered a high severity? (Since in the PE readiness quiz, even a slight misspelling of a parameter was considered an Medium)
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/58042582/201738431-a4f50e26-04fd-4a6a-a6f9-6fa3b57183f3.png">

**Comment by damithc** [comment]
@xiaobill8 Yes, the less information the user has about the feature, the more it hinders the user, and the higher the severity. In some cases it can be `severity.High`.

**Comment by xiaobill8** [comment]
@damithc To clarify, would this be considered a Documentation Bug or Feature Flaw? Since the tester has no information regarding this feature whatsover from the UG.

**Comment by damithc** [comment]
> @damithc To clarify, would this be considered a Documentation Bug or Feature Flaw? Since the tester has no information regarding this feature whatsover from the UG.

@xiaobill8 If the problem is primarily 'the feature exists but not is not documented', it's a documentation bug.

**Comment by xiaobill8** [comment]
@damithc Thank you for the clarification!
