### ISSUE TITLE
PE Phase 3 Deadline confusion

### ISSUE THREAD

**Issue by nealetham** [nus-cs2103-AY2223S1/forum#461]
In the module website, it states that the deadline for PE phase 3 is on Fri, Nov 18th 2359.

![image](https://user-images.githubusercontent.com/49066882/201819469-2a00002b-6420-4b64-b63d-b627e47b8e64.png)

However, in the email sent by prof, it's by Thu, Nov 17th 2359.

![image](https://user-images.githubusercontent.com/49066882/201819529-9d3a2cbd-20bb-4553-9ad1-2985e976628d.png)

It could possibly be a typo?

**Comment by damithc** [comment]
@nealetham the date in the website was updated just a few minutes before the announcement. You must be looking at a cached copy. Try <kbd>Ctrl + F5</kbd> to force refresh the page.

![image](https://user-images.githubusercontent.com/1673303/201821026-2b5b2c64-d037-4203-915f-ee49f8aa824c.png)

**Comment by nealetham** [comment]
Whoops my bad. Thank you prof!
