### ISSUE TITLE
Defining Feature Flaw

### ISSUE THREAD

**Issue by sltsheryl** [nus-cs2103-AY2223S1/forum#462]
Could I ask does it count as a feature flaw if the app behavior seems not very realistic but this is written in the UG, though without much justification why?

Eg. The app is not case sensitive with people's names (treat them as different people) or 

The app does not allow people with the same name (people can have the same name in real life like John Tan but different particulars)

but it is written in the UG that "Person name input must strictly match the name of an existing person, even the casing, extra whitespaces should be regarded as the same person", though not justifying why in the UG.

Does this constitute a feature flaw? 

It is not a functionality bug since it aligns to the UG, but disallowing people with same names and being case sensitive seems to be quite unrealistic for the app in the real world and it makes things more cumbersome for a fast typist (the case sensitive part)

**Comment by parnikkapore** [comment]
I think this counts as a FeatureFlaw, yeah

**Comment by damithc** [comment]
> Could I ask does it count as a feature flaw if the app behavior seems not very realistic but this is written in the UG, though without much justification why?

Yes, although giving a clear notice of it (and even a justification) to the user can be used to justify a reduced severity than otherwise. Also, it is possible to argue it is NotInScope if fixing the flaw is less important than the features already implemented.

**Comment by sltsheryl** [comment]
Thanks!
