### ISSUE TITLE
Possible Feature Flaw: CATcher does not allow the tester to revise the initial bug severity during the tester rebuttal phase

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#463]
CATcher does not explicitly allow the tester to revise the initial bug severity and/or type during the tester rebuttal phase. Is there a reason behind this? 

There is a possible use case for that:

Suppose the tester put the severity as Medium during the Practical Exam.
During the dev team response phase, the dev team downgraded the severity to VeryLow.
The tester disagrees with the dev team, but now realises that the severity should be Low, and would want to correct the error.

Currently, a workaround is to explain in the response box that the tester is revising the severity, but I am not sure if that is allowed.

**Comment by damithc** [comment]
> Currently, a workaround is to explain in the response box that the tester is revising the severity, but I am not sure if that is allowed.

@cheeheng It's allowed.
![image](https://user-images.githubusercontent.com/1673303/201825275-0c82b171-5ad3-49c5-9564-8004780d3766.png)

**Comment by cheeheng** [comment]
Oops, I did not notice this. Perhaps it can be implemented in the following semesters so that it would be more intuitive to users.

Thanks prof!
