### ISSUE TITLE
Question regarding navigability

### ISSUE THREAD

**Issue by sharmaine1028** [nus-cs2103-AY2223S1/forum#464]
Consider that Class A has a field Class B, then there is navigability between Class A and Class B.

Class A -> Class B

Class B has a field Class C, there there is navigability between Class B and C.
Class B -> Class C

My question is whether this means Class A has navigability to Class C? (Class A can only access Class C through a getter in Class B)

Can the class diagram be drawn as such
Class A -> Class C ?

**Comment by damithc** [comment]
Good questions @sharmaine1028 Let's wait a bit to see what others think...

**Comment by kxrt** [comment]
The textbook definites navigability as:

> When two classes are linked by an association, it does not necessarily mean the two objects taking part in an instance of the association `knows about (i.e., has a reference to)` each other. The concept of which object in the association `knows about`) the other object is called navigability.

I think the key point here would be the highlighted phrase, "knows about". A does not directly know about C, and you cannot access C from A without the intermediary (B). If C was unidirectionally navigable from A, I believe there would be a separate arrowhead pointing from A to C as their association. 

Furthermore, the textbook defines the directions of navigability with the phrase "b has a reference to r". In your example, A does not directly hold a reference to C, which further makes it non-navigable.

I might be wrong here, but I believe composition/aggregation are transitive whereas navigability is not.

**Comment by lulucopter** [comment]
Agree with @kxrt here. If an intermediary is required for A to 'navigate' to C, then A does not actually have a reference to C, but rather, a reference to an intermediate that has a reference to C.

This touches a bit on coding practices as well, and if good coding practices are done by the coder, A should not be able to directly navigate to C within its' code (I believe this should be the law of demeter)

**Comment by sharmaine1028** [comment]
I think the above responses makes sense, thank you!

**Comment by damithc** [comment]
@sharmaine1028 as @kxrt and @lulucopter have suggested, navigability is not transitive i.e., A -> B and B -> C doesn't necessarily mean A -> C.
