### ISSUE TITLE
Does notInScope count towards accuracy?

### ISSUE THREAD

**Issue by dexter-sim** [nus-cs2103-AY2223S1/forum#465]
If the type.* and severity.* match, does not in scope count towards accuracy?

<img width="752" alt="image" src="https://user-images.githubusercontent.com/95021334/201850944-cc706e71-effd-46ea-98ca-b4b8ad39b77f.png">

**Comment by damithc** [comment]
> If the type.* and severity.* match, does not in scope count towards accuracy?

Yes.

**Comment by dexter-sim** [comment]
Thank you for the clarification.
