### ISSUE TITLE
Is it ok to reject severity downgrade if I accept the bug rejection?

### ISSUE THREAD

**Issue by dexter-sim** [nus-cs2103-AY2223S1/forum#466]
The developer team rejected the bug report and lowered the severity of the bug report. 

However, only justification for rejection is given and not for lowering severity.

Is it ok to reject the lowering severity but accept that the bug report is rejected?

**Comment by damithc** [comment]
> Is it ok to reject the lowering severity but accept that the bug report is rejected?

@dexter-sim If the tester agrees the bug should be rejected, the type and severity doesn't matter any more (because 'reject' means it's not a bug at all).

**Comment by dexter-sim** [comment]
Thank you for the clarification.
