### ISSUE TITLE
Duplicate rejection dependent on result of other bug report

### ISSUE THREAD

**Issue by Nephelite** [nus-cs2103-AY2223S1/forum#467]
I reported 2 similar bugs that cannot be fixed independently if ruled as functionality bugs. However, the dev team reported them as documentation bugs and set one of them as a duplicate. Indeed, if ruled as documentation bugs, they would be fixed by the same changes.

I believe I have good reason to reject their reasoning for why the bug should be a documentation bug, i.e I believe I was right about both bugs being functionality bugs, but if my reasoning is not accepted, my duplicate rejection is also going to be rejected by default. Is there some way to indicate that I only reject a duplicate declaration in the event another bug report gets accepted by the tutor?

**Comment by damithc** [comment]
> I believe I have good reason to reject their reasoning for why the bug should be a documentation bug, i.e I believe I was right about both bugs being functionality bugs, but if my reasoning is not accepted, my duplicate rejection is also going to be rejected by default. Is there some way to indicate that I only reject a duplicate declaration in the event another bug report gets accepted by the tutor?

@Nephelite You can explain this in your response comment.

**Comment by Nephelite** [comment]
@damithc Thanks!
