### ISSUE TITLE
Is it ok to accept severity downgrade if I reject the bug rejection?

### ISSUE THREAD

**Issue by jontmy** [nus-cs2103-AY2223S1/forum#469]
Inverse of #466.

I have to justify the severity I chose (which got downgraded), but...:

If I accept the downgraded severity but the dev team's rejection is overruled, will it end up as a lose-lose? (I lose accuracy, dev team gets penalized for the bug). Or does the original severity get applied?

If I disagree with the downgraded severity, will both the downgrade and my rejection to the dev team's rejection need to be accepted by the TA for the rejection to be accepted? (in which case I can avoid risking my disagreement with the rejection getting overruled because I should have accepted the severity downgrade)

**Comment by damithc** [comment]
@jontmy 

1. Only disputed items will be decided by the teaching team. If you agree with the dev team, the teaching team doesn't interfere.
2. Each disagreement is evaluated independently. If you disagree with two things of the same bug, it's possible the teaching team sides with you on one and sides with the dev team on the other.

Does the above clear up your doubt? Feel free to ask follow up questions.

**Comment by jontmy** [comment]
Yep it does, thanks prof!
