### ISSUE TITLE
'Put every class in a package' - should this apply to Duke.java?

### ISSUE THREAD

**Issue by leonidas1712** [nus-cs2103-AY2223S1/forum#47]
I'm referring to the coding [standard](https://se-education.org/guides/conventions/java/intermediate.html#package-and-import-statements) given, under the heading **Package and Import Statements**

Just wanted to clarify as if so, the provided runtest.sh or runtest.bat would have to be changed to accommodate the new location of Duke.java.

**Comment by damithc** [comment]
> the provided runtest.sh or runtest.bat would have to be changed to accommodate the new location of Duke.java.

@huzaifa1712 yes, that's correct.

**Comment by leonidas1712** [comment]
Hi Prof, so to confirm would we need to put Duke.java into its own package in order to conform to the coding standard? Or can an exception be made for a file like Duke.java which is the entry point of a project? Thanks!

**Comment by damithc** [comment]
> Hi Prof, so to confirm would we need to put Duke.java into its own package in order to conform to the coding standard? Or can an exception be made for a file like Duke.java which is the entry point of a project? Thanks!

@huzaifa1712 Every class must be put in a package, including the Duke.java.

**Comment by leonidas1712** [comment]
Thank you!
