### ISSUE TITLE
Do bugs in these pages in the DG count as part of the scope?

### ISSUE THREAD

**Issue by CeereeC** [nus-cs2103-AY2223S1/forum#470]
![Screenshot 2022-11-15 at 7 00 18 PM](https://user-images.githubusercontent.com/90279138/201903644-d266e86e-ebdb-40a3-8e54-daea95ef88c1.png)

**Comment by damithc** [comment]
@CeereeC No. Only the content of the DG PDF file uploaded to LumiNUS is evaluated in the PE.

**Comment by CeereeC** [comment]
Alright got it. Thank you
