### ISSUE TITLE
Clarification on applying `NotInScope` criteria on `DocumentationBug`

### ISSUE THREAD

**Issue by chloeelim** [nus-cs2103-AY2223S1/forum#471]
Hi,

I was wondering how the criteria for bugs classified as `NotInScope` should apply to a `DocumentationBug`.

Here's the relevant snippet in question from the module website:

<img width="692" alt="Screenshot 2022-11-15 at 4 57 56 PM" src="https://user-images.githubusercontent.com/79991214/201910441-d2187e65-1102-47e2-b517-414cbda53ec8.png">

As you can see, it appears that the set of criteria provided would most suitably apply to a `FeatureFlaw` or `FunctionalityBug` since the two requirements don't really apply to a `DocumentationBug`.

So I'm quite confused how we should determine whether a `DocumentationBug` (eg: image mismatch between UG and product) we've reported really qualifies for `NotInScope` as claimed by the developers' response.

Thanks!

**Comment by damithc** [comment]
@chloeelim For this specific case, you can weigh the effort required to update those images against the damage caused by the mismatching images, to decide whether it is acceptable to postpone the fix to a future version. Keep in mind that updating documentation can be time consuming too.

**Comment by chloeelim** [comment]
Got it, thanks Prof!
