### ISSUE TITLE
Outcome of tutor moderation phase

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#472]
Will both the tester and the dev team be notified of the final severity and type of the bug (i.e., whether the teaching team sided with the tester or the dev team)?

Pros: It will be a good learning opportunity for both the tester and the dev team to understand why the bug is actually of a certain severity or a certain type. 

Cons: If additional explanation is given, there will be more work from the teaching team because they have to adjudicate a few thousand disputed bugs. If additional explanation is not given, it could defeat the purpose because the tester and the dev team may not fully understand why the severity and type of the bug is judged as such.

**Comment by damithc** [comment]
@cheeheng we don't plan to reveal the final outcome, as most of them will be judgement calls that can invite further arguments from the tester or the dev team. We do however an additional check in the moderation phase: if the moderator is not sure about the decision, the case is passed to me for the final decision.

**Comment by cheeheng** [comment]
Indeed, this is also one of my biggest concerns. Thanks prof for your quick reply.
