### ISSUE TITLE
[PE] Clarification on UG pdf conversion

### ISSUE THREAD

**Issue by leirdas** [nus-cs2103-AY2223S1/forum#473]
Hi,

I would like to clarify if the conversion of UG to pdf which results in certain command examples being invalid due to missing whitespace during the conversion process can be classified as a `DocumentationBug`.

Thanks

**Comment by kxrt** [comment]
Sounds like it would fall under correctness as an inaccuracy.

<img width="593" alt="Screenshot 2022-11-16 at 12 10 21 PM" src="https://user-images.githubusercontent.com/73589885/202081525-d1ee3e32-44c7-4c3f-bf90-dcbf134dc368.png">

**Comment by damithc** [comment]
Yes, they _can_ be.
![image](https://user-images.githubusercontent.com/1673303/202083637-7f9a4832-d29c-4e09-977c-b3db48be206e.png)

**Comment by leirdas** [comment]
Thank you! @kxrt @damithc
