### ISSUE TITLE
No response from Dev team 

### ISSUE THREAD

**Issue by Qiaoran-M** [nus-cs2103-AY2223S1/forum#474]
Hi, I have a question about PE tester response

If the dev team only changed the severity level, but didn't give any other response (the bug report is neither accepted nor rejected), how should I reply since I don't really know the bug is accepted or not?

**Comment by damithc** [comment]
@Qiaoran-M If CATcher doesn't give you an option to disagree with the team's `response.*`, that means it was `response.Accepted` (i.e., there is nothing for you to disagree with).


For the change of severity, you are free to disagree. The team not providing a justification tilts the case in your favor, but you can make your case even stronger by providing an explanation of why you think your initial severity choice is correct.
