### ISSUE TITLE
Quiz Week 8A, Question 19

### ISSUE THREAD

**Issue by zbz-lvlv** [nus-cs2103-AY2223S1/forum#476]
![image](https://user-images.githubusercontent.com/9377433/202719229-77217202-3a82-4c7e-a7ce-8d641d817f3a.png)

Why is Mat having exactly 5 helpers wrong? The array can hold up to 5 elements, but shouldn't the diagram be modelling the problem (which there can be one which requires exactly 5 helpers) instead of modelling the implementation?

**Comment by lulucopter** [comment]
As you suggested, you are right to say that the array can hold up to 5 elements. But do that note the difference between *up* to 5 and *exactly* 5. 

In this case, the UML diagram should be `0..5` to represent the "up to 5" idea. However, in the diagram, having the multiplicity be `5` suggests that there **MUST** be exactly 5 bots, which is wrong.

**Comment by zbz-lvlv** [comment]
Thank you for your response. I understand that according to the code, it is such that 0..5 is the more sensible answer. However, we do not know the problem domain in this case, and in that case, am I right to say that there can exist a particular problem domain in which exactly 5 elements are needed?

**Comment by kxrt** [comment]
> Thank you for your response. I understand that according to the code, it is such that 0..5 is the more sensible answer. However, we do not know the problem domain in this case, and in that case, am I right to say that there can exist a particular problem domain in which exactly 5 elements are needed?

That sounds true to me, however, that would be an OODM specific to that problem domain and not a general class diagram.

**Comment by kxrt** [comment]
> However, we do not know the problem domain in this case, and in that case, am I right to say that there can exist a particular problem domain in which exactly 5 elements are needed?

@zbz-lvlv That sounds true to me, however, that would be an OODM specific to that problem domain and not a general class diagram.

**Comment by damithc** [comment]
Example: consider the following extracts from a software for managing student team projects

* You talk to the prof who is your target user, and s/he says "A team can have up to five members. For example, the team 1 over there has five members"
  * Problem domain: ... A team can have up to five members. ...
  * A specific object structure of the problem domain at a specific time: ... Team 1 has five members. ...

* You go and design a system for managing team projects. You use `Student[]` to keep track of team members. 
  * Solution domain: ... The `Team` class uses a `Student[]` of size 5 to store `Student` objects representing team members ...
  * A specific object structure of the solution domain at a specific time: ... `team1` array has five `Student` objects. ...


&nbsp; | to show _general rules_ for object structures (aka the _class structure_) | to show the object structure at a _specific time_
-------|-------------|------------
problem domain | OODM | object diagram
solution domain | class diagram | object diagram

So, you guys can think about which cell in the table above relates to the quiz question cited above.

**Comment by zbz-lvlv** [comment]
okay i see, thank you!!
