### ISSUE TITLE
How to cite reused code now?

### ISSUE THREAD

**Issue by pratham31012002** [nus-cs2103-AY2223S1/forum#477]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/71367149/202898560-41c92ce3-aadb-400d-91a1-108a7a4fb673.png">

As mentioned above, we can still cite reused code, so do we create a new PR and merge it after giving the credit in the required place(s)?

**Comment by damithc** [comment]
> As mentioned above, we can still cite reused code, so do we create a new PR and merge it after giving the credit in the required place(s)?

@pratham31012002 yes, that's correct.

**Comment by pratham31012002** [comment]
Okay thank you prof!
