### ISSUE TITLE
Will the solutions to the mock exam and practice exam be released?

### ISSUE THREAD

**Issue by Hongyi6328** [nus-cs2103-AY2223S1/forum#478]

**Comment by jontmy** [comment]
The results and explanations for the MCQ and follow-up questions can be viewed on the Examsoft website (assuming you have already submitted):

[https://apac.examsoft.com/GKWeb/login/NUS](https://apac.examsoft.com/GKWeb/login/NUS)

**Comment by Hongyi6328** [comment]
> The results and explanations for the MCQ and follow-up questions can be viewed on the Examsoft website (assuming you have already submitted):
> 
> https://apac.examsoft.com/GKWeb/login/NUS

Thank you so much!!
