### ISSUE TITLE
[Spoiler Alert] Not sure about a question in the Practice Exam

### ISSUE THREAD

**Issue by Hongyi6328** [nus-cs2103-AY2223S1/forum#479]
![image](https://user-images.githubusercontent.com/58073006/203022441-9fc60267-fcae-4552-abb9-540e1d0f71e6.png)

The options are 0, 1, 29, 31, and 32.
I think both 0 and 1 are in the same equivalence class as 5. How do we determine the least suitable value then?

**Comment by jontmy** [comment]
> Rationale: 29 is a non boundary value but the question says 5 (also a non-boundary value from the same partition) is already being used as a test case. (examiner note: the partitions are [-MAX..0][1..31][32..MAX])

The answer is 29 according to the answer report on Examsoft.

**Comment by Hongyi6328** [comment]
> > Rationale: 29 is a non boundary value but the question says 5 (also a non-boundary value from the same partition) is already being used as a test case. (examiner note: the partitions are [-MAX..0][1..31][32..MAX])
> 
> The answer is 29 according to the answer report on Examsoft.

But why is this so? Feb in leap years has exactly 29 days, so 29 should be a boundary value too.

**Comment by damithc** [comment]
@Hongyi6328 Hint: The behavior of `isValidMonthSize` is somewhat different from the question in https://nus-cs2103-ay2223s1.github.io/website/schedule/week11/tutorial.html

I'll leave it at that for now, so as not to preempt further discussion. Pls remind me to explain if this thread doesn't reach a conclusion by tomorrow.

**Comment by nehcuy** [comment]
My reasoning behind the answer key's construction of the partition is as such:
Since the method is asking for `isValidMonthSize`, 29 and 31 would both return a value of `true`. This is because despite 31 not being a valid date for the month of February, it is still a valid month size for other months such as January.

However, what I don't understand is why one partition is [1..31], when 2 would not be a valid month size? Shouldn't valid month sizes fall between the values of 28 (February on non-leap years) to 31 (January for eg.)? In other words, shouldn't the partition be [MIN_INT..27] [28..31] [32..MAX_INT] instead?

**Comment by damithc** [comment]
> However, what I don't understand is why one partition is [1..31], when 2 would not be a valid month size? Shouldn't valid month sizes fall between the values of 28 (February on non-leap years) to 31 (January for eg.)? In other words, shouldn't the partition be [MIN_INT..27] [28..31] [32..MAX_INT] instead?

@nehcuy Yup, the question is incorrect. I changed the question from isVaidDay to isValidMonthSize but forgot to update the rest of the question. Will fix. @Hongyi6328 please ignore that question.

**Comment by nehcuy** [comment]
@damithc Ah so according to the new `isValidMonthSize` method name, both 0 and 1 are equally bad test cases to include, given that 5 was already used? In which case I think this is where @Hongyi6328 confusion stems from.

**Comment by damithc** [comment]
> @damithc Ah so according to the new `isValidMonthSize` method name, both 0 and 1 are equally bad test cases to include, given that 5 was already used? In which case I think this is where @Hongyi6328 confusion stems from.

Yes, only one of them should have been given as an option. Sorry, @Hongyi6328

**Comment by damithc** [comment]
Here's the updated version of the question:

>![image](https://user-images.githubusercontent.com/1673303/203071356-424db9d0-1dc7-40a6-9f02-fa674a7c0ba2.png)

<details>
    <summary>Answer (click to expand)</summary>
    <p>26</p>
</details>

**Comment by Hongyi6328** [comment]
Thank you prof!! Now I get it.
