### ISSUE TITLE
Line Limit in runtest.bat Output

### ISSUE THREAD

**Issue by cliftonfelix** [nus-cs2103-AY2223S1/forum#48]
It seems like there is a limit for the output of the difference. Is there a way to remove/increase the limit?

**Comment by kxrt** [comment]
Maybe [this](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fc) website might be helpful - focusing on the excerpt about `/lb<n>` which is explained as

"Sets the number of lines for the internal line buffer to N. The default length of the line buffer is 100 lines. If the files that you are comparing have more than 100 consecutive differing lines, fc cancels the comparison."

**Comment by cliftonfelix** [comment]
Thanks @kxrt I'll try it
