### ISSUE TITLE
Clarification on "best match for the code"

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#481]
Sometimes, I feel that I have to make judgement calls for Part 3, when it comes to UML diagrams (because none fit exactly what I have drawn). I would like to clarify regarding the criteria for "best match for the code", in particular the following:
1) If the UML notation contradicts the code or is syntactically incorrect, it is not the correct answer.
2) If two or more UML diagrams match the code, then pick the diagram which has the most detailed optional notation.

**Comment by damithc** [comment]
@cheeheng Yes, that's correct.

**Comment by cheeheng** [comment]
Thanks prof! That was very helpful.
