### ISSUE TITLE
Answers for practice papers

### ISSUE THREAD

**Issue by PeiYee88** [nus-cs2103-AY2223S1/forum#482]
Hi! I would like to ask if there are any answer keys provided to the practice papers on Examplify. If there is, where can I find them?

**Comment by damithc** [comment]
@PeiYee88 Your score and answers for the mock/practice exams can be retrieved by visiting [https://examsoft.com](https://apac.examsoft.com/GKWeb/login/NUS).

**Comment by cheeheng** [comment]
Please refer to [this comment](https://github.com/nus-cs2103-AY2223S1/forum/issues/478#issuecomment-1321884140).

**Comment by PeiYee88** [comment]
Thank you so much!
