### ISSUE TITLE
Interpreting class diagrams with omitted multiplicity

### ISSUE THREAD

**Issue by melissaharijanto** [nus-cs2103-AY2223S1/forum#485]
<img width="1225" alt="Screen Shot 2022-11-23 at 19 14 36" src="https://user-images.githubusercontent.com/97304787/203533140-b3c01625-21c5-4a7e-a9ad-2681bdeafe47.png">

Hello, I would like to ask regarding this question in Week 4's weekly quiz in LumiNUS. 

In the class diagram, the multiplicity between the `Admin` class and the `Student` class is omitted. Are we allowed to assume that there is a `0...1` multiplicity between an `Admin` and a `Student` (i.e. an admin can have `0...1` student(s))? 

I am confused as the solution only says that the object diagram is not compliant with the class diagram only because of the professor to professor association. Is an `Admin` object allowed to have no associations to a `Student` object?

**Comment by florentianayuwono** [comment]
In the website, it is said that for Object UML Diagram multiplicity is omitted because it is always 1. So I also wonder whether the case for omitted multiplicity in Class Diagram translates to `1`, `0...1` or `*` multiplicity.

**Comment by damithc** [comment]
> In the class diagram, the multiplicity between the `Admin` class and the `Student` class is omitted. Are we allowed to assume that there is a `0...1` multiplicity between an `Admin` and a `Student` (i.e. an admin can have `0...1` student(s))?

@melissaharijanto multiplicity omitted simply means multiplicity is not specified. It can be _anything_ (e.g., yes it _can_ be `0..1` but it can just as easily be `999`), and hence, we should not assume it to be any specific value.
So, we don't have enough data to say the `Admin` object not having any association with `Student` objects  makes it not-compliant with the class diagram.

**Comment by melissaharijanto** [comment]
Ah I see, thank you prof! I understand now 👍
