### ISSUE TITLE
Reconsider use of web-browser in finals

### ISSUE THREAD

**Issue by RezwanArefin01** [nus-cs2103-AY2223S1/forum#488]
> Do not use Web Browsers, even to view local files. 
> Reason: invigilators will not be able to distinguish viewing local files from visiting online websites. 

Does the invigilator need to check accessing online websites, when Exemplify already blocks access to the internet? I guess it is to stop communication in between the parts of the exam. But does just not allowing use of a browser prevent that? Since the examinees will have internet access in the venue anyway. 

Also the reason given for the restriction does not seem very rational, as web-browsers can look like PDF readers and vice versa. It is likely that invigilators will still not be able to tell the difference from far away even with this restriction. 

And for many of us, web-browser is the way to view PDFs; uncomfortable using other readers. This restriction gives slight advantage to those using PDF readers regularly.

IMO, the restriction adds very little security while making it inconvenient for many. Please reconsider the restriction. :pensive:

**Comment by damithc** [comment]
@RezwanArefin01 You raise some good points. 
One issue is, Examplify network blocking is only active during part 1 and 3. As the exam is not 'open Internet', we don't want students to access other online resources during part 2.
Yes, PDF readers can look similar to Browsers from far, but it's easier to 'catch in the act' if the student is using a Browser when s/he is not supposed to.
Also, I expected it is easier to prevent "accidentally" opening Web pages by clicking on links in the PDF, if using a PDF reader instead of a Browser.
So, the choice is not clear cut.

**Comment by damithc** [comment]
I've relaxed the rule to allow the use of Browser:

![image](https://user-images.githubusercontent.com/1673303/203689834-3852228d-4b49-44c5-a0f2-3bc950308b97.png)

**Comment by RezwanArefin01** [comment]
> We don't want students to access other online resources during part 2.

@damithc How about setting a dummy exam in Examplify during Part II? There is a slight problem that a student may start late / submit early and use the rest of the time to access the internet :joy:. But this could be countered by verifying the start / end times later, as Examplify keeps track of those. 

Another solution would be to merge Part II and III in one and give the PDF as attachment in Examplify. But I guess this is unwanted as we cannot impose ~2 min per question in Part III then.

**Comment by damithc** [comment]
> @damithc How about setting a dummy exam in Examplify during Part II? There is a slight problem that a student may start late / submit early and use the rest of the time to access the internet 😂. But this could be countered by verifying the start / end times later, as Examplify keeps track of those.

@RezwanArefin01 That's a good idea. This crossed my mind too, but only today. As this is the first time we are using Examplify for this module, and also a bit too late to add it now, I'm shelving it for next time.

> Another solution would be to merge Part II and III in one and give the PDF as attachment in Examplify. But I guess this is unwanted as we cannot impose ~2 min per question in Part III then.

Yup.
