### ISSUE TITLE
 Venue for CS2103 Final Exam 

### ISSUE THREAD

**Issue by xhphoong** [nus-cs2103-AY2223S1/forum#489]
May I ask where is the Final Exam tmr taking place at? Thank you!

**Comment by damithc** [comment]
@xhphoong It's UTOWN-AUD1 or 2. I don't know how you guys receive the exact location. Perhaps another student can help?

**Comment by sltsheryl** [comment]
It's on Edurec > Academics > Exams > View exam schedule

**Comment by xhphoong** [comment]
Thank you !
