### ISSUE TITLE
Unable to retake in-video quiz for W3.7

### ISSUE THREAD

**Issue by XenonShawn** [nus-cs2103-AY2223S1/forum#49]
As per the title, I put in the wrong answer the the test cases per method question, am I allowed to resubmit it?

Side question, the bonus marks only require answered in-video quizzes in at least 7 weeks, which mean the result of the quizzes are inconsequential, only the attempt matters?

**Comment by lulucopter** [comment]
I had the same issue for some of the in video questions as well. Don't think we are allowed to resubmit it

**Comment by damithc** [comment]
> the result of the quizzes are inconsequential, only the attempt matters?

Yes, that's right.  For in-video quizzes, correctness doesn't affect the participation points.
Nevertheless, resubmission should be allowed. Let me know which ones doesn't allow so that I can update their settings to allow resubmission.

**Comment by eesung00** [comment]
> > the result of the quizzes are inconsequential, only the attempt matters?
> 
> Yes, that's right. For in-video quizzes, correctness doesn't affect the participation points. Nevertheless, resubmission should be allowed. Let me know which ones doesn't allow so that I can update their settings to allow resubmission.

For me, I cannot resubmit the quiz in video in W3.6b and W3.7

**Comment by damithc** [comment]
> For me, I cannot resubmit the quiz in video in W3.6b and W3.7

Fixed both.

**Comment by deeyonn** [comment]
Thank you for the clarification!

**Comment by Hikoya** [comment]
Hello prof, for W4.2 and W4.3, the videos do not allow resubmission as well!

**Comment by damithc** [comment]
> Hello prof, for W4.2 and W4.3, the videos do not allow resubmission as well!

Thanks @Hikoya Fixed.

**Comment by flairekq** [comment]
Hi @XenonShawn, do close the issue if it is solved :)
