### ISSUE TITLE
Cannot cmd f on Module Website pdf

### ISSUE THREAD

**Issue by elizabethhky** [nus-cs2103-AY2223S1/forum#490]
Hi, I created a pdf version of the Software Engineering textbook on the module website and when I open the pdf file using Preview on Macbook, cmd f does not work for certain keywords like "OODM" and "Software Engineering". Is there a way to fix this issue? Thanks!

**Comment by damithc** [comment]
Mac users, any help?

**Comment by jontmy** [comment]
Using the Textbook.pdf downloaded from LumiNUS as an alternative seems to search fine (macOS Ventura):
<img width="1132" alt="Screenshot 2022-11-24 at 11 59 20" src="https://user-images.githubusercontent.com/50949210/203690983-03896bbc-11a2-41c5-a657-1057987cc373.png">

Also worth double checking whether exact match search is on:
<img width="385" alt="Screenshot 2022-11-24 at 12 00 10" src="https://user-images.githubusercontent.com/50949210/203691080-86b15bb9-324c-4756-b9fb-9d3e9c0e7bb0.png">

---

The table of contents gets completely garbled in Preview though, not sure why:
<img width="1293" alt="Screenshot 2022-11-24 at 12 03 07" src="https://user-images.githubusercontent.com/50949210/203691471-91fde1e8-0895-4369-8180-8863c1442395.png">

**Comment by elizabethhky** [comment]
Oh I see, thank you so much for your help! 😊 The table of contents page also appears garbled on my computer, not too sure why either.
