### ISSUE TITLE
Question on system testing

### ISSUE THREAD

**Issue by malwaregarry** [nus-cs2103-AY2223S1/forum#494]
Hi, I would like to ask if system testing is done with access to the source code. 
As system testing is done internally, it makes sense that the testers would have access to the code. At the same time, the test cases are based on external behaviour, implying that they do not care about how the functionality is implemented.

Thanks in advance!

Excerpt on system testing from the textbook:
> System test cases are based on the specified external behavior of the system. Sometimes, system tests go beyond the bounds defined in the specification. This is useful when testing that the system fails 'gracefully' when pushed beyond its limits.

**Comment by damithc** [comment]
@malwaregarry  It is possible that system test cases are written with full/some knowledge of the code. While the system test cases target the external behavior, knowledge of the internals can still be useful to increase E&E of those test cases. 

Consider system testing of a word processing application. If the tester knows that the code uses a different file loading mechanism (internally) if the file is bigger than a certain size, the system testing can take that into account.

**Comment by malwaregarry** [comment]
@damithc Thank you prof for the explanation! I guess testing the whole system with knowledge of the code could be better considered as integration testing (of the whole system)?

**Comment by damithc** [comment]
> @damithc Thank you prof for the explanation! I guess testing the whole system with knowledge of the code could be better considered as integration testing (of the whole system)?

@malwaregarry Not really. Integration testing is specifically about _interactions_ between sub-components.

**Comment by malwaregarry** [comment]
I see, thank you
