### ISSUE TITLE
Query regarding p1.15 of Practice Exam (Part 1)

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#496]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/13196670/203755253-c74cbc9c-2f3b-4d96-847a-62574c0761f8.png">

While it is true that pushing code to the fork will update the PR, the implicit assumption is that the branch matches? 
This is because pushing code to the `master` branch in the fork will only update the PRs merging from the `master` branch in the fork. Is this right?

**Comment by damithc** [comment]
> While it is true that pushing code to the fork will update the PR, the implicit assumption is that the branch matches?
> This is because pushing code to the `master` branch in the fork will only update the PRs merging from the `master` branch in the fork. Is this right?

Yes @cheeheng, that's the implicit assumption: i.e., we are referring to PRs for which the code update is relevant

**Comment by cheeheng** [comment]
Thanks prof.
