### ISSUE TITLE
Question 17 in Lecture 13's discussion on software design

### ISSUE THREAD

**Issue by kxrt** [nus-cs2103-AY2223S1/forum#499]
<img width="216" alt="Screenshot 2022-11-24 at 8 48 34 PM" src="https://user-images.githubusercontent.com/73589885/203790131-66cc003b-069e-4472-9f56-ac1ba834697f.png">

Hi! I don't seem to be able to find the meaning of padding here in relation to software design, unless it's a reference to UI padding or the padding files from the PE.

**Comment by damithc** [comment]
@kxrt Where did you find that question? Can you give a screenshot with more context?

**Comment by nehcuy** [comment]
@damithc That is a question from the final Lecture 13 slides if I'm not wrong.

**Comment by kxrt** [comment]
![image](https://user-images.githubusercontent.com/73589885/203791946-dfc9adcc-df0b-4f7c-a2c1-27684b3624b9.png)

@damithc Hi prof, here's a screenshot with the timestamp visible.

**Comment by parth-io** [comment]
'Padding' is a term specific to project management as well.

> The padding refers to extra time added to a schedule that isn’t really needed but that is added just to feel confident in the estimate. The impact of padding could be significant on project schedule. The quality of the estimates directly affects whether or not the project can meet scope, cost and schedule commitments. The accumulation of padding all the tasks can result in overly cautious project schedules and uncertainties across the project schedule.

from [here](https://svprojectmanagement.com/avoiding-problem-of-padding)

I think the question meant to contrast the idea of having a buffer after a realistic estimate for the project's completion schedule, instead of including the buffer as 'padding' in the project's completion time, which would then make the completion time an unrealistic estimate.

Edit: grammar correction

**Comment by Devanshshah1309** [comment]
Though (just to clarify) I don't think we're expected to know terms which are not in the textbook or under the optional sections right?

**Comment by damithc** [comment]
> 'Padding' is a term specific to project management as well.

Yup. I asked for context so that you can see what the question refers to. 

![image](https://user-images.githubusercontent.com/1673303/203795621-e47486b4-f9b5-47cb-94f8-1aac82bb0aae.png)

**Comment by damithc** [comment]
> Though (just to clarify) I don't think we're expected to know terms which are not in the textbook or under the optional sections right?

Yes.

**Comment by kxrt** [comment]
Ah okay, thanks everyone! @damithc  @Devanshshah1309 @parth-io @nehcuy
