### ISSUE TITLE
Running Junit test on Duke

### ISSUE THREAD

**Issue by LuYiting0913** [nus-cs2103-AY2223S1/forum#50]
As per the title, How could I test with assertEquals as Duke only accept command through the keyboard?

**Comment by teekaytai** [comment]
I think one way you could test the main Duke method is to separate out the part that reads the keyboard input from the rest of Duke. Then your JUnit test can directly feed in a string to Duke to test it.

Normal operation:
```
 UI
  |
  | sends input from keyboard to
  v
Duke
```

Testing:
```
JUnit
  |
  | directly sends some hardcoded string to
  v
Duke
```

Hope this helps.
