### ISSUE TITLE
Reposense does not recognise @@author tags for Markdown comments

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#501]
`[//]: #(some comment text here)` is a Markdown comment. However, the following, which is a minor deviation of only 1-2 non-empty extra lines, occurred:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/13196670/204099826-71e4a932-527c-486d-a626-1196dcbd1419.png">

**Comment by damithc** [comment]
@cheeheng I think RepoSense doesn't support this type of Markdown comments. But HTML comment format `<!-- @@author JohnDoe -->` inside Markdown files should work.

**Comment by cheeheng** [comment]
Prof Damith is right, `<!-- @@author JohnDoe -->` inside Markdown files indeed work. If it didn't, then it would have been a major deviation since some parts of my team's developer guide have `<!-- @@author JohnDoe -->` comments to ensure correct authorship, in particular to prevent minor changes in formatting from changing the authorship.

This is a feature flaw and not a bug, but there isn't a label 'Feature flaw', hence I had no choice but to put the label 'Bug'. 

Perhaps prof could include 'Feature flaw' or 'Feature request' label in the forum for future semesters?

**Comment by damithc** [comment]
> This is a feature flaw and not a bug, but there isn't a label 'Feature flaw', hence I had no choice but to put the label 'Bug'.

That's OK @cheeheng 

> Perhaps prof could include 'Feature flaw' or 'Feature request' label in the forum for future semesters?

Most likely no need. As this issue tracker is primarily a discussion board, just one label to catch all 'problem reports' should be enough to get the job done.
