### ISSUE TITLE
Class not found in module error in Run/Debug Configurations

### ISSUE THREAD

**Issue by maxng17** [nus-cs2103-AY2223S1/forum#53]
As seen in the picture below, it pops out the problem where the class Blink is not found in the run application. Although I can still run the program and run the test file, I am afraid if this would affect future code when more things are implemented, so I am wondering if this requires fixing and how to do so. 

For the context, 
I have renamed duke package to blink and Duke file to Blink, so I assume blink.Blink is looking into the blink package for Blink file.
Also that the module is ip, which is the name of the repository I have saved the project under.

This problem first arise when I was doing A-Gradle, since I missed reading the part where we have to merge with the add-support-gradle branch, leading to me making the build.gradle file myself. Halfway through, upon realizing the beforementioned error, I went to delete gradle from my project and this lead to my files no longer being in the root source. Searching online, led to me trying a solution for others which was to configure the project structure settings. I set the ip repository as the module (unsure if this was the right thing to do) and also reinstalled gradle by directly copy-pasting the build.gradle file from add-support-gradle branch. 
This allowed me to run the program and test file again but the issue below was still not solved. Although not causing any problems now, I am afraid if it will.

![2103_askForHelp_pic](https://user-images.githubusercontent.com/97393375/186072295-b88a8e4a-7c1f-4e83-b728-c5d08672b863.png)

**Comment by hauchongtang** [comment]
In your `build.gradle` file, the `shadowJar`'s `archiveBaseName` is still named duke. That might be the issue.

**Comment by damithc** [comment]
In case your previous experimentation confused intellij, here are suggestions for a clean start:
* Delete all intellij files in the project folder and open the project in intellij again (when you do, intellij will set up the project based on the build.gradle -- so, ensure you are using the clean gradle file that we provided)
* Alternatively, clone the repo to a new location and open the project in Intellij again

**Comment by maxng17** [comment]
> In your `build.gradle` file, the `shadowJar`'s `archiveBaseName` is still named duke. That might be the issue.

I have changed this but the problem still persist. Yet, thank you for pointing out this error.

> Alternatively, clone the repo to a new location and open the project in Intellij again

Also could I clarify how this should be done as to my understanding, I will need to make another local repository for my github ip repo. From there, I will have 2 local repos for the same github repo am i correct to say? Then would this cause problems if one local repo is updated but the other is left untouched?

**Comment by damithc** [comment]
> Also could I clarify how this should be done as to my understanding, I will need to make another local repository for my github ip repo. From there, I will have 2 local repos for the same github repo am i correct to say? Then would this cause problems if one local repo is updated but the other is left untouched?

@maxng17 In this option, you basically abandon the current local repo. You can even delete the whole folder (assuming you have pushed any recent changes to your fork already). When you clone again, all the code you pushed before will be copied to your new local repo, but it will not have any past intellij settings files (as those are not pushed to the fork). Hence, your new intellij project will not be affected by the experiments you did earlier. BTW, this is exactly what you had to do if your hard disk failed and you can't recover your local repo. Because you have a copy of the repo in your fork, you can resume work by cloning the fork again into a new computer.

The grading is based on your fork, not your local repo; it doesn't matter how many local repos you have.

**Comment by maxng17** [comment]
Thank you, after cloning into a new local repo, intellij setting has been reconfigured and no problems like the abovementioned persist.
