### ISSUE TITLE
Cannot write to text file while running JAR file

### ISSUE THREAD

**Issue by Hikoya** [nus-cs2103-AY2223S1/forum#54]
Hello everyone, while running my main code in IntelliJ, I was able to read from text file, and write to the text file as well.

However, after compiling into JAR file and running, I notice some issues:
1. If the file does not exist, it automatically creates (intended) and can write to file just fine.
2. If I quit the application, and try to run it again, it reads from the file just fine, but now shows an error whenever I try to save the file.

![image](https://user-images.githubusercontent.com/13346668/186118248-98d44ce9-da26-44f3-989d-ccd9f8f2e36f.png)

Thank you for the help.

**Comment by damithc** [comment]
Does this behavior depend on the folder? e.g., you can run it somewhere else (i.e., not inside a system folder such as the `Downloads` folder).

**Comment by Hikoya** [comment]
Hello Prof, thanks for the comment. 

I tried to run it somewhere else eg. C:\CS2103-test and it worked as intended (able to write to file)

To my fellow peers who may be facing the same issue: try running it on a different folder and not spend time figuring out what has happened!

**Comment by damithc** [comment]
It's possible the `Downloads` folder has some additional access control (for security reasons) such as only the process that created a file is allowed to update it later.
