### ISSUE TITLE
Unable to run gradle

### ISSUE THREAD

**Issue by april-anh** [nus-cs2103-AY2223S1/forum#56]
Although I successfully build the project using gradle. When I try to run it under `application\run`. The following error occurs. 
`Could not find or load main class seedu.duke.Duke` but there is no `seedu` folder in the repo. How can I fix this?

**Comment by hauchongtang** [comment]
The problem might be in build.gradle file:

`
application {
    mainClassName = "seedu.duke.Duke" // change this to your package name for instance duke.Duke
}
`

**Comment by april-anh** [comment]
Solved! Thank you!
