### ISSUE TITLE
User Input in iP

### ISSUE THREAD

**Issue by Aishwarya-Hariharan-Iyer** [nus-cs2103-AY2223S1/forum#57]
Hi! A minor doubt:
Reg. how the user interacts with Duke, how much variation must we account for in user commands, generally? 
For example, for this week's Lvl8 task, in addition to accounting for the cases where the user types in "**deadline/2019-10-11 08:00**", should we also try to recognize commands like "**deadline/20 Nov 2020 8 P.M.**" and so on?
Thank you!

**Comment by EmilyOng** [comment]
https://github.com/nus-cs2103-AY2223S1/forum/issues/46 I think Duke should minimally recognise one date format, and other date formats are optional if you want.

**Comment by damithc** [comment]
> #46 I think Duke should minimally recognise one date format, and other date formats are optional if you want.

Correct. Thanks @EmilyOng

**Comment by Aishwarya-Hariharan-Iyer** [comment]
Thanks, @EmilyOng! Thanks, Prof. @damithc!
