### ISSUE TITLE
Doing later tasks first (A-Gradle before Level-7)

### ISSUE THREAD

**Issue by Yongbeom-Kim** [nus-cs2103-AY2223S1/forum#58]
I'd am currently on the Level 7/8 task (halfway through 7), and I think I'd like to do the A-Gradle task first.

This is because I'd like to do read/writes on json files, and use the `org.json` dependency, and the easiest way to do this is using a tool like Maven or Gradle (and Gradle conveniently happens to be an upcoming task).

So what this means is that I'll be doing a git stash on the current branch, do the Gradle on a new branch, and then do a git fetch/merge on the level 7 branch to fetch the changes.

Can I do this?

**Comment by damithc** [comment]
@Yongbeom-Kim Sure, you can do A-Gradle earlier if you wish.
