### ISSUE TITLE
Added Gradle Manually

### ISSUE THREAD

**Issue by Nephelite** [nus-cs2103-AY2223S1/forum#59]
I saw the instruction where they mentioned the add-gradle-support branch and didn't connect the dots that we were supposed to merge from a branch in the original repo until just now. I instead added Gradle manually for all the subsequent parts. Is this going to cause an issue later down the line for the iP? Do I have to merge from the original branch to show I know how to merge from there?

**Comment by damithc** [comment]
@Nephelite it's fine if you already managed to get Gradle to work. The provided branch is for added convenience only.

**Comment by Nephelite** [comment]
Oh, thank you prof! 

Hopefully my brain doesn't give out on me like this again in the future...

**Comment by damithc** [comment]
Mistakes while doing learning tasks usually result in _more_ learning, like in this case :-)
