### ISSUE TITLE
Changing the name of the main file

### ISSUE THREAD

**Issue by pratham31012002** [nus-cs2103-AY2223S1/forum#60]
I had changed the name of the main file from Duke.java to Pluto.java (Pluto being my bot), and subsequently DukeException.java to PlutoException.java. However while going through some of my peers' codes, I see that most of them haven't changed the names of the files(some have). 

Is it fine either way?

**Comment by damithc** [comment]
@pratham31012002 Changing the name to match the bot name is recommended.

**Comment by pratham31012002** [comment]
Thank you prof!
