### ISSUE TITLE
A-Jar: Changing the command to run the JAR file

### ISSUE THREAD

**Issue by Berted** [nus-cs2103-AY2223S1/forum#61]
In the Duke A-Jar section, it's stated that: 
> You can assume the user will run the jar file in the following way only:
> - Copy the jar file into an empty folder
> - Open a command window in that folder
> - Run the command `java -jar {filename}.jar` e.g., `java -jar Duke.jar` (i.e., run the command in the same folder as the jar file)

However, as my application is using UTF-8 in its outputs, running `java -jar Duke.jar` will usually result in the UTF-8 strings to not be properly rendered. As such, would it be okay if I slightly change the command to `java -Dfile.encoding=UTF-8 -jar Duke.jar`? 

I've also added the appropriate information and runner scripts in the [release body text](https://github.com/Berted/ip/releases/tag/A-Jar) to indicate this change.

**Comment by damithc** [comment]
@Berted Should be OK, if you can convey this info to the user in a relatively fail-safe way. e.g., At the launch, you can display a banner and a message below it `If the banner above doesn't render nicely, please run the JAR file using the command ...`.

**Comment by Berted** [comment]
Understood, thanks for the suggestion prof!
