### ISSUE TITLE
Error when running checkstyle

### ISSUE THREAD

**Issue by notle1706** [nus-cs2103-AY2223S1/forum#64]
Whenever I try to run `./gradlew checkstyleMain` I get the following error.
`ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.`
Thanks in advance!

**Comment by damithc** [comment]
@notle1706 while we wait for suggestions from others, a general suggestion: Seems like a general Java error; perhaps Google for the error message and try any suggested solutions?
Note that IDE/terminal need to restart for it to see any changes done to system variables such as JAVA_HOME

**Comment by notle1706** [comment]
update: I added the JAVA_HOME path in my enviroment settings and it's working now.
