### ISSUE TITLE
Testing Duke only using JUnit and not text-ui-test

### ISSUE THREAD

**Issue by stevenlimhw** [nus-cs2103-AY2223S1/forum#65]
As we make progress with our iP project, can we not touch text-ui-test anymore and just create tests using JUnit only? Thanks!!

**Comment by damithc** [comment]
@stevenlimhw It's not a _module requirement_ for you to keep updating text-ui-test. So, it is up to you.
Note that certain behaviors are easier to test using the UI (e.g., via text-ui-test or manual testing) while some are easier to test using JUnit (e.g., internal behaviors). So, multiple types of testing can co-exist without any duplicating the effort of the others.

**Comment by stevenlimhw** [comment]
Ahh I see what you mean, thank your Prof!
