### ISSUE TITLE
Formatting suggestions for line exceeding 120 characters

### ISSUE THREAD

**Issue by Darren12345677** [nus-cs2103-AY2223S1/forum#67]
For the design of ROOFUS's greeting, I want to display this design. However, it does not conform to the hard limit of 120 characters per line. Is it possible for me to exceed the limit for this case? Otherwise, does anyone have any other suggestions? 

![image](https://user-images.githubusercontent.com/63776243/186678063-849ba801-2fae-44f8-9dbc-d8b93d12feca.png)

**Comment by lfrostbytee** [comment]
Is it okay if you were to post your code here using the "Add code" function instead of the screenshot?
This will make it easier for others and myself to debug with the actual code that you have at hand (otherwise we will need to generate our own text logos".

**Comment by damithc** [comment]
> However, it does not conform to the hard limit of 120 characters per line. Is it possible for me to exceed the limit for this case?

@Darren12345677 Yes this seems like a case where you can exceed the char limit. Perhaps you can also add a comment to explain the reason for breaking the coding standard.

On a related note, consider using a narrower logo. Otherwise it will not look nice if the user's Window is not as wide as the logo, right?

**Comment by clarence-chew** [comment]
Another possibility is storing it in a text file - A reason for that is so that you can see how it looks like without the \\ escape characters.

**Comment by damithc** [comment]
> Another possibility is storing it in a text file - A reason for that is so that you can see how it looks like without the \ escape characters.

Good suggestion @clarence-chew 
That file will need special handling when packaging the app as a JAR file though.

**Comment by Darren12345677** [comment]
Thank you all! I think the next file is a great idea! @damithc @clarence-chew. 
Yes I will follow your suggestion in the future, thanks @lfrostbytee
