### ISSUE TITLE
Cannot build or run after using Gradle

### ISSUE THREAD

**Issue by florentianayuwono** [nus-cs2103-AY2223S1/forum#68]
In IntelliJ, in the beginning I cannot run the file Duke.java after merging the Gradle branch to master.
![Screenshot (471)](https://user-images.githubusercontent.com/76247368/186678048-8c1ff2ad-8596-4dde-9da7-31eea94a2bdf.png)

So, I tried running specifically from the Duke.main() and it shows successful run.
![Screenshot (473)](https://user-images.githubusercontent.com/76247368/186677802-f2ab9990-eebe-49a8-9f63-819a3c592a44.png)

But then when I tried `gradlew clean test` in my terminal, it shows something like this.
![Screenshot (474)](https://user-images.githubusercontent.com/76247368/186678443-fa5ef241-d490-4423-a1d6-07caa148665b.png)

So I tried `.\gradlew clean test`, but then it shows error like this.
![Screenshot (475)](https://user-images.githubusercontent.com/76247368/186678612-03c245e2-0eaf-4ff8-a159-cc0da795070e.png)

I have tried googling the error type:
```
* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
```

But according to this [article](https://youtrack.jetbrains.com/issue/IDEA-253061/Could-not-initialize-class-orgcodehausgroovyruntimeInvokerHelper), it said that:
Looks the Gradle version is not incompatible with your Project JDK version.
Please try to use the Gradle version 6.3 or later. If it doesn't help, also try to update the JDK version to JDK8/11/14.

But I have make sure that my Gradle version and JDK is as specified. Here are the references for my Project Setting:

![Screenshot (476)](https://user-images.githubusercontent.com/76247368/186679439-de31aa42-cb2e-41c1-92f9-a380bf8114ea.png)
![Screenshot (477)](https://user-images.githubusercontent.com/76247368/186679456-42eb519b-95e7-4469-b697-1bd370da3e3e.png)
![Screenshot (478)](https://user-images.githubusercontent.com/76247368/186679458-eda1fa97-24cb-49af-ae6f-55f8b5b7379b.png)
![Screenshot (479)](https://user-images.githubusercontent.com/76247368/186679463-f0bc6fe6-9437-436a-857a-37aefc943490.png)

I have an assumption that the Gradle error is connected to the issue that I cannot run from Duke but have to go to Duke.main(), but I don't know what went wrong that caused that issue.

**Comment by Berted** [comment]
Hi, I'm not sure if this is the issue, but it's worth a shot since I can't see your repository directly:

In the build.gradle file, try changing:
```
application {
    mainClassName = "seedu.duke.Duke"
}
```

to
```
application {
    mainClassName = "duke.Duke"
}
```

I believe that's your package naming scheme based on the screenshot? But basically, change it to the correct package specifier for the Duke class. Hope this helps, GL!

**Comment by florentianayuwono** [comment]
Thank you! Yes, I have tried doing that. Update on my case:

In Intellij, after deleting some file with heavy string content, I can run the Duke.java directly. I have tried build and running from the Gradle toolbar and it seems successful. I have also tried clicking on other type of tasks also.
![Screenshot (480)](https://user-images.githubusercontent.com/76247368/186699848-7165a0d3-7005-487b-adaf-4d166c24fb0e.png)


But somehow when I tried to type in the terminal, the error still persists. Here is the full info on the error. I am wondering on what went wrong with the terminal way? It said something about `Java home is different.`
```
PS C:\Users\HEWLETT PACKARD\ip> .\gradlew --info clean test                                                                                             
Initialized native services in: C:\Users\HEWLETT PACKARD\.gradle\native                                                                                 
Found daemon DaemonInfo{pid=3156, address=[e6f39c89-cbf1-432e-b507-58a1456f57d2 port:64887, addresses:[/127.0.0.1]], state=Idle, lastBusy=1661438419670,
 context=DefaultDaemonContext[uid=b1414354-1abd-438c-a414-2526f4d8c732,javaHome=C:\Program Files\Java\jdk-11.0.13,daemonRegistryDir=C:\Users\HEWLETT PAC
KARD\.gradle\daemon,pid=3156,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang
=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDu
mpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=utf8,-Duser.country=ID,-Duser.language=en,-Duser.variant]} however its context does not match the desired criteria.
Java home is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=C:\Program Files\Java\jdk-17.0.1,daemonRegistryDir=C:\Users\HEWLETT PACKARD\.gradle\daemon,pid=32472,idle
Timeout=null,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/ja
va.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=ID,-Duser.language=en,-Duser.variant]
Actual: DefaultDaemonContext[uid=b1414354-1abd-438c-a414-2526f4d8c732,javaHome=C:\Program Files\Java\jdk-11.0.13,daemonRegistryDir=C:\Users\HEWLETT PACK
ARD\.gradle\daemon,pid=3156,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=
ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=utf8,-Duser.country=ID,-Duser.language=en,-Duser.variant]

  Looking for a different daemon...
Found daemon DaemonInfo{pid=27056, address=[ac2d7e8e-87d6-4ddf-9b39-e0b8f774c479 port:65067, addresses:[/127.0.0.1]], state=Idle, lastBusy=1661439351975
, context=DefaultDaemonContext[uid=6a0bfc11-7cf4-4c39-8a66-a76402321890,javaHome=C:\Program Files\Java\jdk-11.0.13,daemonRegistryDir=C:\Users\HEWLETT PA
CKARD\.gradle\daemon,pid=27056,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.la
ng=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+Heap
DumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=ID,-Duser.language=en,-Duser.variant]} however its context does not match the desired criteria.
Java home is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=C:\Program Files\Java\jdk-17.0.1,daemonRegistryDir=C:\Users\HEWLETT PACKARD\.gradle\daemon,pid=32472,idle
Timeout=null,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/ja
va.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=ID,-Duser.language=en,-Duser.variant]
Actual: DefaultDaemonContext[uid=6a0bfc11-7cf4-4c39-8a66-a76402321890,javaHome=C:\Program Files\Java\jdk-11.0.13,daemonRegistryDir=C:\Users\HEWLETT PACK
ARD\.gradle\daemon,pid=27056,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang
=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=ID,-Duser.language=en,-Duser.variant]

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 650ms

```
Here are few articles I have found regarding this error, but none seems to solve my problem.
[java home is different](https://stackoverflow.com/questions/37960949/intellij-idea-says-java-home-is-different)
[build error](https://stackoverflow.com/questions/35536013/intellij-build-error-context-mismatch/41053289#41053289)

**Comment by damithc** [comment]
@florentianayuwono Just a general comment: if you change a system variable such as JAVA_HOME, you need to restart your IDE or the terminal for it to be able to see the updated system variable.

**Comment by Berted** [comment]
I think the issue is due to conflicting JDK versions, i.e. in the Terminal the one that is running seems to be Version 17, whilst this project uses Version 11. 

I had a similar issue in my set-up and I wasn't able to resolve the issue. Albeit, I found an alternative to avoid dealing with the version conflict using IntelliJ's run configuration feature.

Say you want to run JUnit tests with `gradlew testClasses test`, what you can do is:
1. Click on the dropdown menu next to the Run button.
![image](https://user-images.githubusercontent.com/46164341/186705753-fe52c076-8394-4e2d-9a3c-c583f815670c.png)
1. Click on Edit Configurations
1. Click the Add New Configuration button (That's the + button)
1. Name the new Configuration to your preference, and add `testClasses test` to the "Run" textbox field.
1. Click Apply, now you should be able run the configuration by selecting it in the dropdown menu.

Hope this can help achieve what you want to do.

If anyone has a better solution to resolve this issue, i.e. dealing with conflicting JDK versions, feel free to chime in!

**Comment by florentianayuwono** [comment]
Thank you for the help!

Update:
- I have restarted the IDE and terminal, but seems like now it isn't the cause.
- For @Berted, yes now that I remember, my terminal is indeed the Java 17. I have tried your Edit Configurations and it showed successful build even though I haven't tried with the real JUnit tests. I will update again later after adding JUnit tests. Once again, thank you!

**Comment by florentianayuwono** [comment]
Update: it works! Thank you everyone!
