### ISSUE TITLE
Should you change commit message if you break git conventions

### ISSUE THREAD

**Issue by Puakii** [nus-cs2103-AY2223S1/forum#69]
Should I update the commit message if I have accidentally break git conventions, i.e. adding a full stop after my commit?

If yes, how should I go about it?

**Comment by xiaobill8** [comment]
If the commit was your latest commit in your local repository, and not pushed to origin (github), you can use `git commit --amend` which should bring up vim to let you edit the commit message, after which you can `:wq` to save and quit.

**Comment by Puakii** [comment]
@xiaobill8 what if its an older commit and it has already being pushed?

**Comment by xiaobill8** [comment]
In that case, you may need to use the rebase function to "re-do" all the commits from a point in the branch history (the earliest commit that you want to change). You can refer to section 2 of https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History for details.

**Comment by teekaytai** [comment]
To add on, if you edit an old commit using rebase, be forewarned that every commit after that one will actually become new commit objects as well. In particular, any tags those commits may have had would need to be replaced.

If you do choose to go ahead with rebasing, GitHub has a pretty clear [guide](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message#amending-older-or-multiple-commit-messages) on how to amend the subjects of past commits (refer to the section "Changing the message of older or multiple commit messages").

After you are done with the rebasing, notice that you will also need to _force push_ the changes to override what's on GitHub. I suggest doing it with the force-with-lease flag:

```
git push --force-with-lease origin master
```

The with-lease part helps check that you don't accidentally overwrite someone else's work when you force push. Not too relevant now but may save you from an angry teammate one day.

**Comment by Puakii** [comment]
okay thanks guys for the input!
