### ISSUE TITLE
Confirming Assessment Breakdown

### ISSUE THREAD

**Issue by XenonShawn** [nus-cs2103-AY2223S1/forum#7]
I've noticed that the actual result of the quizzes aren't part of the assessment criteria, as long as you score at least 70% it'll be counted under participation marks.

Can I confirm that there is no need to redo the quizzes until we get 100%?

**Comment by damithc** [comment]
> Can I confirm that there is no need to redo the quizzes until we get 100%?

Yes, that's correct @XenonShawn
