### ISSUE TITLE
Unable to build and run Duke using Gradle

### ISSUE THREAD

**Issue by Dilysss** [nus-cs2103-AY2223S1/forum#71]
I have merged the 'add-gradle-support' branch and followed the steps for Scenario 2, however the following exceptions occur every time I open my IP.  I can't run my java files as well. May I know how to solve this issue? Thanks!

<img width="1438" alt="Screenshot 2022-08-26 at 1 41 25 PM" src="https://user-images.githubusercontent.com/97424532/186830353-36ed4eac-46b4-411d-8a6a-cba3fcdae512.png">

**Comment by damithc** [comment]
@Dilysss perhaps push your current code to a branch in your fork and give the link here. That'll allow others to check if they can reproduce the error.

**Comment by hauchongtang** [comment]
Try to check your `build.gradle` whether your main entry point of the application plugin is pointing to the correct package.

It should be:
`
application 
  {
    mainClassName = <Enter your duke entry point here> // for instance -> duke.Duke
  }
`

**Comment by Dilysss** [comment]
> @Dilysss perhaps push your current code to a branch in your fork and give the link here. That'll allow others to check if they can reproduce the error.

Here is the link: https://github.com/Dilysss/ip/tree/branch-Temp
Thanks!

**Comment by hauchongtang** [comment]
>

@Dilysss I was able to build it successfully, maybe can try deleting the iP folder and `git clone` your repo again to your device.

![image](https://user-images.githubusercontent.com/56034480/186835072-59ac3c0b-8954-411e-af7d-4da6e8169b15.png)

**Comment by damithc** [comment]
Yes, as suggested by @hauchongtang , a common remedy is to clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.
