### ISSUE TITLE
Auto-Formatting in IntelliJ

### ISSUE THREAD

**Issue by kavantan** [nus-cs2103-AY2223S1/forum#72]
Hi, I don't think this is an issue but basically I am using IntelliJ and as of right now I am using the default key-bind to 'Reformat Code', but I am wondering if it possible to enable some form of auto-formatting in IntelliJ. For instance in VS Code, there is an option to enable auto-format every time you save a code file. I have definitely been spoilt by VSCode's auto-reformat, so if anyone has any suggestions or better approaches to reformatting code and doesn't mind sharing, please do! Thank you

**Comment by sltsheryl** [comment]
Hi I'm not sure if this helps but you can try 
https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat-on-save
⌘ , to open the IDE settings and select Tools | Actions on Save.
Enable the Reformat code option.

Eg. as mentioned by other comments on removing the indent for switch cases, you can do ⌘ , and search for switch, and modify it in Editor > Java > 'switch' statement.

Also, after you have the Preferences tab (⌘ , ) opened, you can search Smart Keys and check the ones you want are ticked.

**Comment by leirdas** [comment]
Hi, as suggested in the module’s coding conventions website, you could configure IntelliJ to save and format your code in accordance to the coding standard. For example, if i’m not wrong, you could configure switch cases such that the case keywords are not indented.
