### ISSUE TITLE
JUnit test on private methods

### ISSUE THREAD

**Issue by Hongyi6328** [nus-cs2103-AY2223S1/forum#73]
To follow Gradle testing conventions, I need to save JUnit tests at a different location. For example if I want to test a method in root/main/java/util/Duke.java, I need to save the "mirrored" test classes in root/**test**/java/util/Duke.java. So is there a workaround for me to test internal private methods from outside without changing their access modifier? I also do not want to maintain a public copy of the methods, because I might update the original methods and it would be very troublesome to sync the two versions.

**Comment by cheeheng** [comment]
[https://softwareengineering.stackexchange.com/questions/100959/how-do-you-unit-test-private-methods](https://softwareengineering.stackexchange.com/questions/100959/how-do-you-unit-test-private-methods)

According to this link, it is not done in the industry.

**Comment by cheeheng** [comment]
[https://softwareengineering.stackexchange.com/questions/100959/how-do-you-unit-test-private-methods](https://softwareengineering.stackexchange.com/questions/100959/how-do-you-unit-test-private-methods)

According to this link, testing private code should be avoided as much as possible, but there are ways around this issue.

**Comment by Hongyi6328** [comment]
Thank you Chee Heng!
