### ISSUE TITLE
Missing textbox to write answer

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#74]
I don't know whether this is a bug. However, the lack of a textbox to write a template answer makes it tempting to look at the hint directly, which is not consistent with the teaching style of CS2103/T. This is found in Week 4, section 4.1b.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/13196670/186885128-c0db48f0-ff19-4f0b-80f2-dae9fd050bed.png">

**Comment by damithc** [comment]
@cheeheng thanks for the bug report. Fixed.
