### ISSUE TITLE
Unable to run Gradle

### ISSUE THREAD

**Issue by jchilling** [nus-cs2103-AY2223S1/forum#75]
Hi, I have merged 'add-gradle-support' branch and followed the steps for Scenario 2. However, when I run gradle the display is like the images below. Here is my code's link: https://github.com/jchilling/ip. Can anyone help me to solve this issue? Thanks!

![issue4](https://user-images.githubusercontent.com/83859498/186900511-5f9b6988-993f-46f8-a39d-77e7c495c812.png)
![issue5](https://user-images.githubusercontent.com/83859498/186900517-ad0410f2-4d05-4b8b-b810-60fd7c99970e.png)

**Comment by damithc** [comment]
@jchilling  If you are using Intellij, a common remedy you can try is to push the code to your fork, clone the fork to a new location, and open the project in Intellij again.

**Comment by damithc** [comment]
@jchilling any updates?

**Comment by jchilling** [comment]
Hi sorry for the late reply. My gradle functions as normal now, thanks prof!
