### ISSUE TITLE
Is a class name considered an association notation?

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#77]
Is a class name considered an association notation? The explanation below did not explain anything about class names being an association notation while the answer does include (d).

<img width="499" alt="image" src="https://user-images.githubusercontent.com/13196670/186918182-4cba7868-3866-4568-a10f-98c09f745d23.png">

**Comment by damithc** [comment]
@cheeheng It's an 'association notation' in the sense it's needed to show an association. Probably best to remove it to avoid confusion.

**Comment by cheeheng** [comment]
Thanks so much prof. The reason behind the confusion is that class names on its own do not show an association, yet they are needed to indicate association.
