### ISSUE TITLE
Is 1..0 multiplicity the same as 0..1?

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#78]
Is 1..0 multiplicity the same as 0..1? I saw 1..0 multiplicity in the following image. 

If so, when is it preferable to use 1..0 instead of 0..1?

<img width="334" alt="image" src="https://user-images.githubusercontent.com/13196670/186936282-de1a8bab-fa10-4f65-8a62-530dec251b49.png">

**Comment by damithc** [comment]
Looks like a typo. Should be `0..1`.
In fact, it should be `1` in this case, as a snake in this context should always be in exactly one board.
