### ISSUE TITLE
Unable to use JUnit with Gradle on IntelliJ

### ISSUE THREAD

**Issue by lizekai-richard** [nus-cs2103-AY2223S1/forum#79]
Hi, I'm having difficulties building JUnit tests on my IP. The problem is I can't import

`org.junit.jupiter.api.Assertions.assertEquals;`

`org.junit.jupiter.api.Test;`

Although they are in my Gradle dependencies.

<img width="762" alt="Screenshot 2022-08-27 at 10 25 07 AM" src="https://user-images.githubusercontent.com/88566387/187010745-a2d84f42-e03f-4a4e-aefe-e3a5fea0d7fb.png">
<img width="278" alt="Screenshot 2022-08-27 at 10 25 21 AM" src="https://user-images.githubusercontent.com/88566387/187010749-d6c055cc-6b35-4ca2-8dbc-2b6466489340.png">
<img width="845" alt="Screenshot 2022-08-27 at 10 25 40 AM" src="https://user-images.githubusercontent.com/88566387/187010753-2695ae04-c8a7-42e5-ae22-5b1788eb97cc.png">

Does anyone encounter the same issue? I'm using Mac OS.

**Comment by rylzxc** [comment]
Are there any prompters/error messages when you hover over 'Assertions' and 'Test' which are highlighted in red?

**Comment by lizekai-richard** [comment]
It says "Can't resolve symbol Test", and IntelliJ suggests that I should add this library to the Gradle classpath, which I think I have already included in the dependency.

**Comment by rylzxc** [comment]
Have you tried syncing? You can try this by going to `View -> Tool windows -> Gradle -> Sync (an icon beside the '+')`

**Comment by lizekai-richard** [comment]
I have just tried, but still not working.

**Comment by damithc** [comment]
Things you can try:
* Push the code to a branch and share here so that other can try to replicate the problem.
* Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by lizekai-richard** [comment]
Here is the branch I create

https://github.com/lizekai-richard/ip/tree/branch-JUnit-Error

**Comment by Echomo-Xinyu** [comment]
Hi @lizekai-richard, I have cloned the branch you have created and imported the two lines you mentioned above successfully without encountering any error. Hence, I suspect the issue is pertaining to your environment setup instead of the project itself.

**Comment by rylzxc** [comment]
Have you tried these 2 options: 
1. File -> Invalidate caches
2. Delete the .idea folder -> Close and re import the project

**Comment by lizekai-richard** [comment]
@rylzxc Thanks a lot! Your second option works.
