### ISSUE TITLE
branches not showing up in ip progress dashboard

### ISSUE THREAD

**Issue by zylee348** [nus-cs2103-AY2223S1/forum#80]
My branch-level-8 and A-CodingStandard aren't showing up on the iP progress dashboard. For branch-level-8, after 3hrs of continual screw ups with sourcetree, I redownloaded my repo and continued work from there for wk3 tasks. However, the branch-level-8 still failed to show up and now the A-CodingStandard. This is the current state of the master branch
![image](https://user-images.githubusercontent.com/90611909/187011971-58f5f482-bae6-4925-813c-33016bff184d.png)

![image](https://user-images.githubusercontent.com/90611909/187011959-e298cf63-8277-423a-91d4-87f94a820895.png)

**Comment by hauchongtang** [comment]
Hi, your branch name is wrong for Level-8, it should be `branch-Level-8` with Capital L for level. Try to check your branch naming, whether it corresponds to the name stated in the CS2103 website as your branch name needs follow the exact name given in the task page else it will not be detected.

You can refer to this article on how to [rename your local and remote branches](https://stackoverflow.com/questions/6591213/how-do-i-rename-a-local-git-branch)

**Comment by damithc** [comment]
> Hi, your branch name is wrong for Level-8, it should be `branch-Level-8` with Capital L for level. Try to check your branch naming, whether it corresponds to the name stated in the CS2103 website as your branch name needs follow the exact name given in the task page else it will not be detected.

Good catch @hauchongtang . But I think it doesn't matter in this case as the dashboard script does a case-insensitive match.

@zylee348 You can take screenshots after enabling this setting so that we can also see the if the branches have been pushed.

![image](https://user-images.githubusercontent.com/1673303/187013307-63874fb0-d746-494c-8a62-4de9c17ec57d.png)

**Comment by parnikkapore** [comment]
If the branches appear on GitHub, they have been pushed and the script should pick it up on the next update.

So far, I see:
* [branch-level-8](https://github.com/zylee348/ip/tree/branch-level-8) should be picked up by the next update
* branch-A-CodingStandard showed up as [heads/branch-A-CodingStandard](https://github.com/zylee348/ip/tree/heads/branch-A-CodingStandard) - this is definitely not right. I don't use SourceTree myself so I'm not sure what the recovery procedure is here.

**Comment by parnikkapore** [comment]
I had a look into the commit tree; branch-level-8 seems to have been merged into master using a fast-forward merge. I'm not sure if the script is looking for a merge commit...

**Comment by damithc** [comment]
@zylee348 That branch in your fork is not merged

![image](https://user-images.githubusercontent.com/1673303/187059464-6a09fe3a-c190-46fd-8133-337622ce574b.png)

That is also why you see this (Sourcetree is telling you that your remote branch has a commit that you don't have locally).

![image](https://user-images.githubusercontent.com/1673303/187059498-1f74e3d6-7209-46f5-ac7a-4eac4522f6f7.png)
