### ISSUE TITLE
How to approach creation of files (Level 7)

### ISSUE THREAD

**Issue by PokezardVGC** [nus-cs2103-AY2223S1/forum#83]
How to go about checking if folder exists using relative paths without hardcoding filepaths? I still don't quite understand how to use the relative path, since we might be working on diffrerent directories.

**Comment by cheeheng** [comment]
You could refer to these two links for help.

[https://stackoverflow.com/questions/3634853/how-to-create-a-directory-in-java](https://stackoverflow.com/questions/3634853/how-to-create-a-directory-in-java)
[https://stackoverflow.com/questions/8197049/how-to-get-just-the-parent-directory-name-of-a-specific-file](https://stackoverflow.com/questions/8197049/how-to-get-just-the-parent-directory-name-of-a-specific-file)

**Comment by PokezardVGC** [comment]
Thanks, really helped alot. Was having trouble understanding how to create the file paths required but realised I could have created it recursively
