### ISSUE TITLE
Unable To Login GitHub Account from SourceTree

### ISSUE THREAD

**Issue by johnrhimawan** [nus-cs2103-AY2223S1/forum#84]
![Screenshot 2022-08-27 181613](https://user-images.githubusercontent.com/65337049/187025870-6a29c615-0aed-4fc0-830d-2135c629af8f.jpg)
I tried to push some of the changes I committed to GitHub, but I saw that I suddenly had to login GitHub and it rejected my username and password. I would like to confirm if the fix for this issue is to generate a personal access token on GitHub for my ip repo?

**Comment by damithc** [comment]
> I would like to confirm if the fix for this issue is to generate a personal access token on GitHub for my ip repo?

@johnrhimawan Try it and see if it works...

**Comment by riccqi** [comment]
This article from could be useful: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/
> Beginning August 13, 2021, we will no longer accept account passwords when authenticating Git operations on GitHub.com

GitHub now recommends you to either use SSH, or generate a PAT (personal access token) to authenticate your git actions. Personally I got it to work by generating a PAT, and using that as my password.

**Comment by johnrhimawan** [comment]
Hi, thanks for the help. I generated a PAT, and when the same login page prompts I enter my GitHub username as username and PAT as password. However, the same error message still pops up.

![image](https://user-images.githubusercontent.com/65337049/187035299-97e6f5cf-1f34-4d6f-bb5d-3e79c69d4175.png)

Did anyone experience the same issue?

**Comment by damithc** [comment]
@johnrhimawan Also try to methods given in https://se-education.org/guides/tutorials/sourcetree.html

**Comment by johnrhimawan** [comment]
@damithc @riccqi Thanks for the help! My issue has been resolved.
