### ISSUE TITLE
Checking understanding of UML class diagram

### ISSUE THREAD

**Issue by sharmaine1028** [nus-cs2103-AY2223S1/forum#85]
For the code below, could someone help me check that the diagram I have drawn is correct for the `Car` class please ? Particularly, if no modifier is present, is it right that we use package-private modifer?

```java
class Car {

    Engine engine;
    private List<Wheel> wheels = null;
    public String model;

    public void drive(int speed) {
        move(speed);
    }

    private void move(int speed) {
        ...
    }
}
```

![image](https://user-images.githubusercontent.com/54767477/187025872-0a2aa61e-289b-4e86-acbb-9d0d839a1fe7.png)

**Comment by malwaregarry** [comment]
Hi, your diagram looks good to me. The default visibility modifier (when nothing is specific) is package private. 
Also, since ```wheels``` is a  ```List```, you can signify that it is a collection by appending square brackets to the label:
```
- wheels[]
```

**Comment by damithc** [comment]
> For the code below, could someone help me check that the diagram I have drawn is correct for the `Car` class please ? Particularly, if no modifier is present, is it right that we use package-private modifer?

@sharmaine1028 Yes, it's correct.
