### ISSUE TITLE
Question about association, composition and aggregation

### ISSUE THREAD

**Issue by malwaregarry** [nus-cs2103-AY2223S1/forum#86]
Hi, I have a question about the topics for this week: are compositions and aggregation more specific forms of associations? or are they different?

**Comment by nealetham** [comment]
Hi, I believe it to be the case too. If I'm not wrong, associations simply defines a relationship/connection between any two classes (IS-A or HAS-A). For the case of composition and aggregation, it models a HAS-A relationship.

**Comment by damithc** [comment]
> Hi, I believe it to be the case too. If I'm not wrong, associations simply defines a relationship/connection between any two classes (IS-A or HAS-A). For the case of composition and aggregation, it models a HAS-A relationship.

@nealetham small correction: _IS-A_ relationship is neither composition or aggregation.

**Comment by damithc** [comment]
@malwaregarry I didn't want to post an answer to this question too soon as this topic belongs to the current week and there is still time for others to give their inputs.

The answer is YES, composition (an association that is a _whole-part_ relationship) and aggregation (an association that is a _container-containee_ relationship) are more specific types of associations. But neither is an _is a_ relationship (that one is inheritance).

**Comment by malwaregarry** [comment]
@damithc Thanks prof. I closed the issue as there wasn't any disagreements with @nealetham.
