### ISSUE TITLE
Unable to rename Git branch due to case differences

### ISSUE THREAD

**Issue by xiaobill8** [nus-cs2103-AY2223S1/forum#89]
I accidentally named my branches branch-level-7 and branch-level-8, and it seems like the dashboard isn't picking them up due to 'level' vs 'Level'. However, I'm unable to rename them to branch-Level-7 and 8 as Git branch names are case insensitive apparently. How should I go about resolving this?

**Comment by damithc** [comment]
> it seems like the dashboard isn't picking them up due to 'level' vs 'Level'.

@xiaobill8 This can't be the reason. The dashboard uses a case-insensitive check for this. 
Note that only merged branches are detected by the dashboard.
Wait till the branch is merged, and ensure you push the branch after merging it. Let me know if it is still not detected by the dashboard.

Separately, it is still worth exploring how to rename a branch.

**Comment by Eclipse-Dominator** [comment]
On renaming a branch,
I renamed mine on the website itself but I didn't really change the 'internal' name (It still displays as origin/branch-level-7 on vscode). In the end, I did it locally, deleted the upstream branch, and pushed the renamed branch to the fork.
`git branch -m branch-level-7 branch-Level-7` (rename branch-level-7 to branch-Level-7 locally (similar to `mov` command))
`git push origin -d branch-level-7` (deletes `branch-level-7` from the upstream repo)
`git push origin -u branch-Level-7` (pushes the newly renamed branch to upstream)
As it's only a rename, all your commits done on the branch locally will not change

**Comment by teekaytai** [comment]
@xiaobill8 I took a peek at your repo, and it looks like your master branch only has commits up till Level 6. Your level 7 and 8 branches have your latest work though. You'll need to merge your level 7 and 8 branches into master and then also be sure to push your master branch to github. After that the dashboard should hopefully update.
