### ISSUE TITLE
Unable to push via SourceTree or command line

### ISSUE THREAD

**Issue by jchilling** [nus-cs2103-AY2223S1/forum#9]
I followed all the setups on the course website. I can commit, tag, and pull. However, I cannot push via Sourcetree or the command line. My application just doesn't terminate. 
![issue1](https://user-images.githubusercontent.com/83859498/184610880-9aed0258-88a8-4550-bed1-a33319bae931.png)

I tried the advice online and changed my remote repo path, but it resulted in another error. Could anyone kindly advise how to make the push function work? 
 
![issue2](https://user-images.githubusercontent.com/83859498/184611206-0fa678a6-1ce0-4146-b0bf-570ab2d4fd10.png)
![issue3](https://user-images.githubusercontent.com/83859498/184611637-dd370a49-890f-4d18-a006-0cba4314074e.png)

**Comment by RichDom2185** [comment]
It seems like you are trying to use SSH authentication to GitHub. In the last screenshot you posted, it seems you have not marked GitHub's SSH fingerprint as trusted. Can you try to manually push via command line and press "y" (followed by enter) when the prompt appears? It may or may not work (if I remember correctly GitHub dropped SSH in favour of PATs a while back). But worth a try; if it doesn't work, considering googling how to set up a personal access token (PAT) on GitHub.

**Comment by carriezhengjr** [comment]
I have also faced the same issue and tried the last solution provided in this link:
https://stackoverflow.com/questions/29388207/sourcetree-gui-cant-push-terminal-can-push 

Basically, you can try this method by going to GitHub —> Settings —> Developer settings —> Personal access tokens —> Generate new token. Then, you can configure the permissions (expiration, select scopes) and generate a personal access token. Copy this token.
Next, go to Sourcetree —> Accounts —> Edit… —> Auth Type: Basic. Username: your GitHub username. Password: paste your personal access token here. Protocol: HTTPS —> Save.

I am able to push after changing these settings. Hope this helps!

**Comment by parnikkapore** [comment]
I just checked; GH is deprecating git auth via *the account password*. SSH does not seem to be affected.

I'm not sure how this works exactly, but you might need to change the remote repo path back to the one that starts with `https://` before following Carrie's method (to clone/pull using HTTPS instead of SSH).

**Comment by jchilling** [comment]
Thank yall!! I am able to push after following Carrie's method :)
