### ISSUE TITLE
Running the Main function only returns Executing and Executing finished

### ISSUE THREAD

**Issue by kangqiao322** [nus-cs2103-AY2223S1/forum#90]
After merging my master branch and the add-gradle-support branch, whenever compiling and running the code on Intellij windows, instead of displaying the usual syntax, only this is displayed  "10:44:03 PM: Executing ':Duke.main()'...

10:44:03 PM: Execution finished ':Duke.main()'.", I am unable to input anything and I am unsure what is the cause of this.

**Comment by seelengxd** [comment]
Hmm... I tried to clone your repo and I can't seem to replicate only displaying that message...

- When I run Duke.java directly it seems to work
![image](https://user-images.githubusercontent.com/34371483/187035865-09aec0c8-a94b-48dd-85d0-1b4aabd87158.png)
- When I try to run with gradle I get the `Could not find or load main class seedu.duke.Duke` message (probably need to remove `seedu` in your `build.gradle` -> `application` -> `mainClassName`)

I think you can try recloning the repo`git clone git@github.com:kangqiao322/ip.git directory_name_of_new_clone` and see if it works. :P

**Comment by damithc** [comment]
@kangqiao322 Might not be related to this issue, but is this correct? https://github.com/kangqiao322/ip/blob/master/build.gradle#L21

**Comment by damithc** [comment]
Other things you can try:
* If using Intellij, try these one-at-a-time in this order:
  * File -> Invalidate caches
  * Delete the .idea folder -> Close and re import the project

**Comment by kangqiao322** [comment]
I've tried all of them but they didn't seem to work, the build grade seems to be throwing exceptions but I'm not really sure what is the cause of them. Here is an image of the code, I apologise for the bad quality as my PC can't seem to print screen.
![20220828_003852](https://user-images.githubusercontent.com/93211040/187039901-9ece86fe-b4e3-4ed8-bfd2-bd282cbbd73f.jpg)

**Comment by damithc** [comment]
Are you able to click on this?
![image](https://user-images.githubusercontent.com/1673303/187040093-7755f01d-fb89-4bed-8158-dc1a92e78b0d.png)

If yes, what do you see on the output panel (on the right) when you click on it?

Are you able to run `gradlew run` on the terminal?

**Comment by kangqiao322** [comment]
When I click on the exception, the output panel remains the same and it appears that I can only do gradlew dry run
![Uploading 20220828_005930.jpg…]()

**Comment by vimuthm** [comment]
Hi @kangqiao322 , I'm a senior just dropping in to see if I can assist.

Your previous screenshot has not been uploaded completely, maybe you can post that again.
Similar to @seelengxd , I was able to get your project up and running by simply changing the `mainClassName` of your `build.gradle` to `duke.Duke` and running `gradle run` (you can find this through the gradle sidebar on the rightside)

Maybe you can detail how exactly you're running your gradle?

**Comment by kangqiao322** [comment]
Sorry for the late reply, currently I run the Duke code with the run button, I also input some command such as build file inside t
![Uploading 20220828_005930.jpg…]()
he gradle terminal

**Comment by NicsunXnus** [comment]
Hi @kangqiao322 , just a senior dropping by to help. Maybe you can share how you implemented gradle into your project? etc; Did you follow the grade tutorial listed on the website.

**Comment by kangqiao322** [comment]
I firstly created a add-gradle-support branch for my remote repo, then forked it from https://github.com/nus-cs2103-AY2223S1/ip, afterwards I created a local branch following the remote add-gradle-support and has all the gradle files, then merged the gradle branch and my master branch locally before pushing it to my master branch on github

**Comment by sltsheryl** [comment]
> I firstly created a add-gradle-support branch for my remote repo, then forked it from https://github.com/nus-cs2103-AY2223S1/ip, afterwards I created a local branch following the remote add-gradle-support and has all the gradle files, then merged the gradle branch and my master branch locally before pushing it to my master branch on github

After merging the add-cradle-support branch, did you
1. Close the IDEA project
2. Delete the .idea folder
3. Open the project again 
https://se-education.org/guides/tutorials/gradle.html (scenario 2)

**Comment by kangqiao322** [comment]
hmm I think I followed that but maybe I didn't close the project?

**Comment by NicsunXnus** [comment]
@kangqiao322 Try this and see if it works -> Right click build.gradle and click "Build module...". I could not see any "build" folder under the project tool window inside the picture you sent

**Comment by kangqiao322** [comment]
Ok it is working now, thank you very much!
