### ISSUE TITLE
intellij shows errors with accessing other classes of the same package

### ISSUE THREAD

**Issue by crvstalphua** [nus-cs2103-AY2223S1/forum#93]
After installing gradle, my intellij code suddenly shows errors everywhere. The major error being that my main class Bob cannot access the other classes Parser or Storage despite all being in the same package. When I run and build the code with gradle it all still runs fine, so I'm not sure why all these errors are being displayed on intellij.

<img width="1440" alt="Screenshot 2022-08-28 at 9 31 53 PM" src="https://user-images.githubusercontent.com/89404671/187076584-6316a694-a1a3-47f0-aeed-47694dca1597.png">

Anyone know how I can fix this? :") Even though my code still runs, I wouldn't want it becoming an issue in future.

**Comment by seetohjinwei** [comment]
Have you tried some of the solutions from here?

```
File -> Invalidate Caches / Restart... -> Invalidate and Restart
```

https://stackoverflow.com/questions/39952303/intellij-idea-doesnt-see-classes-but-building-via-gradle-works

**Comment by crvstalphua** [comment]
didn't manage to try any methods listed because not sure why but after working with my code for a few hours, it corrected itself and stopped displaying the errors! thank you though!!
