### ISSUE TITLE
Unable to start addressbook.jar

### ISSUE THREAD

**Issue by janelleljt** [nus-cs2103-AY2223S1/forum#94]
I downloaded addressbook.jar from [this link](https://github.com/se-edu/addressbook-level3/releases), but unable to get it running on my computer. I have tried:
1. Clicking the file, but (I am on Windows) it prompts me to select an application to run it on. 
2. Typing `java -jar addressbook.jar` into my command line when in the same directory as addressbook.jar file, but gives me the following error: 
![image](https://user-images.githubusercontent.com/75255420/187077574-946f82b3-59b3-4c21-a107-ffc1932d742a.png)

Any help appreciated thanks!

**Comment by damithc** [comment]
What's the output if you run the `java -version` in the same terminal?

**Comment by janelleljt** [comment]
Hi prof, this is the output. 
![image](https://user-images.githubusercontent.com/75255420/187078605-861520b5-e338-4e4d-aa9d-e2282eed327c.png)

**Comment by damithc** [comment]
@janelleljt Oh, you are using WSL? What happens when you run it in a regular Windows terminal?

**Comment by janelleljt** [comment]
@damithc Hi prof, it worked when on Windows. Thanks a lot! I will now close the issue.

**Comment by damithc** [comment]
Good to hear that @janelleljt 
Most likely WSL cannot run GUI apps yet.
