### ISSUE TITLE
iP Progress not reflected in iP Progress Dashboard

### ISSUE THREAD

**Issue by Dilysss** [nus-cs2103-AY2223S1/forum#95]
I have merged and pushed the branches 'branch-Level-9', 'branch-A-JavaDoc' and 'branch-A-CodingStandard', as well as the A-Jar tag but I don't know why they are not being reflected in the iP progress dashboard. 
These screenshots show that my branches and tags have been pushed into git:

![Screenshot 2022-08-28 at 11 12 18 PM](https://user-images.githubusercontent.com/97424532/187081146-b846fb37-7b26-4b95-a356-7f0f66243583.png)
![Screenshot 2022-08-28 at 11 13 00 PM](https://user-images.githubusercontent.com/97424532/187081178-abf2c287-d6dd-4c79-ba44-9b0b0b025601.png)
<img width="534" alt="Screenshot 2022-08-28 at 11 14 45 PM" src="https://user-images.githubusercontent.com/97424532/187081251-8b8448cc-6c2d-4e91-af9f-336bd455f091.png">

Any help would be appreciated!

**Comment by damithc** [comment]
The said branch is not merged yet, or you might have added more commits to it after merging it (which makes it 'not merged').

![image](https://user-images.githubusercontent.com/1673303/187082276-fcbb7d05-0134-4c55-a919-662a82381778.png)

**Comment by Dilysss** [comment]
Hi prof, I tried merging again but it says 'Already up to date' for all the branches? Also, I did all the merging and pushing the tags and branches this morning so I believe it should have been updated?

<img width="570" alt="Screenshot 2022-08-28 at 11 47 17 PM" src="https://user-images.githubusercontent.com/97424532/187082783-f7c0df99-4254-4387-a807-98ef94bfbedd.png">

**Comment by damithc** [comment]
@Dilysss Seems to be fine when I did pull just now. Should be detected by the dashboard at the next update. Let me know if not detected again.
![image](https://user-images.githubusercontent.com/1673303/187084080-2a0dbd50-e83b-4cd8-a40a-d691408a19d9.png)
