### ISSUE TITLE
JavaFx version 11 causes error for M1 Mac

### ISSUE THREAD

**Issue by TJun-Jie** [nus-cs2103-AY2223S1/forum#96]
Hey everyone, I was following the guide for JavaFX and the app crashes whenever I run the main method for launcher class. The error I'm getting is `CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].` 

I managed to fix this error by changing the version of JavaFX file in build.gradle to 17. I saw some post about it [here](https://www.reddit.com/r/JavaFX/comments/pvpngx/how_do_i_set_the_default_font_to_be_used_for_my/) with someone facing the similar issues.

**Comment by damithc** [comment]
@TJun-Jie I assume you already followed the advisory given in https://nus-cs2103-ay2223s1.github.io/website/admin/programmingLanguages.html#programming-language ?

**Comment by TJun-Jie** [comment]
Oh sorry I have not!
