### ISSUE TITLE
Editing commit message after it is pushed

### ISSUE THREAD

**Issue by SpecOps2016** [nus-cs2103-AY2223S1/forum#97]
How do we edit commit messages that have been pushed?

**Comment by misterpuffin** [comment]
If you're trying to edit the last commit message, you can do `git commit --amend -m "Your message"`. However, when you try to push it to a remote repository you'll need to force push to override the changes. `git push --force-with-lease origin master` is recommended to prevent override someone else's work on the remote repository.

Actually there seem's to be a previous discussion here https://github.com/nus-cs2103-AY2223S1/forum/issues/69 which might be of more help.
