### ISSUE TITLE
Considerations about code for date-time formatting

### ISSUE THREAD

**Issue by kxrt** [nus-cs2103-AY2223S1/forum#98]
Where do you think it would be better to store the code for parsing and converting the input date-time string to a specified output format? 

At the moment I have the code stored as a public static method in a [separate class](https://github.com/kxrt/ip/blob/master/src/main/java/duke/parser/DukeDateTimeFormatter.java) in my `duke.parser` package. I first thought this made sense since I'm breaking down the input string into a recognizable date-time format for output. Furthermore, since I employ the `LocalDate.parse()` and `LocalTime.parse()` methods in my code, the package name should fit the location.

However, my dilemma arises when I consider the method is only called by my `Deadline` and `Event` classes. Would it be better to turn this into a private command in the `DukeTask` for better encapsulation, as the only use case is for task strings to be shown to users?

**Comment by nehcuy** [comment]
I was wondering if creating a class for it was a little unecessary as no objects are even created. Maybe just a private method within your `Command` class would do? But the problem is duplication of code if future new `Command` class implementations require date formatting. Not sure if making it and Interface would be better?

**Comment by leonidas1712** [comment]
I think it's fine to have it in a separate class. It could make the code more extensible: if you wanted to add more commands that need similar formatting requirements you can re-use the code from that class. 

Another option could be to make a Command class that has the logic you need and have the required classes extend from there, but I'd personally prefer the method you have described.

**Comment by kxrt** [comment]
@nehcuy @huzaifa1712 Thanks for the responses! I think I'll keep it as is then.

**Comment by damithc** [comment]
To add, the Java [`Arrays` class](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Arrays.html) is an example of a class containing a bunch of static utility methods.
