### ISSUE TITLE
Accidentally picked "Request changes" during PR review

### ISSUE THREAD

**Issue by parnikkapore** [nus-cs2103-AY2223S1/forum#99]
I accidentally picked "Request changes" instead of "Comment" for both PR reviews I've made.

What should I do now?

**Comment by damithc** [comment]
> I accidentally picked "Request changes" instead of "Comment" for both PR reviews I've made.
> 
> What should I do now?

It's fine @parnikkapore 
You can leave it be.

**Comment by parnikkapore** [comment]
Alright. Thank you!
